### ISSUE TITLE
vendor modules should use git submodules instead of checking in the entire code

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#1014]
Currently the vendor modules are checked in as actual code instead of references via git submodules. If submodules are used travis-ci breaks. We need to make sure that travis is fixed so that submodules can be used so that too much code isnt checked in.

**Comment by ruflin** [comment]
The reason we currently check in all the vendor directory is that in the past we had too many issue which submodules not available during build time because of github (or other service down). So the current behaviour is intentional. It makes the repository bigger but only one checkout is needed to fetch everything.
