### ISSUE TITLE
[Heartbeat]  HTTP request should include the beat name and the version as part of the user-agent.

### ISSUE THREAD

**Issue by ph** [elastic/beats#10170]
Currently, the HTTP request from beats doesn't contain the agent name of the version number, it would be useful to add the information to help to debug or generating proxy rules.

**Comment by andrewkroh** [comment]
+1. Not sure what scope you had in mind, but I'd like both Heartbeat (http monitor) and Metricbeat (all the http based pollers) to do this.

**Comment by ph** [comment]
@andrewvc I am a strong believer that all projects (not just beat) should correctly report themselves so I would include Heartbeat and Metricbeat. So probably the best way to do it would be that libbeat provides a thin wrapper over the official `http` package. 

**Note:** Also I think it would be sufficient to just scope the user agent to a beat (and not the feature), so in the case of Metricbeat requests to external service and central management requests to Kibana would have use the same user agent.

**Comment by andrewvc** [comment]
I'm +1 on this for heartbeat. It's a little wonky in that we'd need to let users override it. We do let users set headers, and my feeling is they could disable the UA by setting it to `""`.

**Comment by andrewvc** [comment]
WRT the wrapper, one thing about HB is that we override a lot of stuff already. I'll have to look at the code once your wrapper is in, but I'm a little worried we may need to do our own impl.

**Comment by ph** [comment]
@andrewvc Oh, I wonder if we could do the following:

1. If the `user-agent` is not set in the headers we add it, done by the wrapper.
2. If users explicitly override it, we log it when we do the config unpack?

Concerning 2, I am not sure how Golang behave if we explicitly set the user-agent to an empty string.

**Comment by jarpy** [comment]
I'd love to see this. In operations, the growing number of things that all claim to be `Go-http-client/1.1` makes things tricky.

Imagine if all the major browsers said "Oh hai, I'm C++".

**Comment by andrewvc** [comment]
Reproducing the text of  https://github.com/elastic/beats/issues/14291 here since it's a dupe:

Heartbeat currently uses the default golang user-agent Go-http-client/1.1. This appears to be blacklisted by some sites, including our own, when checking some URLs, like https://www.elastic.co/products/beats/heartbeat . You can test the blocked nature of the golang UA by running curl -A "Go-http-client/1.1" -I https://www.elastic.co/products/beats/heartbeat.

We should override the default golang UA and use our own, perhaps elastic-heartbeat/VERSION where VERSION is the heartbeat version number. That should be compliant with the relevant RFC https://tools.ietf.org/html/rfc7231#section-5.5.3 .

**Comment by archon810** [comment]
Any reason this wasn't done to Metricbeat as well, for the same reason?

**Comment by andrewvc** [comment]
@archon810 can you open a separate issue for that? This issue is closed so it won't get much attention.

**Comment by archon810** [comment]
Done.
