### ISSUE TITLE
question about src_server.raw in the source Filed and dst_server.raw in the Target Filed in HOSTS dashboard

### ISSUE THREAD

**Issue by leeyu01** [elastic/beats#103]
Hi,
I've been using for  a week after successfully installing on my Ubuntu 14.04 server with various agents. I should say It's awesome. Thank you so creating such a great product.
Now I have a question regarding on the HOSTS dashboard.

When I configured src_ip in the Source Field and dst_ip in the Target Field, it shows a WOW network flow diagram among the IP addresses including external connection. 
![ip-addressonly](https://cloud.githubusercontent.com/assets/10109746/6623470/98348748-c8b9-11e4-8d26-40f4ab6f0756.png)

But, when I change to src_server.raw in the source Filed and dst_server.raw in the Target Filed. it only shows the internal connection, no network connectivity from the outside the world.
I have attached a screenshot for each case.
![server_raw](https://cloud.githubusercontent.com/assets/10109746/6623477/a32973e8-c8b9-11e4-89b0-85025a9a4cc7.png)

Please advise me how I can see the hostname for the all the network connectivity like "src_ip in the Source Field and dst_ip in the Target Field" configuration.

Thank you,

**Comment by tsg** [comment]
To make sure I understand, you would like to have the unknown IP addresses be represented by themselves? Or would you like an "Other" group that would contain all the unknown IP addresses?

If you have Logstash in the path already (for example if you used Packetbeat Deploy to install), you could instruct Logstash to create a new field that would contain the server name if it exists and the IP address otherwise.  Just an idea, until we make this possible from within Packetbeat.

**Comment by monicasarbu** [comment]
@leeyu01 We are planning to create a special Kibana widget with the topology map and we would love to hear your feedback about it, so we can make it better. What would be useful for you to see in the topology map? Would you like to see all the unknown IP address be represented by themselves? or grouped together under a single point (called Other)?

**Comment by kvch** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
You might want to check out the SIEM UI. It provides similar views, but with updated design: https://www.elastic.co/guide/en/siem/guide/current/siem-ui-overview.html
