### ISSUE TITLE
beat build failure

### ISSUE THREAD

**Issue by thesrinivas** [elastic/beats#1030]
I see some others running into this but the fix has not been mentioned.

# home:packetbeat-0.4.3$ go get
# github.com/packetbeat-0.4.3
./thrift_idl.go:28: field.Id undefined (type *parser.Field has no field or method Id, but does have ID)
./thrift_idl.go:29: field.Id undefined (type *parser.Field has no field or method Id, but does have ID)
./thrift_idl.go:37: field.Id undefined (type *parser.Field has no field or method Id, but does have ID)
# home:packetbeat-0.4.3$ make deps
go get
# github.com/packetbeat-0.4.3
./thrift_idl.go:28: field.Id undefined (type *parser.Field has no field or method Id, but does have ID)
./thrift_idl.go:29: field.Id undefined (type *parser.Field has no field or method Id, but does have ID)
./thrift_idl.go:37: field.Id undefined (type *parser.Field has no field or method Id, but does have ID)
make: *** [deps] Error 2

**Comment by andrewkroh** [comment]
This project vendors its dependencies in the `vendor/` directory so you don't have to use `go get`. I'm pretty sure that error is caused by using the incorrect dependencies. Follow the [CONTRIBUTING](https://github.com/elastic/beats/blob/master/CONTRIBUTING.md) guide for building the project yourself.

Please use https://discuss.elastic.co for questions. Issue are reserved for confirmed bugs and enhancement requests.

**Comment by thesrinivas** [comment]
I'm sorry if this is an obvious problem. I dont see a vendor/ folder. 
make, go build, go get, etc. all return this same error. 
Can you please let me know what I'm doing wrong?

**Comment by andrewkroh** [comment]
Follow these steps: https://github.com/elastic/beats/blob/master/CONTRIBUTING.md#setting-up-your-dev-environment. The `vendor/` is in the repo -- https://github.com/elastic/beats/tree/master/vendor

Are you really trying to build packetbeat-0.4.3? That is an ancient version. It's on version 1.1.1 at this point.

Why are you building from source? We can better help you if we know what your goal is.

**Comment by thesrinivas** [comment]
I have a bunch of other stuff (elastic search, kibana, etc.) on this version. I need to do a modification in the current setup. I do intend to upgrade all but for now would like to test out my changes in the current setup. Would you please let me know what I might be missing?

**Comment by andrewkroh** [comment]
When 0.4.3 was release the project wasn't [vendoring](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) its dependencies and hence the problem you are having today rebuilding an old release. Since that time the Go tooling around vendoring has come a long way.

When you run `go get` Go will reach out and download the latest version of the dependencies from master. You are experiencing a problem with `github.com/samuel/go-thrift` so you'll need to checkout an earlier commit of that project before you can build successfully. Looking at the release date of 0.4.3, you could find a commit in `github.com/samuel/go-thrift` from that date and check it out.

**Comment by thesrinivas** [comment]
found a specific version of the go-thrift that works. Now the "make install" fails with this error:
make: *** No rule to make target `go-daemon/god.c', needed by `go-daemon/god'.  Stop.

Any ideas about how to fix this?

**Comment by thesrinivas** [comment]
Just looked at this a bit more. I needed to make a local copy of fiorix/go-daemon under packetbeat/.
