### ISSUE TITLE
Switch to official Kubernetes client-go

### ISSUE THREAD

**Issue by exekias** [elastic/beats#10337]
We are currently using https://github.com/ericchiang/k8s client, as a way to have a lightweight client for Kubernetes features (autodiscover and metadata processor). We sometimes see issues with the client, being the main ones:

- Error parsing output from API server
- Error while performing watch call (EOF), where we manually handle the reconnect (ie https://github.com/elastic/beats/issues/9078)

Kubernetes [client-go](https://github.com/kubernetes/client-go) handles these issues for us, the only penalty is it increases the resulting binary size (+~30MB).

I think benefits overweight the size penalty

**Comment by Feder1co5oave** [comment]
What is the roadmap on this?

I'm using filebeat v6.7.1 and sometimes when at startup it can't connect to kubernetes master, it just logs an error and never makes any retries. So it (silently) fails and never pushes pods' logs from that host, only logs from statically configured paths. Is this caused by the k8s client currently in use?

**Comment by exekias** [comment]
Hello, we actually did this for 7.4 (already released): https://github.com/elastic/beats/pull/13051. Perhaps you can give that a try and open a new issue if the problem is still happening.

Closing this one now
