### ISSUE TITLE
filebeat send line number (not just byte offset)

### ISSUE THREAD

**Issue by johncollaros** [elastic/beats#1037]
Hi,

I am trying to solve the problem of ordering of events. I can't do it globally with distributed systems, but certainly its important I do it a the log-file level which is written in order. It needs to happen as close to the source as possible since the distrubuted nature of processing cannot guarantee ordering. This means filebeat has to do this job.

I have noticed that filebeat sends the byte-offset, and this is a good start.
But why can't we get the line number as well?

The line number would be preferable for the following reasons:
 - Users reviewing the logs won't be confused by the jumping numbers
 - It is a good way to verify that lines haven't been dropped or gotten lost in the pipeline

Is this something that could be implemented in filebeat?

**Comment by ruflin** [comment]
Filebeat is keeping the state of a file base on the offset. We initially thought about introducing the line number but it didn't bring any benefits and added complexity. The line number would have to be persisted in addition to the offset to continue the counting. In addition if a file is truncated the line number jumps back to zero. For multiline events it is not clear which line number should be sent. The feature exclude_line would add complexity once more.

Filebeat follows the at least once principle so there shouldn't be any log lines missing (at least not cause by filebeat). Sorting based on line numbers will in most cases probably not work because of file rotation. Couldn't you do it based on the timestamp? Filebeat creates a timestamp for each event.

**Comment by ruflin** [comment]
Closing this as line numbers do not fit into features like multiline or filtering, means there would be lines missing or multiple lines combined to one.

**Comment by sreque** [comment]
Sorting by timestamp is insufficient because multiple lines can share the same timestamp. It also sounds like sorting by offset can be dangerous because the number can reset. Is there a reason filebeat doesn't add a per-millisecond counter for multilevel sorting in systems like elasaticsearch?

**Comment by ruflin** [comment]
I agree that line number and offset both have some issues for sorting because they can be reset. 

@sreque I haven't heard of this "per millisecond counter" yet but it is an interesting idea. Alternatively a more precise timestamp (microseconds) could also be helpful for this. Obviously it still doesn't guarantee that each timestamp is different.

**Comment by eLRuLL** [comment]
is there a possibility that this feature could still be added? As @sreque points out, the problem still remains if `offset` is supported and that's being done anyway. 

Here is an [SO question (with bounty)](https://stackoverflow.com/questions/48996697/logstash-how-to-include-input-file-line-number)

**Comment by ruflin** [comment]
Skimming through the SO question I wonder if the requirement is really the line number or it's more a question to have a better way in Kibana to look at the log lines?

Happy to discuss this issue further. Some questions on my list:

* What is the line number in a multiline event? (first, last, ...?)
* How to we figure out the line number when we restart reading a file based on the offset without having to read the full file again?
