### ISSUE TITLE
Heartbeat File Reloading Bug or Misleading Log Message

### ISSUE THREAD

**Issue by Alsheh** [elastic/beats#10552]
Using Heartbeat docker image `docker.elastic.co/beats/heartbeat:6.5.4` and a script that updates files in the `heartbeat.config.monitors.path` every second, I get this error:

```
2019-02-04T23:56:02.486Z	ERROR	cfgfile/reload.go:223	Error loading config: invalid config: stat /usr/share/heartbeat/monitors.d/service-08.yml: no such file or directory
```
The log message is either misleading and falsely reporting an error or there might might be a real error which in this case would be a bug since it's expected that files in the `heartbeat.config.monitors.path` to be updated.

If this is not a real error, I would suggest to gracefully deregister the deleted file and remove it from the list of watched files and log the deregistration process as an `INFO` log level since this is not an error and most likely intentional.

NOTE: the aforementioned script updates the files in `heartbeat.config.monitors.path` by removing them first and write the updated configs in the configured monitors path every second.

**Comment by andrewvc** [comment]
Thanks for the report! The log level is probably a bug. It looks like we could check for this specific error with the [following method](https://github.com/golang/go/issues/1312) and make it `INFO` instead. That said, it's a good thing this was a `ERROR` in your case, because it's surfaced a real problem. So, that makes me think it might be good to leave it as a `ERROR` because the 'false' positives are actually useful.

This looks a lot like a race where we list the contents of the directory, but the file is deleted by the time we try to read it. If you're doing a remove then write there's no real way around this.

The better pattern is to replace the file atomically by writing it to a location outside of `heartbeat.config.monitors.path`, then using `mv` (or the relevant system call) to move that new file to the original file's location, which will essentially be an atomic swap. If you don't do this some monitors might accidentally disappear during your rewrite process due to the aforementioned race.

**Comment by Alsheh** [comment]
@andrewvc thanks for your response and suggesting a better approach to update the configs. Previously, each service had its own monitor config and its own file in the `heartbeat.config.monitors.path` so, theoretically, there could be hundreds of files with mini monitor configs. An update operation can update an existing service monitor config or remove it if the health check for that service is no longer necessary, hence, the need to remove a file permanently!

I changed my setup to write all the services monitor configurations in a single file outside the `heartbeat.config.monitors.path` and move the new file to the original file's location which helped to eliminate the error logs. However, I think a better approach to handle the automation of updating and removing monitor configurations would be to provide a native HTTP endpoint with `POST` and `DELETE` operations. Additionally, posting Heartbeat configs to Elasticsearch (ES) and reloading the configs from ES would be a nice option, too!

**Comment by jsoriano** [comment]
@Alsheh I see you opened an issue for the specific request of having an endpoint to add configurations (#10595). As the log message seems to be fine, as the file doesn't exist, I am going to close this issue. Please reopen if you think that something is still not covered by the other issue.
Thanks!
