### ISSUE TITLE
Metricbeat Dashboards meta-issue

### ISSUE THREAD

**Issue by sayden** [elastic/beats#10594]
This meta-issue is to follow the creation, grooming and update of Metricbeat dashboards. It's purpose is to cover all modules in OSS and X-pack.

Ideally it will be nice to pass through all dashboards and write down the creation date too, just to check if any might be too old and in need of a renew with data coming from new Metricsets.

* [x] Aerospike
* [X] Apache: (Q2-2017?)
* [X] X-Pack: AWS (Q1-2019)
* [x] Ceph
* [ ] Consul
* [x] CoreDNS
* [x] Couchbase
* [x] CouchDB
* [X] Docker (Q2-2017?)
* [ ] Dropwizard
* [x] Elasticsearch
* [ ] Envoy proxy
* [X] ETCD: (Q1-2019)
* [X] Golang (Q2-2017?)
* [ ] Graphite
* [X] Haproxy (Q2-2018)
* [ ] HTTP
* [ ] Jolokia
* [X] Kafka
* [x] Kibana
* [X] Kubernetes
* [ ] KVM
* [x] Logstash
* [ ] Memcached
* [X] MongoDB
* [X] X-Pack: MSSQL (Q1-2019)
* [ ] Munin
* [X] MySQL
* [X] NATS
* [X] Nginx
* [ ] PHP_FPM
* [x] PostreSQL
* [x] Prometheus
* [X] RabbitMQ: (Tested Q1-2019)
* [X] Redis
* [X] System
* [ ] Traefik
* [X] UWSGI
* [ ] VSphere
* [X] Windows
* [X] Zookeeper: (Q1-2019)

**Comment by ruflin** [comment]
I added this to the technical debt issue as I think not having dashboards is a technical debt on our side: https://github.com/elastic/beats/issues/10594

I think above we can check off a few which can't really have dashboards out of the box because it's defined by the user configuration:

* Dropwizard
* Graphite
* Http
* Jolokia
* Munin

I checked off the stack monitoring modules as they have a dedicated UI.

**Comment by Matt-Yorkley** [comment]
Any idea when Postgres will get a dashboard? The Postgres metricbeat is unusable in its current state.

**Comment by sorantis** [comment]
Fixed by: https://github.com/elastic/beats/pull/13126
