### ISSUE TITLE
Heartbeat HTTP POST & DELETE API and ES config Reloading

### ISSUE THREAD

**Issue by Alsheh** [elastic/beats#10595]
**Enhancement Description:**
A native HTTP endpoint with `POST` and `DELETE` operations to update and delete Heartbeat monitor configurations. Additionally, allowing the option to store Heartbeat monitor configs in Elasticsearch (ES) and reloading the configs from ES according to a `reload.period` setting.

**Specific use case for the enhancement:** elastic/beats#10552

**Comment by andrewvc** [comment]
Hey, thanks for the feature suggestion. This is actually something we're working on the background here. We'll probably implement this centrally in Kibana, letting you push out your config to individual beats. We'll let you know when we have more here!

**Comment by andrewvc** [comment]
I don't think we have a specific issue for this *quite* yet but this should be handled at some point in the ongoing fleet project whose issues can be found [here](https://github.com/elastic/kibana/issues?q=is%3Aopen+is%3Aissue+label%3AFeature%3AFleet).

I'm going to close this issue since we won't directly be implementing this ourselves as part of uptime most likely.
