### ISSUE TITLE
[Metricbeat] Cleanup module names in docs

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#10697]
We are not consistent on the naming of modules in the docs. We have `aws` and `couchdb` lower case, but most others start with an upper case letter. And we have `HTTP` but `Nats`, should it be `NATS`? https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-modules.html

All module names / titles must be checked for the correct writing according to the naming of the actual service. The above are just examples.

**Comment by jarrocha** [comment]
Hello @ruflin, can you help me understand this issue, some of these files say they are auto-generated but only some of the content like field headings, is that correct? So this issue requesting changes to the .ascii documents themselves right?

**Comment by ruflin** [comment]
The changes needed here are changes to the `fields.yml` files as all the data comes from there. The asciidoc part is generated.

**Comment by dedemorton** [comment]
I think we should standardize on the following conventions:

* When referring to the module by name, use capitalization that matches the name of the monitored service. For example, use App Search module instead of appsearch module.
* When referring to the configuration setting, use capitalization that matches the setting name and wrap the name in backtics for code formatting. For example, `appsearch`.

Here's an example: https://github.com/elastic/beats/pull/14717

If you agree with this approach, I'd be happy to make the changes.

**Comment by dedemorton** [comment]
One small concern about this approach ^^ is whether there are legal implications to using the service name.

**Comment by dedemorton** [comment]
@ruflin This issue has stalled. I am increasingly annoyed by all the consistencies in the module documentation. The cleanup is a fairly simple task; we just need to figure out the best approach here.

In the title, I think we should use the name of the monitored service because it does make a difference for SEO. 

Within the text of the topic, we can use the name exactly as it appears in the configuration (in back ticks) if that helps. Do you want to poll the team for further discussion, or should I just move forward with the change?

**Comment by ruflin** [comment]
@dedemorton I think just doing it will be most efficient. After it is cleaned up, we should ensure the team knows about the guidelines and follows them (@andresrc )

**Comment by dedemorton** [comment]
I've opened https://github.com/elastic/beats/pull/18142.

Do you think it's OK to close this issue?

Before I come up with a recommendation for the team, I'd like to figure out what's best from a legal perspective. We need to talk about how our naming affects trademarks because this is a problem for the integration packages, too.  Most companies have clear guidelines about how they want you to refer to trademarked names. For example, you shouldn't say "the Oracle widget" but you can say "the widget for Oracle." I'm not proposing that we change the module docs, but we should at least try to get it right for integrations.
