### ISSUE TITLE
Report host name as FQDN on all platforms

### ISSUE THREAD

**Issue by pickypg** [elastic/beats#1070]
Apparently Go does not provide the FQDN on all systems (particularly Linux, it seems) because it checks `/bin/hostname` rather than `/bin/hostname -f`.

Here's the Go test showing that they accept the shortname: https://golang.org/src/os/os_test.go#L1341

It would be great if we could fill in the actual FQDN rather than an unexpected subset, but it does mean providing an appropriate mechanism for _every_ supported system (or falling back to the subpar behavior that comes out of the box).

As a workaround, #715 will allow environment variables to fill this in, but it still requires something else in the environment to be used.

/cc @andrewkroh

**Comment by dMopp** [comment]
+1

**Comment by Lollaskates** [comment]
+1, running topbeat on my linux hosts returns FQDN, but running topbeat on windows hosts (Server 2012R2) only returns the hostname. Would like to have it normalized.

**Comment by JakeDEvans** [comment]
my linux systems (cent 7.2) report fqdn, but my windows report the shortname.

I would prefer the shortname (which is how my rsyslog data comes in).  can we update this request to allow you to specificy the command used to aquire the hostname?

windows: `%COMPUTERNAME%.%USERDNSDOMAIN%` or `%COMPUTERNAME%`
linux: `hostname -s` or `hostname -f`

**Comment by trevorndodds** [comment]
Please make this an option, I for one prefer the shortname as it keeps the field length shorter. Some windows domains have really long FQDNs.

**Comment by richlv** [comment]
it might be preferable to allow running a custom command to determine hostname. on some systems even `hostname -f` returns short name, and user might run a custom command to determine fqdn.

**Comment by dMopp** [comment]
A good idea, too but hostname -f shows the short version only if the system is wrongly setup (or didnt have a domain)

**Comment by mib4fun** [comment]
How can i force this ? We need fqdn

**Comment by popstas** [comment]
@mib4fun, we replaced `host` field with `fields_under_root`, fqdn fills with ansible:
``` yaml
filebeat.prospectors:
- input_type: log
    fields_under_root: true
    fields:
      host: "fqdn"
```

**Comment by popstas** [comment]
Also you can define `beat.name`: just set `name` on top level of filebeat.yml

**Comment by mib4fun** [comment]
@popstas ! Its' working !

**Comment by andrewkroh** [comment]
Duplicates: 

- https://github.com/elastic/beats/issues/6741
- https://github.com/elastic/beats/issues/16507

**Comment by DPattee** [comment]
Found this report while trying to figure out how to do the opposite... 

I only want the hostname part available in a field, not the entire fqdn. I.e. what _hostname -s_ returns. 

Having two fields, one with just the hostname and one with the fqdn, would be a fine solution for me. 

Reasons: 
1) Clutter. All machines reporting in to a single elastic cluster belong to the same domain the way I built things out. Having the extra domain information just clutters up dashboards / viz labels.
2) Mac OS X bug that occasionally reports the .local version of the hostname instead of the correct .<domain> version (https://discuss.elastic.co/t/mac-hostname-showing-as-localhost/48878)

**Comment by willemdh** [comment]
I agree, imho host.name should be without the domain.. Long domain names tend to mess up some visualisations. host.fqdn could be added or sth similar.. Or host.domain could hold the domain..

**Comment by willemdh** [comment]
This is really an issue. The inconsistencies in host.name usage result in all kinds of unwanted results. As this field is used as the primary key for many stuff, this should get cleared out asap, as every query, dashboard, saved search, watch, alert or ml job will have to be revisited and updated once there is finally a consensus on using shortname or fqdn for all `host.name` values in all beats.
As some organizations might index events from different domains where some hosts might have the same name, imho there is no choice but to move to fqdn. (for example dc01.domain1.net and dc01.domain2.net)
To make stuff convenient for users who don't need / want fqdn, an additional field, such as `host.shortname` could be added?

I can understand that it takes some time to update beats host.name output and processors etc, but at least we should asap evolve to a consensus where this is going long-term, so we can make the necessary preparations and if time permits even add the domain ourselves untill Elastic provides it.

**Comment by webmat** [comment]
Agreed, there's a few things we'd like to shore up with regards to host identifiers. I'll make sure fqdn vs shortname is part of the discussion.

**Comment by StefanSa** [comment]
hi there,
please fix it quickly, that is otherwise totally confused with all action.
Currently, with Metricbeat, Filebeat and Packetbeat, the FQDN is not sent as host.name but only the hostname (without FQDN).
However, with one exception, Winlogbeat sends the FQDN as host.name.

**Comment by willemdh** [comment]
@webmat Any news about this?

**Comment by webmat** [comment]
On the ECS side we've just started a more holistic discussion around all the host identifiers, it's [RFC 0006](https://github.com/elastic/ecs/blob/master/rfcs/text/0006-host-identifiers.md). Still very early stage, though. Should start moving in the coming weeks.

**Comment by dMopp** [comment]
Still an issue :(

**Comment by gwhynott** [comment]
Would like to see this adjusted too (host.name).  Seems linux returns whatever is in /etc/hostname,  which isn't the 'correct' place to ascertain the hosts FQDN.  (man hostname).
thanks!
-g

**Comment by DPattee** [comment]
I'm not sure how to follow the progress here. 

7.15.1 still doesn't have a .shortname option, and it still suffers from the MacOS / Go issue where occasionally it decides a hostname should start being returned as foo.LOCAL instead of the foo.DOMAIN that it normally reports.

The linked "RFC 0006" hasn't been updated in over a year, nor have most of the other linked issues.

**Comment by willemdh** [comment]
There has been barely any progress on this problem for years..... :(

Same issue for `user.name`

So many datasets logging `host.name` and `user.name` in different ways, makes all these data barely correlatable.

**Comment by bradenlpreston** [comment]
@nimarezainia - are we still tracking this for 8.6? Both agent and beats?

**Comment by nimarezainia** [comment]
@bradenlpreston not 8.6 - it is on the backlog for 8.7 for the agent. if there are no issues it'll be available in that release.

**Comment by bradenlpreston** [comment]
Thanks Nima. 
cc: @snehsach19 and @norrietaylor

also cc: @ferullo for any related Defend integration work.

**Comment by ferullo** [comment]
Endpoint will have to do work to align with whatever is done for Agent and Beats. I doubt it'll be much work for us, please just let us know what ECS location the fqdn will be placed in and we'll align to it.

**Comment by willemdh** [comment]
Is the new convention lowercase fqdn for host.name ? Imho to make sure its normalisable everywhere it should be lowercase.. I've seen enough logs where one time the host is in caps and in others it's lowercase..

**Comment by MikePaquette** [comment]
@ebeahan Can you please weigh in on this topic?  IMO, we must make any changes in coordination with the ECS specification, which is too vague/ambiguous in it's definitions of `host.name`, `host.domain`, and `host.hostname`.  Specifically, we should remove the "The sender decides which value to use."  sentence from `host.name.`

**Comment by ebeahan** [comment]
@MikePaquette I agree any changes should be made in coordination in ECS.

For context, the original [change](https://github.com/elastic/ecs/pull/144) to add both `host.name` and `host.hostname` was framed as:

* `host.hostname` - what the `hostname` command would return on a host
* `host.name` - a customizable name that could be changed to uniquely identify the host. The `.name` convention followed the pattern set by other fields in ECS, like [`agent.name`](https://www.elastic.co/guide/en/ecs/current/ecs-agent.html#field-agent-name) to set a custom name.

If I understand the discussion here, the proposal is to use always extract or construct the FQDN and place the value into the `host.name` field?

> Specifically, we should remove the "The sender decides which value to use." sentence from host.name.

Beyond just removing, I agree with @willemdh that we should standardize the specifics of whatever convention is decided.

**Comment by MikePaquette** [comment]
Thanks @ebeahan Here are some thoughts based on @willemdh 's suggestion/proposal [above](https://github.com/elastic/beats/issues/1070#issuecomment-963174171) 

> There is only one good solution imho and that it to make host.name lowercase and fqdn. 

- I think this is a good suggestion.
- It is consistent with the thought behind the original comment in this ticket from @pickypg [above](https://github.com/elastic/beats/issues/1070).
- Question:  Are there known use cases where users track `host.name` in an environment where a fqdn is not used or not available?  Should we specify how to populate `host.name` if any such environments?
- Question: Would this be considered a breaking change for ECS in general? or a clarification?

> Then additional ECS fields should be created, host.shortname, which should hold lowercase shortname

- Question: if we choose to implement a new field to hold the shortname, should we use a field similar to the `dns.*` field set? Which uses [subdomain](https://www.elastic.co/guide/en/ecs/current/ecs-dns.html#field-dns-question-subdomain)?

> and host.domain, which should hold the domain. 

- The `host.domain` field already exists, and does not refer to parts of the Internet domain, so I'd prefer that we don't change this definition, as it would be a potentially bigger breaking change.

> Finally host.hostname should get the original whatevercase host name.

- Question: is there a specific proposal as to how to enhance the definition of this field?

**Comment by ceeeekay** [comment]
I'd like to suggest a different field for the FQDN, say, `host.fqdn`. That way, use of FQDNs can be optional and does not impact any existing user pipelines, vis, reporting, scripts, or anything else which uses `host.name` as a fundamental field.

Long-time Elastic Stack users are probably still smarting from the change of `host` from a field to an object with ECS and  having another change here I expect will not be too welcome.

**Comment by MikePaquette** [comment]
Thanks @ceeeekay 

> Long-time Elastic Stack users are probably still smarting from the change of host from a field to an object with ECS and having another change here I expect will not be too welcome.

True, thanks for that reminder. 

There are two issues in play in this discussion:

1. ECS producers such as Beats, Elastic Agent, Elastic Agent integrations, Logstash configs, etc. MAY choose to populate the ECS `host.name` field with the FQDN from the host on which they run.  I think this would NOT be a breaking change. 
-- It is consistent and compliant with the current ECS [definition](https://www.elastic.co/guide/en/ecs/8.5/ecs-host.html#field-host-name) for the `host.name` field
-- It is a value-only change - and does not involve any changes to field data type or array status 
 2. Changing the ECS definition for `host.name` to **_require_** the FQDN, however WOULD be considered a breaking change.
-- Current ECS-compliant producers would be forced to change their code to remain compliant.

A proposal: 
1. All Elastic ECS producers should populate the `host.name` field with the lowercased FQDN from here forward.
2. The ECS [definition](https://www.elastic.co/guide/en/ecs/8.5/ecs-host.html#field-host-name) for `host.name` should be updated to **_recommend_** the use of lowercase FQDN.  e.g., "Name of the host. It can contain what hostname returns on Unix systems, the fully qualified domain name (FQDN), or a name specified by the user. The recommended value is the lowercase FQDN of the host."
3. If users feel strongly that dedicated field(s) for the shortname and/or FQDN would still be useful or required, then a pull request in the [ECS repository](https://github.com/elastic/ecs/pulls) should be created and reviewed by community members.

@ebeahan would you comment on the proposal above?

**Comment by ebeahan** [comment]
> 1. All Elastic ECS producers should populate the host.name field with the lowercased FQDN from here forward.

We would need a group to assess the effort across the different Elastic producers. This may seem straightforward on the surface but there's likely complexity for certain sources/integrations to determine the correct FQDN if that's not something already available/produced.

> 2. The ECS [definition](https://www.elastic.co/guide/en/ecs/8.5/ecs-host.html#field-host-name) for host.name should be updated to recommend the use of lowercase FQDN. e.g., "Name of the host. It can contain what hostname returns on Unix systems, the fully qualified domain name (FQDN), or a name specified by the user. The recommended value is the lowercase FQDN of the host."

Agree this would _not_ be a breaking change. Since it's a change to the recommended value for such a fundamental field in ECS, I'd still suggest working through the [ECS RFC process](https://github.com/elastic/ecs/tree/main/rfcs) to help facilitate and structure the discussion.

> 3. If users feel strongly that dedicated field(s) for the shortname and/or FQDN would still be useful or required, then a pull request in the [ECS repository](https://github.com/elastic/ecs/pulls) should be created and reviewed by community members.

If we're discussing the guidance for `host.name`, there's also opportunity to look at guidance for `host.hostname`, `host.domain`, `host.id`. Maybe another dedicated field is necessary, but maybe there's opportunity to use an existing one.

If `host.name` is normalized to a lowercase value, are there use cases where the original case produced by the data source still needs captured? Concerns have been raised around [other ECS fields](https://github.com/elastic/ecs/issues/838) that lowercasing is a lossy normalization.

**Comment by nimarezainia** [comment]
> 1. ECS producers such as Beats, Elastic Agent, Elastic Agent integrations, Logstash configs, etc. MAY choose to populate the ECS `host.name` field with the FQDN from the host on which they run.  I think this would NOT be a breaking change.
>        -- It is consistent and compliant with the current ECS [definition](https://www.elastic.co/guide/en/ecs/8.5/ecs-host.html#field-host-name) for the `host.name` field
>        -- It is a value-only change - and does not involve any changes to field data type or array status

This would not be a breaking change from the ECS definition perspective. However we are changing the generally expected value of the field. I am very concerned with users who may be using host.name already based on the current value it's populated with and get a rude surprise when that is changed to FQDN.

Is there a reason why we wouldn't want a field specifically for FQDN? seems like a much cleaner solution.

@ebeahan We will create the ECS RFC thank you.

**Comment by DPattee** [comment]
Earlier comments about just having the host name without domain in a field are still relevant imo
Mac Go still sometimes gets confused and will start reporting 'hostname.local' instead of 'hostname.domain'
And at 3 places I've worked, there has never been more than a single domain for all the machines anyway, so cluttering UI with fqdns isn't valuable. 
Having a transform that manipulates every incoming fqdn to extract just the shortname and add it to a new field seems like unnecessary resource utilization in the cluster when it could just be reported as multiple fields in the first place.

There was a comment earlier to follow https://github.com/elastic/ecs/blob/main/rfcs/text/0006-host-identifiers.md but it hasn't been touched in two years, so I'm not sure another comment saying 'file an rfc' would be helpful

**Comment by willemdh** [comment]
@DPattee @nimarezainia Considering `host.name` is used as the primary key in all kinds of host based visualisations, it needs to be unique. I can definitely understand some smaller organizations object because the fqdn is 'longer', but for larger organizations / msp's the consequences and confusion that might follow from host.name collisions from different domains are imho much larger then "cluttering UI" concerns. Only when all builtin `host.name` based visualisations would be ported to sth else such as `host.fqdn` it would be ok'ish, but that seems like a much larger change with much more consequences than the "cluttering UI" concerns..

> I am very concerned with users who may be using host.name already based on the current value it's populated with and get a rude surprise when that is changed to FQDN.

Tbh imho the confusion rising from not having an agreed upon convention is currently a much bigger concern and a root cause of a lot of issues. I'm seeing duplicate hosts everywhere. Some beats / integrations index `host.name` differently for years, so I don't see why you have concerns there is finally some movement to agree on a recommendation for the `host.name` field...

**Comment by joshdover** [comment]
> Considering `host.name` is used as the primary key in all kinds of host based visualisations, it needs to be unique. I can definitely understand some smaller organizations object because the fqdn is 'longer', but for larger organizations / msp's the consequences and confusion that might follow from host.name collisions from different domains are imho much larger then "cluttering UI" concerns. Only when all builtin `host.name` based visualisations would be ported to sth else such as `host.fqdn` it would be ok'ish, but that seems like a much larger change with much more consequences than the "cluttering UI" concerns.. And the results would be the same, considering `host.fqdn` would be used by default then.

I tend to agree quite strongly with this + @MikePaquette's [argument](https://github.com/elastic/beats/issues/1070#issuecomment-1320420046) that there is already a inconsistency in the usage of the existing `host.name`, `host.domain`, and `host.hostname` fields. It doesn't seem that adding an additional field quite solves the problem and I don't think this would need to be considered a breaking change. I'd argue the existing behavior is broken and it needs fixing across the product. There will be some short-term pain associated with this, and we should think about ways to mitigate that pain, but I think the long-term pain we'd experience from the inconsistencies is larger.

I think we need to move this discussion into a new ECS PR to update https://github.com/elastic/ecs/blob/main/rfcs/text/0006-host-identifiers.md and move it to the next stage. I do think updating this RFC and the recommended values for these fields needs to be discussed and decided together, rather than only focusing on the FQDN problem in isolation. Otherwise, we may need to introduce a further painful change in the future.

Specifically, I'd recommend:
- `host.name` be the FQDN, essentially `host.hostname` + `host.domain` - this would be an updated recommendation in ECS 8.x. In ECS 9.0 this could be a required breaking change.
- `host.hostname` be the short host name - this would not be a change from today
- `host.domain` be the domain name - also no change

From a mitigation perspective, we should consider adding the ability for the user to choose to use any of these fields in various places in the UI. For example, in the Fleet UI, we should allow the user to choose which columns to show in the Agent table, with the default continuing to be `host.name` - which would be a FQDN in future versions of Elastic Agent.

**Comment by joshdover** [comment]
Updated my proposal to reflect `lowercase`. Maybe we should do the same for the other fields too?

**Comment by DPattee** [comment]
@willemdh my point isn't "stop work and do not standardize" or "break all visualizations to make it easier for SMBs". 

My point is, from Josh's message (numbering the bullets)

> 1 **host.name** be the lowercase FQDN, essentially host.hostname + host.domain - this would be an updated recommendation in ECS 8.x. In ECS 9.0 this could be a required breaking change.
> 2 **host.hostname** be the short host name - this would not be a change from today
> 3 **host.domain** be the domain name - also no change

1. yep, great, fqdn somewhere in a standardized, lowercased, etc manner is great

2. "this would not be a change" - host.hostname is *not* always just the short hostname. eg. it is not always the output of hostname -s, sometimes it is the output of hostname -f 

3. yep, domain somewhere in standardized, lowercased, etc manner is great

**Comment by JanKnipp** [comment]
Not adding anything too useful for the discussion I just want to say that there are organizations that have multiple domains to seperate environments (test, qa, prod, ...) or regulatory reasons (pci, HIPAA, ...). There are cases where hostnames and users are identical and this can lead to some confusion and makes the use of elastic in a larger enterprise environments hard. The worst thing is that currently some integrations use a full fqdn and some dont so even hosts from the same domain end up being shown twice (i.e. in security host view).
From my end everything will be a "breaking" change but consistency would be the most important thing and of course having a fqdn after waiting since multiple years ;-)

**Comment by joshdover** [comment]
@rylnd does your team have any concerns about the proposal in https://github.com/elastic/beats/issues/1070#issuecomment-1323387491? Specifically, I want to make sure we do not introduce a signficant breaking change to exception lists and alert rules defined by customers.

**Comment by rylnd** [comment]
@joshdover thanks for the ping. Since this proposal looks to be about a forward-looking convention rather than a forced migration, I don't envision significant issues on our end. As others have mentioned, we primarily use `host.name` as an assumed primary key, so in general both old and new datasets should continue to function as expected; any concerns are going to be centered around attempting to correlate _across_ these datasets.

1. Host/Network pages may show "duplicate" entries for old/new `host.name` values (but this is already the case today)
1. Exceptions will continue to function on old data, but new exceptions may need to be added/modified for new data
1. Prebuilt rules may need to updated if they make assumptions about `host.name` (cc @brokensound77 )

We'll probably want to communicate this change to Security users so that they can respond accordingly, but this will always be specific to the user's data and their consumption of it.

**Comment by norrietaylor** [comment]
@ferullo, I ensure you are in the loop about @joshdover's [proposal](https://github.com/elastic/beats/issues/1070#issuecomment-1323387491?). @mitodrummer has started a PR [here](https://github.com/elastic/ecs/pull/2122) to move this along. 

Any concerns?

**Comment by ferullo** [comment]
No, I have no concerns. Endpoint can align with Agent/Beats on this, we'll just need to know the exact release to make the change in.

The only part of the Security App that I can think of that could be affected by this is Endpoint or Detection Engine rules and I really really doubt any Elastic rules are based on `host.name`. But @brokensound77 can you confirm? Sorry for not having looped you in on this sooner.

**Comment by willemdh** [comment]
@AndersonQ What about Windows, will it take the workgroup as domain? I don't see a problem with using .lan for Linux servers not in a domain.

**Comment by AndersonQ** [comment]
As Josh [recommended](https://github.com/elastic/beats/issues/1070#issuecomment-1323387491) on 8.x it'll be optional, thus a config is required, therefore I propose:

 - Elastic Agent (configuring the [host provider](https://www.elastic.co/guide/en/fleet/current/host-provider.html))
   `providers.host.use_fqdn: true|false`

 - Beats standalone (configuring the [add host metadata processor](https://www.elastic.co/guide/en/beats/filebeat/current/add-host-metadata.html))
   `processors.add_host_metadata.use_fqdn: true|false`

**Comment by joshdover** [comment]
Thanks for sharing, @AndersonQ. A couple questions:
- We don't currently support configuring any `providers.*` keys in agent policies from Fleet today. Do you anticipate any challenges on the agent side in adding this to the agent policy? (I'm not familiar with how/where agent applies the agent policy from Fleet)
- When `providers.host.use_fqdn: true` is set, will Agent automatically configure `processors.add_host_metadata.use_fqdn` on config passed to Beats? Or will Beats be required to change the default for the `add_host_metadata` processor based on the agent config? Something else?

**Comment by AndersonQ** [comment]
> We don't currently support configuring any providers.* keys in agent policies from Fleet today. Do you anticipate any challenges on the agent side in adding this to the agent policy? (I'm not familiar with how/where agent applies the agent policy from Fleet)

I don't foresee any problem, as long as we add it to the "policy parser", it should be fine. But I'll confirm with the team later today.

> When `providers.host.use_fqdn: true` is set, will Agent automatically configure `processors.add_host_metadata.use_fqdn` on config passed to Beats? Or will Beats be required to change the default for the `add_host_metadata` processor based on the agent config? Something else?

I'd say the agent would configure the `processors.add_host_metadata` for the beats as well. But it could be the agent would do it only for the monitoring beats. I'd say it's more a product decision, either way shouldn't be too difficult to implement

**Comment by joshdover** [comment]
> I'd say the agent would configure the `processors.add_host_metadata` for the beats as well

I think the issue is that Agent v2 removed all knowledge and assumptions about the underlying streams configuration. AFAIK we don't manipulate it anymore.

However, I think we want to have consistent behavior across all integrations (@nimarezainia please confirm). Once we have the shipper appending these fields, this is more straightforward, but until then we need another solution.

Please do discuss with the team today (I won't be there).

**Comment by jlind23** [comment]
@AndersonQ Please keep us posted in order to take a decision **today**.

**Comment by AndersonQ** [comment]
After discussing with the team, we agreed on having a feature flag config `agent.features.fqdn.enabled: true|false`. It'll be added to the control protocol and the applications the agent runs should be able to understand them.

The generic version is:

```
agent:
  features:
    feature_name:
      enabled:
      config1:
      config2:
      ...
      configN:
```

That way the agent will be able to enable and disable features and the features can have complex configs beyond just enable/disabled

```

**Comment by jlind23** [comment]
Thanks @AndersonQ for the update. Feel free to link Beats and Agent PR to this issue in order to consider this as complete.

**Comment by joshdover** [comment]
@AndersonQ Great thank you. Let's make sure this field is explicitly documented in the control protocol, along with the expected behavior of the application. We should then share that elastic-agent-client PR with the Endpoint developers as soon it's available for them to start integrating with.

**Comment by joshdover** [comment]
One question: does this mean that we are only planning to support this feature in Agent or do we still plan to add a Beats configuration for this?

**Comment by ferullo** [comment]
I have no objections to [this](https://github.com/elastic/beats/issues/1070#issuecomment-1385678732) approach to adding a default domain when needed. Also [this](https://github.com/elastic/beats/issues/1070#issuecomment-1387236070) config looks good to me, please just make sure it's passed to Endpoint over the v2 comms.

@softengchick is going to take over tracking this issue from the Endpoint side.

**Comment by DPattee** [comment]
> folks, a question about the domain. Depending on the system configuration the domain might be missing, thus the FQDN would be just the hostname.
> 
> On Linux `hostname -f` uses `.lan` if no domain name is defined. I'm reproducing that on [go-sysinfo](https://github.com/elastic/go-sysinfo/pull/144), the lib we use to get the host infos.
> 
> Any objections on that? @ferullo is it fine for Endpoint?

Anderson can you run your test on a Mac ? I’m pretty sure the default expected domain would be .local

**Comment by AndersonQ** [comment]
> > folks, a question about the domain. Depending on the system configuration the domain might be missing, thus the FQDN would be just the hostname.
> > On Linux `hostname -f` uses `.lan` if no domain name is defined. I'm reproducing that on [go-sysinfo](https://github.com/elastic/go-sysinfo/pull/144), the lib we use to get the host infos.
> > Any objections on that? @ferullo is it fine for Endpoint?
> 
> Anderson can you run your test on a Mac ? I’m pretty sure the default expected domain would be .local

done. We'll mimic as much as possible the OS behaviour

**Comment by AndersonQ** [comment]
> @AndersonQ What about Windows, will it take the workgroup as domain? I don't see a problem with using .lan for Linux servers not in a domain.

No, the complete behaviour is described on https://github.com/elastic/go-sysinfo/pull/144. For windows, as we can request the FQDN directly to the system, it just returns what we get.
