### ISSUE TITLE
[Discusss] Use index sorting for Elasticsearch

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#10715]
Elasticsearch allows to [sort indices](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-index-sorting.html) on ingest time. This allows for potentially better compressed indices and faster queries as queries can be [terminated early](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-index-sorting.html#early-terminate). Data in Beats across modules has very different structure but the data of each `event.dataset` is very similar (In 6.x this was `metricset.module + metricset.name`).

## Experiment

Under this assumption I run an experiment with some of my Metricbeat 6.4 indices. They contain data from the Metricbeat system module and the default metricsets. I reindexed all the data from January and February into one index each. I did this twice, once with the standard 6.4.0 template, and once I extended the template with the following sorting settings:

```
"sort.field" : ["metricset.module", "metricset.name"], 
"sort.order" : ["desc", "desc"]
```

Note: For 7.x the field would be `event.dataset` for the sorting.

After indexing I did run `_forcemerge` on the indices and got the following result:

```
metricbeat-6.4.0-sorted-jan       2069630      253.8mb 
metricbeat-6.4.0-unsorted-jan     2069630      293mb   

metricbeat-6.4.0-sorted-feb       912413       112.8mb 
metricbeat-6.4.0-unsorted-feb     912413       121.9mb 
```

For the January index, the unsorted index is around 15% larger than the sorted one. For the smaller February index the difference is about 8%. Having different multiple modules and larger dataset I would expect these values to even grow further.

## Queries

I would expect queries to be more efficient especially as most queries first start to filter on the dataset. As the index is sorted, this queries could potentially terminate early. It's tricky to manually compare query and we would need a [rally](https://github.com/elastic/rally) job for this.

## Indexing time

I expect that sorting could slow down indexing time. If and how much should also be measured by a rally job.

## Fields to sort

In the above example I sorted on the `dataset` field(s). Further fields could be used to bring documents closer together which are queried together. An obvious one would be `@timestamp` as in Kibana by default a timestamp range is queried. 

Further fields could be `host.name` to have the data from each host close together. More fields which are common for grouping could be added.

**Comment by jpountz** [comment]
Thanks for starting this discussion @ruflin. Index sorting comes with a number of benefits indeed. The most notable downside is that it comes with a slight indexing throughput penalty, which is the reason why we haven't promoted it much for machine data until now, as we know that a number of users care deeply about ingestion throughput.

This penalty is significant but not crazy either, here is a benchmark that runs daily on the Lucene side: http://people.apache.org/~mikemccand/lucenebench/sparseResults.html#index_throughput. This benchmark is using the nyc_taxis dataset and the baseline (`Dense`) is indexing everything as you'd expect. Then the `Sparse` case uses a different set of fields for yellow taxis (89% of the dataset) and green taxis (11% of the dataset) to see the impact of sparsity. And finally the `Sparse (sorted)` case uses index sorting to partition documents by taxi color in the index, still using different field names based on the taxi color. As you can see on this particular dataset, this incurs a 20% penalty on indexing throughput.

I think early termination is going to not be easy to leverage: Elasticsearch only makes it kick in when the search sort is a prefix of the index sort, which means that if the index is sorted by module, then name, then timestamp, then queries would only be early-terminated when sorting by module, or module then name, or module then name then timestamp, but not when sorting by timestamp alone. However the fact that it colocates documents based on their module+name would help most queries that only look at a single module or a single name since documents would be more likely colocated on disk. In my opinion, we shouldn't try to make early-termination kick in and only use index sorting in order to improve co-colation of documents. Sorting by module then name then host sounds like a good start to me.

The thing that is not clear to me is how many Beats users are maxing out indexing throughput? We might want to be careful about updating the default template if we believe that this number is significant.

**Comment by jpountz** [comment]
Another downside that I'd like to mention for completeness but which doesn't affect Beats to my knowledge is that indices that have index sorting enabled don't allow `nested` fields to be added to the mappings.

**Comment by ruflin** [comment]
Thanks @jpountz for all the details. For indexing throughput I think we have to differentiate two use cases: metrics and logs. I expect on the logging side maxing out indexing is more likely to happen because of peaks. Metrics on the other side are much more predicable as the amount of metrics stays the same independent of the load on a system. We could start experimenting around this with the metrics use case.

For the `nested` objects you are correct that we don't use it anywhere as far as I know.

Thanks to @pcsanwald we now also have a rally track with Metricbeat data. This could be a good place to start experimenting around sorting and see the impact on actual Metricbeat data.

**Comment by jpountz** [comment]
This sounds like a plan.
