### ISSUE TITLE
Heartbeat is not showing the monitor with response code 401 as up

### ISSUE THREAD

**Issue by bhavyarm** [elastic/beats#10971]
For confirmed bugs, please report:
- Version: 6.7.0 BC4
- Operating System: darwin_x_86_64
- Steps to Reproduce: 
Please note I am on trial license with xpack.security.enabled: true but no SSL.

This is a strange one between two BCs. On BC3 - this was my heartbeat config and  http://localhost:9200 showed up as **UP** in uptime UI: 
```
# Configure monitors inline
heartbeat.monitors:
- type: http

  # List or urls to query
  urls: ["http://localhost:9200"]
```

<img width="1920" alt="bc3_up" src="https://user-images.githubusercontent.com/7074629/53512103-f19f6400-3a8f-11e9-9c69-eade8af0bb4c.png">

On BC4: I have the same config again. And http://localhost:9200 is showing up as **DOWN**

```

# Configure monitors inline
heartbeat.monitors:
- type: http

  # List or urls to query
  urls: ["http://localhost:9200"]
```
<img width="1920" alt="bc4_down" src="https://user-images.githubusercontent.com/7074629/53512264-3fb46780-3a90-11e9-99d8-78a02f7a3b14.png">

Also from the docs for 6.7: https://www.elastic.co/guide/en/beats/heartbeat/6.7/configuration-heartbeat-options.html
```
Under check.response, specify these options:

status
    The expected status code. If this setting is not configured or it's set to 0, any status code other than 404 is accepted. 
```

**Comment by andrewvc** [comment]
@bhavyarm is the ES instance returning a 401 in both cases? Looking at the code, the part that checks the status hasn't changed in forever, I suspect those docs were never correct. Will verify later today, but thought I'd throw this out there as an initial thought.

**Comment by bhavyarm** [comment]
@andrewvc yes its 401 in both cases as far as I remember. I don't have that same set up anymore because I am testing BC5 ON 6.7.0. Thanks!

**Comment by andrewvc** [comment]
@bhavyarm looking into this behavior on 6.4, where it seems identical to the latest BC. It also seems that the [code behind this behavior](https://github.com/elastic/beats/blame/master/heartbeat/monitors/active/http/check.go#L99) is very old, and that it is the docs that are wrong.

This is a good outcome as the behavior described by the docs would be strange. There's an argument for all 4xx errors not necessarily being down, but documented behavior of 404 being special is strange and arbitrary.

I'm going to open a docs patch to correctly describe the behavior. 

In my own testing an old version (6.4.0) behaved identically to 6.7. Given that I'm thinking that the discrepancy between BCs was likely due to one test being against ES with security enabled, and one with it not enabled. Please let me know if you are certain that this was not the case and I'll investigate further comparing the actual BCs, but that doesn't seem worth the time given that the latest BC is acting correctly.

**Comment by andrewvc** [comment]
And in fact here is the commit where the behavior was changed https://github.com/elastic/beats/commit/0dbb695cc0d931f6d5782d145045cb277a389838 , but the docs not updated, which gives us a conclusive answer.

**Comment by bhavyarm** [comment]
@andrewvc sounds good to me. Too many releases here. So I am not gonna go back to checking it again :).
