### ISSUE TITLE
[Filebeat] Zeek module pipeline needs an on_failure handler

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#11004]
Without the error handler Filebeat can get into an endless retry loop because Elasticsearch returns an HTTP 500. Here's an example that adds the error to `error.message` and then writes the data to ES.

https://github.com/elastic/beats/blob/76a23773011671cefc0e3f1c5abaebf7033e1915/filebeat/module/apache/access/ingest/default.json#L54-L58

Docs: https://www.elastic.co/guide/en/elasticsearch/reference/master/handling-failure-in-pipelines.html

**Comment by alakahakai** [comment]
Is there a list of the failure scenarios? If the fields are optional, it might be better to handle them directly in the processors by ignoring the errors. If the fields are mandatory, is it possible to control the retries on the beats side, e.g., limit the number of retries and intervals between the retries? Simply logging an error in the event, when the error is temporary on the elasticsearch side, might not be the best option for some failure scenarios, since the required processing won't be done properly.

**Comment by webmat** [comment]
I've always cargo-culted from the docs the example Andrew pasted above, and it's been fine.

Now that I stop and think about it, while [on_failure](https://www.elastic.co/guide/en/elasticsearch/reference/current/handling-failure-in-pipelines.html) can do other things, I think this simple one above strikes a good balance of being helpful and not making any assumptions (such as dumping errors into another index).

So I'd say don't sweat it, and go with the above :-)

**Comment by alakahakai** [comment]
Just an update: this will be addressed in {pull}11105[11105]
