### ISSUE TITLE
Allow CM to control the "SETUP" phase of the beats

### ISSUE THREAD

**Issue by ph** [elastic/beats#11167]
We have two differents "SETUP" phase:

### Install required dependencies by modules

- Make sure templates is installed.
- Make sure Pipeline are correctly installed.
- dashboards.

### Setup of Monitoring and ILM.

CM will send the information about the setup phase using special system configuration blocks.

Beats will do the following setups:

- [ ] On startup: setup will be set to false.
- [ ] If a configuration block contains a system block, beat does the setup with the options.
- [ ] If the setup fails we do not continue.
- [ ] If the setup is successful we start the inputs and the outputs.
- [ ] We set setup to true.
- [ ] System block should not be persisted to disk.

NOTES: Let's take a look where `cloud.id` and `cloud.auth` fit here.

**Comment by jderose9** [comment]
Does this include the setup.template node? I would like to do a couple of things that don't seem currently available:
- append_fields from central management
- change the ilm index name prefix

**Comment by jderose9** [comment]
So yeah, after playing with this, it seems like a rather big issue.

Even though I have an output in CM, if I put setup parameters in the filebeat.yml they do not work as expected, because at the time it tries to use those parameters, it hasn't loaded my output. So, I need to include my output credentials in the filebeat.yml also.

Once I've done that, I still need the output in CM for some reason - it seems to clear the outputs when it loads the management configuration.

Since ILM is enabled by default, if you DON'T have the output credentials in the filebeat.yml, it gets in a weird state where it writes into an index using the non-ilm index pattern, and if filebeats ends up creating an index, it doesn't update the aliases as expected, and you end up with lifecycle errors because there are no aliases with is_write_index: true.

**Comment by ph** [comment]
We have stopped developed CM and we are moving to Agent/Fleet/EPM, the setup phase will be handled by the Elastic Package Manager.

**Comment by jderose9** [comment]
@ph Can you point us at information about those upcoming changes?
