### ISSUE TITLE
libbeat: create index manually when index does not exist

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#11567]
**Describe the enhancement:**

Users may disable [auto_create_index](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docs-index_.html#index-creation), causing indexing failures when this behavior is relied on, like in the default 6.x date-based index configuration `"beat-index-prefix-%{[agent.version]}-%{+yyyy.MM.dd}"`.  In that case, elasticsearch will return a 404 `index_not_found_exception`.

```
PUT _cluster/settings
{"persistent":{"action.auto_create_index":"false"}}
```
triggers:
```
no such index [apm-7.0.0-span-2019.04.01]
```

while:
```
PUT _cluster/settings
{"persistent":{"action.auto_create_index":"foo"}}
```
triggers a more helpful:
```
no such index [apm-7.0.0-span-2019.04.01] and [action.auto_create_index] ([foo]) doesn't match
```

libbeat should try to create the index manually, relying on index templates for mapping, in those cases.

**Comment by urso** [comment]
The JSON response will be something like this: `{"type":"index_not_found_exception","reason":"no such index and [action.auto_create_index] contains [-*] which forbids automatic creation of the index","index_uuid":"_na_","index":"apm-6.6.1-metric-2019.03.19"}`.

On error we need to check the `type` field and use the `index` field as is. Index creation can still fail. Events we managed to create an index for should be retried without backoff. Events that failed otherwise, or index creation failed for should still be subject to default retry logic (in case user dynamically creates index via API while Beats is running).
