### ISSUE TITLE
Enable elastic cloud as output in CBM

### ISSUE THREAD

**Issue by vaivars** [elastic/beats#11990]
**Describe the enhancement:**
Set elastic cloud as an output option, replacing host/auth with cloudid and cloud auth

**Describe a specific use case for the enhancement or feature:**
Unified and logical way of using elastic cloud with CBM.

**Comment by ph** [comment]
We have stopped the development of Central Beats management, the feature is not going away but will be replaced by Fleet. In the context of fleet we will use Elasticsearch's API key instead of cloudid/cloud auth because this give us finer control over the credentials. 

ref: https://github.com/elastic/beats/issues/14485
