### ISSUE TITLE
Metricbeat Doesn't Get ILM Policy via Auto ILM

### ISSUE THREAD

**Issue by dsanders11** [elastic/beats#12563]
- Version: 7.0.1
- Operating System: CentOS 7.4

**Logs**

```
idxmgmt/std.go:165	Set output.elasticsearch.index to 'metricbeat-7.0.1' as ILM is enabled.
idxmgmt/std.go:361	Set setup.template.name to '{metricbeat-7.0.1 {now/d}-000001}' as ILM is enabled.
idxmgmt/std.go:366	Set setup.template.pattern to 'metricbeat-7.0.1-*' as ILM is enabled.
```

Can anyone spot the problem? The template pattern won't match the index name, so the index gets created without the template applying, so ILM doesn't actually apply.

**Comment by ph** [comment]
@dsanders11 Can you share your metricbeat configuration?

**Comment by dsanders11** [comment]
@ph, it was the standard configuration on CentOS 7.4. All I changed was the `cloud.id` and `cloud.auth` settings.

**Comment by webjunkie** [comment]
I figured out I have the same problem. Default config, no special index names set. ILM seems to be enabled automatically and the template seems not to be used because of the pattern mismatch.

**Comment by slothmotion** [comment]
The metricbeat.reference.yml contains the following lines:

> output.elasticsearch:
...
Optional index name. The default is "metricbeat" plus date
and generates [metricbeat-]YYYY.MM.DD keys.
    In case you modify this pattern you must update setup.template.name and setup.template.pattern accordingly.
    index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

The documentation should be updated, the default is "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}" as the example in last line shows.

In addition, I applied the following configurations:

> output.elasticsearch.index: "metricbeat-%{+yyyy.MM.dd}"
setup.ilm.enabled: false
setup.template.name: 'metricbeat-tmpl'
setup.template.pattern: 'metricbeat-*'

According the docs, Metricbeat should create a template with name `metricbeat-tmpl`, but instead it creates the following template (highlighting the important part):

> curl -X GET "localhost:9200/_template/metricbeat*"
"metricbeat": {"order": 1,	"index_patterns": ["metricbeat-*"], "settings": {"index": {"lifecycle": {"name": "default",	"rollover_alias": "metricbeat"} ... }

The problem here:
* the template name is wrong
* it contains a 'default' lifecycle policy, which does not exist as I set `setup.ilm.enabled: false`
* even configures the ILM policy with rollover_alias, which will be identical for all of my daily indices

This issue makes impossible to have a properly working ILM policy for metricbeat, especially a customized one (my main goal was to disable all automated template and ILM policy creation and setup it manually before booting Metricbeat).

**Comment by CodeAdminDe** [comment]
The problem seems to exist. 
At a fresh cluster (kibana 7.8.0, elasticsearch 7.8.0 with metricbeat 7.8.0) after inital import of index_template, ilm-policy, index-pattern and dashboards via `metricbeat setup` command.

At first run of metricbeat to collect data, an index will be created (index: metricbeat-7.8.0) but the template (index patterns: metricbeat-7.8.0-*) won't be applied. 
It was noticed because no rollover index was created and because of this, the ILM Policy was not applied to the index.
Manual application of ILM Policy to the metricbeat-7.8.0 index failed, of course.

Adjusting the template index pattern after creation (before first data collection) seems to be a workaround. But is that a good idea, or does it trigger not yet known problems?

**Comment by abraxxa** [comment]
@Elastic: please check if this problem still exists, for me 7.13 seems to have finally fixed this issue but I also have changed metricbeat_writer rights which might also have been a problem.

**Comment by jsoriano** [comment]
> ```
> idxmgmt/std.go:165	Set output.elasticsearch.index to 'metricbeat-7.0.1' as ILM is enabled.
> idxmgmt/std.go:361	Set setup.template.name to '{metricbeat-7.0.1 {now/d}-000001}' as ILM is enabled.
> idxmgmt/std.go:366	Set setup.template.pattern to 'metricbeat-7.0.1-*' as ILM is enabled.
> ```
> 
> Can anyone spot the problem? The template pattern won't match the index name, so the index gets created without the template applying, so ILM doesn't actually apply.

> At first run of metricbeat to collect data, an index will be created (index: metricbeat-7.8.0) but the template (index patterns: metricbeat-7.8.0-*) won't be applied.

This is expected, but it is important to notice that `metricbeat-7.0.1`/`metricbeat-7.8.0` are not indexes, but aliases that point to the actual indexes whose names match with the template pattern. These indexes are managed by ILM, what also updates the alias when a new write index is created.
On a new installation, or after an upgrade, you will see that you have an alias `metricbeat-<version>`, and indexes named `metricbeat-<version>-<date>-<sequence>`, that match the index pattern.

A common problem with this is that if the alias is manually removed while beats are running, beats will continue trying to write there, and Elasticsearch will create a new index without any mapping. Beats have some checks to detect this kind of situations on startup, and try to solve it or explicitly fail, but they cannot detect them when they are already running, or if ilm is disabled. This alias shouldn't be removed when Beats are running.

>  please check if this problem still exists, for me 7.13 seems to have finally fixed this issue but I also have changed metricbeat_writer rights which might also have been a problem.

7.13.2 had a fix that solved an issue creating the write index the alias points to https://github.com/elastic/beats/pull/26146, so this may actually solve some of the issues caused by manually deleting the alias or the write index.
