### ISSUE TITLE
Tell Filebeat to always retry events, no matter the type of failure

### ISSUE THREAD

**Issue by maxozerov** [elastic/beats#12572]
**Describe the enhancement:**
In some situations, such as running out of disk space, Elastic return _status=403_
But 
`if status < 500 `
See [libbeat - code](https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/client.go#L534)
Filebeat - Just skips the messages, considering them processed.
As for me this is quite critical and need restore events by hand.

**Describe a specific use case for the enhancement or feature:**
We lose all events, all messages from logs.
I turned to a _discuss.elastic.co_:
More information from me is given there.
[filebeat-how-set-always-retry-publish-events](https://discuss.elastic.co/t/filebeat-how-set-always-retry-publish-events/185202) - thx to _Shaunak Kashyap!_

So, Perhaps it is worth making optional settings:
retry events if **hard failure** happened, 
or specify http_error when need to resend (retry) events.

**Comment by ph** [comment]
After discussing this issue in our Triage meeting, we believe that Beats is doing the right thing in this scenario and allow beats to not become deadlocked. We assume that _403 Forbidden error_ is a fatal  and we won't retry. The idea here if the situation can be recovered Elasticsearch should not return a 403.

**Comment by ph** [comment]
related to https://github.com/elastic/elasticsearch/issues/49428

**Comment by mattiagalati** [comment]
I don't want to bother or anything, just I stumbled upon a scenario that might need a deep reflession on Filebeat behaviour: during some tests with Filebeat, my Elastic runned out of disk space.

Immediately after that, Elastic put the index where I want to write to "read only" and then, every other subsequent attempt of Filebeat to publish events resulted in a 403 error.

Maybe the "read-only" index is a feature that could be enabled programmatically or at will, but in this case Elastic did it to protect itself, and I'm ok with that. On the other hand, unfortunately, Filebeat did 3 attempts and then dropped the event since considered the 403 as an, unrecoverable, hard failure.

That said, even if I proceed to free space on the disk, that events will not be recovered anymore from Filebeat.

**Comment by archon810** [comment]
I, too, would love a feature to keep retrying longer, with a backoff. 

For example, we were doing some migrations and ran into stuff like this:
```
2023-02-09T15:02:43.460-0800   ERROR   [publisher_pipeline_output]     pipeline/output.go:180  failed to publish events: Post "http://XXXXXXXXXX:9200/_bulk": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2023-02-09T15:02:43.792-0800    ERROR   [elasticsearch] elasticsearch/client.go:226     failed to perform any bulk index operations: Post "http://XXXXXXXXXX:9200/_bulk": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2023-02-09T15:02:44.944-0800    ERROR   [publisher_pipeline_output]     pipeline/output.go:180  failed to publish events: Post "http://XXXXXXXXXX:9200/_bulk": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

These timeouts were temporary and I didn't want to lose the data because of them.

Alternatively, can filebeat be instructed to reprocess all input files and find what it may have missed, without creating dupes?

**Comment by archon810** [comment]
Wait, does filebeat retry indefinitely or not? https://www.elastic.co/guide/en/beats/filebeat/7.17/elasticsearch-output.html#_max_retries

```
max_retries
Filebeat ignores the max_retries setting and retries indefinitely.
```
