### ISSUE TITLE
APM server Docker image

### ISSUE THREAD

**Issue by barkbay** [elastic/beats#12686]
Hi,

I have opened the ~[following PR](https://github.com/elastic/apm-server/pull/2325) on the APM project~ [following PR](https://github.com/elastic/beats/pull/12905) because the Docker image of the APM server can't be run on Openshift.

I would like to have your thoughts on this PR since it would allow the [ECK](https://github.com/elastic/cloud-on-k8s) project to deploy the APM server on Openshift _(or on any Kubernetes cluster with some restricted PSP btw)_ It's just about adding some permissions to users who are in the `root` group. Unless there are some good reasons to do so I'm not sure it is a good idea to run the APM server in the privileged SCC as it is described [here](https://www.elastic.co/guide/en/beats/filebeat/master/running-on-kubernetes.html#_red_hat_openshift_configuration).

Thank you !

**Comment by barkbay** [comment]
Hi,

Just a heads-up, this is a blocker for the deployment of the apm server on Openshift and with ECK.

Thank you

**Comment by urso** [comment]
The files you adapted are templates. The Docker image builder uses the templates, so to build per Beat specific images. The apm-server project vendors files from Beats, which means that any modifications must be made in the Beats project.

Setting `ENV BEAT_STRICT_PERMS "false"` is quite a big ask. This would remove security check requiring the config files to be owned by the user starting the Beat. Also for non OpenShift users. Why not set the environment variable when starting the container, instead of fixing it in the docker image?

**Comment by barkbay** [comment]
We can set `ENV BEAT_STRICT_PERMS` in ECK at runtime.
I have opened a new PR [here](https://github.com/elastic/beats/pull/12905).

**Comment by barkbay** [comment]
Fixed with #12905
