### ISSUE TITLE
Auditbeat fields does not contain a field to show user who triggered alert for file integrity monitoring 

### ISSUE THREAD

**Issue by echibuogwu** [elastic/beats#12761]
To enable us know user who made changes to a file or folder in the file integrity monitoring

**Comment by iArtur** [comment]
UP

**Comment by echibuogwu** [comment]
Sorry i don’t get you iArtur

**Comment by iArtur** [comment]
It's  just a way to saying that i'm having this problem as well

**Comment by wajahatraza** [comment]
I have same query from Auditbeat FIM that when a user deletes file/folder, the event generated from auditbeat does not show the user name who deleted this file. However if we use Auditd filters, events shows who deleted the file. Is there any way we can modify anything to get username from File integrity module?

**Comment by andrewkroh** [comment]
The file_integrity module tells you when a file changes, but does not tell you information about the user that made changes. None of the OS [APIs used to monitor](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-file_integrity.html#_how_it_works_2) the changes provide this detail.

If you need to monitor the user that makes the changes then use the operating system's auditing features. On Windows you can setup a file auditing policy and then collect the audit events with Winlogbeat https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder. On Linux you can use the auditd module that's part of Auditbeat.

It would take some big changes to get this level of data in the FIM module since you need to get this data from the kernel and we'd want to implement it for each OS. So I recommend using the OS'es audit mechanisms if you need to know the user.

**Comment by willemdh** [comment]
@andrewkroh , I was playing around with Elastic Endpoint Security on my home test Windows 10 system and noticed the endpoint file events do contain a user.name and process.name field. (Which is awesome)

![image](https://user-images.githubusercontent.com/6462991/103461267-59bed100-4d1d-11eb-8716-cb639777b259.png)

Not sure how it is done (documentation about the endpoint datastreams seems very limited) and what this means for the Auditbeat file integrity module.

**Comment by Jonas-268** [comment]
> The file_integrity module tells you when a file changes, but does not tell you information about the user that made changes. None of the OS [APIs used to monitor](https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-file_integrity.html#_how_it_works_2) the changes provide this detail.
> 
> If you need to monitor the user that makes the changes then use the operating system's auditing features. On Windows you can setup a file auditing policy and then collect the audit events with Winlogbeat https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/apply-a-basic-audit-policy-on-a-file-or-folder. On Linux you can use the auditd module that's part of Auditbeat.
> 
> It would take some big changes to get this level of data in the FIM module since you need to get this data from the kernel and we'd want to implement it for each OS. So I recommend using the OS'es audit mechanisms if you need to know the user.

But how do you get the information that a file or folder was created in windows? 
If i create a new folder C:\monitored path\test i get a create child 4656 Event on C:\monitored path\new folder and a 4663 delete event on C:\monitored path\new folder. But C:\monitored path\test does not appear in the eventlog until something else happens with it, like deletion.
