### ISSUE TITLE
Metricbeats http module does gives error for parsing json.

### ISSUE THREAD

**Issue by syedsfayaz** [elastic/beats#13137]
I am using metricbeat to parse jenkins build parameters. I am using http module. But I am seeing error. 

Please post all questions and issues on https://discuss.elastic.co/c/beats
https://discuss.elastic.co/t/error-metricbeat-sending-json-data-to-elastic-search/192582

Also tried the solution in the github link which does not work. 
https://github.com/elastic/beats/pull/8292

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  7.2
- Operating System:  RehHat
- Discuss Forum URL: https://discuss.elastic.co/t/error-metricbeat-sending-json-data-to-elastic-search/192582
- Steps to Reproduce:

**Comment by jsoriano** [comment]
Hi @syedsfayaz,

I [see in the topic](https://discuss.elastic.co/t/error-metricbeat-sending-json-data-to-elastic-search/192582/15?u=jsoriano) in discuss that you managed to get the event, but it had some unparsed fields. This `actions` field is a list of objects, what can be problematic to store.

Were the rest of fields parsed correctly?

**Comment by syedsfayaz** [comment]
Not all the fields parsed correctly. As you see the actions fields are not parsed. As mentioned  in this link. https://www.elastic.co/guide/en/elasticsearch/reference/7.3/nested.html Can you guide me how I can use this nested data type. Do I need to add these settings in http.yml?

**Comment by jsoriano** [comment]
Yeah, I think that all fields that are arrays of objects, as `actions`, or this `parameters`, are not going to be correctly handled by Beats and/or Elasticsearch.

The use of nested types may need further development, because they are not completely supported by Beats and Kibana.

I think there is no good solution at the moment for the data you want to collect.

One option to support it would be to handle arrays of objects in the `http` module, but it is not clear what should be done in this case, and how to do it in a generic way. Another option would be to implement a jenkins [module](https://www.elastic.co/guide/en/beats/devguide/7.3/creating-metricbeat-module.html), or [community beat](https://www.elastic.co/guide/en/beats/devguide/7.3/new-beat.html), to collect this information.

**Comment by syedsfayaz** [comment]
Can Logstash parse this data?

**Comment by jsoriano** [comment]
> Can Logstash parse this data?

I think that with logstash the problematic is similar, it is not clear what to do with fields that are lists of objects.

**Comment by syedsfayaz** [comment]
I mean I can write some curl command or some python/power shell script to get what exactly values I need from the jenkins api and then pass those to log-stash.

**Comment by jsoriano** [comment]
@syedsfayaz if you use an external script to create the event with the values you want, you can also use the [HTTP server metricset](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-http-server.html) of Metricbeat to send these events to Elasticsearch.
