### ISSUE TITLE
filebeat flag to disable deviceId as part of the file identification in the registry

### ISSUE THREAD

**Issue by frueht68** [elastic/beats#13314]
Based on the issue we described in [discuss](https://discuss.elastic.co/t/deviceid-changes-of-the-drive-where-filebeat-reads-log-produces-a-lot-of-duplicate-log-messages/196310)
, we added a flag `ignore_device_id` to the filebeat log input configuration, which allows to disable the deviceId in the registry. This is done by setting the deviceId always to `0`.
The first version of the implementation can be seen here: https://github.com/breml/beats/tree/ignore-device-id

**Comment by breml** [comment]
I am the author of said workaround in https://github.com/breml/beats/tree/ignore-device-id. It was a rather quick implementation and it does not include any tests. The idea is to gain some experience in our integration environment to find out, if the workaround does in fact work.

**Comment by breml** [comment]
@ph @urso I had a chat with @ruflin about above mentioned change to filebeat and he encouraged me to create a PR for the further discussion.

I look forward to your feedback.

**Comment by johnhoughton-v** [comment]
I would like to see this made available. 

My use case is this: filebeat is running in a scripted AWS instance that is prospecting from an dedicated AWS volume. During an update/upgrade, the instance is rebuilt, and the AWS volume is reattached to the new instance (remounted by AWS volume id).  But, since the filebeat's calculates a different device id, all of the existing files are re-prospected.  (in my case, duplicates are not the issue, rather it could take days to reprocess all of the data.)

Making filebeat able to detect that the same volume is remounted, or making it ignore device id changes would be very helpful.

**Comment by breml** [comment]
@kvch, @frueht68: I was not yet able to verify if the new functionality introduced in #18748, but I think we can close this one.

**Comment by kvch** [comment]
@breml You are right. Thank you for the ping.
