### ISSUE TITLE
Metricbeat docker dashboard missing containers

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#13462]
Using metricbeat with docker autodiscover, the kibana dashboard is loaded but displays incomplete data.
In the following image it shows 9 containers are running, but only 5 are displayed on the left table (Docker containers), also the memory usage is missing 4 containers:
![Docker_dashboard](https://user-images.githubusercontent.com/22418250/64079059-595a9400-cceb-11e9-9e91-76d191e91a3e.png)

After adding a filter for a missing container, it is correctly displayed in the top left table :

![Docker_dashboard_filter](https://user-images.githubusercontent.com/22418250/64079075-8eff7d00-cceb-11e9-954b-2d27240c1ce0.png)

It seems that the missing containers from graphs have low values and have been omitted, which is acceptable, but the top left table should contain **all containers.** 
As you can see from the filtered dashboard, the container has data values that are higher than some of displayed containers (CPU, Mem RSS), thus is relevant to be displayed.

Elastic stack 7.3.0

**Comment by odacremolbap** [comment]
@cdalexndr thanks for the issue.

Please, consider creating an issue at https://discuss.elastic.co/c/beats before opening one here.
We usually limit aggregated data at visualizations in order to fit most scenarios. Top 5 (ordered by most significative metrics) is the most common used strategy.

For nodes with many containers showing all of them at the table or at any other visualization, would at the very least make the dashboard large, and most probable hard to read.

If you think that shouldn't be the default let's discuss it at the link provided at this post. If you want to change it for your scenario, you can edit the visualization and change the terms aggregation to display more items, and optionally paging the table.

**Comment by cdalexndr** [comment]
The problem is that sorting the table using a header column will only sort the displayed containers, even though they are not the most relevant for that sorted column. Thus, relevant containers will be skipped.

**Comment by cdalexndr** [comment]
Opened issue regarding to table sorting: https://github.com/elastic/beats/issues/13529

**Comment by cdalexndr** [comment]
For clarity, the dashboard visualization headers where only the top N containers are shown should be prefixed with _Top_.
Docker containers -> Top docker containers
Memory usage -> Top memory usage
