### ISSUE TITLE
Document more precisely the supported operating systems

### ISSUE THREAD

**Issue by tsg** [elastic/beats#135]
We should make it clear on which Linux distros and other OSes is Packetbeat and other beats running.

Current tests show that our binaries work on:

* Debian 6
* Debian 7
* CentOS 6
* CentOS 7
* Ubuntu 12.04
* Ubuntu 14.04
* OS X

**Comment by dedemorton** [comment]
Is this something that we want to add to the product documentation or a support matrix somewhere?

**Comment by dedemorton** [comment]
@tsg I'm not sure if this fully addresses your concerns, but the PR referenced above adds a link to the support matrix: https://www.elastic.co/support/matrix. If this is sufficient, you can close this issue. If it's not, then I think we should add clarification to the support matrix rather than trying to add this to the doc.

**Comment by dedemorton** [comment]
Closing as we now point to the support matrix for the list of supported OSs.
