### ISSUE TITLE
Make filebeat pub/sub input work with Google pub/sub emulator

### ISSUE THREAD

**Issue by jbogp** [elastic/beats#13511]
Hello

**Describe the enhancement:**
Google makes a pubsub emulator available for local development, https://cloud.google.com/pubsub/docs/emulator
I've tried to make the pub/sub filebeat input work with it by exporting the environment variables PUBSUB_EMULATOR_HOST and PUBSUB_PROJECT_ID inside the container running filebeat (following the emulator documentation linked above), unfortunately filebeat still crashes with a "missing API key" error which seems to indicate the pub/sub library used doesn't take into account the possibility of an emulator

**Describe a specific use case for the enhancement or feature:**
This would be NTH to be able to develop the pipeline entirely locally without relying on a real pub/sub instance. Also the emulator is an official Google product so it's maintained and here to stay.

**Comment by andrewkroh** [comment]
The emulator is used by the pubsub input's integration tests so it works with it. In order to satisfy Filebeat's config validation try setting the `credential_file` option to a dummy value like the tests do and see if that works.

https://github.com/elastic/beats/blob/56103a3303cdd01ca3773c88a77d03244e32cdbc/x-pack/filebeat/input/googlepubsub/pubsub_test.go#L205

**Comment by jbogp** [comment]
Thank you that worked.
