### ISSUE TITLE
[Filebeat] PANW module: TCP with TLS support

### ISSUE THREAD

**Issue by d0b3rm4n** [elastic/beats#13533]
**Describe the enhancement:**
PANW syslog module currently just listens on UDP port, for syslog messages from the Palo Alto firewall.
Would it be possible to support also TCP with the support of TLS/SSL?

Sending firewall syslog messages with sensitive info over the network unencrypted, is in my opinion not state of the art any more. That might be fine for some testing in a lab but not for some more serious testing in a real network, with real data, even the module is marked as BETA. And TCP provides some better reliability in the network.

**Describe a specific use case for the enhancement or feature:**
Operate the firewall in local premises, while the ELK stack with filesbeat runs in the cloud. (not in the same network, no VPN in between)

**Comment by andrewkroh** [comment]
The Filebeat syslog input does have support for TCP and TLS (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-syslog.html). But these settings are not currently configurable through the module variables at the current time.

As a workaround you could modify the `module/panw/panos/config/input.yml` file that's include in the Filebeat distribution to change the `protocol.udp` to `protocol.tcp`. Like

```
type: syslog
protocol.tcp:
  host: "{{.syslog_host}}:{{.syslog_port}}"
  ssl.certificate: server_cert.pem
  ssl.key: server_key.pem
```

**Comment by MorrieAtElastic** [comment]
@andrewkroh if customers were to change the protocol from UDP to TCP themselves, would this be considered supported? After the panw module becomes GA, I mean.

**Comment by andrewkroh** [comment]
If it's just a change to the protocol I don't see any issue in supporting this. It also shouldn't be much work for us to expose these knobs through the module's `var.X` config.

**Comment by willemdh** [comment]
@andrewkroh We seem to be loosing about 15% of our panw logs when using the panw module with udp. There is no trace in any log when or why these events are lost. I will try to find some to test changing the filebeat panw udp input to tcp.

**Comment by willemdh** [comment]
@andrewkroh Is there any plan to allow tcp with ssl support for the panw input? These logs are far too critical to send them in cleartext..

**Comment by willemdh** [comment]
@andrewkroh Just wanted to add that for testing purposes, I tried to configure IETF format instead of BSD, as that is the recommended by Palo Alto when sending syslog over TCP. (https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/configure-syslog-monitoring)

Configured it Tuesday and ingestion seemed to work at first sight, but today I was alerted by our Logstash PR node's disk filling up fast and apparently I'm getting huge amount of "can't parse event as syslog rfc3164" errors since we updated the syslog format to IETF from BSD.

`Nov 22 12:32:21 logstashnode filebeat: 2020-11-22T12:32:21.274+0100#011ERROR#011[syslog]#011syslog/input.go:239#011can't parse event as syslog rfc3164#011{"message": "517 <14>1 2020-11-22T12:32:21+01:00 PANODE - - - - 1,2020/11/22 12:32:20,013101001305,TRAFFIC,end,2049,2020/11/22 12:32:20,5.68.15.103,1.5.1.2,0.0.0.0,0.0.0.0,A_DST_CP_and_NS,,,dns,vsys1,Data,Trst-Servers,ae1.182,ae2.493,Panorama,2020/11/22 12:32:20,36815306,1,38072,53,0,0,0x19,udp,allow,25,8,163,2,2020/11/22 12:31:51,0,any,0,6891267525836876234,0x8000000000000000,10.0.0.0-10.255.255.255,10.0.0.0-10.255.255.255,0,1,1,aged-out,0,0,0,0,Core,PA52,from-policy,,,0,,0,,N/A,0,0,0,0"}`

**Comment by cb1234** [comment]
i have the same issue . getting "can't parse event as syslog rfc3164" errors after enabling IETF with tcp/ssl

**Comment by Whysmerhill** [comment]
Same issue here, if we activate IETF with udp we get a lot of error "can't parse event as syslog rfc3164" for TRAFFIC & THREAT logs. This issue disappear if we go back to BSD format.

**Comment by smandolare** [comment]
TLS for PANW is required for ingesting logs from the Cortex Data lake as they will only ship via verified TLS connections. Used in conjunction with a local Panorama or NGFW device, multiple module inputs would be required. 
- Can the TLS parameters be added as supported?
- Can the module be defined twice with different parameters to support each of Cortex and On-prem log sources to the same beat?

Thanks

**Comment by jamiehynds** [comment]
We're currently in the process of adding support for TCP and TCP+TLS for Palo Alto, and all other firewall integrations. I'll close this issue out in favour of the issue we're currently working on: https://github.com/elastic/integrations/issues/1878
