### ISSUE TITLE
Add pod restarts to kubernetes module

### ISSUE THREAD

**Issue by ceastman-ibm** [elastic/beats#13717]
**Describe the enhancement:**
Can the number of pod restarts be added to the kubernetes module?

**Describe a specific use case for the enhancement or feature:**
This would be useful in tracking if bad code is causing the pods of a microservice to constantly restart.

**Comment by kaiyan-sheng** [comment]
maybe @odacremolbap ?

**Comment by odacremolbap** [comment]
@ceastman-ibm there is already an `state_container` metricset that retrieves kube-state-metrics `kube_pod_container_status_restarts_total` as `status.restarts`.

You will need to deploy kube-state-metrics and configure as stated here: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kubernetes.html

Also, please, consider the [discuss forum](https://discuss.elastic.co/c/beats) for these kind of questions, since it is a lot more probably that someone from the community can ask and provide further info and experience.

**Comment by ceastman-ibm** [comment]
i found the metric thank you.

**Comment by ceastman-ibm** [comment]
@odacremolbap yep i see that restarts is in the kube-state-metrics but that requires a separate install of the kube state metrics microservice, i think it would be nice if pod restarts as added to the metricbeat.modules: kubernetes module so we dont need to have a separate installation.

**Comment by odacremolbap** [comment]
@ceastman-ibm thanks for that comment

`kube-state-metrics` is upstream maintained as a subproject at SIG-Instrumentation. I don't think it  is going too far saying that it is the canonical way of retrieving metrics that would be used to conform dashboards and alerts.

The recommended request resources for `kube-state-metrics` are 200MB memory 100m cores, for a production cluster under 100 nodes. That sounds lightweight.

**Comment by odacremolbap** [comment]
@ceastman-ibm I will close this issue. We recommend using `kube-state-metrics`
If there is something you are missing not provided at this moment, we encourage you to open a new issue so we can discuss it.

Thanks for being an active part of Beats
