### ISSUE TITLE
Issues running Filebeat on Windows

### ISSUE THREAD

**Issue by jmcinnis** [elastic/beats#1391]
Hi, I have a Windows 7 Client VM that I'm trying to run Filebeat on. I can run "Start-Service filebeat" without getting any errors, but when I look at the log file, it's having a connection failure. My ELK Stack is running on CentOS and I also have a CentOS Client VM which connects fine. I have attached screenshots of my filebeat configuration file as well as the log file.

![screenshot 2016-04-13 22 27 24](https://cloud.githubusercontent.com/assets/18019365/14515448/3bcbe5ca-01c8-11e6-99d0-6e772059d0f6.png)
![screenshot 2016-04-13 22 27 07](https://cloud.githubusercontent.com/assets/18019365/14515450/3f465046-01c8-11e6-8623-689ee3a6561e.png)

**Comment by andrewkroh** [comment]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there.

When you post to Discuss, please paste your logs and configs rather than posting screenshots. It makes it easier for us to test your config and for others to find similar issues when searching.
