### ISSUE TITLE
Use new Kibana Saved Objects API in place of Dashboard Import/Export API

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#14196]
Taken from https://github.com/elastic/kibana/issues/41439:

> The [dashboard import/export API](https://www.elastic.co/guide/en/kibana/current/dashboard-import-api.html) has been superseded by the [saved objects import/export API](https://github.com/elastic/kibana/issues/16831)

> Since this change introduces a new API endpoint and file format (`json` -> `ndjson`), dashboards will have to be re-exported using the new API.

Beats code needs to be enhanced to use the new API, depending on the Kibana version the Beat is talking to. Also, dashboards need to be redone to use the new format.

**Comment by andresrc** [comment]
On hold.

**Comment by exekias** [comment]
It would be nice to retake this, after a few discussions I think this is where we are now:

- We want to implement the objects API as an alternative way to import dashboards, deprecating the old method in 8.0. This means the `setup` command will keep working in 8.0, using the new API.
- In order to do that, we will need to convert existing dashboards, @mtojek has done this already in the beats-import script. My understanding is that we will need to keep both original format and the new one (autogenerated) during 7.x. Then switch to saved objects format only in 8.0.

**Comment by exekias** [comment]
about dashboards, I guess we could keep developing them as we do now during the 7.x timeframe, adding some scripting to automatically convert those into the new format

**Comment by pgayvallet** [comment]
Reopening. See https://github.com/elastic/beats/issues/20672, this is still required, and the deadline is getting close.

**Comment by joshdover** [comment]
I believe this and #20672 are duplicates. I am going to close this issue in favor of the other which has more details.
