### ISSUE TITLE
Packetbeat AMQP support is not documented

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1434]
We support AMQP since this [PR](https://github.com/elastic/beats/pull/768) but it doesn't seem to be mentioned at all in the docs.

**Comment by monicasarbu** [comment]
For this we just need to document the configuration options for AMQP under: https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-protocols.html. 

@Keylor42 would you be interested in helping us with the AMQP documentation?

cc-ed @dedemorton

**Comment by Keylor42** [comment]
I can. How should I proceed ?

**Comment by andrewkroh** [comment]
* [ ] We need to add AMQP [here](https://github.com/elastic/beats/blob/master/packetbeat/etc/fields.yml#L1458) and run `make update` so that AMQP shows up in the fields documentation.
* [ ] And then document AMQP and its configuration options in  https://raw.githubusercontent.com/elastic/beats/master/packetbeat/docs/reference/configuration/packetbeat-options.asciidoc
