### ISSUE TITLE
CI fails on metricbeat couchbase test

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#14562]
Per https://github.com/elastic/beats/pull/14543#issuecomment-554552040

```
21:21:06 compose.service: ERROR: 404 Client Error: Not Found ("pull access denied for docker.elastic.co/observability-ci/beats-integration-couchbase, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")```
```

**Comment by jsoriano** [comment]
I have been investigating this issue and I could reproduce it locally, but got mysteriously fixed after a `docker system prune`, so not sure what can be happening. It seems to happen only in jenkins and not in travis, it can be something with the local docker cache.

**Comment by kuisathaverat** [comment]
related to https://github.com/elastic/beats/issues/14660

**Comment by kuisathaverat** [comment]
We have three options:
* to login on the docker registry before access to the Docker image, also
* Put the image in the Packer cache
* Move this image to a namespace without authentication

**Comment by kuisathaverat** [comment]
there is another issue here, there is not a `docker.elastic.co/observability-ci/beats-integration-couchbase` image pushed

**Comment by jsoriano** [comment]
Error log in #14660 is confusing. We first try to pull images ignoring all errors, but these ignored errors are the ones being logged.

The important part of this error log I think that is the following one. This happens when the container starts (so the image is available), but it finishes before being healthy:
```
09:12:17 Exception: Container couchbase_1 unexpectedly finished on startup
```

The problem seems to be then on the container startup, not with the availability of the image. Although, I saw this happening in my machine and it got solved by doing some cleanup in my docker, what implied to regenerate the image, so maybe we have something flaky in the image creation itself.

**Comment by jsoriano** [comment]
> there is another issue here, there is not a `docker.elastic.co/observability-ci/beats-integration-couchbase` image pushed to `docker.elastic.co`

We have to continue adding `supported-versions.yml` files for that (https://github.com/elastic/beats/issues/14606).
