### ISSUE TITLE
Managing templates when using Logstash is hard

### ISSUE THREAD

**Issue by jarpy** [elastic/beats#15138]
**Describe the enhancement:**
Automatic template management works really well when using the Elasticsearch output, but is not available when using the Logstash output. 

The documentation states that the operator is responsible for manually loading the template into Elasticsearch before shipping traffic. That's probably fine in a small-scale, low dynamism environment, but it quickly becomes difficult to arrange for in (for example) a large, fast changing Kubernetes environment.

Indeed, in such an environment, it may be difficult for the operator to even know which Beats, at which versions, are targeting which Elasticsearch clusters (at which versions), but the Beats themselves know all that and can make it easy.

Possible solutions:

The ultimate user experience would probably be if the Logstash output behaved exactly like the Elasticsearch output, and simply took care of loading the template with no further configuration required. I recognize that this would be difficult to implement within the constraints of the Lumberjack protocol.

A compromise solution might be to enable the user to declare both the Logstash and the Elasticsearch output, but with the Elasticsearch output having some kind of `setup_only` flag that would enable template (and ILM) management before letting traffic flow through the Logstash output. This tightly couples knowledge of the Elasticsearch cluster to the Beat, which is a shame, but maybe it would be simpler to implement?

**Describe a specific use case for the enhancement or feature:**

My team runs an event processing pipeline based on Logstash that has a large fleet of Beats with heterogeneous versions as inputs, and a collection of Elasticsearch clusters (also at different versions) as destinations. Manually maintaining a matrix of all the version combinations and automating the loading of templates would be a pretty nasty experience. It would also be difficult to ensure that the templates are always loaded before any Beats traffic was allowed to arrive in an Elasticsearch cluster, thus creating documents with the wrong mapping.

**Comment by ph** [comment]
@jarpy I do understand the pain of managing templates, especially when using Logstash in the middle. Concerning your suggestion, we did consider to allow the beats to send a command to Logstash like "Please install this set of templates" as part of lumberjack v3, but we haven't added that to our roadmap.

> A compromise solution might be to enable the user to declare both the Logstash and the Elasticsearch output, but with the Elasticsearch output having some kind of setup_only flag that would enable template (and ILM) management before letting traffic flow through the Logstash output. This tightly couples knowledge of the Elasticsearch cluster to the Beat, which is a shame, but maybe it would be simpler to implement?

A setup only option is somewhat possible today by using the **setup** subcommand and using a few `-E` flags.

```
./filebeat setup --index-management -E "output.logstash.enabled=false" -E "output.elasticsearch.host=localhost"
```

Now, where are we going with that?  I do not think in the short term we will add a `--setup-only` flags or support multiples output to do that. Because we want to move all the module's definition to Kibana. And for us, the _template_ must is an important part of the definition (See the Elastic Package Manager). 

When this happens, installation and upgrade will be managed by a single place actually removing the problem between beats and Logstash.
