### ISSUE TITLE
Elasticsearch Input

### ISSUE THREAD

**Issue by strawgate** [elastic/beats#15273]
**Describe the enhancement:**
Similar to how Logstash has an Elasticsearch Input where you can define a custom DSL query it would be useful to have an input for Filebeat that allows making arbitrary queries against Elasticsearch, can run the documents through the Filebeat processors and then output them via the Beats/Logstash/Elasticsearch protocols.

**Describe a specific use case for the enhancement or feature:**
Replace Logstash for use-cases where Elasticsearch is queried, the documents are processed, and then sent back to Elasticsearch or some other tool.

**Comment by ph** [comment]
@strawgate this is a good suggestion but have you tried using the [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) API and an ingest pipeline? With these two you can achieve the majority of the transformation? But the output is limited to Elasticsearch only.

**Comment by strawgate** [comment]
The big advantage to this would be to move data between Elasticsearch instances in a similar way to how you can do it with logstash today

Elasticsearch <-Poll- (Logstash Elasticsearch Input -> Logstash Elasticsearch Output) -Push> Elasticsearch

This would allow removing of Logstash in this scenario:
Elasticsearch <-Poll (Filebeat Elasticsearch Input -> Filebeat Elasticsearch Output) -Push> Elasticsearch

**Comment by ph** [comment]
@strawgate You can already move data between Elasticsearch cluster using the reindex API, with that you can both remove Logstash and Beats from the equation.

See our documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#reindex-from-remote

Also, the feature is built with the tasks system in Elasticsearch which allows you to query what is the status of the jobs. 

Because of Logstash and the Elasticsearch's reindex API used with the ingest pipeline. I don't think it's necessary to add that feature to Filebeat, I don't see what  Filebeat would add more to the mix since outputs to other systems are limited if you compare that to Logstash.

So If the alternative works for you I would be more inclined to close this issue. WDYT?

**Comment by strawgate** [comment]
For our particular use-case it would not work as the remote reindex api request has to be initiated from the destination Elasticsearch server and cannot be initiated from the source Elasticsearch server (i.e. a Pull instead of a Push).

For regulatory compliance reasons we have different security zones and cannot initiate inbound connections from the low security zone into the high security zone.

This could also be paired with a beats UDP output to support pushing data through a [data diode](https://en.wikipedia.org/wiki/Unidirectional_network) to another beat listening over UDP on the other side.

**Comment by ph** [comment]
@strawgate Thanks for the clarification about your use-case, I will leave this issue open.

**Comment by strawgate** [comment]
I think this is an open feature request

**Comment by strawgate** [comment]
This is an open feature request

**Comment by strawgate** [comment]
Still an open feature request
