### ISSUE TITLE
Evaluate options for Kerberos auth

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#15619]
We have outstanding requests (#5413, #7404) to add Kerberos support for the communication with both Elasticsearch and Kafka.

The goal of this issue is to evaluate the currently available options and define an action plan.

Some considerations:
* The client library that we are using for Kafka seems to have added [some support](https://github.com/elastic/beats/issues/15618)
* The preference would be to use the same library for both Elasticsearch and Kafka

**Comment by kvch** [comment]
Two years ago there was another round of research regarding which Kerberos library to use: https://github.com/elastic/beats/issues/7404

The lib selected by @andrewkroh is called [github.com/jcmturner/gokrb5](https://github.com/jcmturner/gokrb5). Since then, the lib has matured a lot and is still maintained. New releases are available regularly. Furthermore, sarama uses this library of v7.5.0. So by choosing this lib, we would be able to support Elasticserach and Kafka using one dependency.

There are a few honourable mentions out there both pure Go and with CGO. But all of those are abandoned. So I would not opt for those.

All in all, I agree with the choice of Andrew.

@urso WDYT?

**Comment by urso** [comment]
Sounds good. +1 using gokbr5.

**Comment by kvch** [comment]
Closing as a desicion has been made to use `github.com/jcmturner/gokrb5`.
