### ISSUE TITLE
Add option to easily disable outputs

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1589]
One currently needs to comment out the whole section to disable an output. Because metricbeat has the option to use `enable: false` to quickly disable modules, it makes sense to add the same for the outputs at libbeat level.

**Comment by tsg** [comment]
Loosely related to #1417.

**Comment by drenalin23** [comment]
Any idea why this was removed from filebeat before 1.0.0 version?  It made it into the filebeat cookbook (which now doesn't work as expected by reading the docs) and would be an *extremely* useful option when working configuration management to have a toggle for nodes/roles/environments instead of having to add/remove/comment out entire sections.  Sorry if I'm ignorant of the overall architecture but hoping that adding this back to libbeat might push it upstream to filebeat.

In my use case I was rolling out filebeat to several environments, so wanted to setup the same config everywhere and then rollout it one environment at a time, planning on setting enabled to true as I went along.

**Comment by drenalin23** [comment]
For reference if this is implemented it is useful in the chef supermarket cookbook.  https://github.com/vkhatri/chef-filebeat/issues/55

**Comment by andrewkroh** [comment]
Original proposal to remove: https://github.com/elastic/libbeat/issues/264

Summary: We had both `enabled` and `disabled` options with varying defaults and it was confusing. Adding back just `enabled` should be fine if the default is consistent everywhere that it is used.

**Comment by tsg** [comment]
This should be done now in master.
