### ISSUE TITLE
[Filebeat] pods on new nodes sometimes don't detect the Kubernetes environment

### ISSUE THREAD

**Issue by jameshiew** [elastic/beats#16064]
For confirmed bugs, please report:
- Version: filebeat-oss:7.1.2
- Operating System: Linux
- Discuss Forum URL: N/A
- Steps to Reproduce: 

We sometimes see logs like the below in filebeat pods when starting up a k8s node

```
add_kubernetes_metadata: could not detect kubernetes env: Get https://<ip>/version?timeout=32s: dial tcp <ip>: i/o timeout
```

All logs from that node then don't have k8s metadata attached (e.g. `kubernetes.pod.name`), until the `filebeat` pod is recycled, and we see a log line like the following

```
add_kubernetes_metadata: kubernetes env detected, with version: v<k8s version>
```

It would be good to have some sort of retry/timeout configurability around here this bit of code in the `add_kubernetes_metadata` processor

https://github.com/elastic/beats/blob/75ddc22031b5cb4e1a881216a9fd452040f16230/libbeat/processors/add_kubernetes_metadata/kubernetes.go#L118-L120

We only get one shot at detecting Kubernetes at start up, but it seems filebeat can progress past this before a node is fully ready(?).

**Comment by ChrsMark** [comment]
Hey @jameshiew and thank you for reporting this!

The proposal of having the processor to give more attempts before failing sounds good to me.

However we should consider the limits to this so as to avoid having busy-wait situations in case of k8s environment does not exist, since this processor is enabled by default for Filebeat. 

@exekias @odacremolbap any comments?
cc: @jsoriano who might be interested in this as well

**Comment by jsoriano** [comment]
> The proposal of having the processor to give more attempts before failing sounds good to me.
> 

Sounds good to me too.

> However we should consider the limits to this so as to avoid having busy-wait situations in case of k8s environment does not exist, since this processor is enabled by default for Filebeat.

We could maybe make an asyncronous initialization of the processor, so the kubernetes availability check and the watcher initialization are retried in a separate goroutine.
Meanwhile calls to run won't enrich anything, or maybe we can try to keep them on hold (not sure what would happen if we do that).

**Comment by ChrsMark** [comment]
Tried to get it fixed with https://github.com/elastic/beats/pull/16373. It seems to be fairly easy to handle these situations since we had already been running the processor [without an impact](https://github.com/elastic/beats/blob/997cd0abc08a11c8ea4c57527b0b5c68bd1eadba/libbeat/processors/add_kubernetes_metadata/kubernetes.go#L193) in case the processor was not able to reach k8s API. @jsoriano @exekias feel free to comment or raise concerns:) !
