### ISSUE TITLE
Add ECS version information to module documentation

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#16089]
**Describe the enhancement:**
Docs should indicate the version of ECS a module was written against

**Describe a specific use case for the enhancement or feature:**
From @leehinman:

"With the ever increasing number of modules that Filebeat (and other beats) support and the release of new versions of ECS we are running into an interesting problem.  Right now we don't know what version of ECS a particular module was written against.  

So if our users want to search for a specific ECS field, they can't tell if the module should support it.  For example, a user might want to search for tls.protocol on data ingested with the Apache module, but that won't work because that module was written before ECS supported those fields.  And as a maintainer I don't know what the gap is between when the module was written and current ECS fields."

**Comment by dedemorton** [comment]
I agree that it would be very useful to provide the ECS version. I wonder if:

a) we should make this optional.
b) we should update the module generator to prompt users for the ECS version (assumes that a is false).

If we don't provide the tooling, we can add a commented out section to the docs template that guides contributors to provide the ECS version.

There's also some additional work required to update the existing modules. I think we'd want this for Filebeat and Metricbeat, no?

**Comment by weltenwort** [comment]
As someone writing a solution that consumes Filebeat documents I would find that a useful piece of information. If I currently specify that the solution requires ECS 1.2-compliant documents there is no easy way for the user to predict whether a specific module would satisfy that (short of trying it out).

**Comment by leehinman** [comment]
The generator could make a high probability guess as to what version of ECS the module will be written to by looking at the version of ECS that libbeat is using.  It would be very rare to write against an earlier version, and writing against a future fields is hard be cause we have good checks for undefined fields.

**Comment by webmat** [comment]
I love this proposal. It would indeed be great if the docs made this clearer to our users (and maintainers). But the way the `ecs.version` field is defined in ECS, each event source (meaning each module) should actually state what ECS version they're targeting as well. Right now libbeat is setting a value globally for a given release, but this doesn't reflect the reality of which sources haven't been updated to reflect recent additions to ECS.

We can do this gradually, but I'd like to expand this proposal to all Beats, not only the Metricbeat and Filebeat modules. Another example where the implementation is lagging with ECS is Auditbeat's "package" events. ECS has had a "package" field set since 1.2.0 (completed in 1.3.0); however Auditbeat still has package details at `system.audit.package.*`, rather than `package.*`. This is not a problem in itself, except for the fact that Packetbeat populates `ecs.version` with 1.4.0.

For an ECS event to be considered valid, `ecs.version` must be populated. I would not make it optional in the sense of it being absent in the event. If making it optional in the module tooling means it falls back to the latest ECS version, I think it's not ideal, as this leads to the situation we have right now. But at least the misleading `ecs.version` would be per module rather than across the board, so it's an improvement. So ideally I'd rather not, but at least it's a step in the right direction 👍

**Comment by webmat** [comment]
This could also be leveraged to address questions such as https://github.com/elastic/ecs/issues/734, which stem from the confusion caused by the current loose approach to filling `ecs.version` accurately vs the state of a given event source.
