### ISSUE TITLE
Log basic information for protocols we don't understand

### ISSUE THREAD

**Issue by tsg** [elastic/beats#162]
For protocols that we don't have yet support for, or that we cannot understand because they are encrypted, we can still log some basic information:

* IP addresses
* GeoIP information
* Ports
* Domain name
* Estimation of response times (?)

**Comment by german23** [comment]
+1

**Comment by rshriram** [comment]
+1

This is very useful for HTTPS traffic and other binary protocols over TCP. You could imagine logging just the MAC, IP, PORT (of source) and IP, PORT of destination, and possibly connection duration. RTT estimation might be of little use since it is not possible to get RTT of a single layer-7 request response. TCP RTTs are useful only for buffer tuning.

**Comment by andrewkroh** [comment]
Duplicates #670
