### ISSUE TITLE
[libbeat] Parallelize execution of processors

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#16585]
**Describe the enhancement:**

When publishing multiple events I would like for them to be processed in parallel by the processor chain. This parallelization would happen if there are multiple goroutines publishing events. For example, publishers like the Filebeat TCP input or Google PubSub input would be able to take advantages of this.

**Describe a specific use case for the enhancement or feature:**

This would help Beats achieve higher throughput rates in cases where processors are the bottleneck and you are willing to utilize more CPU resources to get a speed up.

**Details**

For a given publisher client instance there is a lock that is acquired before executing the processors ([source code](https://github.com/elastic/beats/blob/0197d01c50cd8e68182d9833f70d4501718075ea/libbeat/publisher/pipeline/client.go#L55-L69)). By executing the processors before acquiring the lock, events can be processed in parallel if multiple goroutines are publishing.

**Comment by pessoa-poli** [comment]
Hello @andrewkroh.
If I use the same publisher to publish many events during an specific run of my beat, do you know if these publications happen atomically? I mean, if after the first publication my beat looses connection to elasticsearch, would elasticsearch delete the publication, since the publisher did not close properly?

**Comment by softengchick** [comment]
I think we hit this with the CVA/H kit for the Air Force.  No matter what we do we stay around 10K EPS and FIlebeat(Suricata module) gets way behind the file written to.  CPU/memory are plentiful.   We removed the Suricata module and just pushed the file via standard filebeat and went to 40K EPS. 

We broke the Suricata ouput into files by type and then deployed a Kubernetes pod with FIlebeat for each file to get around this and try to keep up Suricata.  I can't imagine others aren't seeing an issue with this module in particluar.

**Comment by urso** [comment]
Each beat.Client instance has it's own set of processors. The problem with filebeat inputs is that they do not create a beat.Client instance per go-routine, but use a shared one. This is why we introduced the mutex in the first place, because filebeat did share resources it should not. Same for metricbeat it seems.

The Filebeat v2 input API creates a beat.Client per go-routine. Once we have moved all inputs to the new API, we will have full concurrency, with the point of congestion becoming the shared memory queue used to batch up events in order to create bulk requests.

In filebeat (old style inputs), each input gets its own beat.Client instance. But with inputs that are configured to collect from multiple URLs, files, we will have the unwanted sharing. The need for sharing was initially introduced by the logs input. As workaround one can duplicate the input configuration, introducing one configured input per URL.

Normally processors are fast enough, and filebeat internally can collect events at a quite high rate. Backpressure often comes from the outputs. Bandwidth limitations are normally fixed downstream or at the network layer.

**Comment by zez3** [comment]
> Once we have moved all inputs to the new API, we will have full concurrency, with the point of congestion becoming the shared memory queue used to batch up events in order to create bulk requests.

Almost there https://github.com/elastic/beats/issues/15324
