### ISSUE TITLE
[Uptime] Integrate uptime / heartbeat with Agent

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#16848]
This issue is here to discuss the datasource configuration for uptime for the agent and EPM data source for uptime.

This is a placeholder, but we should flesh this out around 7.8

Pinging @ph @jen-huang @drewpost

**Comment by ph** [comment]
@andrewvc, as promised here, is the [link]( https://github.com/elastic/beats/blob/feature-ingest/x-pack/agent/docs/agent_configuration_example.yml) to the Current Agent configuration that contains a lot of examples. I think your configuration will be similar to the "system" [section](https://github.com/elastic/beats/blob/feature-ingest/x-pack/agent/docs/agent_configuration_example.yml#L81-L140). 

I believe the other configs construct that might require changes on our side is how [constraints](https://github.com/elastic/beats/blob/feature-ingest/x-pack/agent/docs/agent_configuration_example.yml#L40-L42) works, we might need to allow them to be enabled at the **stream** or **input** level.

I think you will have to define the conditions that enable or not how a monitor is enabled for execution on a specific Agent, because all agents enrolled in a configuration will receive the same configuration.

But it's something we can discuss around 7.8

**Comment by ph** [comment]
I've created an apm-server issues with an initial plan of steps to work on.

* Adopt the new [indexing strategy ](https://github.com/elastic/kibana/blob/f91c795e30b7221cdce36e235470a4cda82f70b2/docs/ingest_manager/index.asciidoc)
* Define an integration package for apm-server in https://github.com/elastic/package-storage/
* Define configuration definition based on  https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/docs/elastic-agent_configuration_example.yml (will changes soon)
* Do you need any kind of custom action to send from Ingest manager to apm-server?

We should resolve the above before we do any programing work.

**Comment by andrewvc** [comment]
Part of https://github.com/elastic/uptime/issues/235
