### ISSUE TITLE
Add event.dataset to filebeat for cloud foundry fields

### ISSUE THREAD

**Issue by bvader** [elastic/beats#17000]
@blakerouse 
@mukeshelastic 

- Version: 7.7.0-SNAPSHOT
- Operating System: ALL 

Please add `event.dataset` to the exported fields with values from the `source.type` so that in the exported data field the following values will be available.
```
event.dataset = logmessage
event.dataset = httpstopstart
```

**Comment by blakerouse** [comment]
@bvader why is this needed? normally only metricbeat sets the `event.dataset` not filebeat

CloudFoundry does have `cloudfoundry.*.type` to all the types:

* `access`
* `log`
* `counter`
* `value`
* `container`
* `error`

**Comment by bvader** [comment]
@blakerouse setting a type in a field aids in processing, filtering, visualization, alerting. ML etc at a number of levels. Checking a "type" is much preferable for boolean than to see if a field exists.... 

could we add
```

cloudfoundry.type = access
cloudfoundry.type = log
cloudfoundry.type = counter
cloudfoundry.type = access
cloudfoundry.type = access
```

**Comment by bvader** [comment]
@blakerouse 

FYI... and I see this issue is already merging...and I think what we are setting is fine but according to the ECS documents logs can have `event.dataset `as well. 

https://www.elastic.co/guide/en/ecs/current/ecs-event.html

**event.dataset**

Name of the dataset. If an event source publishes more than one type of log or events  (e.g. access log, error log), the dataset is used to specify which one  the event comes from. It’s recommended but not required to start the dataset name with the module name, followed by a dot, then the dataset name. type: keyword example: apache.access

**Comment by blakerouse** [comment]
@bvader Nice! I have updated the PR to use that for the filebeat input, so it will match the metricbeat module.

**Comment by blakerouse** [comment]
@bvader After review it was determined that setting `event.dataset` from an input would not be really correct. Because in the case of filebeat you can use an input with different modules and a module sets that event dataset.

Example being using the apache module from the messages from cloudfoundry input. In that case `apache.access` would be set as the `event.dataset`.

So the PR has went back to using `cloudfoundry.type` and that will be on all events whether from metricbeat or from filebeat.
