### ISSUE TITLE
[Metricbeat] Add monitoring of ingest pipelines

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#17025]
Today Metricbeat captures some node stats in the `elasticsearch` module but the ingest node is not part of it. The stats for ingest pipelines is an important piece of data that should be accounted for in stack monitoring use cases. (`GET _nodes/stats?filter_path=nodes.*.ingest.*`)
Add ingest pipeline metrics to the existing elasticsearch integration.

## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).
* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

**Comment by ycombinator** [comment]
@sorantis Thanks for filing this issue. I have a few questions to start us off:

1. As you know the stack modules in Metricbeat can run in one of two "modes": with `xpack.enabled: true` or without it. Which one is this for?

2. If it for the `xpack.enabled: true` path, then I have a few more questions:

   1. Is there a Kibana issue describing or discussing what the UI for this should look like? This is an important pre-requisite because we try not to index _all_ stats about a metric to save on space. Instead we only index stats (fields) that will be used by the UI. So typically, having a UI issue with mockups/wireframes or even a text description first provides useful guidance for the collection implementation.

   2. As you know, we currently have to support two types of collectors - internal and external (aka Metricbeat). So we will need a corresponding issue for internal collection as well. Since these are ES stats, that issue would be in the ES repo. Again, having the Kibana issue fleshed out first will help guide the ES collector implementation as well. 

   3. We'll also need to add the fields to be indexed into the `.monitoring-elasticsearch-*` index template as well, which lives in the ES repo. So this should probably be it's own ES issue or could be combined with the one in the previous point. Either way, knowing which fields the Kibana UI will need is a pre-requisite.
