### ISSUE TITLE
In Metricbeat Kafka modules based on Jolokia, collect OneMinuteRate instead of MeanRate

### ISSUE THREAD

**Issue by danielyahn** [elastic/beats#17295]
**Describe the enhancement:**
- For Metricbeat Kafka Jolokia module, we should be able to use different mbean attributes (other than the default MeanRate) 
- I think OneMinuteRate makes much more sense than MeanRate as a default value
- Maybe make it configurable?

**Describe a specific use case for the enhancement or feature:**
By default, it seems like Metricbeat Kafka Jolokia module takes MeanRate attribute of metrics. A lot of times, I would prefer using OneMinuteRate to using the MeanRate. For example, `name=BytesOutPerSec,type=BrokerTopicMetrics`. MeanRate would have mean value of the throughput from broker start time. I want Metricbeat to ingest more granular value, and do necessary aggregation using lastic.

**Comment by andresrc** [comment]
@jsoriano can you please comment on this?

**Comment by jsoriano** [comment]
Hey @danielyahn, thanks for your feedback!

It makes sense, it also looks to me that `OneMinuteRate` would make more sense for most of the metrics, as we periodically collect data and we are more interested in the most recent one.
If we see that some metric makes sense as `MeanRate`, we can add it, we can decide metric by metric.
I wouldn't make it configurable in the provided module, so we have control on the metrics collected for documentation, dashboards and so on.

@ChrsMark do you see any problem with collecting `OneMinuteRate` instead of `MeanRate`?

If after changing these metrics, some user still finds that some metric is not being collected as they would like, they can still use the [Jolokia module](https://www.elastic.co/guide/en/beats/metricbeat/7.6/metricbeat-module-jolokia.html) directly, and the Kafka metricset [manifests](https://github.com/elastic/beats/blob/v7.6.2/metricbeat/module/kafka/broker/manifest.yml) can be used as help to create the mappings.

**Comment by ChrsMark** [comment]
> @ChrsMark do you see any problem with collecting `OneMinuteRate` instead of `MeanRate`?

No, I don't see any problem since it makes more sense.

**Comment by gquintana** [comment]
MeanRate doesn't mean anything (it's too smoothed as time passes) and doesn't reflect Kafka's current status.
 #22733 should fix
