### ISSUE TITLE
[Agent] Add Specification and information around configuration.

### ISSUE THREAD

**Issue by ph** [elastic/beats#17793]
We have an [example configuration](https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/docs/elastic-agent_configuration_example.yml) in the code but we do not have documentation that describes the following:

* Why named outputs
* Why data sources an array and not references?
* Why data source -> inputs -> streams
* How does the UI impact the structure -> Data source
* It should be possible to import a config in the future

cc @ruflin @michalpristas Lets complicate the above list if you see something that needs to be documented either structure or behavior.

**Comment by jlind23** [comment]
@ruflin shall we keep that issue? It does not seem to be relevant anymore.

**Comment by ruflin** [comment]
This issue was / is around documenting some of the decision made on how we landed on what we have with the elastic agent config format today. There were many discussions and scattered around many places. It would be good to have this documented and it likely falls mostly on my plate to do it. Also it is an internal need not necessarily something that needs to be exposed. 

I'm going to close this issue but took a not on my end to take a stab at it one day.

**Comment by ruflin** [comment]
@ph I suggest we let the above topics flow into the docs around v2 architecture.
