### ISSUE TITLE
[CI] Upload test result files

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/beats#17907]
The test suit generates some files (build/system-tests) that are needed for diagnosing issues, we have to upload those files to Jenkins to help to diagnose when an error happens.

see https://github.com/elastic/apm-server/blob/master/Jenkinsfile#L303-L305

**Comment by v1v** [comment]
This is tricky one :P

I've seen those system-tests folder contains symlinks, if the idea is to archive them as a tarball then no issues, otherwise, the implementation https://github.com/elastic/beats/pull/18695 might be something to look at, there is a specific CI archiving implementation to bypass some issues when archiving files in big repositories. The `system-tests\` folder has been skipped to bypass some issues with symlinks:

```
[2020-05-28T17:29:16.586Z] FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\?\\C:\\Users\\jenkins\\workspace\\Beats_beats-beats-mbp_PR-18695\\src\\github.com\\elastic\\beats\\auditbeat\\build\\system-tests\\run\\test_file_integrity.Test.test_non_recursive' -> 'build\\.\\build\\auditbeat\\build\\system-tests\\last_run'
````

**Comment by kuisathaverat** [comment]
there are tons of files, on the APM Server we upload a tar file with all the content of the folder.

**Comment by v1v** [comment]
For the record, test result files for the integration tests are now uploaded to the build as artifacts:

![image](https://user-images.githubusercontent.com/2871786/87941361-f3a60080-ca92-11ea-851e-5a79feb8bd72.png)


Format: `<beat-name>--system-tests-<os>.tgz`

For instance:
- libbeat--system-tests-linux.tgz
- metricbeat--system-tests-darwin.tgz
- metricbeat--system-tests-linux.tgz
