### ISSUE TITLE
docs-preview is not working as docs imply

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#18007]
Docs: https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#documentation

Actual: `make docs-preview` under a Beat directory does not work. This target is only available under `libbeat` directory.

We either need to make this cleat in the docs or to add this target for Beats.

**Comment by dedemorton** [comment]
This has been broken for a long time. Now that the doc build is tested when PRs are created, I don't think the command is needed, though it might be useful. For now, I'm going to link to the docs howto and leave this issue open in case we want to fix the tool. removing the docs tag, though, because it's no longer a doc issue.
