### ISSUE TITLE
Centos7 is reported as RHEL by MB/FB 

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#18665]
I'm seeing Centos7 OS reported as the wrong OS RHEL (not surprising right, but its not technically true).  I looked for existing bugs and discuss topics but seeing none have logged it for review.

For confirmed bugs, please report:
- Version: 7.8 Build Candidate 2
- Operating System:  Centos7
- Discuss Forum URL: https://discuss.elastic.co/t/i-m-seeing-centos7-os-reported-as-wrong-os-rhel-not-surprising-but-is-that-expected-beat-behavior/233206
- Steps to Reproduce: 
1) set up a centos 7 vm
2) install the Alpha BC 2 Stack and Fleet etc.
3) deploy the Agent to the centos image and it will return as noted.  see this image:
![Centos7-Shows-As-RHEL](https://user-images.githubusercontent.com/12970373/82475415-78c46780-9a9a-11ea-87bd-8b5c2e305181.png)

I was using older infrastructure to reproduce it, let me know if you don't see this on other CentoS public images!

**Comment by ph** [comment]
This is an issue with [go-sysinfo](https://github.com/elastic/go-sysinfo/issues), this is the same library that we use to collect metrics inside metricbeat.

I don't think its high priority, because as you said it's not totally false :)

@andresc I would be tempted to reassign that issues to another team, but I am not sure where it fall.

IIRC @andrewkroh initially created it and I see that @fearful-symmetry committed and fixed a few issues.

**Comment by andrewkroh** [comment]
What data backs that UI? Can you share a raw JSON document showing the data?

The `host.os.family` should be `redhat` and the `host.os.platform` should be `centos`. This is the test case we have for centos 7:

https://github.com/elastic/go-sysinfo/blob/2e4263c5c548ff5352fd86b0a29330fb08b5c98f/providers/linux/os_test.go#L69-L76

**Comment by ph** [comment]
oh we indeed incorrectly use `Platform: info.OS.Family`

nevermind thanks @andrewkroh, that would be one line to fix.
