### ISSUE TITLE
Allow Google Cloud module credentials to be passed in as environment variables

### ISSUE THREAD

**Issue by EthanStrider** [elastic/beats#19260]
**Describe the enhancement:**
Right now, the Google Cloud module can only access credentials via a file path:
`credentials_file_path: "/etc/gce_creds.json"`

It would be nice to also be able to pass them in as environment variables. Example:
`cloud.auth: ${CLOUD_AUTH}"`

**Describe a specific use case for the enhancement or feature:**
When using kubernetes helm charts it's more convenient to use environment variables than to go through the hassle of creating a file, a volume mount, etc.

This could be abstracted out as a nice feature for all beats modules.

**Comment by ChrsMark** [comment]
@EthanStrider in Kubernetes if you are using Autodiscover you can use env variables (as well as Keystore). Please have a look into this related issue: https://github.com/elastic/beats/issues/12597

**Comment by hhollenstain-soda** [comment]
@ChrsMark I believe the point Ethan made with this issue is missed. Currently, the metric/beats modules only support use of a json file. The only configuration that is accessible is via passing a path to a json file [Elastic docs](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-gcp.html#_authentication_authorization_and_permissions). As previously noted this is a hassle in kubernetes helm charts. 

There is a few options that would make this much easier task. It would be nice to be able to just pass in the value of the credentials file as a string and not simply the path of the json file. The other option is you don't need to pass in any credentials. Ideally this is due to our usage of Google's built in identity access management linking kubernetes service accounts to IAM service accounts.
