### ISSUE TITLE
Filebeat is losing events due to file rotate

### ISSUE THREAD

**Issue by mostolog** [elastic/beats#1956]
Hello

As exposed in https://github.com/elastic/logstash/issues/5503 we have found a strange behavior with filebeat and file rotation.
Seems it's not clear yet if the problem it's on the logstash side or the beat side, but something is happening _in da hood_.

@ruflin has been a great help for this, and has prepared some phyton tests https://github.com/elastic/beats/pull/1954. I was born on the bash side of life ;)

To sum up:
- A generator is creating a lot events and writing to a file (generator.log)
- FilebeatA reads that file and write "processed events" using rotation (filebeat.log)
- FilebeatB reads A's files and write the processed events (final.log)

Checking generated and final events show that there are events missing, even missing all the events from a filebeat-insertyourrotatevaluehere file.

For the sake of brevity and text-saving, here are the configuration files and explanation of the problem: https://github.com/elastic/logstash/issues/5503#issuecomment-226263986, but reading the whole thread could be better for understanding my poor english.

If you can, moving the original issue to this repo will be - IMHO-  better, to avoid having multiple threads.

Please, if you can replicate the issue, tag it as bug and pioneer program _for the eternal glory of ruflin and me_.

Regards

**Comment by ruflin** [comment]
The issue is definitively on the filebeat side. https://github.com/elastic/beats/pull/1954 reproduces it quite reliably. It only seems to happen on very fast file rotation and lots of rotations at the same time, so I assume it is some kind of race condition internally in starting the harvesters.

**Comment by ruflin** [comment]
@mostolog It seems I found the source of the issue and also have a potential fix. See https://github.com/elastic/beats/pull/1954#issue-163666153 for more details

**Comment by mostolog** [comment]
Please, excuse my plain words, but I'm not able to articulate it better.

IIUC, you're saying something like this is happening:
1. Consumer open file and gets fd=1
2. Consumer check status, if match, it uses current reading offset=1234
3. File is renamed/rotated (fd is still valid, but the offset it isn't)
4. Consumer cant read at offset 1234, and closes fd or whatever it does

You solved doing:
1. Consumer open file and get fd=1
2. File is renamed/rotated
3. Consumer check status and notice the file is different, setting offset=0
4. Consumer reads rotated file from offsett

Did I understood properly, or my english/coding is worse than I though?

What happens with the old file which could contain a few unreaded lines? it's detected on file creation and resumed from last _offset_ position?

What happens if file is rotated **after** consumer checks status?


I still think it's much easier to "monitor" files naming "file-creationtimestamp" as creation name. Files will be read until EOL+timeout without changes, while new files will be easily detected. Rotation, on the other hand, should compare "creationtimestamps", although I understand you may want to stay under _logrotate standard_.

Regards

**Comment by ruflin** [comment]
Filebeat keeps track of files by storing their state internally (inode, device). To open a file handler, a path is needed. As soon as a file is opened, the path can change but the file handler stays the same. What happened was:

1. Filebeat fetches the state and compares it with existing files
2. Filebeat opens a file with the path in the state

What now happened between 1. and 2. is that the path changed because of the heavy file rotation. That means state and path were correlated wrongly. Now a third step was introduced:

1. Filebeat fetches the state and compares it with existing files
2. Filebeat opens a file with the path in the state
3. Check if path and state still correlated

In case the third step returns a wrong result, an error is returned. As the file handler is already open in 3, the state comparison does not depend on any path, so even if the file rotates, the comparison is correct. The state is still persisted and will be checked the next time the file is picked up. No data is lost.

Let me know if you need more details.

Filebeat tracks files by inode/device on Linux and potentially with fingerprints in the future. Relying in file names does not work for rotating files.

Can you check if the above fix also fixes your issue?

**Comment by mostolog** [comment]
Download source+compile+patch+test? (I don't know how, but I'll do my best once I finish with current task ;) )

**Comment by ruflin** [comment]
No need to build it yourself. It should be available soon in our nightly builds: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/
