### ISSUE TITLE
Beats agent ID is often not unique

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#19741]
Currently the beats `agent.id` field, which is a UUID generated on the first run of the beat, cannot be depended on for uniqueness. While not common, it does happen that users sometimes 'bake' machine images by cloning a machine that has run in the past, thus creating a situation where different machines share the same `agent.id`. @jeffvestal ran into this trying out heartbeat.

While we could improve the situation by documenting the right way to do things, I doubt users will read this, and it doesn't make the situation less painful.

I have two questions:

1. Should we keep this field? Is it actually useful if it can't be depended on? We are moving away from depending on it in the Uptime UI.
2. If we do keep it, is there a way to determine if the UUID has been copied? We could, for instance record the hostname, ip, or other similar characteristics of the machine that generated `agent.id` alongside the `agent.id` (or just hash them into the `agent.id`). If one of those changed we could just regenerate the `agent.id` or alert the user.

Pinging @urso @ph and @exekias

**Comment by exekias** [comment]
@ph do you know if we are using the agent id in fleet? I guess fleet must have a way to identify agents.

In general I see value in having agent id (or whatever fleet uses) in the events, so we are able to identify the source of the data. For instance, to know what configuration is applied there.

**Comment by urso** [comment]
When building an image there should be no need to actually run the Beat. The '<beatname> setup` is better run by another provisioning job, instead from the building image as well.
The data directory should be cleaned up. Beats also store a lock file in here and the registry file. If the beat does not shut down correctly, then the image can even be broken as well. That is, besides having an invalid `agent.id`, users might see other issues as well.

Another potential gotcha is that on cloud providers all images have the same hostname once build. A special service that is started via systemd is used to fetch the actual hostname and update. Beats systemd file has no dependency on said service and it is not uncommon to have multiple instances report the hostname of the build image.

> Should we keep this field? Is it actually useful if it can't be depended on? We are moving away from depending on it in the Uptime UI.

This field was introduced for stack monitoring. It is also required, because the hostname is not a good enough uniqe identifier (multiple beats run on one host). Maybe some things change with agent + fleet though.

@ycombinator you know if `agent.id` is still required for monitoring?

> If we do keep it, is there a way to determine if the UUID has been copied? We could, for instance record the hostname, ip, or other similar characteristics of the machine that generated agent.id alongside the agent.id (or just hash them into the agent.id). If one of those changed we could just regenerate the agent.id or alert the user.

With the switch to agent I'd rather not spend too much time and energy on this issue on the beats side.

**Comment by andrewvc** [comment]
@urso I agree that there's no reason to run the beat while building an image. However, the process @jeffvestal described, getting it running then saving a snapshot is not uncommon.

We could just document this, but people rarely have the time to read all the docs, and can easily forget them. It makes sense to help users out here and try and do the right thing even if they've made it hard for us.

That's a great point about hostnames not being unique. I'm wondering if there are enough pieces of metadata we can use to fingerprint the beat. Alternatively, if a user is using the `add_cloud_metadata` processor, maybe that should set the `agent.id` from the instance ID.

That being said, if it's not really being used, as I mentioned in my original comment, I'm OK with it being removed.

**Comment by ycombinator** [comment]
> This field was introduced for stack monitoring. It is also required, because the hostname is not a good enough uniqe identifier (multiple beats run on one host). Maybe some things change with agent + fleet though.

> @ycombinator you know if agent.id is still required for monitoring?

From what I can tell, `agent.id` is not being used by the Stack Monitoring UI. Instead, it looks like it's [using `beat.uuid`](https://github.com/elastic/kibana/blob/master/x-pack/plugins/monitoring/server/lib/beats/get_beats.js#L90).

**Comment by ycombinator** [comment]
> If we do keep it, is there a way to determine if the UUID has been copied? We could, for instance record the hostname, ip, or other similar characteristics of the machine that generated agent.id alongside the agent.id (or just hash them into the agent.id). If one of those changed we could just regenerate the agent.id or alert the user.

We've seen similar issues with instance UUIDs generated by Logstash and Kibana (due to users copying over the `data` folder, baking it into an image and deploying that image in multiple places, etc.). One idea we've discussed in the past to detect this is to create a Stack Monitoring Cluster Alert: https://github.com/elastic/kibana/issues/64779.

**Comment by jeffvestal** [comment]
Good points about not needing to run heartbeat when building an image. In my case I didn't realize there was a lock file or that the data dir needed to be cleaned. I would have minimally shutdown the process to release the lock file and cleaned the data dir prior to creating machine image in GCP. 

@urso I do have a question about the comment :
> Another potential gotcha is that on cloud providers all images have the same hostname once build

Unless I'm just not following what you mean by hostname, each VM I'm running has a distinct hostname as reported by `hostname`. 

<img width="1492" alt="Screen Shot 2020-07-08 at 8 05 35 PM" src="https://user-images.githubusercontent.com/53237856/86985738-8c658380-c157-11ea-9e90-40d90cf6989b.png">

**Comment by urso** [comment]
> Unless I'm just not following what you mean by hostname, each VM I'm running has a distinct hostname as reported by hostname.

This is because on startup a systemd service does fetch the instance metadata and reconfigured the hostname. If the beat is started before this service (not uncommon as there is no direct dependency), then beats can report the hostname of the build image. It's race condition in system startup. Not sure about GCP, but AWS Linux for example runs cloud-init and cloud-final targets.

**Comment by jeffvestal** [comment]
Thats good to know, thanks @urso !

**Comment by andrewvc** [comment]
Is there a clear direction to take this issue in?

I don't see a clear direction forming in the discussion. If that's the case it may be best to just leave the field as is.
