### ISSUE TITLE
Make WinLogBeat service not dependent upon DNSclient

### ISSUE THREAD

**Issue by rugabunda** [elastic/beats#19834]
Some people use DNS clients for Windows such as Acrylic and Simple DNScrypt, Enabling DNSclient causes many problems for me.
Please allow WinLogBeat to work automatically with the dns bindings to the adapter, rather than to the service which is not necessary.

**Comment by andrewkroh** [comment]
Could you please elaborate on this request. So you would like a way to configure the DNS server that a Beat uses and ignore the system's default resolver?

This would not be an enhancement that's specific to Winlogbeat as it would affect all beats (primarily because all of the output code is from libbeat).

**Comment by rugabunda** [comment]
When using a third party DNS client in windows disabling "dnsclient", winlogbeat fails to function... it would function if it ignored the systems default resolver.
