### ISSUE TITLE
Metricbeat shows swap usage after disabling Windows paging file

### ISSUE THREAD

**Issue by ErnestoBezanilla** [elastic/beats#19875]
Reproduced with  7.5 / 7.6 +  Win 2016 Server / Win 10 

After disabling the paging file on Windows systems via `System Properties → Advanced → Performance → Advanced → Virtual memory` metricbeat still shows swap usage. 

<img width="1274" alt="87032262-a1d4bf00-c1e4-11ea-8088-45916f0f6843" src="https://user-images.githubusercontent.com/12344110/87401708-ccdf5a00-c5ba-11ea-89d4-15dd70c63778.png">

 
Current library version gets swap info from the windows syscall `GlobalMemoryStatusEx`. Newer versions of the library have switched to an alternate approach, using the Windows system utility `wmic`, i.e. `wmic pagefile list full`

**Comment by narph** [comment]
@ErnestoBezanilla I had a look at the type of information `GlobalMemoryStatusEx` returns and it looks like this:

> `ullTotalPageFile` The current committed memory limit for the system or the current process, whichever is smaller, in bytes. 
> 
> `ullAvailPageFile` The maximum amount of memory the current process can commit, in bytes. This value is equal to or smaller than the system-wide available commit value.
> 

The committed memory limit here could be thought as the maximum potential pagefile usage if pagefile is enabled and it will still be counted in systems with no pagefile. 
Either way, it does not seem to reflect the current pagefile usage.

I would not go on the `wmic` path since we had cpu and memory high usage issues in the past but it looks like another option might be the using the `'\Paging File(*)\% Usage'` performance counters.

 At the moment users can try the `windows/perfmon` metricset to get this information.

That said, the documentation should either be clarified on the windows side or a new implementation should be considered here.

**Comment by martinscholz83** [comment]
The `ullTotalPageFile` is the physical RAM + pagefile.sys. I think the only way to detect how much of the swap memory is used, is to check with performance counters. Because although you have enough free physical memory windows is still using the pagefile for internal stuff. So the calculation in metricbeat doesn't reflect the swap usage instead the whole memory usage.

**Comment by bczifra** [comment]
This is still not fixed.
