### ISSUE TITLE
Filebeat setup is not creating index pattern in kibana 

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#19965]
- Version: 7.9.0 BC1 
- Operating System: Ubuntu 16
- Steps to Reproduce: 
Install and run ES/Kibana. 
Install Filebeat. 

Due to #19964 - I tried running ```./filebeat setup --dashboards``` instead to get around it and it seemed to pass, 
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards

However, it is not creating the index and even using filebeat setup does not create index pattern .

**Comment by LeeDr** [comment]
I hit the same problem with 7.9.0 BC1 on centOS 7.  Kibana debug logs didn't show anything related to it.

**Comment by liza-mae** [comment]
@LeeDr after looking at this closer, I would consider it a blocker since it is causing wider problems in Kibana when creating this index manually and more so when it is the default index pattern.

![Screenshot from 2020-07-16 07-37-21](https://user-images.githubusercontent.com/23424008/87678264-f70a5680-c737-11ea-93d4-f139765556c1.png)

**Comment by kaiyan-sheng** [comment]
I'm seeing the same issue when trying to create a kibana index pattern for Filebeat:
<img width="1305" alt="Screen Shot 2020-07-21 at 4 11 50 PM" src="https://user-images.githubusercontent.com/14081635/88112446-20c6e180-cb6d-11ea-9f4d-ad73aa530e91.png">

Metricbeat seems to work just fine.

**Comment by andrewkroh** [comment]
To elaborate on @kaiyan-sheng last comment, while creating the index pattern in Kibana, it requests all of the fields for filebeat-* and gets back about 6700 fields (almost a 1MB response) then tries to PUT the index pattern it created and fails with HTTP 413. This is same error code we see when Filebeat tries to insert the index pattern that it generates (although the error was silently ignored due to https://github.com/elastic/beats/pull/20121).

<img width="1727" alt="Screen Shot 2020-07-21 at 6 49 23 PM" src="https://user-images.githubusercontent.com/4565752/88115048-3c3ce700-cb83-11ea-85bc-7afa8c1db038.png">

**Comment by urso** [comment]
This is quite a many fields...

Is the error because of too many fields in general, or does it indicate some other error?
I wonder if the API would allow us to add fields in batches to the index pattern. Then we could try to split the index pattern into batches of 1000 fields and call it until all fields are installed.

**Comment by andrewkroh** [comment]
I tried a small hack and I was able to slim down the size of the index pattern request body from Filebeat by omitting some of the parameters with default values (e.g. count=1, analyzed=false). This allows Filebeat setup to work, but even with that working there are still problems in Kibana.

It seems like Kibana still wants to update the index pattern when visiting Discover or opening the Index Pattern UI and this triggers the HTTP 413 despite have already pushed an index pattern.

**Comment by andrewkroh** [comment]
I have identified about 2000 fields that should not present. That's about 1/3 of the fields in the mapping so when we fix that it should help this issue.

`$ ./filebeat export index-pattern | jq '.objects[0].attributes.fields | fromjson | .[].name' | sort | uniq | grep -E "(microsoft|cisco|fortinet)\.rsa"`

The fields returned in that list were meant to be named `^rsa.*` and not be prefixed with their module names (e.g. `microsoft`). Of the 21 new modules added in #19713, this problem only affected modules that had existing filesets.

**Comment by andrewkroh** [comment]
### Summary of Changes

- https://github.com/elastic/beats/pull/20170 Fix field mappings to reduce overall number of fields
- https://github.com/elastic/beats/pull/20156 Assert size of index patterns is less than 1 MiB
- https://github.com/elastic/beats/pull/20121 Fail in 'setup --dashboards' if index pattern cannot be installed
