### ISSUE TITLE
[Ingest Manager] Elastic Agent persistence (ps1) script sets service to be 'delayed start' and should set it to immediate (and start it up)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#20106]
I am running Persistence tests.  Here are my concerns.

1) I see that Agent shows as a ‘delayed start’ after the powershell install script is run and it isn't started, and never starts up on its own.  I think that is the essence of the bug.  If we do intend the delayed start, whats the benefit / reason for this?  

And 2)  whats the mechanism for when it is intended / expected to be started?  
 - it doesn't start even if Agent is started (via starting Agent on command line), not sure if that was expected to start it tho... whats the spec here?

Tested on 7.9 BC 2 with Agent/Endpoint against cloud stack and win 7 x64 vSphere host

steps:
- deploy stack 7.9 to cloud
- transfer agent/Endpoint to host (and manually put Endpoint into Agent download if needed)
- follow steps in 7.X guide for starting Agent https://www.elastic.co/guide/en/ingest-management/7.8/run-elastic-agent.html
 which means to me, to:
 -- unzip Agent
 -- call powershell script
 -- call enrollment command as output by Fleet
 -- start agent via: ./elastic-agent run

If this isn't right and/or needs to be updated in docs or we have a bug, please lets follow thru asap.  I know we were just making changes to the .rpm / .deb installs, not sure if those need further changes to support persistence (or the guide / steps need more details or not)

screenshot
<img width="1246" alt="persistence-host-info" src="https://user-images.githubusercontent.com/12970373/88082704-1cd89680-cb50-11ea-9862-5294fef4294c.png">

**Comment by EricDavisX** [comment]
discussed and we think the bug and fix is that... Elastic Agent persistence (ps1) script sets service to be 'delayed start' and should set it to immediate (and start it up)

**Comment by kamalpreetpahwa-qasource** [comment]
Hi @EricDavisX ,
We have validated this ticket on 7.9 BC4 cloud environment with 7.9 agent on Windows 10 Host OS.

We have created 07 test cases under [Persistent agent](https://elastic.testrail.io/index.php?/suites/view/27&group_by=cases:section_id&group_order=asc&group_id=3520) section in Testrail.

Moreover, we have kept the test cases as pending under [Persistent agent script](https://elastic.testrail.io/index.php?/runs/view/484&group_by=cases:section_id&group_order=asc) test run, due to elastic-agent service not start up when we enroll and run the agent with below steps:
Once the issue will get fix, will execute the created the test cases.

Steps to be followed.

1. Run the PS1 command ".\install-service-elastic-agent.ps1" where agent is unzipped at location.
2. Then enroll the agent from "Fleet" with string having token.
3. Run the agent with command: ./elastic-agent run
4. Go to the services and observed elastic-agent service shows "Automatic (Delayed Start)" status type and agent service is not running.

Screenshot 1:
![AutomaticDelayed](https://user-images.githubusercontent.com/61860613/88539308-a5fb3c00-d02e-11ea-95e5-b50ab1b5361d.png)

Please let us know if we are missing anything or need to add any other validation scenario.

**Comment by blakerouse** [comment]
Using the service, after `elastic-agent enroll`, you will not use `elastic-agent run`. Instead you would start the service that will perform the (`elastic-agent run`).

**Comment by kamalpreetpahwa-qasource** [comment]
Hi @blakerouse 

Thanks for sharing the feedback on clear steps for persistent test.

Hi @EricDavisX 

We have validated this ticket on 7.9 BC 4 cloud environment on Host OS Windows 10_x64 .
Please find below are test case execution status and our observations:

We have executed 07 test cases, out of which Failed 02 test cases under [Persistent agent Script  test plan](https://elastic.testrail.io/index.php?/runs/view/484&group_by=cases:section_id&group_order=asc) , due to defect https://github.com/elastic/beats/issues/20260.

Observations:
1. We observed that agent service successfully running and agent gets enrolled and display with status as Online.
Screenshot:
![PS120106](https://user-images.githubusercontent.com/61860613/88643722-b3bcca00-d0df-11ea-8f5e-14d0ecdf58be.png)

2. Agent service stops gracefully and agent moves to Offline status.
Screenshot:
![StopPS1](https://user-images.githubusercontent.com/61860613/88643821-d18a2f00-d0df-11ea-92d8-6c6518fe8f2a.png)

3. Agent service become crashed when we restart the service and corresponding defect is reported for same.
https://github.com/elastic/beats/issues/20260

Screenshot:
![CrashedOnRestart](https://user-images.githubusercontent.com/61860613/88643978-04342780-d0e0-11ea-92c2-bbde43050384.png)

Please let us know if anything else need to be verify.

Thanks

**Comment by blakerouse** [comment]
This fix has not be pushed out into a BC yet, next BC will have this fix.

**Comment by EricDavisX** [comment]
yes, please test in BC 5 or later

**Comment by rahulgupta-qasource** [comment]
### Bug Conversion:
Following **07** Test-Cases already Exist for this ticket:
- https://elastic.testrail.io/index.php?/cases/view/15846
- https://elastic.testrail.io/index.php?/cases/view/15847
- https://elastic.testrail.io/index.php?/cases/view/15848
- https://elastic.testrail.io/index.php?/cases/view/15849
- https://elastic.testrail.io/index.php?/cases/view/15850
- https://elastic.testrail.io/index.php?/cases/view/15851
- https://elastic.testrail.io/index.php?/cases/view/15852
