### ISSUE TITLE
Add the possibility to truncate the harvested file (truncate_after)

### ISSUE THREAD

**Issue by g13013** [elastic/beats#20410]
This issue is related to #714  #2187 and #16357

We have tried to combine many tools to manage log files but it is far from being easy to do so, and its really painful to combine the state of all the tools (logrotate, filebeat, filebeat script cleaning), we have wrote a script to manage finished files and experienced weird outcome like this one below that reports offset greater than the filesize:

![image](https://user-images.githubusercontent.com/2730430/89214497-d0b13b80-d5be-11ea-8515-cc355d9aebb6.png)

We combine 3 tools just to manage logs life time where its could be very easily avoided in the filebeat side

We would like to request a feature `truncate_after`:

"truncate_after": the file would be truncated after the max file size would be reached

considering the fact that if filebeat consumes directly from the log file written into by the application, it would be the only garant of line indexing. If this option is added we could completely get rid logrotate and filebeat cleaning scripts

the rule is simple once the filebeat reaches the end of file and if the size exceeds `truncate_after` filebeat would truncate the file.

**Comment by urso** [comment]
The difficulty in general is that we have multiple processes that need to coordinate on what they think the file state is, while having no means of coordination, signaling, or communication. If possible I'd prefer to have the log rotation handled by the application itself, instead of introducing logrotate (there are many 'workarounds' that logrotate applies trying to overcome limitation in the application writing the logs). 

> "truncate_after": the file would be truncated after the max file size would be reached

Filebeat currently can not tell if a file is actively written. There is no 'max file size' for an active log file. Thanks to copy based strategies, one might find files growing even if they've been rotated.

> "truncate_after": the file would be truncated after the max file size would be reached

In your scenario, is the file still subject to rotation handled by logrotate? Would the truncate just be an "let's release some disk space early"?

**Comment by NerdSec** [comment]
This would be a real life safer. I am tired of managing the script for deleting log files and the corresponding celery tasks.
Also, for scenarios where a large number of files are created and dumped to be read, without any logrotate, this is a big issue.

I currently have an integration with a SIEM product that supports only dumping raw logs to files. These files are never updated, or rotated, and I have to ensure that files are deleted once I have consumed them, or it leads to drive being full.

**Comment by g13013** [comment]
> Filebeat currently can not tell if a file is actively written. There is no 'max file size' for an active log file. Thanks to copy based strategies, one might find files growing even if they've been rotated.

Makes sense, but the conditions I mentioned are

> if there is are max file size and reaching the end of file

most of scenarios use logrotate, copying the log file to new location and trucating the source, What I am suggesting is rather than copying we would simply truncate the file once the offset equals the current file size, it would be better than most scenarios using log-rotate anyway because we are getting rid of the "copy" step.
