### ISSUE TITLE
Elasticsearch module generates 400 error docs for disabled ES xpack components

### ISSUE THREAD

**Issue by A-Hall** [elastic/beats#20667]
For confirmed bugs, please report:
- Version:  7.8.0
- Steps to Reproduce: 

The `elasticsearch` module for monitoring the stack requires all xpack related metricsets to be enabled if `xpack.enabled: true` is set.  However, it's possible to disable X-Pack features.  If a feature is disabled, Metricbeat creates a 400 error doc:

```
       @timestamp		Aug 14, 2020 @ 15:16:03.175
	_id			Gxhm7nMBgj-ss5sZhxYG
	_index			metricbeat-7.5.1-2020.07.28-000001
	_score	 		- 
	_type			_doc
	agent.ephemeral_id	2a7dac95-6499-404b-8d0f-3d3b77a30112
	agent.hostname		es-master-0
	agent.id		bd24a669-537c-480b-9f81-4b6a8c7667fa
	agent.type		metricbeat
	agent.version		7.5.1
	ecs.version		1.1.0
	error.message		HTTP error 400 in : 400 Bad Request
	event.dataset		elasticsearch.ml.job
	event.duration		8,249,255
	event.module		elasticsearch
	host.name		es-master-0
	metricset.name		ml_job
	metricset.period	10,000
	service.address		0.0.0.0:9200
	service.type		elasticsearch
```

**Comment by ycombinator** [comment]
One way to resolve this would be to do an API call to Elasticsearch at the start of the metricset's `Fetch()` method to check if the ES feature being monitored is disabled. If it is disabled, we bail out without any further processing. We have such logic in place for ES version checks so that same logic could be extended to feature checks.

This approach would work well for the current `elasticsearch-xpack` module configuration. When a user enables this module configuration, it results in the `elasticsearch` module being enabled with `xpack.enabled: true` set. The latter, in turn, enables certain specific metricsets that are necessary for Stack Monitoring. 

---

Another way (suggested by @A-Hall off-issue) would be to discover which Elasticsearch features are available and then auto-enable the corresponding metricsets. This is an interesting approach. @exekias @urso do we have any precedent for such an approach in other Metricbeat modules? Also, I'm wondering if this approach would translate well when we migrate from modules to packages.

cc: @sayden

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
