### ISSUE TITLE
[Heartbeat] Add negative body match

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#20728]
**Describe the enhancement:**

Today, heartbeat can match bodies using an arbitrary regexp with `check.response.body`, however this only matches positively. Users might want to perform a negative match as mentioned [in this well written forum post](https://discuss.elastic.co/t/heartbeat-make-http-check-response-body-get-negative-result-based-on-the-match/245332).

One thing that makes this tricky is that `check.response.body` expects a list of strings to match, so extending its syntax is a bit awkward. The best idea I can think of here is to add a new config option, `check.response.not_in_body`, but that feels awkward too. I'm curious if others have better naming ideas. There is an alternate proposal in the forum post, but it is not valid YAML.

**Describe a specific use case for the enhancement or feature:**

See the aforementioned forum post, where there are a large number of good values, but one bad value.

**Comment by xiaofengmanlou** [comment]
Hi Andrew,
I'm the original poster of https://discuss.elastic.co/t/heartbeat-make-http-check-response-body-get-negative-result-based-on-the-match/245332.
Thanks for creating this issue that we can discuss it here.

I'm working on this issue in my local fork too.
Actually, right now I put the new option under check.response as you mentioned too since want it to reverse the checkBody's result.

  check.response:
    status: 200
    body:
      - red
    reverse_check_body_result: fals

Then all I need to do is to update the checkBody function to add logic to check this option.
Wondering if there any possible I can file a PR to this issue with my code change?

Thanks.

**Comment by shahzad31** [comment]
@xiaofengmanlou  definitely go ahead and open a pr.

**Comment by shahzad31** [comment]
it would be nice if we can also improve the body mismatch error as mentioned in this issue by me https://github.com/elastic/beats/issues/18765

**Comment by xiaofengmanlou** [comment]
@shahzad31 
Thanks for your suggestion.
Opened a PR. But will need some time to sign contribute agreement.
Maybe I can take a look at your issue once my PR tests is success.

**Comment by andrewvc** [comment]
Resolved in #20746
