### ISSUE TITLE
Metricbeat Prometheus module - unable to decode response from prometheus end point

### ISSUE THREAD

**Issue by ArvindhVenkatraman** [elastic/beats#20762]
error.message
unable to decode response from prometheus endpoint: unexpected status code 403 from server

Prometheus.yml |
 - module: prometheus  
 period: 300s   
hosts: ["https://promethus-url" ]   
metrics_path: '/federate'  
 #bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token  
 bearer_token: 
query:    
 'match[]': '{job=~"apiserver"}'  
 headers:    
  accept: "text/plain"

if i run it through CURL, it works fine. 

"@metadata": {
--
  | "beat": "metricbeat",
  | "type": "_doc",
  | "version": "7.8.0"
  | },
  | "event": {
  | "dataset": "prometheus.collector",
  | "module": "prometheus",
  | "duration": 27971955
  | },
  | "metricset": {
  | "name": "collector",
  | "period": 300000
  | },
  | "service": {
  | "address": "prometheus-k8s-openshift-monitoring",
  | "type": "prometheus"
  | },
  | "error": {
  | "message": "unable to decode response from prometheus endpoint: unexpected status code 403 from server"
  | },
  | "ecs": {
  | "version": "1.5.0"
  | },
  | "host": {
  | "name": "host"
  | },
  | "agent": {
  | "ephemeral_id": removed
  | "id": "removed
  | "name":,removed
  | "type": "metricbeat",
  | "version": "7.8.0",
  | "hostname": removed
  | }

**Comment by ArvindhVenkatraman** [comment]
Team:metricbeat
Team:bug

**Comment by jsoriano** [comment]
Hey @ArvindhVenkatraman,

This looks like an authentication issue. In your configuration it seems that you have commented out the `bearer_token_file` setting. Is it like this in your configuration file?

We use Github issues for confirmed bugs and enhancement requests, your issue seems to be some kind of configuration problem. We use the discuss forums in http://discuss.elastic.co for community support and questions. Could you please open a topic there with your issue?

Thanks!
