### ISSUE TITLE
[Filebeat] tail_files option for Nginx module

### ISSUE THREAD

**Issue by sgc109** [elastic/beats#20950]
**Describe the enhancement:** It would be better if we can use *tail_files* option not only in filebeat.inputs section of config file but also in Nginx module, which has some useful features such as making sure each multiline log event gets sent as a single event, when we just want to read from the end of the log file rather than from the beginning.

**Describe a specific use case for the enhancement or feature:** An Nginx log file can be sent to the output from the end of the file rather than the beginning utilizing Nginx module

**Comment by kvch** [comment]
The feature you describe is available in Filebeat. You can override the input settings with the keyword `input`. See more here: https://www.elastic.co/guide/en/beats/filebeat/current/advanced-settings.html

Please next time instead of opening an issue, post your question on our [Discuss forum](https://discuss.elastic.co/c/elastic-stack/beats/28). Github is reserved for verified bugs and enhancement requests.
