### ISSUE TITLE
 event.created field in modules pipeline

### ISSUE THREAD

**Issue by immon** [elastic/beats#21243]
**Describe the enhancement:**

I want to bring under discussion the topic how ingest pipelines create `event.created` field.

Pipelines assume that ingested event has `@timestamp` field present. That's true when filebeat ships the log.

The problem is that if we use Pipeline Simulate API it  generates an `error.message` when it's used with test document.

Here is a screenshot showing this behavior. I'm using [nginx ingress_controller pipeline](https://github.com/elastic/beats/blob/v7.9.0/filebeat/module/nginx/ingress_controller/ingest/pipeline.yml) here and first log line [from the testcase](https://github.com/elastic/beats/blob/v7.9.0/filebeat/module/nginx/ingress_controller/test/test.log#L1):

![Screenshot_2020-09-23_11-18-45](https://user-images.githubusercontent.com/541494/94002637-718bce00-fd9a-11ea-8561-3cb543e02f05.png)

Highlighted is `error.message` generated. The problem is that the pipeline in [line 100](https://github.com/elastic/beats/blob/v7.9.0/filebeat/module/nginx/ingress_controller/ingest/pipeline.yml#L100) assumes that `@timestamp` field is available. This is true when Filebeat ships the log, but it isn't if one uses `_simulate` endpoint, or ship logs using custom tool.

The solution to avoid this erros is simple and we could add `"ignore_missing": true` to `rename @timestamp -> event.created` processor.

The question is if we should? If so, it looks that most pipelines are affected by this (I checked with this: `grep -r -C2 'target_field: event.created' beats/filebeat/module`) and `ignore_missing` should be added in multiple places.

Probably another question we should think about is if we should set `event.created` to the current time in cases where the event is lacking `@timestamp` field.

**Comment by andrewkroh** [comment]
> Pipelines assume that ingested event has @timestamp field present. That's true when filebeat ships the log.

The pipelines are made for use with Filebeat and may have requirements for fields like `@timestamp` that Filebeat produces. Because we know that Filebeat always produces certain fields it's safe for a pipeline to depend on them. And by having that hard failure (not ignoring missing) we get much more clear signal that something is wrong when fields are missing. So I would prefer not to add `ignore_missing`.

> Probably another question we should think about is if we should set event.created to the current time in cases where the event is lacking @timestamp field.

AFAIK all beats produce a `@timestamp` so this isn't a case I would worry about. If you trying to use the Filebeat module pipelines in your own application then you could wrap the pipeline with your own that does any requisite setup to mimic what Filebeat produces, then use the [pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/pipeline-processor.html) to invoke the Filebeat pipeline.

**Comment by immon** [comment]
Thanks for the comment Andrew.
We stumbled upon this issue trying to inspect nginx pipeline behavior and verify accepted log format of ingress_controller fileset. Seeing an error in pipeline simulate API was unexpected and only raised additional questions.

I agree with your arguments but I think that user experience could have been improved. Having a `script` processor like below before [rename](https://github.com/elastic/beats/blob/v7.9.0/filebeat/module/nginx/ingress_controller/ingest/pipeline.yml#L100-L102) processor would do the job.

```
    {
      "script": {
        "if": """ctx["@timestamp"] == null""",
        "lang": "painless",
        "source": """
        TimeZone tz = TimeZone.getTimeZone("UTC");
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
        df.setTimeZone(tz);
        ctx["@timestamp"] = df.format(new Date());
        """
      }
    },
```

Note, in the pipeline I linked above starting from line 37 we try hard to correctly handle `source.address`. I think we could do a better with `@timestamp` too.
