### ISSUE TITLE
No rule to make target `install-home'.  Stop.

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#2125]
HI @tsg ,

I am experiencing problems running `make package`.

Build Env = Centos 6.7
Beat = https://github.com/PhaedrusTheGreek/nagioscheckbeat

Whenever I run the packager, it seems to create most containers properly, but then fails on running a certain target: `install-home`.  

Then when running `make package` :

```
Step 5 : ENTRYPOINT /build_go_daemon.sh
 ---> Using cache
 ---> d4af7273ea02
Successfully built d4af7273ea02
# cross compile on ubuntu
docker run --rm \
        -v /opt/go/src/github.com/PhaedrusTheGreek/nagioscheckbeat/dev-tools/packer/build:/build \
        -v /opt/go/src/github.com/elastic/beats/dev-tools/packer/xgo-scripts:/scripts \
        -v /opt/go/src/github.com/PhaedrusTheGreek/nagioscheckbeat:/source \
        -e PACK=nagioscheckbeat \
        -e BEFORE_BUILD=before_build.sh \
        -e SOURCE=/source \
        -e BUILDID=bc58de355e41dfc385835e0801967d57bad1a9f6 \
        tudorg/beats-builder \
        github.com/PhaedrusTheGreek/nagioscheckbeat
Working directory=/go/src/github.com/PhaedrusTheGreek
Copying main source folder /source to folder /go/src/github.com/PhaedrusTheGreek/nagioscheckbeat
Fetching dependencies...
Execute /scripts/before_build.sh github.com/PhaedrusTheGreek/nagioscheckbeat
PWD
/go/src/github.com/PhaedrusTheGreek/nagioscheckbeat
make: *** No rule to make target `install-home'.  Stop.
make[1]: *** [nagioscheckbeat] Error 2
make[1]: Leaving directory `/opt/go/src/github.com/PhaedrusTheGreek/nagioscheckbeat/dev-tools/packer'
make: *** [package] Error 2
```

Strangely, when I run this target manually in the given directory, it works.

```
[root@max nagioscheckbeat]# pwd
/go/src/github.com/PhaedrusTheGreek/nagioscheckbeat
[root@max nagioscheckbeat]# make install-home
mkdir -p /tmp/nagioscheckbeat/kibana
if [ -d "etc/kibana" ]; then \
		cp -a etc/kibana/. /tmp/nagioscheckbeat/kibana/; \
		install -m 755 /opt/go//src/github.com/elastic/beats/dev-tools/import_dashboards.sh /tmp/nagioscheckbeat/kibana/; \
		install -m 755 /opt/go//src/github.com/elastic/beats/dev-tools/import_dashboards.ps1 /tmp/nagioscheckbeat/kibana/; \
	fi
install -d -m 755 /tmp/nagioscheckbeat/scripts/
install -m 755 /opt/go//src/github.com/elastic/beats/libbeat/scripts/migrate_beat_config_1_x_to_5_0.py /tmp/nagioscheckbeat/scripts/
```

I have generated the `vendor/` directory by using glide:

```
glide create
glide install
```

**Comment by tsg** [comment]
For nagioscheckbeat this should be fixed by https://github.com/PhaedrusTheGreek/nagioscheckbeat/pull/3

For the other community beats, we should consider the following changes:

* The generator doesn't encourage people to use a `vendor` directory, but it is actually required for packaging. I think we will save people time if we run `glide create` and `glide install --strip-vcs` during the setup phase and we default the `ES_BEATS` Makefile variable to the `vendor` dir.
* The generation of the `dev-tools` files currently happens at time of `make package`, but since these files should generally be committed, it would make more sense to include them in the generator template.
* The current `dev-tools/packer/Makefile` assumes Cgo, but most community Beats are pure Go. I think it's better to assume pure go, as the compilation is faster and the resulting binaries are static.

**Comment by tsg** [comment]
I spawned #2128 for the above points. Closing this one, but let us know if you hit any issues.
