### ISSUE TITLE
[BUILD][libbeat] stress-tests make goal does not work

### ISSUE THREAD

**Issue by v1v** [elastic/beats#21617]
### Command

```bash
$ make STRESS_TEST_OPTIONS=-timeout=20m -race -v -parallel 1 -C libbeat stress-tests
```

Some build examples:
- [here](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-21614/1/pipeline/891#step-2353-log-1) and
- [master build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/master/511/pipeline/643#step-1699-log-1) with 2.0 pipeline
- [7.9 build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/7.9/133/pipeline/4755) with 1.0 pipeline
- Travis, I cannot find any existing build that triggers the stress-test :/ to compare with

![image](https://user-images.githubusercontent.com/2871786/95317151-add82780-088c-11eb-8586-faf41a520860.png)

### Logs

```
[2020-10-07T09:55:56.175Z] + make STRESS_TEST_OPTIONS=-timeout=20m -race -v -parallel 1 -C libbeat stress-tests
[2020-10-07T09:55:56.175Z] make: Entering directory '/var/lib/jenkins/workspace/Beats_beats_PR-21614/src/github.com/elastic/beats/libbeat'
[2020-10-07T09:55:56.438Z] dirname: missing operand
[2020-10-07T09:55:56.438Z] Try 'dirname --help' for more information.
[2020-10-07T09:55:56.438Z] dirname: missing operand
[2020-10-07T09:55:56.438Z] Try 'dirname --help' for more information.
[2020-10-07T09:55:56.438Z] if [ -n '' ]; then \
[2020-10-07T09:55:56.438Z] 	go test --tags=stresstest -timeout=20m -race -v -parallel 1 ; \
[2020-10-07T09:55:56.438Z] fi
[2020-10-07T09:55:56.438Z] make: Leaving directory '/var/lib/jenkins/workspace/Beats_beats_PR-21614/src/github.com/elastic/beats/libbeat'
```

**Comment by ph** [comment]
@urso Might known more here.

**Comment by urso** [comment]
We did disable these stress tests a long time ago on Travis. These test the publisher pipeline by setting up a fake input and fake output with different profiles (blocking, slow, fast, eventual event drops and other scenarios). These are run for the memory queue and spooling to disk. We have had to disable them, because of performance issues in Travis, especially with spooling making almost no progress after 10min, which does lead to the run to timeout. Actually I'm a little surprised the test is enabled in the Jenkinsfile.

The Makefile tries to find all packages that have a package with a test file that contains `+build stresstest` in order to only run `go test -tags stresstest` for these packages (do not rerun all CI). The list of packages is generated [here](https://github.com/elastic/beats/blob/master/libbeat/scripts/Makefile#L44). `dirname` complains because it is passed an empty line it seems.

The `if` + `go test` comes from [here](https://github.com/elastic/beats/blob/master/libbeat/scripts/Makefile#L263). The output indicates that no packages are reported and there are no tests to run.

Better would be to find packages using this shell command: `find . -name '*.go' 2>/dev/null | xargs grep -l 'build.*stresstest' | xargs -n1 dirname | uniq`.

It seems like we haven't run any of these for a long time. Let me create a PR and see if these tests are actually stable.
