### ISSUE TITLE
Collect all annotations when using kubernetes autodiscovery

### ISSUE THREAD

**Issue by eedugon** [elastic/beats#22187]
**Describe the enhancement:**

Some users would like the ability of retrieving all pod annotations the same way as by default we retrieve all labels from pods.

Based on the [official doc](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html), we provide the setting `include_annotations` to add a static list of annotations to retrieve.

For labels we offer `include_labels` and `exclude_labels` settings, but if none are used, autodiscovery will retrieve all labels by default.

If there's a clear reason to not implement this we can use this issue to give visibility about it. My feeling (not totally sure) is that we don't want to implement this mechanism because annotations are also used internally by Kubernetes and we could be exposing too much information (maybe even sensitive data?), so better to force a static list in the configuration.

What are your thoughts about it?

**Describe a specific use case for the enhancement or feature:**
Needing to have visibility of all used annotations.

**Comment by exekias** [comment]
Hi @eedugon and thank you for opening!

The main reason for this is that from our experience, annotations can contain a huge amount of data. Including all annotations by default (like we do with labels), would bring many new fields that could even end up in mapping explosions. We have seen annotations being used for all kind of things, in many cases containing big JSON docs in.

That's why we went for allowing only to retrieve annotations requested by the user, is there any particular concern that you have here?

**Comment by masci** [comment]
I'm closing as we do have a reason not to do that. @eedugon feel free to reopen if a specific use case arises for this feature.
