### ISSUE TITLE
Agent goes to Offline status in UI for some time on upgraded 7.10.0 BC3 Kibana cloud environment

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#22188]
**Kibana version:**
Kibana: Upgraded 7.10.0 Kibana BC3 cloud environment

**Elasticsearch version:**
Elasticsearch: Upgraded 7.10.0 BC3 cloud environment

**Host OS and Browser version:**
Linux , All

**Original install method (e.g. download page, yum, from source, etc.):**
Upgraded 7.10.0 Kibana BC3 cloud environment

**Description**
Agent goes to Offline status in UI for some time on upgraded 7.10.0 BC3 Kibana cloud environment

**Preconditions**
1. Test Case Id https://elastic.testrail.io/index.php?/cases/view/22506 need to be executed.
2. Login into the above Kibana environment with 'elastic' superuser.
3. Endpoint integration should be added in Default Policy
4. 7.9.3 Linux .rpm enroll-deploy on 7.9.3 BC3 Kibana cloud environment.
Agent download location: https://staging.elastic.co/7.9.3-5a6c73d0/downloads/beats/elastic-agent/elastic-agent-7.9.3-linux-x86_64.tar.gz

**Steps to Reproduce**
1. Upgrade the environment to 7.10.0 BC3 (with commit ed66f41a8a60ad03426beff65ed270a743c46ac4)
2. Navigate to Agents tab in Kibana
3. Wait for some time(say 10 min) 
4. Observe that agent goes to offline status in UI while agent and endpoint service is still running on the Linux host.
5. Wait for some more time(say 10 min) and observe that agent is now displayed in Online status.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Agent goes to Offline status in UI on upgraded 7.10.0 BC3 Kibana cloud environment

**Expected Result**
Agent should not go to Offline status in UI on upgraded 7.10.0 BC3 Kibana cloud environment

**What's working**
 - N/A

**What's not working**
 - N/A
 
**Screenshot**
![agent in Offline_after_upgrade](https://user-images.githubusercontent.com/59917944/97303709-c2528300-1880-11eb-9be5-d093b560d8cf.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment]
@vipulsrivastava-qasource Please review the bug.

**Comment by vipulsrivastava-qasource** [comment]
Reviewed and Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
acknowledged.  I don't feel strongly about its urgency, so I will let the team get to it in usual fashion after reviewing.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX '

While performing smoke today on 7.10.0.BC4 build on locally deployed Kibana with details as folows:

Agent hash: c650b297
BUILD 35887
Kibana COMMIT: 3f7bbe02a2f08f0ad1c7f5a9b35235a4aa066a32
Artifacts link: https://staging.elastic.co/7.10.0-c650b297/summary-7.10.0.html/elastic-agent-7.10.0-windows-x86_64.zip

We found that Agent goes to Offline status in UI after some time of successful agent installation.
Screenshot: 
![Agent_GoingOffineAt7 10BC4](https://user-images.githubusercontent.com/72375798/97561460-39fdea80-1a06-11eb-9e57-a8d6b3b510ba.jpg)


Error message displayed:
` {"log.level":"error","@timestamp":"2020-10-29T15:20:33.479+0530","log.origin":{"file.name":"application/fleet_gateway.go","file.line":176},"message":"Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "http://localhost:5602/api/fleet/agents/37e58452-4f3b-4a91-a92e-2e46ad0f7a82/checkin?": dial tcp [::1]:5602: connectex: No connection could be made because the target machine actively refused it.","ecs.version":"1.5.0"}`

Please find detailed logs in attached file.   [Logs.txt](https://github.com/elastic/beats/files/5457795/Logs.txt)

Due to this issue, we got blocked on the remaining 17 testcases under Testplan: https://elastic.testrail.io/index.php?/runs/view/785

Please have a look at this and let us know if anything is required.

**Comment by EricDavisX** [comment]
Thank you @dikshachauhan-qasource .  In QA sync meeting we discussed if we are able to increase the resources of the vm running the self-managed stack.  we should increase to see if it helps alleviate the problem.  We should also review against the main elastic cited minimum requirements for kibana/elastic when running together on the same host (I think that is the setup here, right?).  I haven't found our formal hardware requirements, but I found this discuss page - https://discuss.elastic.co/t/hardware-recommendation/66833/8

and I know that Kibana itself can take at least 1 Gig of memory to run well, and ES as much as 8 Gigs on just one host which so if we aren't running with about 10 gigs on the vm running them than we can stop our search now and call it an unsupported environment.  Keep in touch and we can discuss more.  I'll ask if anyone knows if we have anything more formal about minimum requirements.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX ,

Thanks for the information and feedback on issue encountered due to unsupported environment. We have gone through the link on minimum requirements for kibana/elastic when running together on the same host.
Further, we have performed smoke for the blocked testcases on 7.10 BC4 Kibana cloud and found it working fine without any issues.
Testrun Link: https://elastic.testrail.io/index.php?/runs/view/785

Also in future, we would make certain about hardware requirements, before performing testing on local environment running kibana/elastic together.

**Comment by EricDavisX** [comment]
@rahulgupta-qasource can you help confirm if we want to close this based on the hardware at the time of the test vs what we can estimate is reasonable expectations?

**Comment by rahulgupta-qasource** [comment]
Hi Eric

We have validated the ticket on 7.10.0 BC6 Kibana cloud environment(with commit 1796b5ec8fa1e60ccea63f2e5c25ccc665b92fdc) from [cloud-prod](https://cloud.elastic.co) platform with following RPM agent(on Linux CentOS7 host) enrolled with Default policy having 'Endpoint Security' integration added.

7.10.0 BC6 RPM agent: https://staging.elastic.co/7.10.0-0624cd63/downloads/beats/elastic-agent/elastic-agent-7.10.0-x86_64.rpm


Observation:
1. Agent remains in Online status on Agents tab in Kibana and does not go into Offline status after sometime(say 10 min).
2. elastic-agent and endpoint service are running on above Linux CentOS7 host.


Screenshot:
1. Agent in Online status in UI:
![agent_online_UI](https://user-images.githubusercontent.com/59917944/99940829-f98a5600-2d92-11eb-805f-992d302a967e.jpg)


2. Elastic-Agent and Endpoint Service are running:
![elastic_agent_endpoint_status](https://user-images.githubusercontent.com/59917944/99940842-0018cd80-2d93-11eb-823b-ddb25628714b.jpg)



Hence, closing the issue.
