### ISSUE TITLE
Auditbeat under k8s fails to enrich short-lived processes

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#22238]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: n/a
- Operating System: Linux
- Discuss Forum URL: n/a
- Steps to Reproduce: 

The sample manifest for k8s provided in [deploy/kubernetes/auditbeat-kubernetes.yaml](https://github.com/elastic/beats/blob/master/deploy/kubernetes/auditbeat-kubernetes.yaml) uses the `add_process_metadata` and `add_kubernetes_metadata` to enrich events based on the `process.pid` field:

https://github.com/elastic/beats/blob/2474f5b08096bf2734f5a2452a8c6e0031dd3384/deploy/kubernetes/auditbeat-kubernetes.yaml#L32-L44
```go
    processors:
      - add_cloud_metadata:
      - add_process_metadata:
          match_pids: ['process.pid']
          include_fields: ['container.id']
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          default_indexers.enabled: false
          default_matchers.enabled: false
          indexers:
            - container:
          matchers:
            - fields.lookup_fields: ['container.id']
```

The drawback of this approach is that it's sensitive to timing. If the process identified by `process.pid` has terminated by the time the `add_process_metadata` processor runs, the `container.id` lookup will fail and no k8s metadata will be added to the event.

This is causing some processes to not be to associated to a container at all, or the association to happen randomly.

**Comment by efd6** [comment]
Following up [comment in 29410](https://github.com/elastic/beats/pull/29410#issuecomment-996437477), because of the variety of contexts in /proc/N/cgroup and interactions with other parts of the ingest pipeline, I think an approach here would be to capture a copy of the cgroup file for a started process and allow the ingest pipeline to process out what it wants from there in much the same way that `add_process_metadata` does now.
