### ISSUE TITLE
max_retries not respected when batch request to logstash fails

### ISSUE THREAD

**Issue by simitt** [elastic/beats#22539]
The publisher's pipeline batch function `reduceTTL` reduces the retry count by 1 for every call and returns a boolean indicating whether or not the batch is still alive. This can be used to determine if the batch should be retried. 

If the batches `ttl` is `0` it returns `true` - indicating that the batch is still alive. If `ttl==0` it should only return `true` if the batch contains any events that return `true` for `event.Guaranteed()`.

This leads to an infinite retry loop when trying to index corrupted events through logstash. 

## Steps to reproduce
The behavior was observed when trying to ingest corrupt data through logstash, which sent a `FieldReference exception` response. 

* start a beat where output is configured to logstash
* send an event that fails to be ingested, e.g. use `[ ]` in a field name of the event. 
* observe that the event is retried endlessly, not respecting the  configured  `max_retries` (which is only expected for `PublishMode` set to `GuaranteedSend`).

**Comment by faec** [comment]
What beat was used to test this? Some beats (Filebeat and Winlogbeat, last I knew) always have guaranteed send turned on, and are known to ignore `max_retries`. On other beats, it should work. There may still be a bug in some contexts, but it isn't as simple as the cause suggested in the report: while the sequence is a little confusing, the logic of `reduceTTL` checks guaranteed send when decrementing to 0, so (in theory) it's safe to return true when encountering a 0 since its contents were checked earlier.

I'm closing this by default for now since it's old and stale, but if it's still relevant I'm happy to take another look, just let me know the beat configuration it happens with (including specific beat).

**Comment by simitt** [comment]
@faec this was tested with APM Server back then; 
as you pointed out this is an old issue though, so no concerns from my side at this point to closing it.
