### ISSUE TITLE
Kibana fleet management does not read the port number from ece/kibana config

### ISSUE THREAD

**Issue by relent0r** [elastic/beats#22722]
For confirmed bugs, please report:
- Version: ECE Version 2.7, Kibana Version 7.10
- Operating System: Linux

In the beta of fleet management it will read the kibana and elastic urls but will not use the port number instead defaulting to 443. So if a non standard port is used for the kibana/elastic endpoint URL the incorrect url will be provided for the add agent guide and the default policy will also overwrite it. Easily corrected by changing the policy URL but would expect if it is getting the host URL from ece then the port number would also be captured.

**Comment by ph** [comment]
@relent0r where the URL is incorrect in the UI?

**Comment by relent0r** [comment]
Hi ph,

Under Fleet management in the overview or agents tab. Clicking on 'Add agent', under the 'Enroll and start the Elastic Agent' section it helpfully provides the command that can be used with custom url information based on the deployment information. This is the first place where the url is incorrect.
Then under the actual Agent policies, under fleet settings, there is a 'Global output' setting with the Kibana URL and Elasticsearch URL which both were incorrect.

in our deployment ece had set the port to 9243 but within fleet it was configured to 443.

**Comment by ruflin** [comment]
My guess is the error is somewhere around here: https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/common/services/decode_cloud_id.ts#L62 Seems we don't read the port in ECE correctly. @jfsiii You might know more?

**Comment by skh** [comment]
I'll have a look.

**Comment by skh** [comment]
This is a bug in Kibana, not in Beats. Closing this in favor of https://github.com/elastic/kibana/issues/84406

**Comment by jfsiii** [comment]
@ruflin @skh, perhaps but that's a port of the code and tests from Cloud itself. Related original issue and PR 
https://github.com/elastic/kibana/pull/65366 & https://github.com/elastic/kibana/issues/64513

Please update the tests if you find anything https://github.com/elastic/kibana/blob/1b6cfe819d4e68553a6bf84b3cee2712eb05cb7c/x-pack/plugins/fleet/common/services/decode_cloud_id.test.ts#L8

I would begin by adding logging in the two places we use it and see what values we have https://github.com/elastic/kibana/blob/89547bc0166e375e3249edffd94dbb2797085f52/x-pack/plugins/fleet/server/services/settings.ts#L87 or https://github.com/elastic/kibana/blob/89547bc0166e375e3249edffd94dbb2797085f52/x-pack/plugins/fleet/server/services/output.ts#L32 and see the values of cloudUrl, flagsUrl, defaultUrl

There's also the situation described in where an initial setup value is retained vs the current value https://github.com/elastic/kibana/issues/71115 As the ticket says, it appears intentional but mentioning it because it's surprised me before when I was looking into these
