### ISSUE TITLE
Add support for symlinks

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2277]
Open this to discuss a proper implementation for symlinks in Filebeat. Filebeat used to have accidental support for symlinks which resulted in duplicates and was removed in #1767.

To summarize the IRL discussions: since symlinks potentially come with lots of corner cases (files change under the symlink, the symlink gets removed by the the file not, the other way around, etc.) we think a correct implementation should be done as a new harvester type.

**Comment by ruflin** [comment]
Playing around with Symlinks and looking at our code again, I realised that our current harvester is not aware if it is a symlink or not. The reason is that `file.Stat()` is used instead of `file.LStat()` during opening the file. Based on the `FileInfo` retrieved it is not possible anymore two make the difference. This is the reason even though checks were in place since LSF to disable symlinks, it always worked.

Initially I was thinking it would be best if symlinks is a different harvester type. I changed my mind here as I like the idea that the harvester does not have to care if it is a symlink or not. It keeps the code simpler and the decision if a harvester should be opened for a symlink is up to the prospector. 

One of the initial ides was to follow the symlink and then open the original file. But based on the discussion in https://github.com/elastic/beats/pull/1767 that does not seem the way it should be in the kubernetes use case where the name of symlink is relevant. If the original would be harvested, also the original file name would be reported.

Based on this my conclusion is that the initial (accidental) implementation was as expected. The only side affect with this is that if the symlink or the original file is removed, no further data can be harvested. But I think this is kind of expected.

Here is a first implementation for further discussions: https://github.com/elastic/beats/pull/2478

**Comment by ruflin** [comment]
Thinking again about the additional harvester type `symlink`: The implementation would be very similar on would not change much. The advantage would be that people would be very aware that they use symlinks and would apply it to specific files. The disadvantage is that symlinks and normal files could not be mixed in one prospector. In case we have an `input_type: file` or `input_type: gz` the question would arise, if these also support symlinks. That would become harder if it is it's own harvester type. Also the more accurate name would probably be `log_symlink`.

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/beats/pull/2478 was merged.
