### ISSUE TITLE
Need: UUID for the fingerpringt processor

### ISSUE THREAD

**Issue by geheim01** [elastic/beats#22770]
**Describe the enhancement:**
Introduction of the UUID method for the fingerprint processor

**Describe a specific use case for the enhancement or feature:**
I'm trying to demonstrate gdpr pseudonymization compliance using the filebeat as described in this article using Logstash: https://www.elastic.co/de/blog/gdpr-personal-data-pseudonymization-part-1
To make the pseudoids bulletproof, I need the UUID method, unfortunately the fingerprint method has no UUID method at the moment.
*UseCaes*
Data comes in. I would like to pseudonymize a certain field. Filebeat checks if the data has this field, if so create a new document in the Index Identities, create a mapping and replace the personal data with a pseudoId created by UUID in the Index Events.

**Comment by urso** [comment]
From logstash documentation about the UUID method: 

> When the target option is set to UUID the result won’t be a consistent hash but a random UUID. To generate UUIDs, prefer the uuid filter.

Using the fingerprint processor in Beats you can only hash. This gives you a value that depends on your event contents. Basically a stable hash. The UUID method generates a random value only (no hashing of fields is required). This is why one should better use the UUID filter.

In Beats there is a [add_id](https://www.elastic.co/guide/en/beats/filebeat/current/add-id.html) processor. Currently it only supports the elasticsearch method, which is constructed based on the timestamp and some kind of counter, which speeds up indexing a little.

Skimming the article the Logstash fingerprint processor is used for consistent hashing (which the UUID method is not). The Logstash filter pipeline in the article first computes a consistent hash from the fields and finally uses the ruby filter to split the event into two events. The identity event has the form `{"_id": <consistent hash>, "<key>": <consistent hash>, "value": <value>}`. The way the pipeline is setup, there doesn't seem to be a lookup feedback cycle, meaning the consistent hash is a must. The strategy depends on Elasticsearch removing duplicate fields for already known hashes.

In order to replace the consistent hash with an UUID one might want to write the complete filter in ruby, as the filter would need to maintain a table of `concrete value => random ID`, in order to ensure that common values will match a single document in the identity index. What is nice about this approach is, that without the identity index one can not "attack" the hash trying to reconstruct the original entry from dictionaries. Drawback is that the table maybe needs to be "cleaned" from time to time and IDs might change between restarts unless you find a way to load your lookup table on start.

Without the table managed within the ruby filter, each event will produce an entry in the identity index otherwise. The advantage of having a common ID for matching values like "user" is, that it is still possible to correlate related events or product meaningful metrics via aggregations, without having the original values. Producing full randomized values per entry makes it impossible to correlate events for related (anonymized) entries without additional processing.

Currently processors in filebeats can not produce new events. There are technical limitations that currently make this impossible. AFAIK ingest node can't be used to split the event into two events as well. In this regard Logstash is most flexible right now.

**Comment by jlind23** [comment]
Backlog grooming: Closing for now.
