### ISSUE TITLE
Prepare beats for impending deprecation of _all field

### ISSUE THREAD

**Issue by dakrone** [elastic/beats#2286]
We've opened an issue over on Elasticsearch about about disabling or removing the _all field: elastic/elasticsearch#19784

Just like Logstash, Beats will need to determine whether they want to support the `_all` functionality out of the box by setting either `index.query.default_field` or using the mapping parameter `copy_to` to create a "catch-all" field for querying in the template. This issue is to open a discussion about moving away from the `_all` field being enabled altogether. It may be good to coordinate on the Kibana issue (https://github.com/elastic/kibana/issues/8007) about how the beats data is likely to be queried.

**Comment by tsg** [comment]
@dakrone thanks for checking with us and sorry for replying so late on this. We've discussed this on our team meeting today, and the general feeling is that while we don't use the `_all` field directly in any way, our users are probably using it quite often via the Discover tab in kibana. So the way this is handled in Kibana is what really matters for us.

One question (if that discussion progressed enough since then to answer this): will it be possible for the search bar in Kibana to search multiple fields at once? To give an example, we'd want the default experience for Packetbeat users to be to search in the `request`, `response`, `src_ip`, and `dst_ip`.

**Comment by dakrone** [comment]
@tsg I think the multi-field search is definitely the way we're headed, check out the feedback on https://github.com/elastic/elasticsearch/pull/20925 if you want to follow along with the development :)

Going to close this for now since you said that you don't use the `_all` field directly, thanks for commenting!
