### ISSUE TITLE
CloudTrail in AWS Module does not work when CloudTrail is enabled at Organization Level

### ISSUE THREAD

**Issue by alaa-mallah** [elastic/beats#23203]
**Describe the enhancement:**
Have the ability to specify a path for the CloudTrail S3 bucket

**Describe a specific use case for the enhancement or feature:**
If CloudTrail is enabled at the organization level, then the path structure would look like this:
"object.key": "AWSLogs/<o-aws-organization-id>/12345678910/CloudTrail/ap-southeast-2/2020/11/30/12345678910_CloudTrail_ap-southeast-2_20201130T1305Z_QuZ9yKG0lRw5wLmx.json.gz

However, filebeat is expecting different path structure:
"object.key": "AWSLogs/12345678910/CloudTrail/ap-southeast-2/2020/11/30/12345678910_CloudTrail_ap-southeast-2_20201130T1305Z_QuZ9yKG0lRw5wLmx.json.gz"

As a workaround, regex changed here, in order to parse the organization id folder in the s3 bucket
https://github.com/elastic/beats/blob/5d077092d3e0aacfecae81ea307a3c6fda748705/x-pack/filebeat/module/aws/cloudtrail/config/s3.yml#L3-L7

from: '^AWSLogs/\d+/CloudTrail/'
to: ^AWSLogs/\S+/\d+/CloudTrail/

**Comment by andrewkroh** [comment]
This is similar to https://github.com/elastic/beats/pull/23126 but the format of the path is different.

**Comment by andrewkroh** [comment]
The docs at https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-find-log-files.html indicate that the format is

`bucket_name/prefix_name/AWSLogs/OU-ID/Account ID/CloudTrail/region/YYYY/MM/DD/file_name.json.gz`

so that patterns we have need adapted to handle the optional `OU-ID/` part.

I was playing with https://regex101.com/r/7WfOYY/2 as a quick test.
