### ISSUE TITLE
[Fleet]: Debug level logs are still streaming in for Agent when logging level is set to 'Warning'

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23243]
**Kibana version:**
Kibana: 8.0.0 snapshot Kibana Cloud environment  

**Elasticsearch version:**
Elasticsearch:  8.0.0 snapshot Kibana Cloud environment  

**Host OS and Browser version:**
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.):**
8.0.0 snapshot Kibana Cloud environment  

**Preconditions**
1.  8.0.0 snapshot Kibana Cloud environment should be available.
```
BUILD 39157
COMMIT a76c666a6153b062d2f9d97b5c7e87620339a181
Artifact link: https://snapshots.elastic.co/8.0.0-a92f4e04/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```
2. Agent should be installed using a test policy [having system integration].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Agents tab. Click on Hostname. And navigate to logs section.
3. Select filter option 'elastic-agent.filebeat' from Dataset filter.
4. Notice, info level logs are displayed by default.
5. Change Agent logging level to 'Warn'. Apply changes and wait for confirmation message.
6. Refresh browser. Notice, agent logging level updated.
7. Wait for 4-5 secs.

**Reference ticket Id:**
N/A

**Actual Result**
Observe, Debug level logs are displayed for Agent under 'elastic-agent.filebeat\elastic-agent.metricbeat'.

**Expected Result**
Warn level logs should be displayed for Agents under 'elastic-agent.filebeat\elastic-agent.metricbeat' when Agent logging level is set to 'Warn'.

**What's working**
Logs under 'elastic-agent' at Dataset filter are displayed as per Agent logging level set.

**What's not working**
N/A

**Screenshots:** 
![Screenshot1](https://user-images.githubusercontent.com/72375798/102885813-ffe71d00-4479-11eb-973f-c62145c0b4d8.jpg)

![Screenshot2](https://user-images.githubusercontent.com/72375798/102885843-083f5800-447a-11eb-8425-a433f69178be.jpg)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@nchaulet @michalpristas I'm not sure how to tell if it is on the Kibana side sending the request or on the Agent or Beat side that it isn't setting the value correctly.  What details do you need to figure this out?

**Comment by EricDavisX** [comment]
I can ask for a re-test @dikshachauhan-qasource ?  We have fixed up all of the feature with the exception of Endpoint log level (which seems a special case).  I did a quick test prior and it looked fixed, but with a closer eye perhaps you'll notice something more, thank you for the attention on it.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated this issue on 7.11 BC5 Kibana cloud build . Build details are as follows:

```
BUILD 37827
COMMIT d801a7bb08e17368584d00fbd97a5d0006285b51
Artifact Link: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
```
**Observations:**
'debug' level log are getting displayed under elastic_agent.filebeat/metricbeat dataset even after 20 minutes of time when agent logging level was last updated.

**Screenshot:**
![23735](https://user-images.githubusercontent.com/72375798/106277735-923fc500-625f-11eb-8bff-859953002bda.png)

Thanks
QAS

**Comment by EricDavisX** [comment]
@jen-huang I think this is a valid bug, that setting 'warning' in the UI doesn't work to do much... the original PR has 'warn' level tested, I see.  So that is probably intended, but it has changed since - I can't see where yet.  I couldn't tell where it was pulling the values from to populate that Agent levels list, maybe it is pulled from an index at run time, relating to this line?  https://github.com/elastic/kibana/pull/83356/files#diff-b026ba2f4007085d2b3977b510bc647e68635512c42590f6d42be5ba6fd7da41R10

Either way, the Agent / Filebeat / Metricbeat all show 'warn' in the actual logs, so I think the UI showing 'warning' and setting it to 'warning' currently is a bug.  

see screenshots:
Warning has nothing:
![no-warning-message](https://user-images.githubusercontent.com/12970373/106326091-ea6bcc80-6249-11eb-8d19-d2e7461e3fe8.png)

'warn' itself is what shows from Agent / Filebeat / Metricbeat
![warn-is-ok-though](https://user-images.githubusercontent.com/12970373/106326092-ea6bcc80-6249-11eb-8970-b00dc5571f17.png)

note: We can leave Endpoint as the outlier, by the way, I would ignore it for now as changing the level isn't modifying Endpoint output at all, separate ticket logged.

**Comment by EricDavisX** [comment]
ok- I spoke with @nchaulet who worked on this part of the Kibana code and he convinced me it is probably just a bug in Metricbeat / Filebeat - the screenshots are telling, but he notes that the actual output in the logs is unrelated to the value sent when setting the log level.  And he says if we set 'warn' via Kibana that Metricbeat rejects it, so that isn't the fix as I had hypothesized.  

@michalpristas want to take a look at this after you finish others? :)

**Comment by EricDavisX** [comment]
I don't think this is 'high' impact, as it is just the helpful logging that is impacted.  and it works for 'debug' and for 'error' which will be the 2 most common levels set, if anyone even bothers to change it from the default of 'info'.

**Comment by EricDavisX** [comment]
More from Nicolas:
...Looks like the log level warning is not transmitted from the agent to metricbeat
https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/core/plugin/process/start.go/#L135-L152

so if the level is warning the level send to metricbeat is “” that fallback to “debug” #23769 
🎉

**Comment by EricDavisX** [comment]
we'll discuss if we want to backport to 7.11 and will confirm back

**Comment by EricDavisX** [comment]
we backported and it is testable in BC6 coming out in a few days.  we can track testing here in this git issue

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated this issue on 7.11 BC6 Kibana Cloud environment and found above reported issue as **Fixed.** Build details are as follows:
```
Artifact page: https://staging.elastic.co/7.11.0-af4ff60e/summary-7.11.0.html
Build: 37890
Commit: 80030db683333591cf7de76bc6780c96e8b733a2
```

Observations:
- 'Warn' level logs are getting generated for elastic-agent.filebeat and metricbeat when Agent logging level is set to 'Warning'.

![image](https://user-images.githubusercontent.com/72375798/107033046-bd379500-67da-11eb-98aa-e07428ade871.png)

Further, we have a query at point raised by you in [comment](https://github.com/elastic/beats/issues/23243#issuecomment-770045107).

Currently, warning option is getting displayed in Agent logging level dropdown. Could you please confirm if it will remain as it is or will update to 'Warn'.

Thanks
QAS

**Comment by EricDavisX** [comment]
it will stay as 'Warn'.  I had a good discussion about exactly that with N Chaulet, and he convinced me it was the better value - as it directly relates to what the actual level value is in Agent / Beats, regardless of what value shows in the logs.  So we can update test content if needed.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thanks for the feedback.

We have updated our 01 testcases for same. Test link link is as follows:

- [C204932](https://elastic.testrail.io/index.php?/tests/view/204932)

Thanks
QAS
