### ISSUE TITLE
[Elastic Agent] Improve log visibility

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#23307]
Can we please improve the visibility of Elastic Agent logs on the host? This will help in troubleshooting connection issues to Kibana/ES. For example, I had problems with my ES certificate and the agent was stuck in enrolling, with no details in Fleet on why. The only way I could get visibility to this issue is in the agent logs on the host.

It's unexpected to me to find logs under /opt/Elastic/Agent. Why not put logs in /var/log? This is the standard location for most distributions of Linux. This is also the default for Filebeat on Debian. Perhaps we can mirror other defaults defined here https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html

Also, I can't read the logs without sudo. Can we make them group adm and chmod 640? This is the permission level for many of the logs in /var/log. If we are not concerned about sensitive info, we could keep group root and chmod 644. Ideally, we are not logging secrets as a best practice.

**Comment by mostlyjason** [comment]
@ph can you review this when you get a chance? I ran into this issue again today when I was troubleshooting why one of my hosts stopped sending data to ES. I imagine this will be a common scenario for people. 

Without execute permission I can't even run wildcard commands to search the logs. These logs are not sent to ES either, so there is no way to search across multiple files.
```
$ sudo grep vpn /opt/Elastic/Agent/data/elastic-agent-1da173/logs/default/*
grep: /opt/Elastic/Agent/data/elastic-agent-1da173/logs/default/*: No such file or directory
```

**Comment by ph** [comment]
There is two problems in this issues.

## Expected path

> It's unexpected to me to find logs under /opt/Elastic/Agent. Why not put logs in /var/log? This is the standard location for most distributions of Linux. This is also the default for Filebeat on Debian. Perhaps we can mirror other defaults defined here https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.

I think we have to explain the why we are doing that, when you install `elastic-agent` via DEB or RPM they will actually install them in the `/var/log`. When you use the `install` subcommand we actually installing everything in `/opt`. Note this is also where Endpoint install his files in both cases. We wanted to be consistent as much as we can.  I haven't double checked, but I believe we have added the layout in our documentation?

## Permissions issues

We are indeed adding more restrictions on files that are available in that directory, I am not sure if it's really a problem because, as we add more protection feature we will probably lock down files or behavior even more. I would expect the user to have administration privileges to see them on the machine and also that the log would be sent off the machine. Which is not working correctly in your current tested version.

@urso @ruflin @blakerouse Would like your opinion here?

I think the following would work for you?
```
sudo grep -r "vpn" /opt/Elastic/Agent/data/elastic-agent-1da173/logs/default/
```

You could also do `sudo bash` and run anything freely.

**Comment by blakerouse** [comment]
@mostlyjason @ph is correct in his usage of `bash`. The reason that `grep` is failing is because the permission level of Agent is root, so a standard user with a wildcard of `*` will not have permissions to even determine the file names. You should do `sudo su` or `sudo bash` to be at the correct permission level.

The usage of `/opt` for the `install` command is because of the [https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). Anytime on Linux software is installed and it is not controlled by the package manager then it should be installed into `/opt`. Just like Endpoint Security installs into the `/opt` directory, for the exact same reason.

**Comment by mostlyjason** [comment]
Ok thanks for the input! I guess these reasons make sense.

I do see the log path documented here https://www.elastic.co/guide/en/fleet/7.10/elastic-agent-installation.html. However, this only contains the log path for the agent, not for the beats. You really need the beats log to troubleshoot problems with the output. Would it be worthwhile to mention the location of the beats logs?

I also don't see the agent and beats logs mentioned in the troubleshooting guide. Perhaps we could add section about it? https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html

**Comment by ph** [comment]
I am closing this issue and move the documentation task in https://github.com/elastic/beats/issues/23597
