### ISSUE TITLE
Unenrolling Agent e2e-test fails - increasing timeout often passes the test, may have performance issue, etc

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23593]
https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2F7.x/detail/7.x/110/tests/

<img width="1069" alt="Screen Shot 2021-01-20 at 12 25 04 PM" src="https://user-images.githubusercontent.com/12970373/105212430-70d23100-5b1b-11eb-87b9-fffd419ecdbf.png">

The tests on 7.9 / 7.10 were / are passing, but 7.x is failing the last 2 days in a row and we've seen the flakiness building (slowly) over a few months.

**Comment by EricDavisX** [comment]
we are going to increase the timeouts (again) for now just to get the Beats PR CI passing.  but this is a hack and we need to investigate why / whats going on.  Thanks @mdelapenya

**Comment by mdelapenya** [comment]
Adding more context:

- the elastic-agent takes almost 6 mins to appear in the Security app, which we see a potential flakiness in the e2e tests, as we are limiting a backoff wait until it appears to 6 minutes. After elastic/e2e-testing#624, we are using 5 instead of 3 as default timeout factor **on CI**, which means that the tests will wait up to 10 mins for the host to be present in the Security app.

**Comment by ph** [comment]
@michalpristas Can you take a look at this, from the discussion on slack even with added timeout this seems a real problem on 7.x
