### ISSUE TITLE
Journalbeat reopen reader on corrupted journal

### ISSUE THREAD

**Issue by kvch** [elastic/beats#23627]
When an input journal file gets corrupted, Journalbeat logs are filled with the following message:

```
Error while reading event: failed to iterate journal: bad message {"id": "{{ uuid }}"}
```

As journals does "rotate-on-corruption", we can reopen the journal file and Journalbeat can continue reading correct journal entries.

The current workaround is to restart Journalbeat on this error manually or restart the Beat periodically to make sure it can restart after it reaches a corrupted entry.

**Comment by kamermans** [comment]
This also affects my servers (Ubuntu 20.04, jornalbeat 7.10.2).  Occasionally (3 times in the last month on one server alone), `journalbeat` does this and fills syslog with 30 GB of error messages per day until the entire disk is full.   Luckily our monitoring systems notify us and we restart the service and delete the log data.

Is there something I can provide that will help replicate or prioritize this issue?

**Comment by kamermans** [comment]
Just a friendly note that this is still trashing my servers regularly.  I am happy to provide more information or test things out, but this beat seems totally unusable to me at this point in (at least in Ubuntu server), and I'll probably just end up switching the entire logging pipeline to `fluent bit` because of this one bug.

@kvch If you have a patreon or paypal or something, I'll gladly compensate you for your time to fix this bug.

**Comment by sisoftrg** [comment]
I also have this issue, journalbeat going crazy several (2-5) times a day on most of loaded servers, eating a free space and cpu.
For now I ended up with the script to restart journalbeat:

```
tail -F -n0 /var/log/syslog | grep --line-buffered 'Error while reading event: failed to iterate journal: bad message' | while read q; do
    systemctl stop journalbeat
    sleep 1
    systemctl start journalbeat
done
```
It works as a dirty workaround, but already tired that the necessary part of the logs may not be found later.

**Comment by angristan** [comment]
I can relate, journalbeat when crazy last night and ate 120 GB of disk space in less than 2 hours:

<img width="518" alt="screenshot_2021-04-08_10-55-09" src="https://user-images.githubusercontent.com/11699655/113998117-0ba7f500-9859-11eb-88d8-c1afa37f0285.png">

**Comment by pd-dfinity** [comment]
+1 here minus the storage consumption. Do we happen to know common workloads or services that might cause this? We run Nginx on these systems.

**Comment by kvch** [comment]
@rsdrakh I have created an alternative solution for this problem. Could you please test it? https://github.com/elastic/beats/pull/26224

If it still fills up your disk, I will disable displaying the error for a period of time.

**Comment by pd-dfinity** [comment]
Would it be feasible to use some logger library to do something like logger.atMostEvery(X seconds).log(blub)? Having a busy loop that fills up the disk space seems really suboptimal

**Comment by kvch** [comment]
@pd-dfinity My second alternative implementation does something similar. Unfortunately, the lib we use does not support such behaviour, so I had to implement our own for now.

**Comment by rsdrakh** [comment]
@kvch I'd do my best to test - but I don't really know how to get your code to my machines other than using a deb file :)
Do you have the possibility to get that into a debian package somewhere?

**Comment by kvch** [comment]
@rsdrakh I have uploaded a test deb package here: https://drive.google.com/file/d/1uo1EZZ1GCexv9svWUe-LJAjEmtv9tFt7/view?usp=sharing

Please do not use it in production!

**Comment by qwinkler** [comment]
Any updates on reopening the journal file? Faced with the same problem. The workaround is not working properly. It works well for an hour or even less, and then the problem appears again. The only fix is to completely clean up the journal logs:
```
sudo find /var/log/journal -name "*.journal" | xargs sudo rm 
sudo systemctl restart systemd-journald
```
When the journal is empty, the journalbeat will work for a week or so.

**Comment by kvch** [comment]
Have you tested it with Journalbeat 7.14?

**Comment by sisoftrg** [comment]
It worked well for last few weeks with 7.14[.1], thank you.

**Comment by kvch** [comment]
I am closing this issue. Feel free to reopen if the problem resurfaces.

**Comment by kamermans** [comment]
Thanks for your work on this @kvch, the log data problem is resolved!

Unfortunately, the underlying issue seems to persist in both `7.14.0`, and after I upgraded to `7.15.2`.

Here are the errors from `7.14.0` (every 5 seconds):
```
Nov 16 15:33:35 ie-osc-1 journalbeat[2696684]: 2021-11-16T15:33:35.405Z        ERROR        [input]        input/input.go:185        Error while reading event: failed to iterate journal: bad message
Nov 16 15:33:40 ie-osc-1 journalbeat[2696684]: 2021-11-16T15:33:40.405Z        ERROR        [input]        input/input.go:185        Error while reading event: failed to iterate journal: bad message
Nov 16 15:33:45 ie-osc-1 journalbeat[2696684]: 2021-11-16T15:33:45.407Z        ERROR        [input]        input/input.go:185        Error while reading event: failed to iterate journal: bad message
Nov 16 15:33:50 ie-osc-1 journalbeat[2696684]: 2021-11-16T15:33:50.408Z        ERROR        [input]        input/input.go:185        Error while reading event: failed to iterate journal: bad message
Nov 16 15:33:55 ie-osc-1 journalbeat[2696684]: 2021-11-16T15:33:55.409Z        ERROR        [input]        input/input.go:185        Error while reading event: failed to iterate journal: bad message
```

We noticed this because `journalbeat` was using 200% CPU (as reported by `htop`, so basically 2 CPU cores were tied up).

I restarted `journalbeat` which had no effect.  I upgraded it to `7.15.2` and restarted it, also no effect.  In both cases, `journalbeat` started hitting the CPU hard immediately after startup and didn't stop.

In the end I had to stop `journalbeat`, vacuum up some of the `journald` journals (which presumably had a corrupt entry) and restart `journalbeat`:

```
sudo systemctl stop journalbeat
sudo journalctl --vacuum-time=1d
sudo systemctl start journalbeat
```
(of course, it was only by chance that the corrupt journal was older than 1 day - if some reader finds this doesn't help, you should clean everything like `sudo journalctl --vacuum-time=1s`)

I will keep an eye out for more occurrences of this.  If we see it again, would it help for me to backup the potentially-corrupt journal files and send them to you or something?
