### ISSUE TITLE
README templates produce confusing documentation for Agent

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#23702]
We use golang templates to generate the README files that are packaged with the beats releases:

```
{{.Description}}

## Getting Started

To get started with {{.BeatName | title}}, you need to set up Elasticsearch on
your localhost first. After that, start {{.BeatName | title}} with:

     ./{{.BeatName}} -c {{.BeatName}}.yml -e
```

This works fine for most things, but with agent, it results in a README.md that looks like this:

```
## Getting Started

To get started with Elastic-Agent, you need to set up Elasticsearch on
your localhost first. After that, start Elastic-Agent with:

     ./elastic-agent -c elastic-agent.yml -e
```

If you're just unpacking agent and trying it out for the first time, that won't work, as you're (obviously) supposed to enroll the agent first. I ran into someone yesterday who _just_ got their documentation from the above README, and it ended up putting the agent in a really odd state where it took even myself a while to figure out what had gone wrong. Agent will probably need its own README that directs someone to either our docs page, or the Kibana enrollment page.

**Comment by dedemorton** [comment]
TBH, I think these instructions are too basic for Beats, too. They gloss over a lot of detail, especially for Metricbeat and Filebeat where users are likely to want to enable modules. Also the leading `./` in the template will cause problems on platforms where we provide a wrapper script. And...the instructions make it sound like you must have Elasticsearch running on the local host. That's not a realistic getting started experience and definitely not "cloud first."

I think the info in the readne is too hand wavy to be useful. (IMO we have a similar problem with the product download pages.) I think that's one reason why users struggle to ingest data. In multiple places, we provide simple instructions that are easy to follow, but they don't work in the real world. Instead of sending users down rabbit holes, we should provide them with instructions that actually work in the real world.

Whoa, I'll get off my soapbox and just say that it would be better to provide a brief description of what the Beat does and then point to the docs for more information.

**Comment by fearful-symmetry** [comment]
Agreed, it would probably be better to provide some summary data and then point to the docs site.

**Comment by dedemorton** [comment]
This has been in the backlog for awhile. I am not sure how much confusion the readme is causing in the field, but I worry that it sends users down the self-managed path and has some confusing bits (for example, the release notes link sends users to the Beats changelog, which does not contain any details about Elastic Agent). It's also very confusing for users to see a setup command that is not even valid when using an Elastic Agent.

We have a redirect set up for the main documentation link, but we cannot create a redirect for the release notes in libbeat because that link is valid for Beats.

@nimarezainia Who should I tag to see if we can get the priority for this bumped? Now that Elastic Agent is GA, I feel it's unacceptable for the readme to be incorrect and confusing.

**Comment by dedemorton** [comment]
For more context, here is what the readme for Elastic Agent currently says:

# Welcome to Elastic-Agent 7.16.2

Agent manages other beats based on configuration provided.

## Getting Started

To get started with Elastic-Agent, you need to set up Elasticsearch on
your localhost first. After that, start Elastic-Agent with:

     ./elastic-agent -c elastic-agent.yml -e

This will start Elastic-Agent and send the data to your Elasticsearch
instance. To load the dashboards for Elastic-Agent into Kibana, run:

    ./elastic-agent setup -e

For further steps visit the
[Quick start](https://www.elastic.co/guide/en/beats/elastic-agent/7.16/elastic-agent-installation-configuration.html) guide.

## Documentation

Visit [Elastic.co Docs](https://www.elastic.co/guide/en/beats/elastic-agent/7.16/index.html)
for the full Elastic-Agent documentation.

## Release notes

https://www.elastic.co/guide/en/beats/libbeat/7.16/release-notes-7.16.2.html

**Comment by fearful-symmetry** [comment]
Most of this is fairly old, closing.
