### ISSUE TITLE
Metricbeat: Oracle module failing to connect while SQL module works

### ISSUE THREAD

**Issue by eedugon** [elastic/beats#24118]
One user is reporting problems connecting to an Oracle DB using our oracle module with very basic configuration.
The Instant Client is installed and tested, and also our SQL module of Metricbeat is able to perform connections and even running a SQL like `SELECT TABLESPACE_NAME, TABLESPACE_SIZE, ALLOCATED_SPACE, FREE_SPACE FROM DBA_TEMP_FREE_SPACE;` with the same user.

The error that appears using the oracle module is:

```
2021-02-10T11:07:08.451+0100 INFO module/wrapper.go:266 Error fetching data for metricset oracle.tablespace: error creating connection to Oracle: error doing ping to database: params=oracle://username%3Apassword%40oracle-server.fqdn%3A1521:xxxxxxxx?connectionClass=xxxxx&enableEvents=0&heterogeneousPool=0&poolIncrement=1&poolMaxSessions=1000&poolMinSessions=1&poolSessionMaxLifetime=1h0m0s&poolSessionTimeout=5m0s&poolWaitTimeout=30s&prelim=0&standaloneConnection=0&sysasm=0&sysdba=0&sysoper=0&timezone= extAuth=0: ORA-12162: TNS:net service name is incorrectly specified
```

Metricbeat config:
```
- module: oracle
   metricsets: ["tablespace", "performance"]
   enabled: true
   period: 10s
   hosts: ["user:password@server-FQDN:1521/DB_SID"]
```

Metricbeat version: 7.9
OCI Client version: 21.1
Oracle version: 12.2

**Comment by falkrist** [comment]
It can be a bug basically. As we were also not able to connect in documented way. Try to use "/" between username and the password instead of ":". Just like that:
```
- module: oracle
   metricsets: ["tablespace", "performance"]
   enabled: true
   period: 10s
   hosts: ["user/password@server-FQDN:1521/DB_SID"]
```
This works for us, BUT oracle module with such config expose login and the password to Elastic logs, and you can see it as a plain text in Kibana UI. What I believe is not secure and should be fixed.

**Comment by sayden** [comment]
The recommended way across all metricbeat is to use the fields `username` and `password` in the configuration yaml so credentials are masked.

There's, however, a mistake in the docs where the connection string in `hosts` must be prefixed with `oracle://`. This way, your username and password will also be masked, because it's properly recognized as a FQDN. Still, it's better to place them in the username and password fields.

**Comment by falkrist** [comment]
Hi @sayden,
thanks for your reply. So the correct connection config should look like this?
```
- module: oracle
   metricsets: ["tablespace", "performance"]
   enabled: true
   period: 10s
   hosts: ["oracle://server-FQDN:1521/DB_SID"]
   username: user
   password: password
```

**Comment by sayden** [comment]
Yes, this is the best approach so we can ensure that the credentials are not visible on the events either. I have been doing local tests too and username and password can also be part of the `hosts` field as far as they are separated by `:` (instead of `/` as you can read here https://github.com/elastic/beats/pull/23101), if not it seems that the password is leaked because the host parser doesn't recognized the field properly
