### ISSUE TITLE
Support reading secrets in K8s agent manifest

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/beats#24143]
Beats on K8s were able to read sensitive data like credentials from secrets to prevent these credentials or any other sensitive data in plain text in the config files. We need to provide similar experience on agent. For example, users can create secrets on command line and then refer it in yaml files from k8s secrets store. 

`cloud_id=test-cloud-id`
`cloud_auth=testusername:test-cloud-id-password`
`kubectl create secret generic cloud-secret --from-literal=cloud-id=test-cloud-id --from-literal=cloud-auth=testusername:test-cloud-id-password`

      valueFrom:
            secretKeyRef:
              name: cloud-secret
              key: cloud-id

We need the agent manifest support reading from K8s secrets.

**Comment by ph** [comment]
@blakerouse I believe our original intention was to add support for secrets inside the provider in this case k8s? So a user could reference a value our tags `${...}` and the provider will resolve the values. Does it need special handling in the framework?

**Comment by blakerouse** [comment]
I think the original idea was to add a single `secret` context provider. This provider would have different backends, with multiple supported at the same time. I would think we could start with a single backend of K8s at first, because that has the biggest use-case at the moment.

With this backend it would allow the value of the secret to be exposed as a variable in the dynamic inputs composer.

Using the secret that @mukeshelastic created in the description of the issue, it could be reference in the configuration with simply: `${secret.kubernetes.cloud-secret.cloud-id}`.

Adding an extra provider backend would just scope secret variable in that named backend. Example below with 2 providers, below (not that we need to start with 2):

```
providers:
  secret:
    backends:
      - type: kubernetes
      - type: keystore
        path: '~/keystore.store`
```

Then either could be referenced with `${secret.kubernetes.cloud-secret.cloud-id}` and `${secret.keystore.cloud-id}`. Adding it all together with order of usage `${secret.kubernetes.cloud-secret.cloud-id|secret.keystore.cloud-id}`.

Now to enable this we need to add a little more to context providers. At the moment it is expected that the context provider push all keys to the composer, for secrets I would expect it to only provide values to keys that are referenced. So a little more needs to be added to the `ContextProvider` interface. Adding more to and possible in the `ContextProvider` is for the Elastic Agent to watch for changes in values of referenced keys so those changes could automatically trigger a re-generation of configuration.

**Comment by ph** [comment]
I've touched briefly with @ruflin on this and after talking to him, I am not sure we actually need a "Secret Provider" that supporting multiple backend and having to deal with resolution priority, but we could instead have dedicated providers. 

```yaml
providers:
  kubernetes_secrets: ~
  file_secrets: 
   path: '~/tmp/keystore.store'
```

Something like "kubernetes_secrets" or "file_secrets" and user could reference them directly like "${kubernetes_secrets.cloud-secret.cloud-id}". Also some of these provider could add subcommands to our CLI, this is a requirement for current libbeat keystore ("add", "list", remove).

I am not totally against the backend strategy, but I am not sure if this is a real use case to have multiple backend at the same time. @mukeshelastic can we get your inputs to align the technical implement?

**Comment by ph** [comment]
> So a little more needs to be added to the ContextProvider interface. Adding more to and possible in the ContextProvider is for the Elastic Agent to watch for changes in values of referenced keys so those changes could automatically trigger a re-generation of configuration.

@blakerouse is that a supported mechanism for k8s, ie does k8s sent a notification or we would have to an internal watchdog for the values?

**Comment by mukeshelastic** [comment]
> I think the original idea was to add a single `secret` context provider. This provider would have different backends, with multiple supported at the same time. I would think we could start with a single backend of K8s at first, because that has the biggest use-case at the moment.

I am in support for getting this working with single K8s backend and then expanding to additional backend when  required. So  just restating what @blakerouse mentioned as a way to read this secret in config files  `${secret.kubernetes.cloud-secret.cloud-id}` is a good first step.

**Comment by blakerouse** [comment]
> I've touched briefly with @ruflin on this and after talking to him, I am not sure we actually need a "Secret Provider" that supporting multiple backend and having to deal with resolution priority, but we could instead have dedicated providers.
> 
> ```yaml
> providers:
>   kubernetes_secrets: ~
>   file_secrets: 
>    path: '~/tmp/keystore.store'
> ```
> 
> Something like "kubernetes_secrets" or "file_secrets" and user could reference them directly like "${kubernetes_secrets.cloud-secret.cloud-id}". Also some of these provider could add subcommands to our CLI, this is a requirement for current libbeat keystore ("add", "list", remove).
> 
> I am not totally against the backend strategy, but I am not sure if this is a real use case to have multiple backend at the same time. @mukeshelastic can we get your inputs to align the technical implement?

We could also go with the what you described, I just liked the cleanness of `secrets.*`. Going with what you described would be easier to implement and would keep the flat namespace.

**Comment by blakerouse** [comment]
> > So a little more needs to be added to the ContextProvider interface. Adding more to and possible in the ContextProvider is for the Elastic Agent to watch for changes in values of referenced keys so those changes could automatically trigger a re-generation of configuration.
> 
> @blakerouse is that a supported mechanism for k8s, ie does k8s sent a notification or we would have to an internal watchdog for the values?

I believe there to be a way to watch for changes in secrets, but would need to fully confirm. I believe watching changes for any resource is generic.

**Comment by ruflin** [comment]
As ph mentioned, I prefer a separate provider for each secret "type". Like this we have just one implementation. I understand that from a usability perspective the `secret.*` is nice. Maybe we can get almost there by calling the providers `secret_kubernetes` etc? Every secret provider should have the `secret_*` prefix`. 

An other solution (but not sure if intuitive for users) is that inside a provider the prefix can be specified or even have a different default from the name itself. 

```
providers:
  kubernetes_secrets: ~
  prefix: kubernetes.secret
```

The nice part about the above is that all data coming from k8s has the same prefix, but now it is not unique anymore which is problematic.

I think my favorite solution at the moment is to just use `kubernetes_secret` to have a similar prefix to `kubernetes` provider.

**Comment by ph** [comment]
@ChrsMark would be nice to have your opinion on this.

**Comment by ChrsMark** [comment]
Both ways ("flat" one and "backend-based" one) look good to me. It was useful in Beats to implement different keystore backends but now I understand that the variable resolution happens based on the relationship between the dynamic-inputs and the provider.

+1 for the "flat" one since its looks more straightforward.

Also we should keep in mind that enabling dynamic inputs to retrieve a Kubernetes secret, through `kubernetes_secrets` means that `kubernetes_secrets` provider will make an API call to k8s api to retrieve the secret's value on resolution time. To achieve this we need to add `secrets` k8s resource to the elastic-agent's ClusterRole and we should be careful about this to ensure we don't expose Secrets k8s api (through agent) to malicious users.

**Comment by ChrsMark** [comment]
Posting a use case here as a complete example (feel free to comment/edit):

```
- name: redis
  type: redis/metrics
  use_output: default
  meta:
    package:
      name: redis
      version: 0.3.6
  data_stream:
    namespace: default
  streams:
    - data_stream:
        dataset: redis.info
        type: metrics
      metricsets:
        - info
      hosts:
        - '${kubernetes.pod.ip}:6379'
      username: '${kubernetes_secrets.default.redisPass.value}'
      idle_timeout: 20s
      maxconn: 10
      network: tcp
      period: 10s
      condition: ${kubernetes.pod.labels.app} == 'redis'
```

Users can refer a Kubernetes Secret with the following pattern:

`${kubernetes_secrets.<namespace>.<secret_name>.<value>}`
For instance, `${kubernetes_secrets.default.redisPass.value}` where `kubernetes_secrets.default.redisPass.value` specifies a key stored as a Kubernetes secret with the following:

Kubernetes Namespace: `default`
Secret Name: `redisPass`
Secret Data Key: `value`

**Comment by ph** [comment]
@chrsblck looking at `kubernetes_secrets.default.redisPass.value` is the `value` part necessary, is there something else that `value` that could be retrieved for the `redisPass` key?

**Comment by ChrsMark** [comment]
> @chrsblck looking at `kubernetes_secrets.default.redisPass.value` is the `value` part necessary, is there something else that `value` that could be retrieved for the `redisPass` key?

`.value` can be anything so we need to explicitly mention this "field". Here is an example:

```
apiVersion: v1
kind: Secret
metadata:
  name: redisPass
type: Opaque
data:
  value2: "abcd"
```

Another one:

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
```

**Comment by blakerouse** [comment]
This all looks good to me. I think we should go with `secrets_kubernetes` so all secrets providers is prefixed with `secrets_`. We could also make `secrets.kubernetes` work without different backends, by allowing `secrets.*` just to be converted to `secrets_*`. That is something that the composable controller could easily do. I think it just reads better than using a `_`.

@ChrsMark Do you think that cross namespace secret addressing is needed? Is that dangerous to enable?

**Comment by ChrsMark** [comment]
@blakerouse we have a convention about this in Beats:
```
Pods can only consume secrets that belong to the same Kubernetes namespace. For instance if Pod my-redis is running under staging namespace, it cannot access a secret under testing namespace for example kubernetes.testing.xxx.yyy
```
Or autodiscovered workloads can only refer to k8s secrets that belong to the same namespace.  So, cross namespace access should not be enabled I think here too.

**Comment by blakerouse** [comment]
@ChrsMark I think that would be the best way to do it. So we should remove the namespace name from the variable resolution.

Your example above would become `kubernetes_secrets.mysecret.USER_NAME` (removed `default.`)

**Comment by ChrsMark** [comment]
@blakerouse Implementation wise, do you have in mind how the provider will actually fetch the secrets from the API at running time? Will the provider fetch a secret, if this already exists, on startup and then it will be able to watch for new secrets? Or the secret will be actually fetched when needed, means when it will actually be needed by a configuration (this how it is implemented in Beats).

Rephrasing the question: will `kubernetes_secrets` provider fetch all the secrets on startup (and fetch every new one when it will be created) and then dynamic inputs can pull secrets from the provider? If I'm not mistaken providers pass data to dynamic inputs while the opposite cannot happen, dynamic input make the provider to fetch only the wanted secret, right?

**Comment by mukeshelastic** [comment]
From requirements perspective - we can read secrets at startup and so if it changed after that, then agent needs to be restarted to pick that change. Watching secrets so that agent can read them dynamically is nice but we can create separate issue for that and address it later.

**Comment by ChrsMark** [comment]
++ on dealing with `watch` feature later however my actual question is: Do we fetch all Secret objects from k8s api on startup and leverage only what is needed in the dynamic inputs or fetch only the specific secret(s) that is needed? If I have got the design of dynamicInputs+providers so far then we can only implement the first approach (fetch all secrets). @blakerouse can you confirm?

**Comment by blakerouse** [comment]
@ChrsMark I would expect the `kubernetes_secrets` to work somewhat differently than the current context providers. The current providers load all the data at start up, which is not what we want to occur for the `kubernetes_secrets`. I think work needs to be done to have the provide to only fetch the secrets that are referenced. Loading all the secrets even if not used, I think would be incorrect.

**Comment by exekias** [comment]
> Loading all the secrets even if not used, I think would be incorrect.

💯  on this, can we perhaps split this issue in two? We need to update the dynamic providers framework to support providers fetching on demand + implement the `kubernetes_secrets` provider.

**Comment by ph** [comment]
@exekias Concerning timeline, would that mean that we would require changes in the framework to support fetching on demand or the first version of the k8s store will fetch all secrets? I am trying to understand the how the implementation will look like.

**Comment by exekias** [comment]
I think we require the changes, loading all secrets doesn't sound like a good idea

**Comment by ph** [comment]
@ChrsMark Please reach out to us and we can help you figuring out  the changes for the framework.

**Comment by ChrsMark** [comment]
I had some offline chats with @exekias and @blakerouse about this feature, based on the convention of namespace restricted access to the secrets. 

The thing is that we can't easily move away from referring the namespace explicitly as mentioned at https://github.com/elastic/beats/issues/24143#issuecomment-786194840, because if we want to do this, we need to couple `kubernetes_secrets` provider with `kubernetes` provider so as to know the namespace of the discovered Pod. This is not so easy to happen with the current state of the framework cause each provider is independent. Also such an option will make `kubernetes_secrets` provider available only for configurations created through `kubernetes` provider and users wouldn't be able to refer to secretA which actually contains a generic value like ES host or `cloud.id`.

We want `kuberentes_secrets` provider to be generic so we need to refer to secrets with the namespace included like `${kubernetes_secrets.default.secret_name.secret_value}`.

It's not a security  issue with static "autodiscovered" workloads since the administrator  of Agent will be responsible to define such secrets before running Agent. 

When it comes to hints based autodiscover we will prevent users to refer to secrets of other namespaces than their pod's namespace inside `kubernetes` provider which will be responsible to feed the templates by handling the hint's annotations as described at https://github.com/elastic/beats/issues/23876#issuecomment-795491731. This means that when we find a reference to `kubernetes_secrets` provider inside the hints we will apply all the necessary checks so as to validate if the config for the discovered pod can access the specific secret based on their namespaces.
