### ISSUE TITLE
[filebeat] squid module cannot parse CONNECT request because "extract_page failed"

### ISSUE THREAD

**Issue by phuture** [elastic/beats#24260]
- CentOS 8
- filebeat 7.11.1

Squid module for filebeat reporting errors if line containing CONNECT method. With CONNECT there is no URL, just address and port number, like:
<code>
XXXX.XX _time_ TCP_TUNNEL/200 _size_ CONNECT server.ip.com:443 - HIER_DIRECT/A.B.C.D -
</code>

Filebeat log:
<code>
ERROR        [processor.javascript]        console/console.go:54        extract_page failed for 'server.ip.com:443'
</code>

When CONNECT method is used, parser should not use function extract_page because it failed for obvious reason.

However, log is pushed to index, so this is not fatal error.

**Comment by shk3bq4d** [comment]
I can still see the issue on 
CentOS 7.9
filebeat 7.12.1
filebeat version 7.12.1 (amd64), libbeat 7.12.1 [651a2ad1225f3d4420a22eba847de385b71f711d built 2021-04-20 20:58:32 +0000 UTC]

**Comment by piramix** [comment]
It is because regex "pageFromPathRegExp" wants to match anything behind / so for example server.ip.com:443 will be extracted by extract_path to value "/" and extract_path will return undefined in that case.

To fix it we need to return an empty string when path is "/" - just add if (value == "/") return "";

```
function extract_page(value) {
    value = extract_path(value);
    if (!value) return undefined;
    if (value == "/") return "";
    var m = value.match(pageFromPathRegExp);
    if (m) return m[pageName];
}
```

**Comment by piramix** [comment]
It is because regex "pageFromPathRegExp" wants to match anything behind / so for example http://ipecho.net/ will be extracted by extract_path to value "/" and extract_path will return undefined in that case.

To fix it we need to return an empty string when path is "/" - just add if (value == "/") return "";
and in case ipecho.net:443 we need to fill out uriPath (as we are building "fake" uri null://ipecho.net:443/ to handle the case of TCP_TUNNEL)
if (m && m[uriScheme] == "null" && m[uriPort] && m[uriPath] === undefined)
m[uriPath]="/";

in /usr/share/filebeat/module/squid/log/config/liblogparser.js
```
function extract_page(value) {
    value = extract_path(value);
    if (!value) return undefined;
    if (value == "/") return "";
    var m = value.match(pageFromPathRegExp);
    if (m) return m[pageName];
}

function extract_path(value) {
    var m = split_url(value);
    if (m && m[uriScheme] == "null" && m[uriPort] && m[uriPath] === undefined)
    m[uriPath]="/";

    return m? m[uriPath] || m[uriPathAlt] : undefined;
}
```

**Comment by drewboswell** [comment]
We are having the same problem, same behaviour on 7.15.1

**Comment by drewboswell** [comment]
same problemw ith 7.16.1

**Comment by adriansr** [comment]
The actual nuisance here is the unnecessary error message in the logs. I'll change it to be a debug message so it's not logged by default.

Other than that, I think there's no bug in the parser. I don't like returning default values (path="/", page=???,  extension=???) because it can cause problems to surface elsewhere, or have fields populated with unnecessary values. It's better to leave fields unpopulated if the required value doesn't make sense.

I will update Filebeat modules and integration packages with this and other pending fixes soon. Meanwhile, if you're annoyed the error in your logs I suggest to manually update `function url_wrapper` in `module/squid/log/config/liblogparser.js` file with:

```diff
-                  console.error(fn.name + " failed for '" + value + "'");
+                  console.debug(fn.name + " failed for '" + value + "'");
```
