### ISSUE TITLE
7.11.0 Standalone agent is not sending data to 7.12.0 BC-3 Kibana under data streams tab. 

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#24364]
**Kibana version:** 7.12.0 BC-3 Kibana Cloud environment

**Host OS and Browser version:** Windows 10, All

**Build Details:**
```
Artifact link: https://staging.elastic.co/7.11.0-657c0367/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
Build: 39134
Commit: 08417cbd6c15e4c866651a7dcdfeded58845206d
```

**Preconditions:**
1. 7.12.0 BC-3 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana Cloud environment.
2. Navigate to Agents tab and install 7.11 standalone agent with default policy having system integration.
3. Navigate to Data Streams tab and observe no data under Data Streams tab.

**Expected Result:**
7.11.0 Standalone agent data should be displayed under Data Streams tab on 7.12 BC-3 Kibana cloud environment.

**Screenshot:**
![standalone](https://user-images.githubusercontent.com/77374876/109923621-05b47680-7ce5-11eb-9c2e-dea0b7415f54.png)

**Logs:**
`{"log.level":"info","@timestamp":"2021-03-04T01:56:28.135-0500","log.origin":{"file.name":"application/periodic.go","file.line":76},"message":"Configuration changes detected","ecs.version":"1.6.0"}`
[elastic-agent-json.log](https://github.com/elastic/kibana/files/6081417/elastic-agent-json.log)

**Note:**
This issue is also occurring for linux (.tar) and mac (.darwin) 7.11.0 standalone agents installed on 7.12.0 BC-3 Kibana.

**Comment by EricDavisX** [comment]
I wonder about this case, a prior version Agent calling in to a newly upgraded or set up stack.  

@ph @blakerouse thoughts?  Is this pretty urgent to get supported or confirmed?  Let us know if you need more, @amolnater-qasource could you post any Agent side logs that do exist from the host please?

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Please find the agent side logs attached in the defect summary under Logs section:
> **Logs:**
{"log.level":"info","@timestamp":"2021-03-04T01:56:28.135-0500","log.origin":{"file.name":"application/periodic.go","file.line":76},"message":"Configuration changes detected","ecs.version":"1.6.0"}
elastic-agent-json.log

Further as per your request please find elastic-agent.yml below:
[elastic-agent-yml.zip](https://github.com/elastic/beats/files/6088327/elastic-agent-yml.zip)

Please let us know if anything else is required.
Thanks 
QAS

**Comment by EricDavisX** [comment]
Thanks @amolnater-qasource can you give the exact version by calling 'elastic-agent version' command please.

I've assigned @ph for now to make sure he sees it and can comment on need.  @blakerouse or @michalpristas not sure if you'll see this faster than PH and have any thoughts?  We always support the immediately prior minor version Agent right?  Beyond that, I suppose it is an upgrade scenario of sorts though the exact test steps above do not mirror an actual upgrade process (not sure if that matters)

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Please find below screenshot for elastic-agent version:
![agent version](https://user-images.githubusercontent.com/77374876/110124734-77291d80-7de8-11eb-986b-bbf49bc6076a.PNG)

Further we have used 7.11.0 BC-8 artifact link and link for windows agent is as follows:  
https://staging.elastic.co/7.11.0-657c0367/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip

Thanks
QAS

**Comment by michalpristas** [comment]
if this stack is up, can we allow debug logs of agent to get more info and also include metricbeat/filebeat logs as well?

**Comment by michalpristas** [comment]
i see the root cause of this
in the logs:
```
"Failed to read configuration, error: could not emit configuration: could not create the AST from the configuration: missing field accessing 'inputs'
```

which is a known issue

hash of an agent is `84c4d4c` which tracks to Feb 4th
@blakerouse fixed the issue in `05adac7` Feb 11th. 

So i guess this is expected and we can close this

**Comment by ph** [comment]
@amolnater-qasource I would like to understand why these tests are done with 7.11 BC8 and not 7.11.1 that is released?

**Comment by EricDavisX** [comment]
Is the BC8 hash going to map to the 7.11.0 shipped hash since it was not re-built?  The question is a good one, but I think the fix (regardless) is probably 2-fold:
 - review tests we assign and processes on those to make sure that we usually use the latest patch release available for tests unless otherwise noted.  I'm not sure (can't think of any just yet) where we'd want to use the older 'initial' .0 release for a test, unless we were gathering data on a bug.

 - make sure that when we're checking in to path build that the PR author stays in touch with testing team and can help verify intention / availability of the fix.

I traced the commit above to this pr https://github.com/elastic/beats/pull/24005 which relates to 2 issues, including this one: https://github.com/elastic/beats/issues/23829
 - the last comment in 23829 is from me where we aren't sure if the fix was picked up in the build or not and the conversation got dropped.  I'll take the blame there.  I'd like to re-iterate that for patch release check-ins we prefer extra communication, especially when timing of check-ins is tight since we don't have automated traceability of checkins.

So the above question is the right one about tests and 'why'.  But we have some process to prevent it.  @amolnater-qasource if you can answer a quick review over the test case that relates to this and help verify if it incorrectly cites a version to test?  I'm also not very sure about our general 'interoperability' tests between versions either... we may not have much and it is an area we can expand with some off-line discussion to confirm depth we want to go.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX and @ph 
We always pick last patch version for such scenarios. This time we randomly used a lower version of BC that is 7.11.0 BC-8.
However as per feedback we have revalidated this issue with **7.11.1 release agent** and found this issue **reproducible**.

**Test Cases link:** 
[Validate user is able to upgrade standalone agent on windows x64 zip](https://elastic.testrail.io/index.php?/cases/view/35081)
[Validate data under Datastreams and Kibana Discover tab on upgrading standalone agent on windows x64 zip](https://elastic.testrail.io/index.php?/cases/view/35084)
[Validate user is able to upgrade standalone agent on mac](https://elastic.testrail.io/index.php?/cases/view/35082)
[Validate data under Datastreams and Kibana Discover tab on upgrading standalone agent on mac tar](https://elastic.testrail.io/index.php?/cases/view/35085)
[Validate user is able to upgrade standalone agent on linux](https://elastic.testrail.io/index.php?/cases/view/35083)
[Validate data under Datastreams and Kibana Discover tab on upgrading standalone agent on linux tar](https://elastic.testrail.io/index.php?/cases/view/35087)

**Artifact link used[7.11.1 release agent]:** https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.11.1-windows-x86_64.zip

**Agent Logs[7.11.1 release agent]:** 
[elastic-agent-json.log](https://github.com/elastic/beats/files/6105990/elastic-agent-json.log)

**Policy[7.11.1 release agent]:** 
[elastic-agent.zip](https://github.com/elastic/beats/files/6105992/elastic-agent.zip)

**Agent version[7.11.1 release agent]:** 
![version](https://user-images.githubusercontent.com/77374876/110421627-e55d3100-80c3-11eb-9b0f-8c58bac1900b.JPG)

Please let us know if anything else is required.
Thanks
QAS

**Comment by michalpristas** [comment]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1522652/110436692-d1f69980-80b4-11eb-83f8-bfe5b37d9d7e.png">
fix still was not present in tested version, included a day later (in the picture first commit by blake is a fix and last one is what was used)

**Comment by EricDavisX** [comment]
I asked Michal to help confirm the above statement... it is showing that the fix did NOT make it into the actual 7.11.1 build, so the problem is expected.  We can re-test with the 7.11.2 and expect it to work and then close this issue out.  @dikshachauhan-qasource and @amolnater-qasource thank you so much, sorry for the lack of clarity on the fix inclusion.

**Comment by michalpristas** [comment]
it should be present in 7.11 snapshot as well in case 7.12.2 is too distant

**Comment by EricDavisX** [comment]
@amolnater-qasource @dikshachauhan-qasource this is testable now with the 7.11.2 artifact, can you re-run the test and confirm please?

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue with 7.11.2 standalone agent installed on 7.12.0 BC-4 Kibana cloud environment and found it **fixed**.

**Observations:**
- Observed System data under Data Streams tab.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/110751415-d7e1ab80-8269-11eb-8039-fda3fc0db085.JPG)

**Build details:**
Build: 39242
Commit: 99ac38d70e426f589bb61a034c96e602d759cfab
Artifact link used: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.11.2-windows-x86_64.zip

Hence closing this out.

Thanks
QAS
