### ISSUE TITLE
[elastic-agent]: ensure that the enroll command also logs to file if configured

### ISSUE THREAD

**Issue by simitt** [elastic/beats#24897]
The enroll command can be automatically triggered when starting the docker container. In which case the `LOGS_PATH` should be respected. 

Code path that needs to be changed: 
https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/cmd/enroll.go#L197-L200

**Comment by blakerouse** [comment]
This is because of this change here: https://github.com/elastic/beats/pull/24466

I think the change is correct, I would not expect the enroll command by default to write to a log file. We could change the `container` subcommand when it spawns the `enroll` command to send the stdout and stderr to a file when `LOGS_PATH` is set.

Actually with `LOGS_PATH` set I would expect all output from the `container` command to go to a log file. So we could set that up so it writes both to stdout and to a logfile. The logfile would need to be seperate from the main `elastic-agent.log` as they should not collide. Maybe `elastic-agent-startup.log`?

**Comment by simitt** [comment]
That sounds very reasonable to me.
