### ISSUE TITLE
metricbeat does not have "write-environment" and "start-environment" make commands

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#24937]
The first target writes some environment files that contains information to run the systems tests, and the second one, start an environment to run systems tests agains. However, depending on the beat you are testing, this could potentially launch a huge Docker compose file.

**Comment by jsoriano** [comment]
@mdelapenya what would these targets do in the case of metricbeat?

In the cases of filebeat most system tests depend on an Elasticsearch ingest node to run the ingest pipelines, also in libbeat the output tests depend on Elasticsearch and other services, so a common target can be useful in these Beats to start the stack, and some services configured for it.
But in the case of Metricbeat each system (or integration) test suite depends only on the service whose module is being tested, having a single target has no benefit, because there is no shared environment between different suites, and starting all services at the same time is counterproductive and not needed in any case.
Tests frameworks discover the addresses where the services are listening, so in principle it is not needed to write the environment configuration. `elastic-package test` works in a similar fashion, it transparently starts what is needed for the tests of each package. The stack used to test ingest pipelines is managed by `elastic-package stack`.

Perhaps something that can be interesting for Metricbeat could be to have a target to start and stop the environment for a module, with something like `MODULE=apache mage startEnvironment`. But not sure if needed.

In any case these new targets should be implemented as `mage` targets and not in Makefiles, and I don't think they would be generalizable between different beats.

**Comment by mdelapenya** [comment]
I think this can be closed for now
