### ISSUE TITLE
New protocol support: ICMP

### ISSUE THREAD

**Issue by darxriggs** [elastic/beats#250]
You know, it's not only about `ping`. :-)

**Goal**: Detect network issues. (by analyzing ICMP packets sent between servers)

**Comment by darxriggs** [comment]
I already started an implementation. I will add questions here as they come up:

1. Fields "bytes_in" and "bytes_out"
Having look at other protocols I am a bit confused about the directions. This is always from the view of the server? (e.g. for HTTP "bytes_in" is used for the request and "bytes_out" for the response)
So for ICMP i am not sure as for example an ICMP Echo Request could be send by the server the PacketBeat agent is running on or from another server to the server the PacketBeat agent is running on.

2. Field "transport"
This field was introduced with the DNS protocol. Shall it be left out for ICMP or filled with "ip4" / "ip6"? ICMP is using IP (network layer) not TCP/UDP (transport layer).

3. Field "path"
Should this be the IP of the requested server?

**Comment by urso** [comment]
1. Application layer protocols use "bytes_out" for response and "bytes_in" for request. But Application Layer protocols often work in server/client mode. ICMP we can consider "bytes_in"/"bytes_out" for local machines or local vs. outside network. I would propose to keep it simple and keep semantics used Application Layer protocol implementations.

2. I would not include "transport" here. But IP version should be available somewhere.

3. You have a use case for "path". For http it's the file requested. The mysql module stores the table requested.

4. consider "request"/"response" being an object. If one is missing, it's missing in the document indexed in elasticsearch (event with missing object is directly searchable in ES/Kibana). Prefer to publish strings over codes (better publish both). This simplifies search operations. Publishing strings should try to unify ICMPv4 and ICMPv6 differences. For example ICMPv4 "Echo request" uses Type=8 and Code=0, but IMCPv6 "Echo Request" is Type=128.

5. agreed

6. in future I'd like kind of layered plugins too in order to collect some more advanced per layer stats. IP4/6 fragmentation is still missing too.

7. Kinda goes hand in hand with 6. Let's have "icmp.enabled: true" by default in config file + comment and documentation.

**Comment by andrewkroh** [comment]
This has been implemented and released in version 1.1.0.
