### ISSUE TITLE
Elastic Agent should have official support for `HTTP_PROXY`

### ISSUE THREAD

**Issue by ph** [elastic/beats#25021]
All the beats support and respect `HTTP_PROXY` configuration either as an environment variable or as a direct configuration in the Elasticsearch output. We'll add official support to Elastic Agent so that it also uses a proxy for these connections:
1. Elastic Agent -> Fleet Server
2. Elastic Agent -> artifact repo for beats and agent binaries
3. Inputs -> services being monitored

Users will set the proxy using the HTTP_PROXY environment variable at the host level. This is a standard place to set the behavior across OSes and vendors. Users can still disable or override this settings where the configuration allows.

The priority will follow our existing settings for Elasticsearch:
1. If `proxy_disable` is configured we ignore proxy settings in the configuration file and environment variables. All connection attempts are unproxied
2. If proxy support is not disabled and `proxy_url` is configured we always use that URL. This can be defined in an input or an output.
3. If proxy support is not disabled and no proxy url is set we rely on the environment variables `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` (see http.ProxyFromEnvironment).

We also need to document how users can set the proxy connection https://github.com/elastic/observability-docs/issues/593

**Out of scope:**
* Add a new flag to the enroll subcommand
* Add a setting in Fleet to configure the proxy

**Comment by ph** [comment]
@urso @ruflin @blake-kephart @mostlyjason  wdyt?

**Comment by urso** [comment]
+1

We have quite a few HTTP clients in our code base. I would like them to behave more similar, and provide a common set of features/settings.

In order to ease setup and testing, we should provide some support (setup defaults, apply common set of settings, ...) via the `libbeat/common/transport/http` package (or similar). The elasticsearch output has quite a few unit tests validating proxy support. Maybe we can move most of the configuration/client setup + testing to `libbeat` instead of writing tests for every subsystem that uses HTTP and should support proxying.

The ES output just relies on HTTP 1. We would still require tests for HTTP 2, to ensure we can correctly support gRPC using our own HTTP server/client setup.

**Comment by blakerouse** [comment]
+1 from me. 

We need to be careful when it comes to the Elastic Agent talking to its local Fleet Server. We need to ensure that in that case the HTTP_PROXY is ignored.

**Comment by ph** [comment]
> The ES output just relies on HTTP 1. We would still require tests for HTTP 2, to ensure we can correctly support gRPC using our own HTTP server/client setup.

Good Point, its that really different on HTTP2?

**Comment by urso** [comment]
> its that really different on HTTP2?

I don't think so. HTTP2 might still hit a few different code paths in the stdlib http package and I would prefer to have tests that our setup works correctly.

**Comment by urso** [comment]
> We need to be careful when it comes to the Elastic Agent talking to its local Fleet Server.

Good point. We also use gRPC between Beats and Agent. Are there other intneral channels we must ignore the proxy settings for?

Besides `HTTP_PROXY` environment variable we need to support `HTTPS_PROXY` and `NO_PROXY`.

The proxy rules for the [elasticsearch output](https://github.com/elastic/beats/blob/master/libbeat/esleg/eslegclient/connection.go#L126) are:
- If `proxy_disable` is configured we ignore proxy settings in the configuration file and environment variables. All connection attempts are unproxied
- If proxy support is not disabled `proxy_url` is configured we always use that URL
- If proxy support is not disabled and no proxy url is set we rely on the environment variables HTTP_PROXY, HTTPS_PROXY, and NO_PROXY (see [http.ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment)).

The output also wraps the http.Transport with APM, so we can get Traces. We should use the same rules + apm support for all clients.

**Comment by mostlyjason** [comment]
This sounds like a nice addition to the `proxy_url` setting we discussed here https://github.com/elastic/kibana/issues/95306

**Comment by urso** [comment]
Not the complete solution, but initial support for common proxy support in everything HTTP can be found in: #25219

**Comment by ferullo** [comment]
Many users need a proxy when they are at home but when they are in the office cannot use that proxy. Is it correct that Agent/Beats/Endpoint should all try to use the proxy when they can but also try direct connections if using the proxy doesn't work?

**Comment by urso** [comment]
> Many users need a proxy when they are at home but when they are in the office cannot use that proxy.

Beats/Agent are not aware of environment changes. Beats will not fallback if the proxy is not available (proxy support is handled by the net/http package).

Regarding the laptop use-case I would assume it is more about VPN?

**Comment by ferullo** [comment]
OK. For consistency, Endpoint can support only using a proxy when a a proxy is configured. Since the Endgame product (shared code) has code to swap between proxy and no proxy it will be easy for us to do that if Agent/Beats ever add support for it. Just let us know.

We found some Endgame customers configured their networking such that a proxy, not a VPN, is needed when the user is outside the office. I'm not sure how common that is.

**Comment by bradenlpreston** [comment]
It a good call to keep them consistent. I would guess that implementing the fallback will come up as a near term enhancement request.

**Comment by mostlyjason** [comment]
@urso what is needed to close this one out?
