### ISSUE TITLE
Docker image for Heartbeat 7.12.0 too large

### ISSUE THREAD

**Issue by DennisRasey** [elastic/beats#25059]
The docker image for Heartbeat 7.12.0 is about 1.2g after pulling.
The image for 7.11.2 is 433mb after pulling
 
```
docker.elastic.co/beats/heartbeat                                         7.12.0               277422b6c8e6   3 weeks ago     1.21GB
docker.elastic.co/beats/heartbeat                                         7.11.2               6b134b6296c7   5 weeks ago     433MB

```
The 7.12.0 image appears to have some build left-over in /usr/share/heartbeat, the 7.11.2 image does not

```
-rw-r----- 1 root      root            41 Mar 18 06:26 .build_hash.txt
drwxrwx--- 1 root      root          4096 Mar 18 06:26 .cache
drwxrwx--- 1 root      root          4096 Mar 18 06:26 .config
drwxrwx--- 1 heartbeat root          4096 Mar 18 06:26 .node
drwxrwx--- 1 root      root          4096 Mar 18 06:27 .npm
```

main culprits appear to be:
```
389M	.cache
173M	.node
31M     .npm

```

**Comment by andrewvc** [comment]
I understand why it looks like these are unneeded files, however these are all requirements for synthetics. Synthetics uses node JS hence the `.node` and `npm` directories.  The `.cache` directory contains the chromium browser. If you haven't had a chance to check out synthetics the [docs](https://www.elastic.co/guide/en/observability/master/synthetic-monitoring.html) are worth the read.

That said we'd love to hear about what problems the increase in size is causing. We decided we were okay with increasing the size of the image because heartbeat usually runs on dedicated machines where an extra 700 megs or so on disk is not a big deal. From a download perspective this compresses pretty well with our 7.12.0 image only weighing in at around [479 MB compressed](https://www.docker.elastic.co/r/beats/heartbeat). Is this a problem for your environment?

**Comment by DennisRasey** [comment]
Thank you for the explanation!

There really wasn't an issue with the size increase. 
I was simply "surprised" by it and thought it might be a mistake once I saw the "extra" directories within the image.
