### ISSUE TITLE
Filebeat should be able to re-ship specified files

### ISSUE THREAD

**Issue by notrickyd** [elastic/beats#25170]
**A CLI command interface to filebeat to re-ship certain log file**

**I want to re-ship a certain log file (or files by mask)**
1. I open CLI interface on the server where filebeat is runnig
2. I type 
`$ filebeat ship /path/to/dir/filename*.log`
or
`$ filebeat reset stats /path/to/dir/filename*.log`
and press ENTER.
3. Filebeat takes this into count and on closest harvesting point it re-ships files that match the mask from the top.

Detailed description of the case follows here: 
[https://discuss.elastic.co/t/force-filebeat-resend-one-particular-file/267115](https://discuss.elastic.co/t/force-filebeat-resend-one-particular-file/267115)

**Comment by faec** [comment]
Closing; right now nothing like this is in our roadmap.

**Comment by adrianfusco** [comment]
Hello.

Is it not considered yet in a future roadmap?

Thanks.

**Comment by matthiasledergerber** [comment]
Hi

I would also like to add that this feature would be very useful. Especially with the integration of custom log files there should be an easy option where users could resend data without having to edit/delete filebeat registry files to force a resend of files.

This could be a toggle for an individual integration (Custom Log File).

I've seen this request brought to me by several customers using this product. It would help adoption because many systems still write logs directly to a file and building a parser sometimes requires to resend data to be sure that everything works fine

Kind Regards.

**Comment by allan-silverstein** [comment]
I'd like this feature as well.  Thank you.
