### ISSUE TITLE
Incorrect IAM actions in docs

### ISSUE THREAD

**Issue by benberg86** [elastic/beats#25591]
The IAM permissions  for  lambda are documented here and list ELB permissions 
 and not lambda  permissions
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-lambda.html

**Comment by kaiyan-sheng** [comment]
Hello @benberg86, thanks for creating the issue here. The permission listed in the documentation is for collecting monitoring metrics from CloudWatch for Lambda. We don't need special lambda permission when making API calls to CloudWatch. Did you run into permission error when trying to run Metricbeat?

**Comment by endorama** [comment]
Hello @benberg86 did you have the chance to review what @kaiyan-sheng mentioned? We're happy to help if you encountered some issue with the AWS Lambda metricset.
