### ISSUE TITLE
[Docs] Add in CockroachDB example doc

### ISSUE THREAD

**Issue by stefnestor** [elastic/beats#25622]
Howdy! 

It looks like you need to add one of your [test data docs](https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/cockroachdb/status/_meta/testdata/cockroachdb-status.v19.1.1.plain-expected.json) into your [CockroachDB status metricset # Fields](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-cockroachdb-status.html) code slot.

Cheers!

---

<img width="666" alt="image" src="https://user-images.githubusercontent.com/26751266/117554623-21563900-b016-11eb-83fd-03470dfb82ec.png">

**Comment by dedemorton** [comment]
We need to kick this back to the development team because the module is missing required info that should have been added before it was merged:

- fields.yml is incomplete, so the [field reference topic](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-cockroachdb.html) contains no useful info.
- data.json is empty

**Comment by jlind23** [comment]
@elastic/obs-service-integrations Shouldn't it belong to you?

**Comment by ishleenk17** [comment]
Yes @jlind23, this would fall under Service Integrations.
