### ISSUE TITLE
[Agent] Using Fleet Server with 'install' command with RPM/DEB is not supported, can we fix the install cmd to check if RPM/DEB is installed and skip to the 'enroll' step?

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#25967]
This is a request we could have put in a while back, it occurs to me now that it may be doable to allow DEB/RPM usage to use 'install' as well, if we fix the install command to be cognizant of if the install locations exist on disk already where the DEB/RPM package manager puts them.

This has come up a number of times and requires additional testing and additional docs and special cases, it might be nice to clean this up and make for a smoother consistent experience (and allow for less maintenance on the Docs / testing side!)

The error gotten at 'install' time (this is not the documented command to use with RPM/DEB at this time, mind you) is below, it doesn't give enough context for even experienced Admins / Elastic users to know why it failed, so we could improve the logging additionally / separately, too:

[root@ip-172-31-41-197 elastic-agent]# rpm -vi /tmp/elastic-agent-7.13.0-x86_64.rpm
Preparing packages...
elastic-agent-7.13.0-1.x86_64
[root@ip-172-31-41-197 elastic-agent]# sudo elastic-agent install -f --url=https://f9d0e1efab154f2cb28ec074d0a3bd1a.fleet.us-east-1.aws.found.io:443 --enrollment-token=M1pwUEpuUUJfRWJ3MENBX0FwNFY6OEp3STBzX2RRcTZRUVdvT19mX3c3dw==
The Elastic Agent is currently in BETA and should not be used in production
Error: failed to discover the source directory for installation: missing elastic-agent

**Comment by EricDavisX** [comment]
@ph @mostlyjason I don't know if we want to target 7.14 with it... but if it is deemed likely small / easy by the dev team may be a quick win.

**Comment by mostlyjason** [comment]
@ph @urso this seems like a good idea, it would simplify the install instructions and rpm/deb would not be an exception case requiring the user to open up the docs page for separate instructions. i assume deb/rpm still adds a service, so its still "installed".

however, I'm hoping we can steer more people to use tar.gz so they can upgrade their agents. I wonder if this fix will make rpm/deb less common https://github.com/elastic/kibana/issues/80841?

**Comment by mukeshelastic** [comment]
@nimarezainia I was trying to understand the problems we are trying to solve here for users by following the workflow we recommend to users who prefer the RPM/DEB agent package as opposed the the default option we recommend in add-agent UI or in our documentation [here](https://www.elastic.co/guide/en/fleet/7.15/elastic-agent-installation.html)

In the documentation, we have two sections - download and the install agent package from respective package managers, followed by enroll command and starting agent process. So I am curious where do we expect users running into the problem described in this issue.. 

If the reasons users are trying the install command with RPM/DEB packages is because they are not reading the docs, I think the better UX would be include the commands from the docs in the add-agent flyout first.

**Comment by nimarezainia** [comment]
@mukeshelastic it's the latter. Someone not reading our docs. All is being said here to have a friendlier model so that even if someone does make a mistake (not read the docs) and issues an "install", we check and do an "enroll" instead.

It's just that we have made it hard for our customers to use the agent. the UX for this should have been "elastic_agent install" and that is the user's intent.  We should be taking care of platform anomalies under the covers. 

I think this is the right approach. I would/may go as far as saying perhaps the enroll command should be deprecated, but I believe there are otehr use cases for that.

**Comment by mukeshelastic** [comment]
I believe the install command installs agent as a service and uses systemd (and something equivalent on windows) to automate agent and beats subprocesses lifecycle management. While Enroll enrolls agent in fleet-server. So they are doing two separate things.. The install command also accepts the fleet-server params and combines enroll workflow for single command easy UX. In cases where the installation and setup of elastic agent is taken care of, be it via  package manager or OS images with preinstalled elastic agent or when you don't want to enroll it in fleet right away or want to use only standalone agent, you'd just use install command and not enroll. 

I think these commands are separate because they represent separate workflows. 

The bad UX here is that after you install the rpm/deb package and run the elastic agent help, you'd see the install command with fleet server in the help and if you run that then it fails, which looks like a bug that we'd should fix and enroll it in fleet server just like how we do it if it was tar package. However, users still need to explicitly run the systemd or equivalent to start the agent process. Today if they don't read the doc, they wouldn't know that. In addition to enrolling in the fleet-server, if we are also able to automate the agent and beats processes lifecycle management then we have a full parity with tarball binary. 

If we are fixing the install process with RPM/DEB then I'd suggest avoiding the piecemeal approach but rather holistic one that includes 

- fix the install command to also enroll as mentioned in this issue
- taking a look at the fleet-server setup and see if we need to fix anything there when agent is set up using rpm/deb packages
- change the UX on add agent flyout to reflect the install and start service instructions than sending a link to docs
- If possible, automate the agent and beats lifecycle management using the available process manager on the host, doing so will also enable the fleet based upgrade scenarios I suppose.
- If above is not possible then update the elastic agent binary help that appears in the terminal to indicate that you'd need to start agent process using systemd/equivalent process manager 
- Validate the UX by going through the installation ourselves when adding an agent and setting up fleet server using these two package managers. 

One thing I'd be curious to understand is, the impact of not enabling good RPM/DEB end-end UX on agent adoption. Is there sufficient qualitative data available in the agent feedback to prioritize install and upgrade lifecycle improvements for these package managers?

**Comment by michel-laterman** [comment]
Just as a note, the `install` command calls `enroll` after the installation process finishes.

I agree that we likely need better instructions provided by fleet when the agent is installed through rpm/deb.

This issue is to have the `elastic-agent install` command when the agent is installed through rpm/deb to skip the `install` steps and run the enroll? How should the `--force` flag interact with this?
