### ISSUE TITLE
PostgreSQL module should enable message size truncation and log-level filtering.

### ISSUE THREAD

**Issue by cameronkerrnz** [elastic/beats#25978]
**Describe the enhancement:**

Allow the user of a filebeat postgresql module to specify that logging messages below a certain priorities should not be forwarded, and that (multiline) log messages that would larger than a confurable limit should be truncated.

**Describe a specific use case for the enhancement or feature:**

PostgreSQL is configured to enable logging of slow queries with the following configuration:

```
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
log_destination = 'stderr'
logging_collector = 'on'
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = '1d'
log_line_prefix = '%m [%p] %q%u@%d '
log_timezone = 'Pacific/Auckland'
client_min_messages = 'notice'
log_min_messages = 'warning'
log_min_error_statement = 'error'
log_min_duration_statement = '100'
log_statement = 'ddl'
log_replication_commands = 'on'
log_connections = 'on'
log_hostname = 'on'
log_disconnections = 'on'
log_rotation_size = '10MB'
```

The problem is that the generated message size (after multiline processing) can be grossly excessive; Kafka has a maximum message of 5MB (which I think is default but can apparently be configured), and occassionally some SQL runs with seems to produce a message that is larger (from ones I've seen, it may have embedded JSON or HTML.... perhaps some CLOB related stuff; haven't looked too closely; and the all-too-common 'id in [big long list]' sort of construct that makes our DBAs wince).

Given that SQL is often generated, it can often be much longer than is needed; can we have some configurable truncation option within filebeat.

Note that when PostgreSQL is configured to use log_min_duration_statement, you will end up with a LOG level message, and if there were any parameters in use, these parameters will be logged separately in a DETAIL level message; there appears to be no way to not have PostgreSQL log the DETAIL level messages; but given that a generated SQL statement might not use any parameters, the LOG level entry could be equally perverse.

**Comment by jsoriano** [comment]
Hey @cameronkerrnz,

I am not sure of what could be a good approach to implement something like this in the PostgreSQL module, but filebeat already has some features that could help you.

[`exclude_lines`](https://www.elastic.co/guide/en/beats/filebeat/7.13/filebeat-input-log.html#filebeat-input-log-exclude-lines) can be use to exclude log lines, you can use this feature to filter out lines that you don't want.

[`processors`](https://www.elastic.co/guide/en/beats/filebeat/7.13/filtering-and-enhancing-data.html) can be used to adapt (or drop) events before being sent to Elasticsearch. There is for example a [`truncate_fields` processor](https://www.elastic.co/guide/en/beats/filebeat/7.13/truncate-fields.html) that can be used to truncate the message.

I am going to close this issue because I think that Filebeat already has the mechanisms to do what you are trying to do. Let me know if something else would be missing.
