### ISSUE TITLE
filebeat can’t send data to kafka cluster when one kafka can’t connect because of network

### ISSUE THREAD

**Issue by WangXiangUSTC** [elastic/beats#2626]
Filebeat version: 5.0.0-alpha4
Operating System: debian 8
I use filebeat get log from computer A, and then send to a kafka cluster group by two kafka run at two computers named B and C.
Today, I test the high avaliability of this system. below are what I do:

setting the firewall to cut off the network between A and B, and I hope the filebeat can send log to C, but not.these are the log of filebeat:

```
2016-07-22T15:43:34+08:00 WARN kafka message: client/metadata got error from broker while fetching metadata:%!(EXTRA *net.OpError=read tcp A's ip:37157-> B's ip:9093: i/o timeout
)
2016-07-22T15:43:34+08:00 WARN Closed connection to broker B's ip:9093

2016-07-22T15:43:34+08:00 WARN client/metadata fetching metadata for [t_log] from broker C's ip:9093

2016-07-22T15:43:34+08:00 WARN Connected to broker at C's ip:9093 (unregistered)

2016-07-22T15:43:34+08:00 WARN producer/broker/2 starting up

2016-07-22T15:43:34+08:00 WARN producer/broker/2 state change to [open] on t_log/5

2016-07-22T15:43:34+08:00 WARN producer/leader/t_log/5 selected broker 2

2016-07-22T15:43:34+08:00 WARN producer/leader/t_log/5 state change to [flushing-1]

2016-07-22T15:43:34+08:00 WARN producer/leader/t_log/5 state change to [normal]
```
the broker 2 is kafka on computer B.
the filebeat can't get the metadata from B because of the firewall on A, and then get metadata from C. But C can connect to B , and C think B is alive. So C send the metadata to A and suggested A also push data to B. And finally data can't send to kafka cluster.
And when you kill the kafka at B, filebeat can send data to C.

I think this is a bug, so how to fix it ?

**Comment by urso** [comment]
The kafka output being blocked is due to the partitioner trying to publish to all known partitions. It's not really a bug, as pushing to a subset of partitions only comes with other undesirable effects like: uneven distribution of events between partitions, sizing must take into account getting more events per partition then originally expected, consumer load being not evenly distributed (bad horizontal scaling), due to bad distribution of events, state machine in consumers requiring events to be send to particular partitions might break, ... I'm sure you can come up with some more.

Anyway, with beta1 the partitioning strategy in the kafka output has become [configurable](https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_partition).
In your case consider adding the following partitioner:

```
output.kafka:
  partition.round_robin:
    group_events: 1
    reachable_only: true
```

By setting `reachable_only` any broker becoming unavailable will be ignored by the partitioner. In worst case (all but one broker being available) all events might be published to only one partition. Use with car. Make sure sizing can deal with N partitions being unavailable. Actively monitor connections, if sizing can deal with N partitions being unreachable, N+1 connection losses might get you intro trouble.

Adding you to pioneer program, as you've reported issue on discuss quite some time ago making us add the `reachable_only` setting.

**Comment by jiayuchen** [comment]
> We are using Filebeat 6.4.2 and i tried the below config but its stopping sending data once it finds the unresponsive Kafka broker. Any thoughts /suggestions?
> 
> partition.round_robin:
> group_events: 1
> reachable_only: true

I also encountered the same problem, my Filebeat version is 6.5.4.  Did you finally solve it?

**Comment by uttamkollipara** [comment]
it worked with below settings

  close_inactive: 10m
  ignore_older: 2h
  scan_frequency: 10s 
  clean_inactive: 3h

**Comment by jiayuchen** [comment]
> close_inactive

Sadly, my input is TCP, not log

**Comment by sundy-li** [comment]
Met same problem, how to solve it? Help!

**Comment by xilu0** [comment]
Met same problem, how to solve it? Help!
