### ISSUE TITLE
Provide basic log parsing capability in filebeat

### ISSUE THREAD

**Issue by ageetha** [elastic/beats#2644]
We have been extending filebeat to provide basic parsing using Named Regex. The named regex is an optional parameter that can be specified per prospector in filebeat.yml file.  Following is an example. 

parsingRegex: (?P<was_requestHost>\S+)\s\S+\s\S+\s[(?P<was_datetime_date>.+)]\s"(?P<was_requestMethod>\S+)\s(?P<was_uriPath>\S+)(?:\?)?(?P<was_queryString>\S+)?\s(?P<was_requestProtocol>\S+)\s(?P<was_responseCode_int>\S+)\s(?P<was_bytesReceived_long>\S+)\s(?P<was_elapsedTime_long>\S+)?

We have also extended this a little further where 
a) we can do type conversion from string to int,long,float based on the suffix provided on the field name. 
b) convert date from incoming format to ISO-8601 format ( ex: 2015-11-05T08:15:30-05:00)

With above extension, we are able to provide a very simple deployment model of Filebeat->Elastic->Kibana.

We are keen to contribute this feature back to community

**Comment by tsg** [comment]
Hi @ageetha, sorry for the late answer. Our general plan is to make use of the Elasticsearch [Ingest Node features](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) (new in 5.0) to do the parsing. This is nice because it means that we need less CPU usage on the edge server, because the parsing is being done centrally. We can also have Filebeat create the Ingest pipelines for you, so the configuration can still be local to Filebeat.

That said, we're not opposed to add some parsing functionality to Filebeat itself, which can be useful, for example, for filtering before shipping. We just want to be careful with adding this functionality not to confuse users with too many ways of doing the same thing.

If you have the code already, we'd be happy to review a PR and see if it's fits our thoughts on how this should be done. Pinging also @urso here as he has been thinking about this.

**Comment by ageetha** [comment]
@tsg, thank you for the comments, Yes we have the code and would be happy to submit the pull request on this shortly.
