### ISSUE TITLE
Agent possibly fills up disk with logs

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#26452]
A Discuss user reported that when using Agent+Endpoint their disk filled up with log files. They resolved the issue before reaching out so don't have the exact path that logs were saved to.

https://discuss.elastic.co/t/elastic-agent-filling-up-disk-space-with-logs-disaster/276668/4?u=ferullo

In their response, they only remembered the path `"C:\Program Files\Elastic....\logs"`, which could be an Endpoint or Agent log path. I can't point to a specific known bug, but there is a chance Agent is filling up the disk with logs.

I was able to find an Endpoint issue that could have been the problem. But I can't definitely say that is what happened to the user or that there isn't also an Agent issue.

**Comment by kvch** [comment]
To me it seems that the user has tested with an old version. Since then we added a few fixes to logging:
- https://github.com/elastic/beats/pull/27072
- https://github.com/elastic/beats/pull/26176

I believe all logging issues are resolved now. It would be nice if they could test it again with the most recent release.

**Comment by jkelastic** [comment]
@kvch I don't think the mentioned fixes are related to this customer's issue as customer is on 7.16.X already and the github tickets are backported to 7.13 and 7.14. Please advise.

https://github.com/elastic/beats/pull/27072
https://github.com/elastic/beats/pull/26176
