### ISSUE TITLE
Which beat should i use?

### ISSUE THREAD

**Issue by gimler** [elastic/beats#2648]
I am a liddle bit confused about packetbeat topbeat and metricbeat

1. You can beat you system with metricbeat and topbeat? Why both is someone deprecated?
2. You can beat you mysql with metricbeat and packetbeat? Why both is someone deprecated?

**Comment by gimler** [comment]
1. "Topbeat is being replaced with Metricbeat in 5.0."

**Comment by tsg** [comment]
That's right, Topbeat is being extended in Metricbeat in version 5.0.

Regarding Metricbeat vs Packetbeat, they work quite differently. Metricbeat queries the MySQL monitoring APIs and extracts the metrics as reported by MySQL. Packetbeat sniffs and decodes the network traffic received and sent by Packetbeat and stores the transactions in Elasticsearch. So ideally you would use both, but the Packetbeat setup tends to require more planning, so I'd recommend starting with Metricbeat.

Meta: I'm closing the issue for now, because we're keeping Github for issues and enhancement requests. We prefer having discussions and questions on https://discuss.elastic.co/
