### ISSUE TITLE
[Self-managed]: Unable to install Fleet Server agent on 7.14.0.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26818]
**Kibana version:** 7.14.0 Snapshot Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 42157
Commit: dcacd04872050ff322f7e9bb36af913e40d5977e
Artifact Link:
https://snapshots.elastic.co/7.14.0-c5e16e4e/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana self-managed environment should be available.
2. Test Signing should be ON.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents tab and copy install command for Fleet Server.
3. Run install command and observe 

**Expected Result:**
Fleet Server agent must be installed on running install command on self managed 7.14.0 Snapshot Kibana.

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/123917926-f7c7e700-d9a0-11eb-992e-6d81297fdc70.JPG)

**Comment by blakerouse** [comment]
I moved this issue to beats repository because this is an issue with beats, but I can tell you the issue has already been fixed. I can tell from the screenshots that #26760 is not in either of those builds. That is clear to see as the log message `Retrying to enroll...` was changed in that PR and that is not reflected in either screenshot.

First you should see this new log message that is not shown: https://github.com/elastic/beats/blob/3857573d985f9013040e419d19a67797d0b0f27d/x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go#L405

Then you should also see this log message on retry: https://github.com/elastic/beats/blob/3857573d985f9013040e419d19a67797d0b0f27d/x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go#L423

@andresrc ^ was BC2 built with that PR merged? based on this reporting it was not

**Comment by andresrc** [comment]
@amolnater-qasource can you try again? It seems BC2 was "rebuilt", the new one should contain the fix

**Comment by amolnater-qasource** [comment]
Hi @andresrc 
We have re-attempted to elastic-agent on 7.14.0 Self managed BC-2 Kibana and we are able to install Agent now.
Hence closing this issue as it is **fixed**.

**Build details:**
```
Build 42401
Commit: 9826a943dc2e47f26ec6de94816e7d297b752994
Artifact Link: https://staging.elastic.co/7.14.0-e99135ef/summary-7.14.0.html
```
**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/125280511-c18c4f00-e332-11eb-95ce-19c8fb085db8.JPG)

Thanks
QAS
