### ISSUE TITLE
Endpoint, Filebeat reporting different hostnames and OS name for macOS

### ISSUE THREAD

**Issue by crowens** [elastic/beats#26865]
- Version: 7.13.1
- Operating System: macOS
- Discuss Forum URL:
- Steps to Reproduce: Install the Elastic Agent with the Endpoint Security integration enabled.  Look in the Security solution at the 'Hosts' tab.  You will see 2 hosts for a single install:
![image](https://user-images.githubusercontent.com/6376821/125474794-0a8a240f-8c4a-42e6-b663-d04aa24f275f.png)

Two issues: It seems Filebeat and Elastic Endpoint are sending different hostnames.  Second, the OS name is being returned differently as well.  This clutters up the hosts list with multiple entries for the same machine.

**Comment by crowens** [comment]
@ferullo

**Comment by ferullo** [comment]
Endpoint can return the hostname visible in System Preferences or the hostname returned from the `hostname` command on the command line. We aligned with Agent in 7.9, if the situation has changed Endpoint just needs to be told which one to now return. But if the issue is an Agent bug Endpoint won't change anything.
