### ISSUE TITLE
Upgrade the aws-sdk-go-v2 version in beats

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#26873]
Currently in Beats, we are using version 0.9.0 `aws-sdk-go-v2` in AWS related areas. This version is 2 years old and with more bugs getting fixed on the `aws-sdk-go-v2` side, we should investigate on upgrading to newer version of the SDK and figuring out if we want to continuously follow the `aws-sdk-go-v2` release schedule for upgrades.

**Comment by kwinstonix** [comment]
@kaiyan-sheng , hi,  is there any updates?  `aws-sdk-go-v2` latest version is `v1.13.0 ` 🤔

**Comment by kaiyan-sheng** [comment]
Hey @kwinstonix 👋 We upgraded to version `v0.24.0` several months ago but still, it's not all the way to the latest version. Hopefully we will get back to this issue soon!!

**Comment by ofiriro3** [comment]
Hi @kaiyan-sheng,

I am from the @elastic/cloud-posture-security team.
We have been recently developing a new beat [cloudbeat](https://github.com/elastic/cloudbeat) which will be used for fetching some Kubernetes data.
The cloudbeats as most of the beats, uses the `beats` as a dependency (as it uses many libbeat functions).

We are currently working to support the EKS Kubernetes provider as well. 
In order to do so, our beats uses the aws-sdk-go-v2 library.

Currently, we are using the same aws-sdk-go-v2 version as the libbeat, but we would like to use the latest version possible.
We have tried to upgrade the `aws-sdk-go-v2` on our beats, but we couldn't do so since the libbeat requires a different version.
(We tried to overcome it with a couple of solutions but haven't manage to solve it so far - https://github.com/elastic/security-team/issues/3175).

It is not urgent, but we would like to know if have any ETA for it?

**Comment by kwinstonix** [comment]
https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md#migrating-from-v2-preview-sdks-v0240-to-v0250

Is there any possible to upgrade to v0.25.0 first?  There are some breaking changes.

**Comment by kaiyan-sheng** [comment]
PR related to this issue: https://github.com/elastic/beats/pull/31224

**Comment by kaiyan-sheng** [comment]
PR is merged into the main branch.
