### ISSUE TITLE
Agent (Filebeat) stops Endpoint from deleting its own logs

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#26941]
Endpoint logs to `c:\Program Files\Elastic\Endpoint\state\log\`. Log files are broken into 25MB files, once that limit is reached a new log file is started. After 100MB of logs are saved, Endpoint deletes the oldest log to roughly stay under the 100MB cap. If that cleanup fails and a roughly 200MB cap is hit a hard limit is reached. Endpoint will stop logging and report policy failure (unhealthy status) to Kibana

**BUG: When Agent runs Endpoint, Endpoint is unable to delete its oldest logs.**

Steps to reproduce:
1. Install Agent
2. Add Endpoint Security integration
3. To speed up how quickly Endpoint fills up the 100MB cap, set `windows.advanced.logging.file=trace` in Endpoint advanced policy options. Stop/start a lot of processes to generate activity Endpoint monitors. 
4. Notice that once Endpoint has logged 200MB of logs logging stops and Agent is unhealthy because Endpoint is in a failed state.
5. Stop Agent's service via Services UI
6. Notice that Endpoint cleans up its logs within a few minutes
7. Start Agent's service via Services UI
8. Notice that Agent and Endpoint are healthy again (until this happens again)

**Comment by kvch** [comment]
My theory is that log files cannot be deleted because Filebeat is still keeping them open because either
* Filebeat cannot forward events to the output, thus, keeping the files open so nothing gets lost (I assume this is not the case otherwise @ferullo would have mentioned that the output is blocked)
* Filebeat does not close the rotated files even if it has finished forwarding the logs

My questions:
* How does Endpoint rotate its logs? Does it rename the files that are bigger then the 25MB limit and deletes the 5th file to stay under the 100MB limit? Or does it open separate files with different names on every rotation?

Either way I suggest we add `close_renamed` or `close_eof` depending on the input file and the configuration so Filebeat can let go of the file handles, letting Endpoint clean up its own logs.

**Comment by ferullo** [comment]
> Filebeat cannot forward events to the output, thus, keeping the files open so nothing gets lost (I assume this is not the case otherwise @ferullo would have mentioned that the output is blocked)

Correct, There was no issue reaching Elasticsearch. Endpoint and Agent/Beats were able to reach Elasticsearch the whole time for the repro.

> How does Endpoint rotate its logs? Does it rename the files that are bigger then the 25MB limit and deletes the 5th file to stay under the 100MB limit? Or does it open separate files with different names on every rotation?

Endpoint does not rename log files. Log files are named `endpoint-XXXXXX.log`, where `XXXXXX` is a zero-lead number (e.g. `000003`). When a log file fills up Endpoint increments to the next number (e.g. `000004`).

Once the directory is over capacity Endpoint tries to delete the oldest log(s) until it is back under the 100MB limit.

**Comment by kvch** [comment]
@ferullo Please review the proposed fix.
