### ISSUE TITLE
Automatically accept more connections on larger instances

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#26981]
This is the second phase of our [epic to gracefully reject connections](https://github.com/elastic/fleet-server/issues/153), where we'd like to automatically accept more connections on larger instances with more memory.

In the first phase the user has to manually edit the limit. This results in a sub-optimal UX because the user has to make adjustments in two places when scaling the Fleet Server instance. They have to edit the memory size in their container configuration, and they have to edit the integration policy. The user also needs to look up a table of guidance values when updating the integration policy https://github.com/elastic/fleet-server/issues/134.  This is also a blocker for autoscaling.

It'd be a better UX if Fleet Server can automatically adjust based on the instance size or available memory. This will reduce the number of settings the user needs to manually change. It will also enable future autoscaling in ESS/ECE.

**Comment by jlind23** [comment]
@ruflin any clue about how we should implement this? At it seems to be a blocker for autoscaling maybe we should take it into account.

**Comment by ruflin** [comment]
What we discussed in the past is following the same path as apm-server. This basically means hardcoding the values into fleet-server itself. There is the catch that multiple services can impact each other at the same time we can provide good base values so that if we go from 1 to 2GB of memory, the numbers get increased. If this still is not sufficient, further scaling is needed. Agree that this is required for proper auto sclaing.

**Comment by scunningham** [comment]
This is not hard to implement, however to pull it off we would need some form of input that describes either how much RAM we are allowed to use, or more specifically how many endpoints to accommodate.   The Fleet Server does not have the luxury of assuming all of the RAM in the container it is executing in, nor would it necessarily have that luxury when running on premise depending on where the customer staged it.

**Comment by ruflin** [comment]
One approach we could follow is that by default each process for example assumes it can take up 75% (made up number) of the CPU / Memory and based on it defines the correct values. As soon as apm-server and fleet-server for example are run in parallel we end up with 150% needed. But that is when autoscaling kicks in. As soon as one of the processes takes on a decent amount of memory or CPU, the container would be scaled up. Still apm and fleet-server would assume again 75% of the resources but by default would consume only a fraction when not under load.

On premise I think our recommendation should be to only run the fleet-server if possible on the same machine. So by default we give the user a decent experience. If the user needs to customize it, there are always the config flags.

@scunningham What parts do exist in fleet-server where fleet-server would already allocate lots of memory on a large machine by default because of some config variables even if only a few elastic agents talk to it? Would a fleet-server on a large instance with the configs for the large instance still behave well?

**Comment by scunningham** [comment]
As far as a I know, the FleetServer/APM containers do not yet autoscale.  I am hoping that is incorrect.  Most of the issues are around RAM, as CPU usage in the Fleet Server is bursty but not typically sustained unless very badly configured.

The configuration numbers we have recommended are largely RAM driven, leaving only a small percentage for the Fleet Server per container.  For a 512MB image, we set aside 350MB for APM, 100 for Agent/Beats, and a measly 50 MB for the Fleet Server.  We were asked by the APM team to not break current installs by over allocating RAM, so that is how we ended up with these tiny numbers.

All of the memory allocation is done based on configuration.  The only place we preallocate is the [cache](https://github.com/elastic/fleet-server/blob/master/internal/pkg/cache/impl_ristretto.go#L14), and that is currently based on config not RAM size.  The other item that can affect RAM is the [bulk engine](https://github.com/elastic/fleet-server/blob/master/internal/pkg/bulk/engine.go#L74).  However, that is largely in the noise once you get to larger memory footprints.

RAM usage is driven by number of connections.  Each connection takes on average 75KB.  The config recommendations are scaled by expected number of connections.  You could invert that if you knew how much RAM you were allowed (ignoring CPU).

So to follow that model, we could by default look at the amount of RAM in the container and take our currently spec'd 10% - 20%.  This only makes sense however in our Cloud environment.  It would not make sense to auto-configure this way in a stand alone install.

**Comment by ruflin** [comment]
We don't have autoscaling yet but hopefully soonish.

We can detect if we are in Cloud or not, so we could start with having the hardcoded values for Cloud. Ideally it would be a simple formula but if I remember correctly @simitt did this for apm-server and the formula is far from simple. After we have the Cloud case sorted out we can think further about the on prem case proper scaling. I know @nimarezainia has lots of ideas around how to simplify it and make it dependent on a single config option.

**Comment by nimarezainia** [comment]
@ruflin (I may be over simplifying this issue) - We have increased the default RAM budget to 1GB, double what we had previously. Could we not just double the default number of connections for now? 

I certinaly believe that chaging the instance size to achieve higher connection or enrollments is the wrong approach from the customer's perspective. It should all be driven by the the number of agents they want to support. So I rather have number of agent and/or system metrics drive the instance size that is needed.

I am somewhat weary of using complex algorithms and such to calculate the various parameters here - because frankly what ever we perceive to be the right number to choose based on our experience, we will get a customers whose configuration/setup will challenge those *right numbers*. Wasted engineering effort.

Our goal is to achieve auto scaling based on system metrics. That would give customers the best experience with the product (we have the definition document for that but I need to update). That would enable us to move away from "what's the right size RAM/CPU" discussions. How can we incrementally move towards that goal?

**Comment by ruflin** [comment]
The number of elastic agents is a good indicator but likely the situation is a bit more complex. The problem is that Elastic Agents can behave very different based on what the user does. Sending down actions from osquery every few minutes or doing many policy changes requires lots of resources, just having 1000 elastic-agents on the same policy and collecting data but not sending down any changes has a much lower overhead. 

In my ideal scenario, the user does not even hat to specify the max number of Elastic Agents. Instead, if the user makes many changes on the policies and sends down actions, we automatically scale up and later on down again when things become a bit more quiet. The user should not even notice on Cloud.

On prem, we need to have a ballpark number like X agents -> y CPU / Memory with a big * explaining why it might be different. 

If a user puts in 1000 Elastic Agent, does this define the minimum or maximum resources needed?

**Comment by scunningham** [comment]
The majority of the resource usage for Fleet Server is CPU driven from TLS handshake, and RAM.  RAM can be mapped proportionately to the number of connected endpoints.  That will not vary a lot.  CPU usage will vary depending on circumstance.  However, if behind a proxy with persistent TLS connections, we should not get a lot of CPU impact on account of TLS handshake.  We get CPU bursts initially, and when the proxy times out the connections.

We need to measure this, but I do believe that in the general case the number of targeted endpoints is a pretty good starting place to estimate resource usage.

**Comment by jlind23** [comment]
As discussed with @nimarezainia this one is not relevant anymore.
