### ISSUE TITLE
Stop reading memory usage statistics from Elasticsearch.

### ISSUE THREAD

**Issue by jpountz** [elastic/beats#26998]
Elasticsearch is removing the ability to get information about the memory usage of segments in order to prepare for the upgrade to Lucene 9. https://github.com/elastic/elasticsearch/pull/75274

Beats should stop collecting this information. Specifically the following fields would no longer exist in the response when referring to segments:
 - `memory`
 - `memory_in_bytes`
 - `terms_memory`
 - `terms_memory_in_bytes`
 - `stored_fields_memory`
 - `stored_fields_memory_in_bytes`
 - `term_vectors_memory`
 - `term_vectors_memory_in_bytes`
 - `norms_memory`
 - `norms_memory_in_bytes`
 - `points_memory`
 - `points_memory_in_bytes`
 - `doc_values_memory`
 - `doc_values_memory_in_bytes`

For instance we would need to remove these fields: https://github.com/elastic/beats/blob/4da15940f340b9486845edcb767016ac2aa99e33/metricbeat/module/elasticsearch/index/_meta/fields.yml#L65-L78.

**Comment by jpountz** [comment]
Could you also tell me whether you have tests against Elasticsearch master builds, in which case I will wait for this issue to be addressed before merging elastic/elasticsearch#75274.

**Comment by ruflin** [comment]
This issue is about the module / integration of elasticsearch and I think we likely test against master: https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/_meta/Dockerfile#L2 @masci @jasonrhodes In case we test, I think we should get a quick fix into master to not fetch / check for these fields anymore to unblock Elasticsearch.

I mislabeld the issue first. This falls into the integrations and not elastic agent team.
