### ISSUE TITLE
Decode_CEF preprocessor fails when MAC address is without separators

### ISSUE THREAD

**Issue by LaZyDK** [elastic/beats#27050]
**Describe the enhancement:**
Decode_CEF preprocessor needs to support MAC addresses without separating characters. 
https://github.com/elastic/beats/blob/877d8bcd176b2f5d4efd2a81846a481b94798b49/x-pack/filebeat/processors/decode_cef/cef/types.go#L93

**Describe a specific use case for the enhancement or feature:**
While sending syslog in CEF format from Aruba ClearPass we get errors. 

Log from Aruba ClearPass:
`<143>Jul 26 2021 15:09:34 192.168.203.220 CEF:0|Aruba Networks|ClearPass|6.8.7.120583|2001|Failed Authentications|5|cat=Session Logs dvc=192.168.203.220 duser=0011223359e4 destinationServiceName=TEST_PROD MAC-AUTH Wired dpriv=TEST-VL1, [User Authenticated] cs2=Local:localhost cs2Label=Auth Source requestMethod=MAC-AUTH cs4=UNKNOWN cs4Label=System Posture Token outcome=[Update Endpoint Known], TEST-MerakiAP-VL1, MAC-AUTH-port-mode dmac=0011223359e4 src=192.168.1.78 cn1=0 cn1Label=Error Code rt=Jul 26 2021 15:08:37`

Error message:
`error in field 'dmac': address 0011223359e4: invalid MAC address`

**Comment by andrewkroh** [comment]
The parser is expecting a separator because the documention we used to implement it specified it for `dmac`. I tend to think Aruba should fix their formatter, but we should make our parser handle this case too.

> Six colon-seperated hexadecimal numbers. Example: “00:0D:60:AF:1B:61”

<img width="760" alt="Screen Shot 2021-07-26 at 1 54 19 PM" src="https://user-images.githubusercontent.com/4565752/127035692-8d49872e-cc0f-4dd8-9f31-b38ed7333a5d.png">

Reference: https://ia801002.us.archive.org/11/items/commoneventformatv25/CommonEventFormatV25.pdf

**Comment by LaZyDK** [comment]
I agree that Aruba should stick to the CEF format, but even though they might fix this in the future we have no way of supporting their older software versions. 
Having the parser doing this operation will be the best solution to support all needs.

**Comment by andrewkroh** [comment]
PR: https://github.com/elastic/beats/pull/27109
