### ISSUE TITLE
[Agents]: Artifacts related and "Initial configuration application failed" errors on adding Endpoint Security to the Agent policy.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27064]
**Kibana version:** 7.14.0 BC-4 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 42656
Commit: 82a4f6a7fa23946667599787cdb1b2d82c1d0dfb
Artifact Link: https://staging.elastic.co/7.14.0-b3779639/summary-7.14.0.html
```

**Preconditions:**
1. 7.14.0 BC-4 Kibana cloud environment should be available.
2. Agents must be installed using Default policy having System and Endpoint Security integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agent Logs tab.
3. Select `elastic-agent.endpoint_security` from dataset dropdown filter.
3. Apply `error` filter from log level dropdown.
4. Observe error logs.

**Screenshots:**
![Endpoint Security](https://user-images.githubusercontent.com/77374876/127122807-f5b39ef8-90d5-49b9-a405-b51461852b65.jpg)

**Windows Agent Logs:**
[logs.zip](https://github.com/elastic/beats/files/6883757/logs.zip)

**Windows Endpoint logs:**
[endpoint-000000.log](https://github.com/elastic/beats/files/6883746/endpoint-000000.log)

**Expected Result:**
Artifacts related and "Initial configuration application failed" "errors" should not generate on adding Endpoint Security to the policy.

**Note:**
-  These logs are **also observed** for MAC, Linux tar, Linux .rpm, Linux .deb and Linux ARMx64 agents.
- No impact on Agent functionality is observed.
- These error logs are generated at the beginning when Endpoint Security is added.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by ruflin** [comment]
Same as the others, marking this as a bug we need to look into. It might be just a timing / logging issue but it is something we need to investigate.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have observed new `error` logs for MAC Bigsur 11 agent when Endpoint Security is added to the policy on 7.15.0 BC-5.

**Log:**
`15:32:39.770`-
`elastic_agent.endpoint_security`-
`[elastic_agent.endpoint_security][error] Interfaces.cpp:123 Interface name too long to get MAC address; name [stf0], namelen [4], sdl_alen [0], sdl_nlen [4] (see net/if_dl.h -> sdl_data)`


**Build details:**
```
Build 43957
Commit: 0239ff6864dd9930cfe9bcd9a679272f2b7465c2
Artifact Link: https://staging.elastic.co/7.15.0-edd09abf/downloads/beats/journalbeat/journalbeat-7.15.0-linux-x86_64.tar.gz
```

**Logs:**
[endpoint-000000.zip](https://github.com/elastic/beats/files/7135907/endpoint-000000.zip)
[logs.zip](https://github.com/elastic/beats/files/7135909/logs.zip)

cc: @ruflin 

Please let us know if anything else is required from our end.
Thanks

**Comment by ruflin** [comment]
@ferullo Can you and the team take a look at this?

**Comment by ferullo** [comment]
@kevinlog this looks like the artifacts issue your team has been chasing.

**Comment by ferullo** [comment]
I should also mention the log `15:32:39.770-
elastic_agent.endpoint_security-
[elastic_agent.endpoint_security][error] Interfaces.cpp:123 Interface name too long to get MAC address; name [stf0], namelen [4], sdl_alen [0], sdl_nlen [4] (see net/if_dl.h -> sdl_data)` is a known issue. It is unrelated to the policy failure and mostly benign.

**Comment by kevinlog** [comment]
@ferullo possibly - we do have a fix merged that will go out in `7.14.2` and `7.15.0` to address the migration issue customers were seeing. https://github.com/elastic/kibana/pull/111294

I'd need more information into how this occurred so that we can reproduce.  @amolnater-qasource did you take any special steps to setting up this instance?  Was it a clean `7.14.0` build?  Also, did you see Policy failures on the "Management > Endpoints" screen?

@ferullo I'm seeing failure for downloading the `diagnostic` artifacts in the screenshots which come from the protections team and served from a different server. 

This leads me to believe that this may have been a different problem with downloading artifacts.  The specific problem we believe we solved in the above PR was a migration issue.

diagnostic artifacts called out here:
![image](https://user-images.githubusercontent.com/56395104/132687006-fb520599-f9e7-4f40-940e-291c48a46743.png)

I'll need more info on how these conditions occurred.  @amolnater-qasource have you reproduced this since?

**Comment by amolnater-qasource** [comment]
Hi @kevinlog 

>I'd need more information into how this occurred so that we can reproduce. @amolnater-qasource did you take any special steps to setting up this instance? Was it a clean 7.14.0 build? Also, did you see Policy failures on the "Management > Endpoints" screen?

Yes we had the fresh/clean 7.14.0 Kibana build. We created 5 different policies with different namespace to test the datastreams. All the 5 agents were installed initially with System integration only. 

Then we added Endpoint Security to this and found these reported logs getting generated under logs tab with `elastic-agent.endpoint_security` dataset.

Further on Endpoints tab we haven't observed any Policy failure too. It was all in **Success**.
>@amolnater-qasource have you reproduced this since?

We haven't tested it again on 7.14.0, however just today we have attempted the same steps on 7.15.0 BC-5 and observed below attached error logs for `elastic-agent.endpoint_security` dataset under agent Logs tab.

**Windows:**
![Windows](https://user-images.githubusercontent.com/77374876/132690190-ae776cdd-727f-4626-a427-67427f61f5b5.png)

**MAC:**
![MAC](https://user-images.githubusercontent.com/77374876/132690221-318d92d5-5e8b-4e50-beda-5939150f0a75.png)

**Linux .tar:**
![3](https://user-images.githubusercontent.com/77374876/132690326-646337fa-89e9-4928-81bf-6be76d8ec685.JPG)

**Linux .rpm:**
![7](https://user-images.githubusercontent.com/77374876/132690397-f7702f32-b602-462f-bf57-def8ecf5dff6.JPG)

**Linux .deb:**
![4](https://user-images.githubusercontent.com/77374876/132690444-9380a6b4-bc5e-473d-b01e-b7d25f87d07b.JPG)

Please let us know if anything else is required from our end.
Thanks

**Comment by kevinlog** [comment]
Thanks @amolnater-qasource !

I got access to the server Amol was testing on and saw that all of the Endpoints have successful policies.

![image](https://user-images.githubusercontent.com/56395104/132692647-615e1df0-180a-456f-9f5b-fa1453f9ca42.png)

@ferullo are these artifact download errors just an effect of trying to apply the initial policy?  That policy wouldn't contain any URLs yet.

**Comment by ferullo** [comment]
OK. I looked into this more. Sorry for the ping @kevinlog, I agree this is not the issue I first thought it was. All of those logs are benign. Endpoint installs with a configuration that lets it start up and importantly start logging. That configuration fails to enable all Endpoint features and, notably, it fails to download user artifacts because it has no knowledge of Stack configuration yet. Before 7.14.0 it would have caused a failed initial policy because Endpoint sent the result of applying the initial installed configuration to the Stack. However, in 7.14.0 Endpoint stopped reporting the result of that configuration to the Stack.

As long as Endpoint's policy is successful in Kibana, these logs can be ignored. Still, while they arebenign I do understand that they cause confusion and we'll look into ways to prevent them from causing confusion.

**Comment by EricDavisX** [comment]
If I'm understanding the thread, we can move this to Endpoint-dev or just close & recreate it there if desired.  @ferullo sound good and if you want it, can you log the Endpoint-dev bug please with whatever reference info you want to transfer from here?
