### ISSUE TITLE
[DOCS] Update Beats docs to include all of the places where `cloud.id` is needed

### ISSUE THREAD

**Issue by KOTungseth** [elastic/beats#27237]
**Describe the enhancement:**
To learn about `cloud.id` for Beats, the docs currently include [Configure the output for Elasticsearch Service on Elastic Cloud](https://www.elastic.co/guide/en/beats/filebeat/current/configure-cloud-id.html) and [Configure Beats and Logstash with Cloud ID](https://www.elastic.co/guide/en/cloud/current/ec-cloud-id.html). The Beats docs should be updated to include all of the places where `cloud.id` is needed to set up Beats.  

Instead of, `You can find the `cloud.id` in the Elastic Cloud web UI.` and `The base64 encoded cloud.id found in the Elasticsearch Service web console.`, it would be helpful to also include how to locate the `cloud.id`.

**Comment by dedemorton** [comment]
Sorry this got very lost in our backlog. :-/

@KOTungseth Can you clarify your request?

>The Beats docs should be updated to include all of the places where cloud.id is needed to set up Beats.

I'm not sure what you mean by "all of the places." Do you mean in addition to the config file and command line? 

>  it would be helpful to also include how to locate the cloud.id.

Do you mean that we should document the cloud UI steps? I hesitate to do this because the cloud UI changes over time and the steps will be stale for users looking at older versions of the Beats documentation. I would rather point to the cloud docs. Maybe that's the fix here?

**Comment by KOTungseth** [comment]
@dedemorton I vaguely remember opening this issue, but I believe this came from a user that wanted to know all of the places where they needed `cloud.id` to set up Beats. I'm haven't set up Beats in a while, but I assume this also means outside of the config file and command line. 

I wouldn't "double-document" [what is already in the Cloud docs](https://www.elastic.co/guide/en/cloud-enterprise/3.3/ece-cloud-id.html), so I agree that including links to the Cloud docs is the best fix.
