### ISSUE TITLE
useless option path.config

### ISSUE THREAD

**Issue by colttt** [elastic/beats#27458]
The Documentation said "The location for configuration files." So normally that means I can put config files in it that will be parsed/used like /etc/apt/sources.list.d/ in Debian, but that not happens If I specify path.config and add custom config files in it, it will be ignored, so that means for me that the parameter is ignored or the documentation is (in my understanding) wrong.

For confirmed bugs, please report:
- Version: 7.14.0
- Operating System: Debian 10
- Discuss Forum URL: https://discuss.elastic.co/t/in-which-order-are-config-loaded/281014/2
- Steps to Reproduce: 
start filebeat with
```
/usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat
```
and add a config like /etc/filebeat/custom_config.yml that config file will be ignored and if I don't set this parameter filebeat works also fine, so the question is for what is it good for? (absolutely nothing ;-) ) and if it should work, in which order will these config files parsed?

**Comment by jsoriano** [comment]
Hey @colttt,

In principle `path.config` is used to find the main configuration file (`{path.config}/filebeat.yml`) and the modules directory (`{path.config}/modules.d`).
If you also use `-c /etc/filebeat/filebeat.yml`, it uses this file as the main configuration file.

With the flags to mention, filebeat should use:
* `/etc/filebeat/filebeat.yml` as the main configuration file (because of `-c /etc/filebeat/filebeat.yml`).
* `/etc/filebeat/modules.d` for modules configurations (because of `--path.config /etc/filebeat`), though it depends on the `filebeat.config.modules` configuration in the main configuration file.

The main configuration file is not composable (with the exception of `filebeat.config.modules` configurations), so other files are expected to be ignored, there is nothing that would read an extra file such as `/etc/filebeat/custom_config.yml`. If you want to use this file as the main configuration file, you should use `-c /etc/filebeat/custom_config.yml`, but it should be a complete configuration.

Regarding your concern about `path.config` being useless, I think this is a valid point, because with the use of `-c` flag and `filebeat.modules.path` you can achieve the same results. But there can still be users that use `--path.config` to indicate a different directory both for the main and modules configurations, or that use `-c` with the default config path for modules.d. A change in behaviour here would be breaking for them, so I don't think this should be modified in any way.

Maybe this could be more clearly explained in the docs to avoid this kind of confusions, @colttt would you be fine with this or you expect some change in the current behaviour?

**Comment by colttt** [comment]
thanks, now it's much clearer to me. 👍

**Comment by jsoriano** [comment]
@colttt great, do you think that any action should be taken for this issue or you are ok with closing it?

**Comment by colttt** [comment]
for **me** its fine, but maybe you should adjust the documentation?

**Comment by jsoriano** [comment]
Ok, I'll leave it open to review the docs, thanks for your feedback!
