### ISSUE TITLE
[Heartbeat] [Browser Monitor] Bubble Errors up in browser `source` configuration to be viewable in places like Kibana

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#27924]
I think part of this enhancement requires stuff on the Kibana end, but I think the work would start with Heartbeat. If this is incorrect please feel free to close, and I can open in Kibana repo.

**Describe the enhancement:**

Currently when there is an error somewhere in the actual browser `source` configuration (i.e. syntax error), the monitor runs, but exists with an error code. These error never make it to the Kibana interface. This makes it hard for users who are writing the monitors, but don't have access to the underlying heartbeat to see the logs.

**Describe a specific use case for the enhancement or feature:**

If you have users writing the playwright source, but they don't have access to heartbeat to view the logs, then they need to contact the person who has access to Heartbeat to pull the logs. 

Example: using `zip_url` source, user can write the code to a git repo, but never actually have access to heartbeat.

Here is an example of the errors I'd like to see show up in Kibana from Heartbeat:

```json
{"level":"info","timestamp":"2021-09-14T18:35:21.848Z","caller":"synthexec/synthexec.go:224","message":"stderr: SyntaxError: Invalid or unexpected token"}
```

Note; the errors I'm talking about specifically refer to the `source` section, I wouldn't expect heartbeat to show errors within its own config.

**Comment by paulb-elastic** [comment]
This may work best with Monitor Management, as we will have a saved entity from the Uptime UI to which we could attach the error, however needs further thought.

**Comment by andrewvc** [comment]
Another thought here, currently for zip_url monitors we create N monitors, one for each `journey` defined within the source. The problem here is that there's no natural place in the Uptime UI for an error to go if _all_ the monitors are failing.

I propose we create an extra 'base` zip_url monitor containing the state of the whole suite. If all the monitors are passing it's green, otherwise it's red. It would be the natural place to display errors that affect the suite as a whole. Additionally it would be a place to provide insight into how long the whole zip_url suite takes to run.

The overview page would change to add this, something like this:


Currently debugging errors here is extremely difficult, and while this may clutter things a little in the UI it makes some very poor user experiences much more tolerable.

In the future we could render this data as

**Comment by paulb-elastic** [comment]
I like the idea of defining this as a different type (such as `suite`) so that we can treat it differently in the UI, such as filtering it out for those who don't want to see it.

If we did nothing else, is there a chance this *monitor* will trigger existing alerts if there is a problem with the script?  I get the value in being alerted if there is a problem with the suite configuration (and maybe that goes to a different team, responsible for maintaining the scripts), however I am thinking more about existing alerts.

For example an existing rule which triggers if `ANY MONITOR IS DOWN > n times`, an alert could be fired suggesting the infrastructure being monitored is down, as opposed to the monitor itself having a problem.

Could this new `suite` type be excluded from an `ANY MONITOR` check by default with this implementation?  A future enhancement could then be to set up alerts for `suite` specific types?

(/cc @drewpost for visibility)

**Comment by lucasfcosta** [comment]
I like @paulb-elastic's idea of having a different `suite` type because:

1) I think that would match more closely the abstractions that most test runners out there use, and thus are easier for users to understand.
2) Users could recursively group tests and therefore group statuses for sets of tests in whichever way they like, not only 2 (or 3) levels deep.

--------

If you think of `mocha` and `jest`, for example, their constructs map to ours in the following way:

* `describe` = `suite` ➡️  Can be used to recursively group tests into groups
* `it`/`test` = `journey` ➡️  A particular test-case, which may contain multiple steps (expressions) and assertions.
*  `<expressions> ::= <expr>|<expressions><expr>` = `step` ➡️  Given the nature of our product (and what we show users) we must have an extra construct to group expressions which would otherwise just be written as code.

Thanks to the above, especially `describe` (and thus `suite`, in our case), reporters can provide visual feedback that's easier to parse.

See below how Jest's summary nests results under a particular test file, for example:

![](https://olavihaapala.fi/images/06-jest/jest.jpg)

![](https://raw.githubusercontent.com/aXises/jest-compact-reporter/master/images/default.jpg)

As you see above, grouping helps nesting and informing users of where a failure is.

**Comment by paulb-elastic** [comment]
@BenB196 thanks for raising this - as you can see, there's been some thought around possible approaches.  I’m going to close this in favour of https://github.com/elastic/uptime/issues/425, please follow that for progress on us implementing it.  Thanks again for your input.

**Comment by BenB196** [comment]
@paulb-elastic thanks for investigating it. I'll follow the other issue.
