### ISSUE TITLE
[Agent][Windows] Agent doesn't always re-start on reboot (seen on GCP Win host)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#27973]
Testing involves the Endpoint Integration, and Host Isolation feature.  But let us also attempt to confirm this with just Agent as well.  And we can update here.

From Security team:  I had a host Isolated, and it rebooted (standard gcp behaviour for patching). After reboot, it was accessible as the Elastic Agent process hadn't started (I've noticed this quite a few times on windows machines).  Any isolation implications are being handled by Endpoint / ILM Sec teams, and are a symptom of the sitution.

Version seen:
7.15 BC5
Windows Server 2019

Steps to Reproduce: 
- Install Agent
- reboot host
- wait and see if Agent service is started or not.

Implied / possible alternative steps:
Steps to Reproduce: 
- Install Agent
- include Endpoint Integration in policy
- use Endpoint 'isolate host' functionality and confirm it is isolated
- reboot host
- wait and see if Agent service is started or not.

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource @amolnater-qasource can you run through this on the 7.15 latest BC available please? I'd love to see it on our usual vSphere hosts if possible as well as a win 2019 GCP host if you have access.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX,

We have validated above issue on both the scenarios mentioned above in ticket description on latest 7.15 BC7 build on windows server 2019 machine and found it working fine.

**Build details:**
```
BUILD 44040
COMMIT add5d2c5ebeba1d8bcf6a79f8863cd78760e1b3e
Artifact link: https://staging.elastic.co/7.15.0-592034cb/downloads/beats/elastic-agent/elastic-agent-7.15.0-windows-x86_64.zip
```

**Scenario 1:**

- Installed Agent with only system integration
- rebooted host
- waited and found Agent service in running state.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/133972159-5628526b-192b-46a2-b84e-9121299b1fb4.png)


**Scenario 2:**

- Installed Agent
- include Endpoint Integration in policy
- Isolated Endpoint 
- reboot host
- waited and found Agent service in running state.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/133972273-da86b21a-3540-4e48-b18f-4a1683e3f481.png)

Further, @EricDavisX we don't have access to GCP hosts, so unable to validate it there.

Please let us know more if anything is required.

Thanks
QAS

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource could you try using a Windows 2019 host on AWS please?  Thanks for the update so far.  I will go back to the slack thread and see what we want to do further on Engineering side. May need to pull in someone to look at the host on the specific cluster if it is still reproduced/reproducible

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated above issue partially on AWS windows 2019 server instance on 7.15BC7 build and found it working fine for 1st scenario.

- Agent service was in running state after the machine reboot when having only system integration in agent policy.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/134158020-dd24fffc-b741-4353-995a-d82e5a7364c0.png)

Though we have recorded one error log after reboot, however its not related to above reported.

![image](https://user-images.githubusercontent.com/72375798/134158106-c0c39a6e-af35-4df2-a5b7-2657923a21f0.png)


- We were unable to validate isolated host scenario and once host is in isolated state we cannot access the machine through RDP .
Further, console access is also not possible due to instance type currently we use, do not support it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/72375798/134158168-3fe223cc-2d6f-4924-9150-673999b9a6d9.png)

Isolated Host after reboot, refuses to connect through RDP:
![image](https://user-images.githubusercontent.com/72375798/134158254-19808497-dae1-4645-af21-25db5ac3a8cf.png)

![image](https://user-images.githubusercontent.com/72375798/134158356-3bf42857-f09e-4c7d-98ab-1e452d005836.png)

We attempted to resolve instance type issue, however couldn't found AWS nitro system to create instance as suggested in warning.

Thanks
QAS

**Comment by jlind23** [comment]
@dikshachauhan-qasource @amolnater-qasource is this still a valid behaviour?
@AndersonQ maybe you work about the agent shutdown process may have solved this issue?

**Comment by AndersonQ** [comment]
@jlind23 I don't think so. I don't see the connection, the shutdown issue was about how the agent handles the shutdown of the process it's controlling, it should not interfere with the agent restarting after a reboot

**Comment by dikshachauhan-qasource** [comment]
Hi @jlind23 

We have attempted to validate this ticket on 8.1 BC3 build and found it working fine there.

**Observations:**
- Isolated agent with Endpoint security on windows server 2019 machine continues to be in Healthy state even after machine reboot.

- Validate with only system integration as well, and found it working fine.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/154971128-8d472bf9-5b58-45b9-8e6d-56c943d0221f.png)

![image](https://user-images.githubusercontent.com/72375798/154971200-1deb7d0d-2b7b-41c1-b1cd-6a06ef02779b.png)

![image](https://user-images.githubusercontent.com/72375798/154971297-00e94144-0dc3-4b91-a818-e1735a67e51c.png)

**Build details:**
VERSION: 8.1.0-BC3
BUILD: 50346
COMMIT: 0335dd6a26ef29ae9021d0fae9347dc88f3b7d6e
ARTIFACT LINK: https://staging.elastic.co/8.1.0-bee672a6/summary-8.1.0.html

We don't have permissions for GCP, so we used a VM from VSphere. Please let us know if you want more testing on this.

Thanks
QAS

**Comment by ph** [comment]
@AndersonQ and I are looking at similar issues, if you see other situation like this one let us know.
