### ISSUE TITLE
Endpoint fix from pull request 27024 not working in 7.14.1 docker image 

### ISSUE THREAD

**Issue by asazallesmilner** [elastic/beats#28108]
Hi @kaiyan-sheng, 

We are still seeing the same error in the 7.14.1 docker container.  
Logs and configs are exactly identical to the previously provided ones. 

What can we do to figure out why this is still going on that?
These are the logs from the previous issue, as we see no difference than the logs today.
it is still doing  Post "https://cloudwatchlogs.<REGION>.sc2s.sgov.gov/": dial tcp: lookup cloudwatchlogs.<REGION>.sc2s.sgov.gov on 10.X.X.X:53: no such host

rather than what it should be 
logs.<REGION>.sc2s.sgov.gov

Thank you. 

Previous issue.
https://github.com/elastic/beats/issues/27262
[rds-filebeat_logs_2021-08-16_cleansed.txt](https://github.com/elastic/beats/files/7220970/rds-filebeat_logs_2021-08-16_cleansed.txt)

**Comment by kaiyan-sheng** [comment]
Hi @asazallesmilner, sorry I was looking for the problem in a wrong direction... Turned out it's because we are actually overwriting the endpoint config again later on in the code. Here is the fix for this problem: https://github.com/elastic/beats/pull/28170. Sorry again for the delay and inconvenience. Totally my mistake! The fix will be merged and released for 7.15.1 and 7.16.0.
