### ISSUE TITLE
Filebeat systemctl process not producing logs to /var/log/filebeat.  Issue with --environment systemd

### ISSUE THREAD

**Issue by dagutten** [elastic/beats#28119]
Hi,

Systemctl is not producing any logs at /var/log/filebeat.  The "-e" flag is not visible in my filebeat.service at shown below:

`[Unit]
Description=Filebeat sends log files to Logstash or directly to Elasticsearch.
Documentation=https://www.elastic.co/beats/filebeat
Wants=network-online.target
After=network-online.target

[Service]

Environment="GODEBUG='madvdontneed=1'"
Environment="BEAT_LOG_OPTS="
Environment="BEAT_CONFIG_OPTS=-c /etc/filebeat/filebeat.yml"
Environment="BEAT_PATH_OPTS=--path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat"
ExecStart=/usr/share/filebeat/bin/filebeat --environment systemd $BEAT_LOG_OPTS $BEAT_CONFIG_OPTS $BEAT_PATH_OPTS
Restart=always`

According to all the documentation that I read and all the similar issues I found, this issue seems to be focus on the "-e" flag. As you can see in the example above, I do not have the "-e" flag set at all. Instead, after doing a yum install, the systemctl service is including a --environment systemd flag.

After a quick test, I removed the "--environment systemd" flag as follows:

`[Unit]
Description=Filebeat sends log files to Logstash or directly to Elasticsearch.
Documentation=https://www.elastic.co/beats/filebeat
Wants=network-online.target
After=network-online.target

[Service]

Environment="GODEBUG='madvdontneed=1'"
Environment="BEAT_LOG_OPTS="
Environment="BEAT_CONFIG_OPTS=-c /etc/filebeat/filebeat.yml"
Environment="BEAT_PATH_OPTS=--path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat"
ExecStart=/usr/share/filebeat/bin/filebeat $BEAT_LOG_OPTS $BEAT_CONFIG_OPTS $BEAT_PATH_OPTS
Restart=always`

After this change, I can see that the folder "/var/log/filebeat" is now available with the expected logs. 

I believe that this is not the expected behaviour of the "--environment" flag according to the flag explanation:

`      --environment environmentVar   set environment being ran in (default default)`

Is this the expected behaviour? What are the consequences of removing the "--environment" flag?

For confirmed bugs, please report:
- Version:  7.15.0-1
- Operating System:  redhat 8

**Comment by rdner** [comment]
Hello @dagutten,
First of all, I'm very sorry for the long reply.

> Is this the expected behaviour?

What you're describing here is expected behaviour for the `--environment systemd` parameter.

As you can see in the code here, we set logging output to `STDERR` for containers and `systemd` https://github.com/elastic/beats/blob/e208c22507890eb3633d55f1ba7d388f3076b2d6/libbeat/logp/core.go#L143-L150

It's a standard practice for services running in `systemd` to output logs in their console output, so users can access the logs using `journalctl` (in our case it's `journalctl --unit=filebeat`).

> What are the consequences of removing the "--environment" flag?

it should be completely safe to remove `--environment systemd` from your service file if you still prefer to have your logs in `/var/log/filebeat`. This parameter is used for logging configuration only and does not affect the filebeat functionality.

**Comment by rdner** [comment]
Closing it as it is standard behaviour. If this is something you would like to change, feel free to reopen the issue and continue the discussion, we will take care of prioritising it.
