### ISSUE TITLE
Feature request: Filebeat prospector configuration template

### ISSUE THREAD

**Issue by f-ld** [elastic/beats#2854]
We are heavily starting to use filebeat (to push to kafka) and we have a configuration with 100+ prospectors (100+ kafka topics)
For each prospector we repeat some parameters like encoding, ignore_older, scan_frequency, ...

We think filebeat would benefit of either:
- a way to change the default value for all prospectors (for example the default value of max_bytes is currently 10MB (10485760). If I want to set 20MB for all my prospectors, I have to copy past the parameter for each of them. This works for people having many prospectors of the same kind
- a way to define templates: when creating a propsector, we can import values from a template or another. This works for people having many prospectors of a few kinds
- a way to copy parameters from a previously defined prospector

For now, we use puppet to create our configuration file so we use a loop in our ERB file and this works fine. The only problem is that the deployed configuration file is quite long and can be reduced with one of the options above

PS: first published here -> https://discuss.elastic.co/t/suggestion-filebeat-prospector-configuration-template/62687

**Comment by ruflin** [comment]
@f-ld Thanks a lot for sharing all the details and pointing out the various options. I assigned the filebeat and libbeat label as if we think about this, we probably would want to have a generic solution that works for all beats. 

One thing of interest for me would be why you have that many different prospectors? Are these 100 different files from just one machine? Assuming you could use a "dynamic" field that is generated per event for your kafka topic selection, what that already be enough?

**Comment by f-ld** [comment]
@ruflin Yes, the generic solution makes perfectly sense

About the high number of propsectors: we have a microservice architecture with roughtly 50+ different services (multiple instances of each, multiple datacenter, so 200+ services running). Each service has from 2 to 6-7 different log files (first one is http access logs of the service, next is error log. Then we have some "event" logs depending on the service).
And we are going forward service discovery with hashicorp consul, allowing any application to be deployed anywhere (so no static pre-defined set of hosts for one application), meaning we want to deploy the same filebeat configuration on each single host just in case we deploy service X on that host.
So we end up with 50+ prospectors for http access logs, 50+ access logs for errors, etc. and a parameter change for one is likely required for the 49+ others (as pointed, today, puppet is handling it for us). And we are grouping in the same kafka topic logs for the various instances of a same service, but we want to avoid mixing logs of service A with logs of service B, C, D ... even if the beat metadata would allow a kafka consumer to filter them. Just to keep topics not too big and avoid useless network traffic when one consumer is only interested by logs from 1 of the 50+ services.

**Comment by ruflin** [comment]
I assume your setup is having one filebeat container that reads the logs from the docker host which are written from all other container. The number of prospectors makes a lot of sense in this context.

**Comment by f-ld** [comment]
Not using docker since we are using java apps (and JVM are already some kind of containerization).
But yes, many JVM on a host and one filebeat instance per host.

**Comment by friesoft** [comment]
Any news regarding templates for prospectors? :)

**Comment by ruflin** [comment]
No real news on the template side. One new thing which could help in this context is prospector reloading. So instead of shipping filebeat with all the defined prospectors in advance, generate the config files when new services are around. This needs an external script which is aware of the changes happening in the environment and knows how to generate the config files. But this only solves the problem of all config options already shipped and does not help with the templates.

**Comment by mitch-seymour** [comment]
@ruflin Regarding something you said in this comment:

> Assuming you could use a "dynamic" field that is generated per event for your kafka topic selection

Is this currently possible? I know this isn't directly related to templates, but since it was mentioned in this thread, I just wanted to clarify. What I'm trying to do is demonstrated in the following example. Given this message:

`{"fruit": "banana", "color": "yellow"}`

set a dynamic field like:

```
    prospectors:
        fields:
          my_dynamic_field: "%{fruit}"
```

Anyways, I just stumbled upon this thread and your comment made me wonder about this (it would actually solve a problem I've been stuck on for a couple of days).

**Comment by ruflin** [comment]
@mitch-seymour What you have above I never tried if it would work. I don't think we have the field formatter enabled for fields. If it would be even possible depends on our internal processing order which I would have to check. But I don't see how it would be helpful to put an existing field also under `fields`? Field formatter are mainly thought of being used in the output so you could use `fruit` as your Kafka topic for example: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-type.html#_format_string_sprintf

**Comment by mitch-seymour** [comment]
@ruflin thanks for your response. yeah it ended up not working, and it turns out I was able to accomplish what wanted (setting a dynamic kafka key) by putting the field in the Filebeat instance config as `%%{}{[fruit]}`, instead trying to do that in prospector config (as seen above). But you're right, I don't think it really made sense to try to set an existing field under `fields`. Anyways, sorry for the confusion, but thanks for following up!

**Comment by yodog** [comment]
@f-ld @ruflin 

would yaml anchors and aliases work?

something like

    filebeat.config.modules:
      path           : ${path.config}/modules.d/*.yml
      reload.enabled : &re true
      reload.period  : &rp 1h

and then later on

    another.setting
      aaa : *re
      bbb : *rp
