### ISSUE TITLE
Filebeat import dashboards returns internal server error

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#28773]
For confirmed bugs, please report:

Version: main
Operating System: Linux
Steps to Reproduce:
./filebeat setup

```
10:54:30 Exiting: Failed to import dashboard: Failed to load directory /home/vagrant/filebeat-8.0.0-SNAPSHOT-linux-x86_64/kibana/7:
10:54:30   error loading /home/vagrant/filebeat-8.0.0-SNAPSHOT-linux-x86_64/kibana/7/dashboard/Filebeat-cyberarkpas-audit.json: error dashboard asset: returned 500 to import file: An internal server error occurred.: <nil>. Response: {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."}
10:54:30 
```

**Comment by kvch** [comment]
I am cross posting if from Slack. We save dashboards in this JSON format to make reviewing easier for module developers. The dashboard object goes through several transformation before it is loaded to Kibana. LayerListJSON is transformed to string in this code: https://github.com/elastic/beats/blob/master/libbeat/dashboards/modify_json.go#L389-L418 since https://github.com/elastic/beats/pull/28530

I still not believe that it is a Beats issue. Prevously, if a dashboard was not formatted correctly, Kibana responded with exact error messages where the formatting has to be changed. In this case we do not receive any errors on Beats side.

**Comment by pgayvallet** [comment]
> I still not believe that it is a Beats issue

I will have to agree with @nreese on this one. The error from https://github.com/elastic/beats/issues/28773#issuecomment-957962303 is rather explicit, the migration tries to parse `attributes.layerListJSON` and fails because of invalid JSON.

```
[2021-11-02T17:14:58.914+00:00][ERROR][http] Error: Migration function for version 8.0.0 threw an error
```

```
Caused by:
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at setEmsTmsDefaultModes (/usr/share/kibana/x-pack/plugins/maps/common/migrations/set_ems_tms_default_modes.js:28:26)
```

> Prevously, if a dashboard was not formatted correctly, Kibana responded with exact error messages where the formatting has to be changed

Hum, I'm surprised, as we (unfortunately) never had such kind of advanced validation for imports, even with the legacy import that was using `create` instead of `import`. Do you have an example of such exact error message?

**Comment by rudolf** [comment]
Is it possible to get the NDJSON payload that beats sends to the Kibana saved objects import API? We can use that to decide if the payload is well formatted or not. 

I would also add that just because an import worked in a previous version doesn't mean that the payload was correct, it could be that the map was imported but that the maps app was unable to use the layer metadata (just speculating because I'm not familiar with the internals of the maps app).

**Comment by kvch** [comment]
> > I still not believe that it is a Beats issue
> 
> I will have to agree with @nreese on this one. The error from [#28773 (comment)](https://github.com/elastic/beats/issues/28773#issuecomment-957962303) seems rather explicit, the migration tries to parse `attributes.layerListJSON` and fails because of invalid JSON.
> ```
> [2021-11-02T17:14:58.914+00:00][ERROR][http] Error: Migration function for version 8.0.0 threw an error
> ```
> 
> ```
> Caused by:
> SyntaxError: Unexpected token o in JSON at position 1
>     at JSON.parse (<anonymous>)
>     at setEmsTmsDefaultModes (/usr/share/kibana/x-pack/plugins/maps/common/migrations/set_ems_tms_default_modes.js:28:26)
> ```

Where is this error referring to the attribute?

> > Prevously, if a dashboard was not formatted correctly, Kibana responded with exact error messages where the formatting has to be changed
> 
> Hum, I'm surprised, as we (unfortunately) never had such kind of advanced validation for imports, even with the legacy dashboard import that was using `create` instead of `import`. Do you have an example of such exact error message?

The error can be found here: https://github.com/elastic/beats/issues/27988
It was reported a few weeks ago that `layerListJSON` should be a string and I fixed it in https://github.com/elastic/beats/pull/28530

**Comment by kvch** [comment]
@rudolf I will get more detailed logs for you in a few hours. Thanks!

**Comment by pgayvallet** [comment]
> Where is this error referring to the attribute?

In the source code associated to the `setEmsTmsDefaultModes` failing migration:

https://github.com/elastic/kibana/blob/3b3c4b2f4a8fc120b2f9fc35c8945f59042079d0/x-pack/plugins/maps/common/migrations/set_ems_tms_default_modes.ts#L16-L25

**Comment by kvch** [comment]
These are the logs I get: https://gist.github.com/kvch/dcef6cc6be4c0e8b262d5769f9a0df50
I will look into it once more when I get back. Thanks.

**Comment by kvch** [comment]
Ok, that was the wrong output.

But I have checked it locally, and it seems it's indeed a Beats issue. Thank you for pointing me in the right direction.

**Comment by liza-mae** [comment]
Thanks @kvch for #28787 PR, should this be back-ported to 8.0 branch?

**Comment by andresrc** [comment]
Backport to 8.0: https://github.com/elastic/beats/pull/28796

**Comment by kvch** [comment]
The backport is merged.
