### ISSUE TITLE
[Discuss] Clean up of old branches in Beats CI

### ISSUE THREAD

**Issue by cachedout** [elastic/beats#28867]
Hello!

Currently, the Beats CI contains a number of branch tests.
<img width="487" alt="Screen Shot 2021-11-08 at 10 49 23 AM" src="https://user-images.githubusercontent.com/111616/140720288-84355b1e-0799-4fb5-ad04-15b20f420579.png">

Because we gather these dynamically by examining all the branches on the repo, we have already [instituted a filter to limit the number of branches that we test](https://github.com/elastic/beats/blob/master/.ci/jobs/beats.yml#L20).

For both the sake of tidiness, and to reduce the complexity and noise in the Beats CI, I would like to start a discussion about further filtering the branches to only what's truly needed.

Could we go so far as to limit branch testing to just the following?

* 8.0
* 7.x
* most recent minor

Doing so would eliminate the following:

* 6.8
* 7.10
* 7.11
* 7.12
* 7.13
* 7.14
* 7.15
* 7.16
* 7.7
* 7.8
* 7.9

Thoughts?

**Comment by jlind23** [comment]
Seems to be good. 
Here 7.X stands for what?

**Comment by cachedout** [comment]
> Here 7.X stands for what?

That is a good question. In [the branch scan log](https://beats-ci.elastic.co/job/Beats/job/beats/indexing/consoleFull), we have this entry

<img width="698" alt="Screen Shot 2021-11-08 at 11 20 02 AM" src="https://user-images.githubusercontent.com/111616/140724915-d732e0b0-2d2a-45d0-8478-b3396a24d1f6.png">

Perhaps it was created and then removed? I'll defer to @v1v or @kuisathaverat who might know exactly why Jenkins emits that particular message when it scans MBPs.

**Comment by v1v** [comment]
> Thoughts?

+1!

> who might know exactly why Jenkins emits that particular message when it scans MBPs.

A bit of context, the Jenkins Multibranch Pipeline provides these feature but we have disabled it otherwise it will scan for all the branches, this caused some issues in terms of the API quota back in the days.

https://github.com/elastic/beats/pull/19588 was the PR that removed it. 

IIUC, the message means that the existing cached commit in the MBP differs from the commit in that particular branch. I assume, this is related to the above regarding the `periodic-folder-trigger` option that has been disabled.

> periodic-folder-trigger (str): How often to scan for new branches or pull/change requests. Valid values: 1m, 2m, 5m, 10m, 15m, 20m, 25m, 30m, 1h, 2h, 4h, 8h, 12h, 1d, 2d, 1w, 2w, 4w. (default none)

See https://docs.openstack.org/infra/jenkins-job-builder/project_workflow_multibranch.html

For the record, we were forced to do so since the service account was used in different places and unfortunately, we don't manage those accounts but consume them.
