### ISSUE TITLE
New dataset to support Threat Intelligence from Palo Alto Networks MineMeld / Autofocus hosted MineMeld

### ISSUE THREAD

**Issue by colin-stubbs** [elastic/beats#28953]
Palo Alto Networks MineMeld is widely used for threat intelligence publishing.

A new dataset for the existing threatintel module is required to pull TI from a MineMeld feed on a regular basis.

I will issue a pull request from a fork containing code/config to support this.

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

**Comment by jamiehynds** [comment]
Hi @colin-stubbs - thanks for creating this issue, and the other new module issues. For any new integrations, we're focused on Elastic Agent integrations. If you're about to begin development on modules such as MineMeld, Nessus, etc - would you mind working on agent integrations rather than Beats modules? If so, I can move your issues to the [integrations repo](https://github.com/elastic/integrations/issues).

**Comment by colin-stubbs** [comment]
Hi Jamie,

Oh goody, yet another way to do this.

We've avoided the agent thus far, as while the concept is sound, the implementation so far has been lacking.

We'll stick with our filebeat modules for the time being.

**Comment by jamiehynds** [comment]
Thanks for the insight @colin-stubbs. I'd love to dig into where you feel the agent implementation is lacking and what's blocking you from moving towards agent - I'll ping you on Slack to discuss if you don't mind. I'm sure our PM for Elastic Agent would be interested in getting your feedback too //cc @nimarezainia
