### ISSUE TITLE
Align kubernetes module configuration

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#29132]
**Describe the enhancement:**

`Host`:
Metricbeat kubernetes module configuration use `host` in configuration, though in autodiscover k8s provider it was deprecated and renamed to `node`. 
In `add_kubernetes_metadata` processor is used `host`.

We should decide what we want to use and align configuration

`Scope`:
in k8s module is used a bool parameter that passed to 

`Namespace`:
add `namespace` configuration https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/util/kubernetes.go#L50-L57

**Describe a specific use case for the enhancement or feature:**

**Comment by ChrsMark** [comment]
@tetianakravchenko after looking into this I have some concerns. 
I'm +1 for fixing the node/host setting and remove the deprecated one.
For `scope` though I don't think there is any reason to expose it as setting in k8s module since the scope is set explicitly for each metricset by us. Did you think anything differently when you dealt with it?
Also I have mixed feelings about introducing the `namespace` setting in k8s module since this would mean that some events would be enriched by metadata while others not. However we do sth similar in `add_kubernetes_metadata` maybe this is handy for users having limited permissions to avoid having errors if the namespace is not set and there are no permissions to access all namespaces. So I would lean more to add this setting.

@tetianakravchenko let me know what you think here.

**Comment by tetianakravchenko** [comment]
>  For `scope` though I don't think there is any reason to expose it as setting in k8s module since the scope is set explicitly for each metricset by us. Did you think anything differently when you dealt with it?

I think the main reason why I wrote it was that scope is passed as a bool values to the `NewResourceMetadataEnricher` https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/pod/pod.go#L81, this approach is different from the one used for autodiscover or [processors](https://github.com/elastic/beats/blob/master/libbeat/processors/add_kubernetes_metadata/config.go#L33). I thought that those are the same things and likely that users would expect the same behaviour for those different components, but I think I understood your point, that there is no reason for that if we know exact list of metricsets. Sorry for confusion.

 > Also I have mixed feelings about introducing the namespace setting in k8s module since this would mean that some events would be enriched by metadata while others not. However we do sth similar in add_kubernetes_metadata maybe this is handy for users having limited permissions to avoid having errors if the namespace is not set and there are no permissions to access all namespaces.

We already provide this setting for autodiscovery:
[doc](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html):
```
 namespace
    (Optional) Select the namespace from which to collect the metadata. If it is not set, the processor collects metadata from all namespaces. It is unset by default. The namespace configuration only applies to kubernetes resources that are namespace scoped. 
```
the same for `add_kubernetes_metadata`. I thought it is smth we would want to keep aligned.

**Comment by ChrsMark** [comment]
Thanks for clarifying @tetianakravchenko . I pushed a PR for these: https://github.com/elastic/beats/pull/29908
