### ISSUE TITLE
docs: clarify kafka output config and version compatibility

### ISSUE THREAD

**Issue by axw** [elastic/beats#29310]
Caveat: I'm not a Kafka expert. Things I say below may be wrong -- debate welcome. I'm opening this issue in response to https://discuss.elastic.co/t/apm-server-exits-if-kafka-output-is-higher-than-version-2-0/290573

---

Kafka brokers support old client versions. The [Apache Kafka docs](https://kafka.apache.org/protocol.html#protocol_compatibility) say:

> The server will reject requests with a version it does not support, and will always respond to the client with exactly the protocol format it expects based on the version it included in its request.

But then our [docs for the libbeat Kafka output](https://www.elastic.co/guide/en/beats/filebeat/current/kafka-output.html#kafka-compatibility) specify a more restrictive range:

> This output works with all Kafka versions in between 0.11 and 2.2.2. Older versions might work as well, but are not supported.

Why do we specify an upper bound? If it is a matter of which versions we test, can we be more explicit about that rather than implying that the output does not work with newer versions?

Further down in the docs, there is [configuration for the Kafka version](https://www.elastic.co/guide/en/beats/filebeat/current/kafka-output.html#_version_3). Description:

> **version**
>
> Kafka version filebeat is assumed to run against. Defaults to 1.0.0.
>
> Event timestamps will be added, if version 0.10.0.0+ is enabled.
>
> Valid values are all kafka releases in between 0.8.2.0 and 2.0.0.

First, the upper limit on this is wrong. In 7.15.0 the actual upper limit is 2.2: https://github.com/elastic/beats/blob/b35df73b3c6ac243fe37b3d2174e61c671c3fe2f/libbeat/common/kafka/version.go#L81

It seems unhelpful to users to specify the "Kafka version filebeat is assumed to run against" -- this suggests that users need to keep the config in sync with their Kafka broker. I think `version` should rather be stated to indicate the _minimum_ broker version for the purpose of feature support.

We state that for versions 0.10.0.0+ we add timestamps. What other features might the output use that require newer versions? Ideally we would list those out, so users know which minimum version to specify.

**Comment by faec** [comment]
This could definitely use more clarity, and the documentation skew has gotten worse than I'd realized. Here is a brain dump of relevant context :-)

First, some of the language comes from our Kafka support library, Sarama. Here is its relevant configuration field:
```golang
	// The version of Kafka that Sarama will assume it is running against.
	// Defaults to the oldest supported stable version. Since Kafka provides
	// backwards-compatibility, setting it to a version older than you have
	// will not break anything, although it may prevent you from using the
	// latest features. Setting it to a version greater than you are actually
	// running may lead to random breakage.
	Version KafkaVersion
```

but this language seems not very friendly to end-users. The output documentation makes some useful distinction (it says it "can connect to" Kafka up to 2.8, versus the narrower range for the `version` field), but:

- Like you point out, the upper bound doesn't make much sense here; we should probably say "can connect to" versions 0.11 and up. (I thought we also allow at least 0.10? That looks like a discrepancy in the docs, I will need to check to confirm.)
- The listed range for the explicit `version` field is out of date (it currently accepts up to 2.6). Its description should probably say something more like "The version of the Kafka protocol to use. The Kafka broker must be the configured version or later."

There's also skew between the input and output documentation even where they should be the same; the input should probably also be changed to use language "can connect to version 0.11 and higher", and its `version` field updated similarly to above.

Historically I think we've based the upper bound in our documentation on the latest version officially supported by Sarama, but considering our different context this is probably not the most helpful information to emphasize (it is nice to know when troubleshooting but our end users should not care since it doesn't represent the boundaries of our real product support.)

I believe (from memory, I can confirm in more detail) that the timestamp is the only version-specific information that is added unconditionally. Some version-specific features can be enabled implicitly when supported by setting configuration flags that affect the relevant behavior, but I think the timestamp was a uniquely useful addition to very early versions of the protocol -- our overall approach isn't so much "enrich the data on new versions that support fancy features" as "we always want timestamps but extremely old versions have a quirk where they aren't supported."

**Comment by nimarezainia** [comment]
@faec thanks for the detail above - what are the final changes that need to be considered?

**Comment by rdner** [comment]
we had a related issue for the external contributor a while ago https://github.com/elastic/beats/issues/30937

**Comment by faec** [comment]
Condensing the previous comment, I think these changes should resolve the issue:

- change "works with all Kafka versions in between 0.11 and 2.2.2" to "can connect to Kafka version 0.8.2.0 and up"
- change "Valid values are all kafka releases in between 0.8.2.0 and 2.0.0." to "...and 2.6"
- change "Kafka version filebeat is assumed to run against." to "Kafka protocol version filebeat will request when connecting"
- update the input documentation to include the same changes
