### ISSUE TITLE
[Spike] [Heartbeat] Explore implementing `timeout` for browser monitors

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/beats#29454]
Heartbeat exposes a `timeout` field for monitor types. However, `browser` monitors do not currently support `timeout` and the value is ignored

We should consider implementing `timeout` for browser monitors, and the side-effects of doing so. In particular, we will need to determine how this logic ought to behave for both inline and zip URL monitors.

**Comment by andrewvc** [comment]
Building this correctly for inline monitors is pretty straightforward, it's a bit more complex for suites.

I propose the following:

1. We parallelize all suite jobs, to run all journeys simultaneously
2. We stagger the jobs by consistently hashing their journey names to run at offsets to prevent them all running at the same time, thus spreading them out over their test interval. This prevents the problem we currently have, where serially executed journeys can delay the start of one after (head of line blocking).
3. We add the timeout value to these individual jobs
4. After each job we send a new suite status doc per https://github.com/elastic/beats/issues/27924#issuecomment-992861432, rather than waiting till the end of the run, the suite statuses are updated once per journey completion

**Comment by vigneshshanmugam** [comment]
All of this states we need ahead of time compilation for the HB especially for suites, haven't thought about how we would do this.

**Comment by emilioalvap** [comment]
@dominiqueclarke @andrewvc with zip url and suites being deprecated, is this still a requirement?
We already have issues for timeouts to be supported at project level

**Comment by paulb-elastic** [comment]
Captured in https://github.com/elastic/synthetics/issues/133, closing
