### ISSUE TITLE
Replace logfile input with filestream in elastic agent's standalone Kubernetes manifest

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/beats#29565]
In [elastic-agent-standalone-kubernetes.yaml](https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L217) we suggest `logfile` input for collecting container logs.
We should replace it with [Filestream](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-filestream.html)  type which brings [many improvements](https://www.elastic.co/blog/read-active-log-files-more-quickly-and-easily-with-the-new-filestream-input-in-filebeat?ultron). 

With filestream input CRI parsing is also supported by default with the use of [container parser ](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_container)

This has already be done in container-logs integration with  this [PR](https://github.com/elastic/integrations/pull/2139)

**Comment by kaiyan-sheng** [comment]
There are a lot of other integrations using logfile input instead of filestream. Should we create a meta issue to replace them all?

**Comment by ChrsMark** [comment]
@kaiyan-sheng we did it for Pod's logs as it is described in the issue's description. mainly because we see many benefits in adopting the new input so as to resolve pain points we have in k8s usecases. So I guess it's up to the maintainers' of each package/integration to evaluate replacing logfile with filestream.
