### ISSUE TITLE
Filebeat index template no longer working

### ISSUE THREAD

**Issue by Fabian1976** [elastic/beats#29574]
- Version: 7.16.2
- Operating System: Red Hat Enterprise Linux Server release 7.9
 
Because of the log4j problems, we upgraded to 7.16.2. We use puppet to manage Elasticsearch and it's index templates. So according to [this manual](https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-template.html), we do these steps to extract the index template for filebeat:
```
filebeat export template > filebeat-7.16.2.json
```
Place it in out puppet module and run the code.

We get this error message after trying to import the exported template:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "unknown key [priority] in the template "
      }
    ],
    "type" : "parse_exception",
    "reason" : "unknown key [priority] in the template "
  },
  "status" : 400
}
```

Manually trying to import the exported template (as per the instructions in the same manual) with this command:
```
curl -XPUT -H 'Content-Type: application/json' http://localhost:9200/_template/filebeat?pretty -d@filebeat-7.16.2.json
```
Also produces the same error.

When we try removing the `priority` key from the JSON and run the curl command again, the import runs succesfully, but the index template is empty in Elasticsearch.

The same steps worked fine with release 7.12.1 (our previous version).

Another thing i noticed. When importing the index template with this command:
```
filebeat setup --index-management -E 'output.elasticsearch.hosts=["127.0.0.1:9200"]' -E 'output.kafka=nil'
```
There is an index template being made, but by the new "composable" index template standard.
Is that maybe the problem with manually trying to manage the index template? Is the backwards compatibility broken? (not semver)

**Comment by darootler** [comment]
I am having the same issue.

Regards
Richard

**Comment by kvch** [comment]
Unfortunately, it is a breaking change we had to introduce in 7.16 to ease the transition to 8.0. If you are using the template from older versions, you have to set `setup.template.type` to `legacy` as the documentation page you refer to says:

> If your template is still in the legacy format, please set setup.template.type to legacy. Please, convert your index template to the composable format, because in the future support for legacy templates is going to be removed.

Ref: https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-7.16.0.html#_breaking_changes

**Comment by Fabian1976** [comment]
So "easing" to a new version, is breaking the old one? How is that "easing" in to something. Have you ever heard of [semver](https://semver.org/)? I've had multiple occasions now that a minor bump resulted in breaking changes.

**Comment by kvch** [comment]
@Fabian1976 I am so sorry, but I misunderstood your issue in the first place. The breaking change I have described in my first comment is unrelated and does not have an impact on anyone.

The problem you are facing is due to outdated documentation. I have opened a PR to fix that: https://github.com/elastic/beats/pull/29869
The change is basically that now Beats export composable templates. But in the documentation, we still had the endpoint for legacy templates. If you use the new endpoint, you get the same experience, and should not see any break in the existing behaviour.

Also, for the sake of avoiding future confusion the breaking change, we introduced that by default Beats are loading composable template if one chooses to go with the default template or simply adds new fields to our default. In this sense, the breaking change is invisible. For more advanced users, who load their own JSON template using `./filebeat setup` we default to the old legacy index template, so we do not break existing custom index template loading.
