### ISSUE TITLE
[Question] Metricbeat Gcp module should keep the original labels of metrics

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#29573]
## 1.  The problem

When I use metricbeat to collecte instance metrics, I find that there is no `instance_name` label in  `labels.metrics`.  That is different from  google monitoring docs and  make me confused.

*  gcp compute metrics

 https://cloud.google.com/monitoring/api/metrics_gcp#gcp-compute

![image](https://user-images.githubusercontent.com/12824991/147074451-94a7eee1-051e-4a8b-9cb9-44804f04b4de.png)

*  metricbeat event

![image](https://user-images.githubusercontent.com/12824991/147074523-20be4f25-4369-4444-8dbf-b72961df46b3.png)

## 2. The reason

There is a filter logic in compute labels field. 

https://github.com/elastic/beats/blob/76bf18b0c2be4c8adf1f2a0f9168aadcd04e8593/x-pack/metricbeat/module/gcp/timeseries_metadata_collector.go#L80-L89

## 3. Suggestion

 `cloud.intance.name`  is a common ecs filed ,  but  we should also keep original metric labels.  That would be more clear.

**Comment by kaiyan-sheng** [comment]
@kwinstonix Thanks for looking into this and I agree with you, we should keep the original `instance_name` label as well. WDYT @endorama @aspacca ?

**Comment by felix-lessoer** [comment]
Do you also plan to move the other ECS related fields into their ECS equivalent?
E.g. `gcp.labels.resource.container_name` could be `container.name`

Otherwise the Metrics view in Observabilty will not show the exported data from this module and customer has to also use Kubernetes integration to grab more data. But if the customer is doing so, the GCP module for GKE is not adding any value.

**Comment by felix-lessoer** [comment]
:+1

**Comment by kwinstonix** [comment]
@kaiyan-sheng ,  I opened a PR to fix this
