### ISSUE TITLE
[Filebeat] [Processors] Add Append Processor

### ISSUE THREAD

**Issue by mr1716** [elastic/beats#29934]
This adds an append processor to be able to append data to ECS values.

The use case for this specific enhancement is that the majority of filebeat modules already contain the append processor at least 1 time in the ECS Modules, and this would allow beat-side processing to occur rather than on the Elastic side. 
Team: Filebeat

**Comment by mr1716** [comment]
Team: Filebeat

**Comment by mr1716** [comment]
Team: <Filebeat>

**Comment by mr1716** [comment]
<Filebeat>

**Comment by mr1716** [comment]
The use case for this specific enhancement is that the majority of filebeat modules already contain the append processor at least 1 time in the ECS Modules, and this would allow beat-side processing to occur rather than on the Elastic side
Team: <Filebeat>

**Comment by mr1716** [comment]
label: filebeat

**Comment by mr1716** [comment]
label:filebeat

**Comment by mr1716** [comment]
Team:Filebeat

**Comment by mr1716** [comment]
@mtojek Thanks for adding a label. Would it also be worth adding the enhancement and Filebeat labels in addition to the existing label?

**Comment by mr1716** [comment]
Just for additional context, this is one of the more popular elastic processors seen in Filebeat Pipelines, so it will be great to get this ported into Filebeat. It is seen in 52 modules, out of 70 modules in Filebeat, which puts it at 74.285% of the modules.

**Comment by mr1716** [comment]
Hey, I wanted to ping on this to see if there could be some traction on this going forward

**Comment by nimarezainia** [comment]
@mr1716 are you experiencing performance issues and want to move this processing out to the beat? Just trying to understand the use case and what you are trying to achieve. thanks.

**Comment by mr1716** [comment]
@nimarezainia I would like to move this to the beat to make sure that it can handle the data properly and provide parity for my use case.

**Comment by nimarezainia** [comment]
@mr1716 could you explain the use case in a bit more detail? I'm curious why doing this at the Elastic side is not handling the data properly?

**Comment by mr1716** [comment]
@nimarezainia right now, if I wanted to append data to a field in filebeat, I would have to do this via script. I am trying to reduce the work that the backend does. Therefore, I would like to have more parity and help spread out the workload.

**Comment by BenB196** [comment]
I've been following this request and I think a good use case for append to is the setting of the [`*.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address) at the beats level. Today, unless I'm mistaken you can't easily add both the `*.domain` and `*.ip` values to the `*.address` field (I think it might be possible with a script processor, but that seems very clunky (and isn't officially documented)).

A good reason for why I'd want to do this type of thing at the beat level, rather than Logstash or Elasticsearch Ingest level, is a lot of times it isn't really needed, and all using those methods does is add additional complexity. If I can do 95% of what I need to do at the beats level, why add an additional "thing" to the process to do the last 5%, when it would be better to keep it at the beats level.

A point worth noting, is that the concept of `append` isn't really new to beats, the [DNS process](https://www.elastic.co/guide/en/beats/filebeat/current/processor-dns.html) already supports this under its `action` as the default value.

Another note, is that currently this is only being looked at if you're outputting to Elasticsearch or Logstash, but Beats have a variety of [support outputs](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-output.html), so being able to modify the data as needed to these other outputs would also provide value.

**Comment by UcanInfosec** [comment]
@nimarezainia ive also been watching this and would love this to get added. Any thoughts on when this could be added? Adding this would be extremely beneficial to our grater adoption of the tool

**Comment by mr1716** [comment]
Hey, I dont see the documentation for that here: https://www.elastic.co/guide/en/beats/filebeat/current/filtering-and-enhancing-data.html

**Comment by MohamedEHJ** [comment]
Is the append processor added only for libbeat? or for filebeat as well? if not, can we reopen the issue?
