### ISSUE TITLE
Where is functionbeat runtime golang version 1.15 ?

### ISSUE THREAD

**Issue by chipzzz** [elastic/beats#29950]
According to https://github.com/elastic/beats/pull/22495 the runtime golang version was updated to 1.15. That's not true

```
functionbeat-7.12.0-darwin-x86_64 % ./functionbeat export function pubsub |grep runtime
    runtime: go113
```

I also checked functionbeat-7.15.0 it's also not updated there.

**Comment by mtojek** [comment]
@chipzzz Could you please recheck with latest Beats release?

**Comment by jlind23** [comment]
@chipzzz having a look at https://github.com/elastic/beats/pull/22495 I see that it has been backported to 7.X branch last week by @kvch which means that it would be added to the latest 7.X version.
@kvch is my assumption correct?

**Comment by chipzzz** [comment]
@jlind23, so then it won't be available for functionbeat gcp use cases :(

**Comment by jlind23** [comment]
@chipzzz Unfortunately it won't be available you are right.

**Comment by chipzzz** [comment]
@jlind23, you can close this then but the real problem i'm having is this #29967 , was going to try Golang 1.15

**Comment by kvch** [comment]
Functionbeat GCP support is an odd-one-out regarding Go versions. All Beats, including Functionbeat manager is built using the Go version defined in `.go-version`. However, the deployed Cloud Function runs on Golang 1.13 because at the time of the release that was the newest Golang version Google Cloud Platform provided.
