### ISSUE TITLE
`make setup` in custom beat should always use a released version of beats

### ISSUE THREAD

**Issue by voigt** [elastic/beats#2997]
Hey Guys,

first of all: thank you very much for this great package. You made it a breeze to develop new beats!

However I just stumbled upon the following issue, when I wanted to test the installation process of my new beat:

```
➜  redditbeat git:(master) make setup
mkdir -p vendor/github.com/elastic/
cp -R /Users/cv/golang/src/github.com/elastic/beats vendor/github.com/elastic/
rm -rf vendor/github.com/elastic/beats/.git
make update
New python executable in /Users/cv/golang/src/github.com/voigt/redditbeat/build/python-env/bin/python
Installing setuptools, pip, wheel...done.
make[1]: *** No rule to make target `collect', needed by `update'.  Stop.
make: *** [setup] Error 2
```

This is because the collect target has been removed from `libbeat/scripts/Makefile` in `master`, but my custom beat (redditbeat) makefile, generated `X` days ago, does not contain the collector target.

So since `make setup` is copying dependencies form `$GOPATH/src/github/elastic/beats` to `./vendors` it will always be the version which has been checked out there (so mostly `master`, I guess).

I understand why this is happening. In this case I need to either update my custom-beat build files or `git checkout v5.0.0` in `$GOPATH/src/github/elastic/beats` before `make setup` is working. 

However, shouldn't `make setup` make sure, that generated beats always try to build with a released version (e.g. `v5.0.0`) of beats?

Thank you and keep up the great work!

Kind Regards,
Christoph

**Comment by ruflin** [comment]
The easiest solution to your problem is to introduce an empty collect target in your Makefile as you see here: https://github.com/elastic/beats/blob/master/generate/beat/%7B%7Bcookiecutter.beat%7D%7D/Makefile#L44 All newly generated beats should have that. So in general what you do above should just work.

The part I'm wondering now is if it could be that you picked an "intermediate" version where beats and the generator were out of sync. Or do you have an already existing beat and were running `make setup` for a second time?

About the version to tie it to. So far the generator uses the version that is checked out locally. So if it is 5.0.0, this version will be used and as beats is copied to the vendor directory, it will stay like this until someone wants to update. The current assumption is that if someone wants to develop a beat, he kind of knows which version of beats he has checked out locally (most of the time probably master). Happy to hear your thoughts here.

One thing we are definitively missing currently, is a proper changelog / migration guide for beats developers. Not all changes we do internally which do not affect a user but could affect a developer show up in the changelog :-(

**Comment by voigt** [comment]
Thank you so much for your fast response!

> The part I'm wondering now is if it could be that you picked an "intermediate" version where beats and the generator were out of sync. Or do you have an already existing beat and were running make setup for a second time?

When I setup my beat dev environment the make setup was pulling from master (which was on [91907b8be4db3cfb98f30eadfb9940783e1ba40e](https://github.com/elastic/beats/commit/)). Now that I will release my beat I wanted to make sure the install instructions do work in a "freash" environment. But they didn't since `make update` (from master, since I simulated a "fresh" environment) now expected `collect`.
When I started developing I was busy understanding the libbeat structure, I didn't care so much about the scaffolding and what libbeat version its checking out :)

> About the version to tie it to. So far the generator uses the version that is checked out locally. So if it is 5.0.0, this version will be used and as beats is copied to the vendor directory, it will stay like this until someone wants to update. The current assumption is that if someone wants to develop a beat, he kind of knows which version of beats he has checked out locally (most of the time probably master). Happy to hear your thoughts here.

I honestly want to challenge this assumption. If someone wants to develop a new beat he relies on libbeat as a library. I for one don't expect that commands coming from the official ([versioned!](https://www.elastic.co/guide/en/beats/libbeat/5.0/newbeat-getting-ready.html)) elastic tutorial will give me something which is under development. In this case I assumed, that master == last release.

However, I will probably add a glide.yaml to my beat. This way I want to make sure the user always works with a released version of libbeat (I mean: who promises, that `collect` doesn't change with the next commit? ;)).

> One thing we are definitively missing currently, is a proper changelog / migration guide for beats developers. Not all changes we do internally which do not affect a user but could affect a developer show up in the changelog :-(

I recognised that when I checked other community beats which vary heavily in used libbeat versions/work-states.

**Comment by ruflin** [comment]
Thanks for sharing your thoughts. We had in previous version of the beat generate a glide file included. This lead to other issues and created problems when people didn't want to use glide. But that was also with Golang 1.5 before vendor support as default. I'm hoping that somewhere in the future (1.9) we will get dependency support directly in Golang.

I definitively understand that you expected to get a "stable" version. At the time when the tutorial was created, 5.0 was not GA yet so the new generator was only available in master. As we now have a stable generator version, we should probably change that and make people check out the 5.0 branch or even a tag instead of master.
