### ISSUE TITLE
CPU continue 140% when beats not release deleted files and deleted files handles not release for months

### ISSUE THREAD

**Issue by lvgang5213** [elastic/beats#30099]
normal CPU is contine 1%，but when occurs filebeat not release deleted files, the CPU is always 140%，and the handle of the deleted files not release for months.

restart the filebeat process and deleted files released and CPU back to 1%.

**Comment by lvgang5213** [comment]
version filebeat-7.1.0

**Comment by lvgang5213** [comment]
Another, CPU continue 120% when filebeat can't connect to Kafka.

**Comment by ruflin** [comment]
To investigate this further, you need to share your filebeat config especially the close options. In addition, the logs would be useful. Most of the time this issue comes from Filebeat not able to send the events because of some issues in Logstash, Kafka, Elasticsearch.

Can you update to a more recent version of Filebeat? 7.1.0 is a pretty old version.
