### ISSUE TITLE
7.17.0 awk entrypoint broken

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#30435]
With the switch from CentOS to Ubuntu the https://github.com/elastic/beats/blob/main/dev-tools/packaging/templates/docker/docker-entrypoint.tmpl#L13 does not work as expected. This is because that Ubuntu uses `mawk` instead of `gawk`. This change results in the output of the `awk` to be incorrect.

For confirmed bugs, please report:
- Version: 7.17.0
- Operating System: Docker Container
- Discuss Forum URL:
- Steps to Reproduce: 

`docker run -it docker.elastic.co/beats/filebeat setup` does not actually run setup

**Comment by cdavid15** [comment]
Can we confirm this is actually fixed in heartbeat 7.17.1?

I can see it has been merged prior to the 7.17.1 release and it is on the release notes but the issue still exists as discussed on discuss:

https://discuss.elastic.co/t/heartbeat-subcommands-unable-to-run-on-7-17-x-and-8-0-x-docker-images/299630
