### ISSUE TITLE
Mismatch between documentation and `filebeat.full.yml` and missing settings

### ISSUE THREAD

**Issue by astefan** [elastic/beats#3062]
There could possibly be more inconsistencies in default valuess but these are the ones I spotted for Logstash output:

- `#loadbalance: true` inside `filebeat.full.yml` while the [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#loadbalance) mentions a default value of `false`
- missing defaults from `filebeat.full.yml`: `port`, `timeout`, `max_retries`, `bulk_max_size`

**Comment by dedemorton** [comment]
@monicasarbu This issue has been open for awhile. I'm concerned that it's being overlooked because it's labeled as doc.

The default for `loadbalance` in the referece.yml in `master` is `false`, which matches the docs, so it looks like the first problem is fixed (https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml#L784)

The following fields are still missing from the Logstash output in the reference.yml:

- `port` - has been deprecated, so maybe that's OK.
- `timeout`
- `max_retries`
- `bulk_max_size`

**Comment by dedemorton** [comment]
@urso This issue has been open for awhile. I'd like to get it closed, but TBH, I'm not sure how to proceed. The docs are correct now wrt the default values for these fields.

Do we want to update the reference.yml file to include:

- `port` - not sure since it was deprecated in 5.0. It is still in the docs (marked as deprecated in 5.0) and code. I assume we need to keep it in the docs until it's removed completely?
- `timeout` - any reason not to add this to the reference.yml?
- `max_retries` - not sure since Filebeat ignores this setting...maybe it's better not to include it in the reference.yml?
- `bulk_max_size` - I seem to recall something about how this setting is different depending on the Beat. Do we want to add this to the reference.yml?

If we aren't going to update the reference files, then we should close this since the defaults are now correct.

**Comment by urso** [comment]
+1 on adding missing settings with defaults to the reference.yml. Deprecates settings should be marked as deprecated, but included. `reference.yml` is supposed to be the reference containing all settings.

**Comment by dedemorton** [comment]
@urso `port` was marked as deprecated in the docs here: https://github.com/elastic/beats/commit/f241d74ce1d66da6edd330a3d0d95cc73dbd8c84

**Comment by urso** [comment]
ohhhh.... it was even me who marked at as deprectaded 🤔  Setting was deprecated in 5.0. We might remove it for 7.0, or undeprecate it. Will need to discuss the future of the `port` setting. I will create followup issue (for code and docs). But for now (6.x release cycle), we should have it included in our reference docs and reference.yml files.

**Comment by urso** [comment]
@dedemorton ports followup issue: #7881
