### ISSUE TITLE
Internal Collection Monitoring uses previous Version number

### ISSUE THREAD

**Issue by mag-mkorn** [elastic/beats#30648]
When using internal collection for monitoring with beats in version 8 the data is written to indices with version 7 in name: `.monitoring-beats-7-2022.03.02`.

Example event:
```
{
  "_index": ".monitoring-beats-7-2022.03.02",
  "_id": "EKafS38BAySwzwLtFatX",
  "_version": 1,
  "_score": 1,
  "_source": {
    "timestamp": "2022-03-02T17:13:11.250Z",
    "type": "beats_stats",
    "beats_stats": {
      "beat": {
        "version": "8.0.1",
        "name": "es1",
        "host": "es1",
        "uuid": "53c8c63a-a2c9-42f4-ae37-963e590d2068",
        "type": "filebeat"
      },
      "metrics": {...},
      "timestamp": "2022-03-02T17:13:11.250Z"
    },
    "interval_ms": 10000,
    "cluster_uuid": "ebnslkIISm6-jo3LjXM9sQ"
  },
  "fields": {...}
}
```

I would expect the current version number to be used in the index name.

**Comment by jsoriano** [comment]
Hey @mag-mkorn, could you share the configuration you are using? This number is hard-coded in the code, here:
https://github.com/elastic/beats/blob/6e9dd49b5da9c045125078bb95be9f0dc27e8263/metricbeat/helper/elastic/elastic.go#L82

So I wonder where this could come from.

cc @elastic/stack-monitoring in case they know where this can come from.

**Comment by matschaffer** [comment]
While confusing, this is intentional. The "7" is a schema version, not the stack version.

If you launch a 5 series stack, you'll see that the internal collection schema version was actually 6. :)

Internal collection document structure is schema 7, metricbeat document structure (as of latest release) is schema 8.

@jasonrhodes @jbaiera perhaps we _should_ have jumped to 11 ;)

Anyway, closing this out as expected behavior.
