### ISSUE TITLE
import_dashboards adds extra slash on ES endpoint

### ISSUE THREAD

**Issue by henrikno** [elastic/beats#3097]
If you run import_dashboards and add an ending slash to ES url, it appends an extra / so the url becomes is `http://elasticsearch:9200//.kibana`, etc.

E.g.
```
scripts/import_dashboards -es http://elasticsearch:9200/ -user elastic -pass hi -only-dashboards
```
This causes trouble depending on how strict URL parsing it goes through.

- Version: 5.0.2
- Operating System: OSX

**Comment by maddin2016** [comment]
@henrikno, it doesn't append an extra `/`. This is the slash you append. [Here](https://github.com/elastic/beats/blob/master/libbeat/dashboards/import_dashboards.go#L382) it builds the path. An option would be to build the client url from scheme and host [here](https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/client.go#L117) instead of only from the string passed as a param. instead of `s.URL = u.String()` this `s.URL = u.Scheme + "://" + u.Host`. @andrewkroh, @ruflin what do you think?

**Comment by ycombinator** [comment]
Hi @henrikno, the `sciprt/import_dashboards` has now been replaced with the `setup --dashboards` sub command, e.g. `filebeat setup --dashboards`. And 5.x of Beats is now past its EOL. So I'm closing this issue. If you see a similar issue with the new subcommand, please open a new issue about it. Thanks!
