### ISSUE TITLE
[Azure] switch to cost management API for forecast data

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/beats#32033]
This issue concerns the Azure billing integration. This integration collects data about real-time billing costs as well as forecasted costs.

We need to switch from using the [Consumption](https://docs.microsoft.com/en-us/rest/api/consumption/) to the [Cost Management](https://docs.microsoft.com/en-us/rest/api/cost-management/) APIs for collecting forecast data. For the details on why, see below, but TL;DR is that Microsoft have removed the endpoints we are using from the Consumption APIs group, so if we want to use up-to-date API versions, we need to use the new APIs.

---

We currently [use](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/azure/billing/client.go) version `2019-10-01` of the Consumption APIs to collect all our billing data.

In the [OpenAPI spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-10-01/consumption.json) for this version of the API, there is a deprecation warning for forecast operations - `Please note that this API is no longer actively under development. We recommend using our new Forecast API moving forward: https://docs.microsoft.com/en-us/rest/api/cost-management/forecast/usage.`. In the latest version of the spec (`2021-10-01`) the forecast API is removed entirely.

It's confusing because in the [latest docs](https://docs.microsoft.com/en-us/rest/api/consumption/), the forecasts 'operation group' is still listed in the table, but note that if you click it, it doesn't go anywhere.

**Comment by zmoog** [comment]
Maybe we can add an extra “why” for the upgrade: the [new Forecast API from the Cost Management](https://docs.microsoft.com/en-us/rest/api/cost-management/forecast/usage) also supports scope, while the [old one from Consumption](https://docs.microsoft.com/en-us/rest/api/consumption/) doesn’t.

Scope (subscription/department/billing account/etc.) support is essential because Usage Details supports it. If the user configures a different scope on the integration right now, it will apply to usage details only.
