### ISSUE TITLE
[Heartbeat] Zombie-ish processes created under agent

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#32363]
When running under elastic agent heartbeat sometimes receives a signal causing it to restart, leaving orphaned node processes from browser runs (they wind up re-parented to `tini` in our container). We should use either golang's [`prctl`](https://stackoverflow.com/questions/34730941/ensure-executables-called-in-go-process-get-killed-when-process-is-killed) capability or some other strategy to ensure they are properly reaped.

![image](https://user-images.githubusercontent.com/131427/179091337-f4bbd9ed-7264-44e2-8813-ab37e5481166.png)

**Comment by vigneshshanmugam** [comment]
For my own understanding, Is the issue here 
- Not propagating the kill signals to the child process from the parent process OR
- Chromium process keeps hanging even after receiving those signals? 

Playwright server process does handle these signals `SIGINT, SIGTERM, SIGUP` by default and should be cleaned up on restarts. Could we enable debug logs and check if we are getting these signals propagated to the child process? 

Running Synthetics with `DEBUG=* should do it` .

**Comment by lucasfcosta** [comment]
May have found a problem on Mac. See https://github.com/elastic/beats/pull/32393#issuecomment-1205060430.

Just wanted to check if I missed anything on my tests, otherwise I'll open a separate issue for this.
