### ISSUE TITLE
Write configured custom options to filebeat log at debug level

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#3264]
5.1.1

It will be helpful from a troubleshooting pt of view if we can write prospector (and other) options configured to the log file at the debug level. Currently, with all selectors running at debug level, it writes out some information on the configuration it is using, eg.

2016/12/30 19:54:39.740370 async.go:72: DBG  create bulk processing worker (interval=1s, bulk size=50)
2016/12/30 19:54:39.740799 spooler.go:63: INFO Starting spooler: spool_size: 2048; idle_timeout: 5s

But does not write out any custom options set by the end user like ignore_older, close_timeout, etc..  This will be helpful when troubleshooting why (just as an example) ignore_older is not working to isolate if it's because the run didn't pick up the configured options to begin with, or if there is actually a bug where ignore_older is not firing.

**Comment by tsg** [comment]
@ruflin I think you wanted something similar to this for checking the full vs short configs, but wasn't easily possible, right? CC @urso

**Comment by ruflin** [comment]
The reason this didn't happen yet, is because each prospector does not have an identifier. It means if you have 3 prospector and would print out the above, you would just see `ignore_older` listed 3 times but would not know to which prospector it belongs.

I'm planning some changes in metricbeat to add an identifier to each module for reloading purpose. This change can also be applied later to filebeat prospectors, means each prospector would have an identifier. This would help that the identifier could be prefixed and at least it would be visible, which config options which are printed out belong together. So if you have `ignore_older` and `clean_inactive` 3 times in the logs, the ones that belong together would have the same prefix.
