### ISSUE TITLE
Support for Filebeat - fips endpoints for S3, SQS and CloudWatch

### ISSUE THREAD

**Issue by ilknurg** [elastic/beats#32875]
Hello Engineering team, 

My customer is asking the following: 

"We are using version 7.17 right now and we want to upgrade to 8.3 I believe. One of the things holding us back has been two outstanding bugs in the filebeat module:
S3 Module in Filebeat: The FIPS enabled endpoint for sqs in govcloud is using the same as commercial “sqs-fips” when govcloud uses the normal “sqs” endpoint. There is no “sqs-fips” endpoint in govcloud.
Cloudwatch module in Filebeat: The FIPS endpoint is set to the non-fips endpoint “logs” instead of “fips” (there is no “logs” endpoint in govcloud).
 
Using FIPS enabled endpoints is critical for us. To workaround, we’ve been custom compiling the Elastic code for filebeats to use the correct endpoints, but we would REALLY like to not be doing that."

**Background:** 
I have talked with @aspacca & @kaiyan-sheng on this topic. More details can be found here on this slack thread: https://elastic.slack.com/archives/C0D8SUKB2/p1660772334528309

I am creating this bug report to track the development of these requests. It seems like in the past there were some developments but still there is no working solution. One is here: https://github.com/elastic/enhancements/issues/9051 

Kaiyan also recommended asking the customer for their current working solution to see if we can do a PR on that and customer uploaded that to here: 

https://upload.elastic.co/d/d78964f6dc00dfbd5702292848bbaa4603f0e043d6805ea2177ac4dd96287cd3

Use this authorization token: 7b4c62280b91852d

You can also download it on the command line:

```
curl -L -H 'Authorization: 7b4c62280b91852d' \
	-o 'cwl_input.go.patch' \
	https://upload.elastic.co/d/d78964f6dc00dfbd5702292848bbaa4603f0e043d6805ea2177ac4dd96287cd3
https://upload.elastic.co/a/u/c/a237d22b-7026-4f82-a361-f2160fcf4dd2

```

Customer message with the upload above: 
" I haven’t been able to look at anything related to 8.3 yet. I pushed our current filebeat patches for 7.17 up to the file share (https://upload.elastic.co/u/a237d22b-7026-4f82-a361-f2160fcf4dd2): cwl_input.go.patch and s3_input.go.patch." 

Please let me know if I can provide any more information and please keep me posted so I can communicate the progress on this with the customer. 

Thanks, 
Iko

**Comment by kaiyan-sheng** [comment]
Hi @ilknurg, thanks for creating the issue. I'm looking at the main branch code (also 8.3 branch) I see the log service name `logs` is not hard coded anymore: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awscloudwatch/input.go#L123-L124

Did the user try `aws-cloudwatch` input with 8.3 and get the same error?

**Comment by aspacca** [comment]
> I'm looking at the main branch code (also 8.3 branch) I see the log service name `logs` is not hard coded anymore: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awscloudwatch/input.go#L123-L124

in order to clarify the comment from @kaiyan-sheng 

with 8.3, if the customer set `us-gov-east-1` or `us-gov-west-1` as region, the service part of the endpoint url will be correctly suffixed with `-fips` or not according to the service 

there more services with `-fips` suffix on govcloud: https://aws.amazon.com/compliance/fips/#FIPS_Endpoints_by_Service, but they are not services we support

indeed in was looking in the aws sdk v2 code and I wonder if we can remove at all passing the endpoint resolver and relay on the default one: all the logics we have accumulated it's already there, just more complete and maintained directly from aws ;) (so we don't have to worry about keep it in synch)

we could refactor [`aws.EnrichAWSConfigWithEndpoint`](https://github.com/elastic/beats/blob/df3733e2496ad72c6a3daa1cd7518f4e56f8667d/x-pack/libbeat/common/aws/credentials.go#L169) to just cover this case: https://github.com/elastic/beats/blob/df3733e2496ad72c6a3daa1cd7518f4e56f8667d/x-pack/libbeat/common/aws/credentials.go#L175

what do you think @kaiyan-sheng ?
