### ISSUE TITLE
[Heartbeat] Pip install doesn't work on windows tests

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#32994]
Now that https://github.com/elastic/beats/pull/32937/files is merged https://github.com/elastic/beats/pull/30632 no longer passes with errors such as the following:

```
[2022-09-01T21:51:57.634Z] DONE 14 tests in 74.803s

[2022-09-01T21:51:59.665Z] >> go test: Unit Test Passed

[2022-09-01T21:52:08.306Z] >> python test: Unit Testing

[2022-09-01T21:52:30.845Z] ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\jenkins\\AppData\\Local\\Temp\\pip-uninstall-d3e3cua0\\pip.exe'

[2022-09-01T21:52:30.846Z] Consider using the `--user` option or check the permissions.
```

I assume https://github.com/elastic/beats/pull/32937 was green when merged, but perhaps that wasn't the case. I think there was a misunderstanding, I had thought that we had disabled those windows tests that were failing in that PR, but it seems we did not do that.

We should disable those as they provide very little real value and are not worth maintaining.

**Comment by v1v** [comment]
I think `ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\jenkins\\AppData\\Local\\Temp\\pip-uninstall-d3e3cua0\\pip.exe'` is not relevant since it happens always as we discussed in https://github.com/elastic/beats/pull/32937#issuecomment-1233924710 and https://github.com/elastic/beats/pull/32937#issuecomment-1234465068

I'm a bit confused what to do in here, I guess the uptime can decide how they would like to proceed, either disabling the tests or reverting https://github.com/elastic/beats/pull/32937 if that's the case, and if so then comment out in https://github.com/elastic/beats/issues/23957 and https://github.com/elastic/beats/issues/23958, or maybe something else

**Comment by andrewvc** [comment]
Closing, I disabled the windows build steps in https://github.com/elastic/beats/pull/32937 . The issue is that `docker-compose` is not available on windows for integration tests. Maybe we can fix these in a subsequent issue, but TBH it's not at the top of our priority list.
