### ISSUE TITLE
beats/libbeat/scripts/generate_template.py does not support numeric types integer, short and bytes

### ISSUE THREAD

**Issue by breml** [elastic/beats#3303]
Followup for #3257, as suggested by @ruflin. 

I would like to use the numeric types `integer`, `short` and `byte` which are supported by Elasticsearch ([Numeric datatypes](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)) in the templates for [Netsamplebeat](https://github.com/breml/netsamplebeat/). 
With this beat I collect samples of network packets (mainly layer 2, 3 and 4 information). This also includes fields like IPv4 TTL (8-bit, unsigned, could be saved to a field `short`), IPv6 hop limit (8-bit, unsigned, could be saved to a field `short`) or IPv6 payload length (16-bit, unsigned, could be saved to a field `integer`).

Currently `beats/libbeat/scripts/generate_template.py` only supports `long` (and `integer`, which is [converted](https://github.com/elastic/beats/blob/master/libbeat/scripts/generate_template.py#L228-L230) to `long`).

**Comment by ruflin** [comment]
I remember we started to convert integer to long as there was no real downside in using a integer instead of a long related to compression but we got rid of all the problems where MAX_INTEGER was reached. Short and Byte is probably a different story. +1 on supporting it in our template script. It should be fairly easy to add them. Can you open a PR?
