### ISSUE TITLE
Metricbeat - Incorrect system.socket.direction

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3306]
Some sockets are being incorrectly identified as outgoing when they are really incoming connections. It looks the cause is that the listening socket is listed as AF_INET6 and the incoming connection is AF_INET. Probably the listening socket is bound to both ipv4 and ipv6.

For confirmed bugs, please report:
- Version: 5.2
- Operating System: Linux (CentOS 6)
- Steps to Reproduce: Enable system socket metricset.

```
State      Recv-Q Send-Q                                  Local Address:Port                                    Peer Address:Port 
LISTEN     0      128                                                :::443                                             :::*     
LISTEN     0      128                                                :::22                                              :::*     
LISTEN     0      128                                                 *:22                                              *:*
```

In the `ss` output above 443 accepts both ipv4 and ipv6 connections, but only ipv6 listed. Connection on 443 are identified by Metricbeat as outgoing. Need to investigate more.

**Comment by andrewkroh** [comment]
One potential improvement here would be to use `inet_diag_req_v2` where supported. The metricset uses `inet_diag_req ` because it supports more kernels. I recall there being better support for selecting the address family with v2 (make one request for ipv4 sockets and another for ipv6).

With `inet_diag_req` it asks for AF_INET sockets and gets back ipv4 and ipv6 sockets. https://github.com/elastic/gosigar/blob/master/sys/linux/inetdiag.go#L242

**Comment by simianhacker** [comment]
Because any good bug report needs a visualization... I'm seeing this when I backup to S3 from my laptop.

![image](https://cloud.githubusercontent.com/assets/41702/23835581/123da92c-0727-11e7-85ac-fcdd59582a0c.png)

**Comment by kiju98** [comment]
Hi @andrewkroh @simianhacker 
I have a user who is affected by this issue.
Do you have any update?
Thanks and Regards,
Kiju

**Comment by cwurm** [comment]
I think I found the cause:

To determine the direction of a socket, we save the list of listening sockets and match non-listening sockets to them. If we find a match, the non-listening socket is `Incoming`, otherwise `Outgoing`.

A problem occurs when matching an IPv6 socket listening on all interfaces (`::`) with an IPv6 socket that has an [IPv4-mapped IPv6 addresses](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses) (e.g. `::ffff:127.0.0.1`). Golang's `To4()` will determine it is an IPv4 address and miss the listening IPv6 socket here:

https://github.com/elastic/beats/blob/a995334013c2d9639e6fed79d353721312deb937/metricbeat/helper/socket/listeners.go#L136-L150

I think what we need to do is to provide the information whether a socket is IPv4 or IPv6 explicitly, which we can do. I'll work on a PR.
