### ISSUE TITLE
threatintel module for anomalithreatstream not handling delta gracefully 

### ISSUE THREAD

**Issue by sam42man** [elastic/beats#33284]
https://github.com/elastic/beats/blob/main/x-pack/filebeat/module/threatintel/anomalithreatstream/ingest/pipeline.yml

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  7.17.3
- Operating System: eck 
- Steps to Reproduce: 
- -set up anomalithreatstream integration with a beats instance reading date from anomali. 
- - we use the beats configuration and ingest pip-lines from the module.
- - restart the anomily thretstream integrator 
expected results:
only new records of IOC should be ingested in to our elastic search cluster

actual results:
when the thretstream integrator restarts it re send s all IOC to our beats instance and all ioc are converted to records in elastic search causing duplicate.

**Comment by Hashtpari** [comment]
@jamiehynds Can we please get this assigned? Thanks a million

**Comment by efd6** [comment]
This was fixed in #29014 which was included in v8. The fix was to add a [fingerprint processor](https://github.com/elastic/beats/blob/3e928b702b660d5cf31e8f3090c57f2feb541338/x-pack/filebeat/module/threatintel/anomalithreatstream/ingest/pipeline.yml#L10-L15) using the `event.dataset` and event id field from the original event. Making this change to v7 would be a breaking change and so it was not back-ported, and would unfortunately not help in the current situation until all old logs are not available for filebeat to reprocess.

**Comment by jamiehynds** [comment]
Closing as the PR linked by Dan resolved the issue in 8.x
