### ISSUE TITLE
proposal: add package watcher to auditbeat file_integrity module

### ISSUE THREAD

**Issue by efd6** [elastic/beats#33481]
There is a potential for the file_integrity module to replace the system.package module. This could be done by setting up a recursive watcher on the root of the system's package manager database since these are well known. With the addition of the new feature of file parsers (https://github.com/elastic/beats/pull/28802) we can add [`file_integrity.FileParser`](https://github.com/elastic/beats/blob/1fb24844a802941a581cffb68bb82104d5bff42f/auditbeat/module/file_integrity/file_parsers.go#L26-L29) types for each of the package managers that we currently handle. On file change in the watched database directory the `FileParser` takes a path and so the package parser would be able to know when an fsnotity event has happened in the database directory and would then be able to determine the state of the package database as the system.package module does now. The system.package module diffs against a previous cached state and we could take the logic from that module to re-implement the behaviour here.

One concern is that the RPM monitoring behaviour in system.package depends on Cgo and a C library, librpm. There is [a pure Go library for interacting with RPM packages](https://pkg.go.dev/github.com/cavaliergopher/rpm) but it does not provide access to the package manager's database so we will not be able to avoid the use of Cgo. The homebrew and deb monitors are already pure Go.

Open concerns:

- configuration complexity for users; the approach above requires that the user set up watchers and also configure the file parser for the package manager fields to populate. It should be possible with minor changes to the file parser configuration set-up to install watchers for the well known locations. Doing this would silently enable recursive watching which may negatively surprise some users.
- some package stores (deb and homebrew) have hefty weight and so could impose significant performance load with a recursive watcher

**Comment by andrewkroh** [comment]
I really like the idea of making package changes event driven through fsnotify. As an alternative proposal, maybe we make improvements to the current package dataset and set it on path toward GA.

- Add fsnotify to watch for changes.
- Migrate storage format to FlatBuffers to be consistent with FIM. IMO flatbuffers will be more maintainable w.r.t. schema evolution and less prone to accidental breakages.
- Plan support to additional types like chocolatey, chrome/firefox extensions, etc.

My biggest concern with adding this to file_integrity is complexity. The model for packages differs a bit from what the file parser enrichment is doing. With file parsing today it's a stateless enrichment to the FIM event (if the file was change we use the parser to enrich the event and it requires no additional persistence). With package monitoring, one event from FIM might trigger multiple events to be generated because it is comparing the state of the whole database against the state we have stored about each package.

My concerns:

- Code complexity.
  - Persistence needs for package metadata differ from regular file metadata.
  - One FIM event can generate multiple package events.
- Configuration is more complex for users.
- Has the potential to slow down the event loop. This isn't a new problem, but as we add more processing we have greater potential to drop fsnotify events if we cannot keep up. It might require some changes to making processing more async.

**Comment by andrewkroh** [comment]
I moved the tasks for this into https://github.com/elastic/beats/issues/33765.
