### ISSUE TITLE
configurable keepalive for outputs

### ISSUE THREAD

**Issue by robin13** [elastic/beats#3397]
Feature request:

In cases where the output (e.g. logstash) is forwarding documents through a load balancer (LB) or other proxy which has a connection timeout, disconnects can occur resulting in these kind of error messages in the logs:

```
2017-01-12T17:40:11+01:00 ERR Failed to publish events caused by: write tcp 10.10.10.99:52273->10.10.10.100:5045: wsasend: An existing connection was forcibly closed by the remote host
```

This occurs when the source is producing documents at a rate less than the disconnect.  The closed connection does not result in either lost or duplicate documents, so in this case the disconnect is not actually an error.  Unfortunately there is no way to discern between this class of disconnect, and other types which could result in duplicate documents being forwarded.
It would be very useful to have keepalive signals which can be sent from beats -> logstash/elasticsearch/... (with a configurable interval) to ensure that connections are not forcibly closed by intermediary actors such as a LB - this would ensure that this class of error does not occur in the logs and only valid disconnect errors are seen.
Obviously this will only be possible on such protocols as can support some form of keepalive signal, but wherever possible it would be great! :)

**Comment by DirkAmelinckx** [comment]
+1

**Comment by tsg** [comment]
@urso this is up you alley.

**Comment by urso** [comment]
Keepalives is somewhat vague.

We're not going to change any of the protocols to implement keep-alive on application layer. Instead I'd opt for enabling keep-alive support on TCP level (this still might be subject to tuning on OS level though) via [`(*TCPConn).SetKeepAlive`](https://golang.org/pkg/net/#TCPConn.SetKeepAlive) and potentially duration. 

Note, TCP keepalive can only become configurable for clients we have control over socket-creation.

**Comment by andrewkroh** [comment]
On Windows TCP keep-alives are not sent very often making them less useful. https://technet.microsoft.com/en-us/library/cc957549.aspx

**Comment by robin13** [comment]
@urso There are many ways to skin a cat... - I agree that "keepalive" is vague.  I guess what I'm thinking of is some way to do a null-operation which will cause some minimal amount of bits to be transferred without doing anything, or requiring any OS / TCP level fiddling.
For Elasticsearch simply a `GET /` would do.  Is there any equivalent null operation in the lumberjack protocol which could be used for a logstash output?

**Comment by jordansissel** [comment]
This topic comes up from time to time, so it's good to revisit it in case things change. Thank you for filing!

First and foremost, I want users to have a good experience. With this request, I look at this problem mostly summarized this way: _Some users have a firewall that interferes with healthy network connections_. Our software (beats/logstash) cannot configure user firewalls to avoid causing interference.

I offer some resistance to the keepalive proposal: the beats protocol tries to detect and correct for any network problems. A firewall interfering with an otherwise-stable connection is detected just like any other network problem.

For the specific poorly-behaving firewall, keep alive techniques only solve for one class of specific firewall issue which is the firewall deciding to forget (or actively destroying) an active and otherwise-healthy network connection. As counterpoints against keep alives, here are some problems caused by firewall interference that are not protected by keep alives:

* If you reboot the firewall, it will forget everything it knows and all previously-healthy sessions are destroyed, and keep alives will not protect from this. 
* If you have too many connections through a firewall, and the firewall decides to destroy or forget older connections in order to accept new ones, keep alives will not protect from this this.
* Operator maintenance on a firewall could cause previously-healthy sessions to be destroyed.

The three above instances are what I would roughly classify as "planned network problems" as in you must have installed a firewall and configured it to behave in this way that it causes problems on healthy connections.

If folks are looking for a way to determine "planned network problems" separately from "unplanned network problems" then I don't really have much advice because I personally don't know how to determine this programmatically. The most common proposal is an implementation request for keep alives on the beats protocol to try and defend against this scenario, but this only solves one very specific problem on a specific class of device that has numerous kinds of different interference.

To try and get closer, I have a few questions:

* Is the problem network problems are being logged and some folks do not want them logged?
* What is the measurable negative impact of not having a keep-alive-like implementation?
* How do we determine or prevent "planned network problems" (firewalls destroying healthy connections) separately from "unplanned network problems" ?

**Comment by jordansissel** [comment]
If the problem is log level noise, then maybe we can change the log level on this particular message from Error to Info or Debug?

**Comment by robin13** [comment]
> Is the problem network problems are being logged and some folks do not want them logged?

The problem is that network disconnects due to timeout are not bad (no duplicate data, not an actual problem), but are being logged as an error.  Exactly the same log would be created by an actual error / problem in the system (e.g. reboot of firewall).  Just changing the loglevel would not solve anything here because both classes of error are thrown in one pot.  By having a keepalive signal, the first set of error messages should not happen any more, and those remaining are actual errors which (may) warrant investigation.

> What is the measurable negative impact of not having a keep-alive-like implementation?

No insight into when there are actual infrastructure problems: any real errors will be hidden in the noise of the timeout disconnects.

> How do we determine or prevent "planned network problems" (firewalls destroying healthy connections) separately from "unplanned network problems" ?

Firewall destroying healthy connections should IMO be classified as a problem: while no data is lost, it indicates a lack of infrastructure capacity which should be dealt with, and so should be logged just the same as other "unplanned network problems".  I think it is only the disconnects resulting from a configured timeout which should be avoidable.

**Comment by jordansissel** [comment]
I don't think keep alive will solve what we hope it will solve, as mentioned, there are numerous kinds of temporary faults that resolve without human intervention, and fundamentally, I believe this is the summary of the problem -- we are signalling a problem for a temporary problem that is otherwise resolved on its own, and error signals should always be actionable.

My proposal, for now, is this: Focus on identifying persistent network failures.

To achive this proposal, I have the following implementation idea:

* Let's remove this log message (or make it a much lower-priority log level, like debug or trace)
* Keep track of the health of a given endpoint (up, down, duration in that state)
* Log a warning when a single (of many) endpoint has been down for a long time.
* Log an error when all endpoints are down for a long time.

The primary goal of this is to make behavior more noticeable and make the signals (logs) be more actionable.

In doing the above, I believe we will be providing more actionable reports to operators in a way that I believe solves the problem more broadly.

**Comment by urso** [comment]
Different log-level for connection errors as described by @jordansissel have been discussed and agreed upon in the past (hm... can not find related issues right now).

To me it's still questionable if we really want to suppress them all... depending on 'timing' of connection loss (e.g. waiting for ACK), beats might drop events or send duplicates. That is something is/might actually happening.

Note:
Keepalives are somewhat available by logstash-input-beats plugin sending an `ACK 0` every 5 seconds (not configurable it seems) while processing a batch of events (which is a great mechanism to signal back-pressure). Still network equipment can be a pain. But logstash-input-beats also closes 'inactive' connections, which seems to lead to 'premature' connection loss at times for some plugin versions (seems to be top 1 issue on beats discuss) + at least 1 second wait-time before beat reconnects.

This (new behavior) + interleaving with windowing in beats trying to not overload LS somewhat complicates error handling in the output, which definitely must be refined to match behavioural changes (and spurious connection loss) we discovered in 5.x release cycle.

**Comment by PhaedrusTheGreek** [comment]
+1 for **not** logging ERR when the timeout expires.   

This seems like normal operation and is very easy to reproduce.  If you don't send any events for 60 seconds, then begin sending again, then this is logged:

```
2017-04-07T12:39:12-04:00 ERR Failed to publish events caused by: write tcp 127.0.0.1:55128->127.0.0.1:5045: write: broken pipe
```
