### ISSUE TITLE
libbeat should support context passing

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#3399]
Would it be nice if libbeat implements the `context` paradigm fro golang ?

https://blog.golang.org/context

Basically, all goroutines/functions that may be blocked (waiting for htttp response, background routines, etc.) should be concealable using the go `context`.

For instance, the standard package `cxthttp` uses the context to cancel pending HTTP requests.
See https://godoc.org/golang.org/x/net/context/ctxhttp

**Comment by cyrilleverrier** [comment]
I looked at the libbeat source code and it should be as easy as to pass a `context` object to all cancelable operations like `PublishEvents` so that it can be used when calling HTTP requests.

Suggested modifications:

1. `libbeat/publisher/client.go`

```
type Client interface {
	Close() error
	PublishEvent(ctx context.Context, event common.MapStr, opts ...ClientOption) bool
	PublishEvents(ctx context.Context, events []common.MapStr, opts ...ClientOption) bool
}
```

2. `libbeat/outputs/elasticsearch/client.go`

```
func (conn *Connection) execHTTPRequest(ctx context.Context, req *http.Request) (int, []byte, error) {
	resp, err := conn.http.Do(req.WithContext(ctx)
```

**Comment by cyrilleverrier** [comment]
@ruflin It is an easy change but it requires many files to be changed in order to propagate the context to all functions.

**Comment by ruflin** [comment]
Pinging @urso on this one as he is the expert here.

**Comment by urso** [comment]
I will have to push back on support of Context for now.

Please Note: The publisher pipeline was completely rewritten for 6.0.

The context cancelling will not propagate as nicely as you'd expect. In 5.X and 6.0 a many Client instances can be active. Actually every producer is supposed to have a `beat.Client` instance for publishing. All events published by multiple clients are combined into one batch and thusly forwarded as one big set of events to the output. In 5.x we have had some kind of signaler + logic to combine/split signaling. But this has been removed + greatly reduced complexity in cancelling/stopping/signaling.

The new pipeline decouples the outputs using a configurable queue. The queue implementations might differ. The current reference implementation uses a broker like go-routine and implements it's 'API' using channels. But once the required feature set settles down, I'm considering to remove the go-routine and channels in favour of using conditionals/mutexes and such. Unfortunately go channels (for closing as used in Context), do not mix well with conditionals and other synchronisation primitives. Plus more queue types (e.g. disk based queue) might join beats as well. In order to keep some of my sanity with all the features we have and we might add, I'd rather keep Context until the dust has settled. We might re-eavluate support for context in the future, though.

To me it sounds like one reason to ask for Context is because the (new) beat.Client is shared between multiple go-routines (e.g. HTTP handlers). An instance of beat.Client is not required to be thread-safe and you are well advised to either protect it's usage using a mutex or have a client per go-routine. In the later case some cancelling can be implemented like this (I didn't check this for type correctness or typos):

```
type beatClient struct {
     beat.Client
     closed chan struct{}
     once sync.Once
}

func ClientWithContext(client beat.Client, ctx context.Context) beat.Client
    c := &beatClient{
        Client: client,
        closed: make(chan struct{}),
    }
    
    go func() {
       select {
       case <- ctx.Done():
           c.close()
       case <- c.closed:
       }
    }()
    
    return c
}

func (c *beat.Client) Close() error {
     c.close()
     return nil
}

func (c *beat.Client) close() {
     c.once.Do(func() {
         c.Client.Close()
         close(c.closed)
     })
}
```

Then in your http request handler add:

```
client, err := beat.Pipeline.ConnectWith(beat.ClientConfig{ ... })
if err != nil {
  // TODO
}

client := ClientWithContext(client, ctx)
defer client.Close()

client.PublishAll(events)
```

Note, by default `PublishAll` is async. If there is enough space in the queues, it will return right now. If the queue is full, it will block.

If you want some sync handling you will need to add an ACK handler as well:

```
sig := make(chan struct{})
total := len(events)
client, err := beat.Pipeline.ConnectWith(beat.ClientConfig{
    ACKCount: func(n int) {
        total -= n
        if total == 0 {
           close(sig)
        }
    }
})

client = ClientWithContext(client, ctx)
defer client.Close()

client.PublishAll(events)
select {
case <-sig:
    // all events have been ACked by queue
case <-ctx.Done():
     // request was cancelled
}
```
