### ISSUE TITLE
BeatsV2Manager will restart the entire beat with the removal of a single unit

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#34048]
Looking at the `BeatV2Manager` it is clear that it is not implemented correctly to work with the way the Elastic Agent V2 protocol is designed. It has a concept of a main unit which is not something that the Elastic Agent defines, it is possible at any time for a unit to be added or removed during the life of the component.

Example of this is say when running to monitor kubernetes containers:

1. Component starts with 1 unit for container A
2. Another unit is added for container B
3. Container A is stopped and its removed so unit from 1 is removed

**Comment by fearful-symmetry** [comment]
So, the concept of a "main" unit was largely a hack to deal with beats' own management API, where a beat can call back into the management system for registering actions, stopping the beat, logging status, etc, and the concept of a "main" unit is helpful there, since the beats themselves have no concept of a unit or unit ID. 

We can work around this and juggle units to do things like reporting or registering actions, unless things like `UpdateState` changes should be propagated across all units.
One Question then becomes how the agent tells the beat to shut down, which is presumably when _all_ units are removed.

**Comment by fearful-symmetry** [comment]
There's another hitch to this I forgot about: the beats management API has no concept of a "stop" for a reloadable component, so if we get a request to stop a given module/input/whatever, we can't really do anything other than shut down.

**Comment by fearful-symmetry** [comment]
Alright, so at least some beats should be able to handle removing units, but I want to test this a bit.

**Comment by cmacknz** [comment]
Just to clarify that we are talking about this part of the management code:

https://github.com/elastic/beats/blob/c78f9a111c298fa739793c7b949293acbb26b247/x-pack/libbeat/management/managerV2.go#L271-L277

I which case I agree, stopping the entire Beat when a single unit is removed isn't the correct thing to do. Hopefully Alex's experiment with removing units works as an alternative. The Beats themselves outside of the management package here still aren't well adapted to running under agent.

**Comment by fearful-symmetry** [comment]
cc @cmacknz  okay, so, there's some...complexity here.  I assume that when I decided to give the beat manager a "main" unit it was because the agent seemed to be spinning up multiple beats per-input, which is what it does today. So, if you have a setup with `system` and `docker` integrations, you get this:
```
Components:
  * docker/metrics  (HEALTHY)
                    Healthy: communicating with pid '538736'
  * system/metrics  (HEALTHY)
                    Healthy: communicating with pid '538754'
```

I can make two inputs map to one beat by starting two inputs with the same type. I'm not sure how common/supported this is, however I strongly suspect it won't work in beats, for the same reason that not restarting the beat won't work (or won't work easily), and that's that the libbeat fleet client will diff the list of configs it gets, and shut down any modules that aren't in the new config. Basically, only the metricsets in the latest config will run, meaning that if a beat has multiple input units, only the last to hit the `Reload` callback will be running. Or at least I think, I'm still testing it out, but that's what it looks like [this function](https://github.com/elastic/beats/blob/main/libbeat/cfgfile/list.go#L55) is doing. I'm not sure if the case of "multiple inputs with the same type" is unsupported or just rare, but if it's rare we need to start testing it, because it will probably break things.

This also means that I'm not sure how to approach the "main unit" thing since if we're only ever going to get one input unit, it's effectively our main unit. However, I agree that the behavior to explicitly shut down the beat when the unit is stopped should be removed, since there might be some weirdness there.

**Comment by fearful-symmetry** [comment]
<img width="1292" alt="Screen Shot 2022-12-14 at 1 54 32 PM" src="https://user-images.githubusercontent.com/8418476/207723226-a0c4d464-2f67-4e3c-8ad3-df02198b90b1.png">

So you can, in fact, do that in fleet. Is that something we actually support?

**Comment by cmacknz** [comment]
Just had a quick meeting with @fearful-symmetry to clarify this:

1. Multiple different units being mapped to the same process is definitely a valid use case. The most common use case would be multiple filestream inputs running in a single Filebeat process, most commonly encountered with Kubernetes and container log ingestion.
2. We can likely solve this problem by changing the way we generate the Beat configurations from the units we receive. We currently generate a Beat configuration per unit, treating the units individually as we receive them. What we need to do instead is collect all of the units, and then generate a single combined Beat configuration with every input from every unit in it. This allows the Beat [dynamic reloading function](https://github.com/elastic/beats/blob/837c426ca1701dff10271a91bf1dc43f95e868b5/libbeat/cfgfile/list.go#L55) to properly calculate which inputs need to be started and stopped by looking at the diff from the last combined configuration. This maps to how this worked in the V1 agent when it was sending a single configuration to each Beat, and also to how reloadable Beat configurations work when they are written by hand.

**Comment by cmacknz** [comment]
@blakerouse is most of the way through this already, assigning it to him to finish.
