### ISSUE TITLE
Enhance add_docker_metadata processor upon docker restarts

### ISSUE THREAD

**Issue by gizas** [elastic/beats#34339]
**Describe the enhancement:**
The `add_docker_metadata` processor requires users to mount the docker.sock. If the docker daemon restarts, this sock connection becomes unavailable. This functionality has been [documented](https://www.elastic.co/guide/en/beats/metricbeat/8.6/add-docker-metadata.html#add-docker-metadata) and relevant workarounds have been provided. Additionally we would like to enhance the processor's ability to reconnect upon such failures.

**Describe a specific use case for the enhancement or feature:**
As described in [#29481 ](https://github.com/elastic/sdh-beats/issues/2948#issuecomment-1399229942), the `add_docker_metadata` processor should be able to understand such docker socket failures and be able to reconnect on a given time period. The solution enhancement should be able to support beats in a containarised and non-containarised environments.

Relevant issues:
- https://github.com/elastic/beats/issues/19323

**Comment by ChrsMark** [comment]
@gizas I tried to reproduce the issue running Filebeat natively and it seems that the issue does not exist there. 

I think that the issue reported at https://github.com/elastic/beats/issues/19323 has to do with mount itself. This could happen when  the daemon is restarted and there is a new socket which is not actually updated inside the Filebeat's container so a result the mounted socket is outdated. In that case I don't think that the code can handled it because the issue has to with how we make the socket available to Filebeat. 

I will investigate this further.

**Comment by ChrsMark** [comment]
FYI I did an extra test (I'm using latest `main` (==`8.7`),  and restarting the docker daemon without recreating the target container:

```console
➜  ~ docker run --restart always -d chentex/random-logger:latest
➜  ~ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS              PORTS     NAMES
429f496c4fe8   chentex/random-logger:latest   "/entrypoint.sh 100 …"   2 minutes ago   Up About a minute             keen_snyder
➜  ~ sudo systemctl restart docker
➜  ~ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS     NAMES
429f496c4fe8   chentex/random-logger:latest   "/entrypoint.sh 100 …"   2 minutes ago   Up 5 seconds             keen_snyder
```

So it seems that when Filebeat is running natively and the docker daemon is restarted there is no issue with Filebeat being able to handle such restarts and continue collecting logs along with docker metadata.


I will double check what happens when Filebeat runs as a docker container and the socket is mounted.

**Comment by ChrsMark** [comment]
Running Filebeat as a docker container too makes me realize that when the local docker daemon will be restarted then the Filebeat container will be restarted too. In that case the mount will be valid again and hence the metadata will be added properly again. For example I run filebeat as:

```console
docker run --restart always -d \
  --name=filebeat \
  --user=root \
  --volume="$(pwd)/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro" \
  --volume="/var/lib/docker/containers:/var/lib/docker/containers:ro" \
  --volume="/var/run/docker.sock:/var/run/docker.sock:ro" \
  docker.elastic.co/beats/filebeat:8.6.1 filebeat -e --strict.perms=false
```

and then issue a docker daemon restart with `systemctl restart docker`. The Filebeat container will be restarted and will continue to collect logs along with their metadata.

So in that case I'm not sure about a valid usecase where the docker daemon will be restarted and the Filebeat container of the same node will not be restarted.
Even in that case we have documented with https://github.com/elastic/beats/issues/19323 a valid way to tackle the "issue".

Having said all these I think that there is nothing more to fix here and we can close this issue since we have check all the cases.

**Comment by gizas** [comment]
> when Filebeat is running natively and the docker daemon is restarted there is no issue with Filebeat being able to handle such restarts

So in this case we should only make sure we mount the top directory of the socket and the file itself. If mount is done on top directory the code can handle restarts

> Running Filebeat as a docker container too makes me realize that when the local docker daemon will be restarted then the Filebeat container will be restarted too. 

Great, as FB is a container itself. So no issue.

I dont think we also miss something in documentation here. I am closing this issue
