### ISSUE TITLE
[CI] golangci-lint: no reproducable locally

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#34344]
Linter issues are not easy to reproduce locally, that could be caused by some dependency of the `golangci/golangci-lint-action@v3`, example - https://github.com/elastic/beats/pull/34161#issuecomment-1370760219, https://github.com/elastic/beats/pull/33763#issuecomment-1330543603

in some cases it fails on `darwin` only - here I've opened a [PR](https://github.com/elastic/beats/pull/34175) to demonstrate that the linter fails on darwin only - https://github.com/elastic/beats/actions/runs/3873023889 

those reported issues are by `typecheck` smth like: `podMetaGen declared but not used (typecheck)`, that is actually not correct and in the end often just ignored, example: https://github.com/elastic/beats/pull/33865#discussion_r1083566102 or https://github.com/elastic/beats/pull/33763#issuecomment-1330543603, but we still spend some time to check those errors

even though linter is not treated as something blocking the merge, it's just for notification purposes for the reviewers, but when it fails - some time is spent to check it, fail to reproduce, get the idea that linter is not reliable and ignore it next times

**Comment by ruflin** [comment]
@tetianakravchenko Do you have some guesses where these diffs come from?

@cachedout It would be great if your team could take a look at this. Local and CI linting must be identical.

**Comment by ChrsMark** [comment]
+1 I think this specific false alarm is quite annoying and might be a bug of the linter?

**Comment by tetianakravchenko** [comment]
@ruflin I think it is either bug of the linter itself https://github.com/golangci/golangci-lint, or some dependency of [golangci/golangci-lint-action@v3](https://github.com/golangci/golangci-lint-action), back at the time I've checked both those repos if there are similar to ours issues -  couldn't find anything, also tried to change version of linter - without success

**Comment by cmacknz** [comment]
When this happens does your local version of golangci-lint match what is in the linter configuration used for CI? https://github.com/elastic/beats/blob/762ad188b7ecdd5bae65bb525e5eca393c4a86d7/.github/workflows/golangci-lint.yml#L42

We have also seen the linter struggle with files that have CGO dependencies but I don't think that is the case here.

**Comment by cachedout** [comment]
It is possible to run these “locally”, but it’s a bit of a hack. Here’s how I did it:

 brew install act
 act -j golangci

This uses [this project](https://github.com/nektos/act) to download the requested containers and execute the GitHub action on your local machine instead of having GitHub do it. You could use this technique in the short-term to produce the same results that the GitHub check on PRs should be giving to you.

However, the use of `act` is not really a viable long-term strategy here. In reality, what needs to happen here is that we need to isolate the linter in a container of its own which can be built and run either locally or via CI. 

I’m speculating a bit, but based on reading some of the Slack threads where this problem is come up, it appears to me as if there may have been some version differences in golangci-lint [pinned by the GH Action](https://github.com/elastic/beats/blob/main/.github/workflows/golangci-lint.yml#L42) which is 1.47.2 and what was being tested locally. (As already pointed out by @cmacknz above as well.)

Additionally, it looks like the Action is set to [use the version of Go](https://github.com/elastic/beats/blob/main/.github/workflows/golangci-lint.yml#L54) on the Action runner which likely varies from what’s present locally.

IMHO, we need to do the following to address this in the long run:

1. Encapsulate the entire linting workflow within a single container (which could be built from the golangci-lint base. That container should have the same Go binary that the project is currently using. Both the CI and developers should lint their code only by running that container.
2. Possibly move the linter into Buildkite, which is where the rest of the project is going
3. Remove the multiple operating systems that the linter runs on in GH Actions. There should be no need for this when linting, unless there is a use case here that I'm missing.

@v1v Do you have anything else to add here?

**Comment by cmacknz** [comment]
> Remove the multiple operating systems that the linter runs on in GH Actions. There should be no need for this when linting, unless there is a use case here that I'm missing.

Beats has platform specific implementations that are ignored by the compiler and linter unless you are targeting that OS. If we don't do per OS linting, we will be skipping entire packages. Example:

https://github.com/elastic/beats/blob/ae638c4a0fc8388e23b7352162a655e4ce937ea5/metricbeat/module/windows/perfmon/perfmon.go#L18-L19
