### ISSUE TITLE
[Filebeat][httpjson][Enhancement] Need support for Parsing XML Response

### ISSUE THREAD

**Issue by vinit-chauhan** [elastic/beats#34438]
We are trying to parse XML responses into filebeat. However, we are unable to parse those responses where the content type is application/XML. It shows the **`unable to unmarshal first_response.body: json: cannot unmarshal string into Go value of type mapstr.M`** error while parsing. We suspect the issue in `request.go` file on this [line 312](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/httpjson/request.go#L312).

**`Content Type`: Application/XML**

**Response log example:** 

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE REPORT_LIST_OUTPUT SYSTEM "https://qualysapi.qualys.com/api/2.0/fo/report/report_list_output.dtd">
<!--sample comment-->
<REPORT_LIST_OUTPUT>
	<RESPONSE>
		<DATETIME>2017-10-30T22:32:15Z</DATETIME>
		<REPORT_LIST>
			<REPORT>
				<ID>42703</ID>
				<TITLE>
					<![CDATA[Test now]]>
				</TITLE>
				<TYPE>Scan</TYPE>
				<USER_LOGIN>acme_aa</USER_LOGIN>
				<LAUNCH_DATETIME>2017-10-30T17:59:22Z</LAUNCH_DATETIME>
				<OUTPUT_FORMAT>PDF</OUTPUT_FORMAT>
				<SIZE>129.1 MB</SIZE>
				<STATUS>
					<STATE>Finished</STATE>
				</STATUS>
				<EXPIRATION_DATETIME>2017-11-06T17:59:24Z</EXPIRATION_DATETIME>
			</REPORT>
		</REPORT_LIST>
	</RESPONSE>
</REPORT_LIST_OUTPUT>
```

**Comment by efd6** [comment]
This is not a trivial addition due to the nature of the encoding/xml package and the complexity of XML. There is a long-standing proposal to add support for unmarshalling XML whose structure is not known at compile time (without heroic effort)[here](https://go.googlesource.com/proposal/+/master/design/13504-natural-xml.md).

Note that even with that addition, there are complexities that arise because the xml package will not understand the DTD (and there is not good [any?] support for DTD handling in the Go ecosystem). An example of how this will be difficult in the document above, the DTD defines REPORT_LIST_OUTPUT as holding an optional REQUEST, which would be a non-array field in a `mapstr.M` while REPORT_LIST is defined as holding a non-empty array of REPORT which would be a slice field in a `mapstr.M`. Without reference to the DTD's definition of the document structure, we cannot know these details.

**Comment by andrewkroh** [comment]
This is what the `decode_xml` processor reports for that XML. Could we apply a similar transformation directly in the httpjson input?

```
- decode_xml:
    field: message
    target_field: ""
```

```json
    "report_list_output": {
      "response": {
        "datetime": "2017-10-30T22:32:15Z",
        "report_list": {
          "report": {
            "user_login": "acme_aa",
            "launch_datetime": "2017-10-30T17:59:22Z",
            "output_format": "PDF",
            "status": {
              "state": "Finished"
            },
            "title": "Test now",
            "expiration_datetime": "2017-11-06T17:59:24Z",
            "id": "42703",
            "size": "129.1 MB",
            "type": "Scan"
          }
        }
      }
    }
```

**Comment by jamiehynds** [comment]
@efd6 this enhancement to a Qualys Vulnerability Management integration we were hoping to work on. If it helps, Qualys provides an [XML/DTD Guide](https://www.qualys.com/docs/qualys-api-vmpc-xml-dtd-reference.pdf). @clement-fouque has kindly agreed to providing sample data/Qualys access if needed.

**Comment by efd6** [comment]
I've looked into this a bit more and there is an [XSD parser](https://pkg.go.dev/aqwari.net/xml/xsd#Parse) that we could use if we make the config for the processor take an XSD which can be trivially generated from the DTD.

I have tried this out with an XSD generated from the DTD above with dtd2xs and the critical information is embedded into the resulting schema (the `Plural` field in [`Attribute`](https://pkg.go.dev/aqwari.net/xml/xsd#Attribute)). This could be looked up to decide whether to make an array or an object/value during the `mapstr.M` construction from XML.

**Comment by andrewkroh** [comment]
@efd6's approach of using the DTD to determine the plural types sounds like a good technical approach to solving the data type issues. I think the next step here is to have someone propose how a user would configure the httpjson input to handle application/xml responses (i.e. what are the new configuration option(s) that we would add).
