### ISSUE TITLE
Add EDNS and DNSSEC awareness to DNS protocol plugin

### ISSUE THREAD

**Issue by McStork** [elastic/beats#345]
Hello,
I would like to implement the DNS protocol missing features. I already forked and the TCP part is on its way.

**Comment by andrewkroh** [comment]
@McStork I am happy to hear TCP support is being worked. If you have any questions let us know. Also feel free to open up a pull request for your branch even in incomplete form if you would like to get some early feedback.

Regarding EDNS and DNSSEC, I was considering switching from using gopacket to [miekg/dns](https://github.com/miekg/dns/blob/master/msg.go#L1578) since miekg/dns already has support for these. However I haven't looked to see how easy or difficult it would be to switch.

**Comment by andrewkroh** [comment]
I am updating the title to reflect the fact that support for monitoring DNS traffic over TCP has been added.

**Comment by andrewkroh** [comment]
So that status here is that Packetbeat now uses miekg/dns for parsing. The work remaining is to update Packetbeat to use the library to get the data from the EDNS and DNSSEC records. @McStork Is that correct? Thanks

**Comment by McStork** [comment]
@andrewkroh Correct. FYI my schedule requires that I implement it in two months at the latest. But I might work on it sooner than that.

**Comment by McStork** [comment]
https://github.com/elastic/beats/pull/1292 closes this.
The DNS protocol in Packetbeat could still use some work (watch the 'TODO' in the package), but as far as TCP, EDNS and DNSSEC go, it's done with ^_^.
