### ISSUE TITLE
Report FQDN on Windows hosts

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#34782]
**Describe the enhancement:**

In https://github.com/elastic/beats/pull/34456, we enhanced Beats to accept configuration for feature flags via the top-level `features` configuration key.  

The first feature we added a flag for was FQDN reporting (also implemented in the same PR).  To enable FQDN reporting, users must set `features.fqdn.enabled: true` in their Beat's configuration.

FQDN reporting has not yet been implemented for Beats running on Windows hosts, however.  This issue is to track the necessary implementation.  See background and suggestions in https://github.com/elastic/beats/pull/34456#discussion_r1128319563.

**Describe a specific use case for the enhancement or feature:**

See https://github.com/elastic/beats/issues/1070.

**Comment by cmacknz** [comment]
I think this only applies to events read using the winlog input, if I am interpreting https://github.com/elastic/beats/pull/34456#discussion_r1128319563 correctly.

**Comment by amitkanfer** [comment]
Marking this as P0, like all the other FQDN issues.
Would be great to get an effort estimation for this task ASAP.

**Comment by cmacknz** [comment]
We investigated the behaviour of add_host_metadata and the winlog input and concluded:

- When the event is forwarded from a separate host, we want to leave the host.name as is. This is accomplished by the `forwarded` tag on the add_host_metadata process condition.
  - Under agent, this is configured in https://github.com/elastic/beats/blob/e7e6dacfca2055d14fba269253dade2d197906d8/x-pack/filebeat/cmd/agent.go#L49-L53
  - For standalone Beats, this is in the default configuration file: https://github.com/elastic/beats/blob/e7e6dacfca2055d14fba269253dade2d197906d8/filebeat/filebeat.yml#L167-L169
- When the event is not forwarded from a separate host, we want to overwrite the host.name received from winlog to match the one determined by the add_host_metadata processor. This appears to work today with no changes.
  - winlog sets the `host.name` attribute here: https://github.com/elastic/beats/blob/34a87e51a5a30a40f60372acfdae17a14a5faa2c/winlogbeat/eventlog/eventlog.go#L101
  - add_host_metadata has logic to skip adding host.metadata if it already exists, but will ovewrite `host.name` if it is the only host field that is set: https://github.com/elastic/beats/blob/e7e6dacfca2055d14fba269253dade2d197906d8/libbeat/processors/add_host_metadata/add_host_metadata.go#L156-L170

The conclusion is that the only action we have is to test winlogbeat (which is the winlog Filebeat input under agent) with the fqdn feature enabled and ensure it has the behaviour we want for both of these cases. We should be able to do this by configuring a the winlog integration for agent to read from an evtx file with the appropriate preconditions. There are some sample evtx files in https://github.com/elastic/beats/tree/9b4bd2d32a6cf6f179c2e3cf32848ca7ac3c8e95/x-pack/winlogbeat/module/security/test/testdata/collection for reference.

We want to test that:

1. A winlog event that sets host.name to a value that is different than what add_host_metadata would set has the host.name corrected to match.
2. A winlog event that sets host.name to a value that is different from what add_host_metadata would set but is forwarded from another machine is unchanged.

Since the only work here is testing the estimate is set to Small (<2 days).

**Comment by jlind23** [comment]
Thank you @cmacknz for the update!

**Comment by ycombinator** [comment]
> The conclusion is that the only action we have is to test winlogbeat (which is the winlog Filebeat input under agent) with the fqdn feature enabled and ensure it has the behaviour we want for both of these cases. 

Chatted with @jlind23 about this in a 1-1 today.  We decided that since the only work expected for this issue is testing, we will close this issue for now.  Things are expected to work as-is; if testing reveals that they don't, we will reopen this issue.  This gives more accurate visibility into the state of this issue.
