### ISSUE TITLE
[Heartbeat] NPM-less synthetics execution

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#34942]
We currently execute synthetics journeys using NPM, but this is less than ideal. NPM is big and complex, ideally we'd just run node. It also sometimes makes network requests and is a little tricky to run in a minimal offline fashion.

Some options we could explore:

1. Just using `ln -s` to install libs, but still using NPM for things to work
2. Combining the synthetics lib with the compiled project to form a single file of JS that node can execute
3. Something else

CC @vigneshshanmugam

**Comment by paulb-elastic** [comment]
With https://github.com/elastic/beats/pull/34936, this can be closed

**Comment by vigneshshanmugam** [comment]
@paulb-elastic This is not done on the other issue. The issue is more about moving away from calling `npm install` and basically symlinking the global elastic package in other way to avoid time spent on the installation phase. 

We can move this to the backlog and work on it as a future enhancement.

**Comment by paulb-elastic** [comment]
@andrewvc ^^ (reopening and putting on the backlog)
