### ISSUE TITLE
[Testing] Input reload not working as expected under Elastic-Agent

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/beats#35178]
# Related Issue
https://github.com/elastic/beats/issues/33653

# Description
Implement some Integration Test using our new Framework to catch the input reload bug before trying to do the implementation.
By doing it, we will be able to ensure that the fix we will provide is covering correctly every workflow.
More details in the related issue.

# Acceptance Criterias

- [ ] The publishing pipeline doesn't contain remaining event when the input is stopped
- [ ] Harvester status is the correct one 
- [ ] Restarting an input doesn't generate errors
- [ ] ...

**Comment by cmacknz** [comment]
Do we need this to be an integration test, or to even test it under the Elastic agent at all?

Can this behaviour be isolated to just Filebeat itself? The agent is just configuring Filebeat inputs using essentially the same logic used when configuration file reloading is enabled.

Can this be a Filebeat system test, or even just a unit test?

**Comment by pierrehilbert** [comment]
I based myself on the issue's description.
If we can isolate this bug to Filebeat only, I agree we can test it there directly instead of in the Agent.

**Comment by cmacknz** [comment]
Discussed today and we believe we have isolated the behaviour using only Filebeat itself. @belimawr if we need another round of discussion and brainstorming on this let me know and I'll set it up.

**Comment by pierrehilbert** [comment]
@belimawr don't hesitate to update the issue following your investigation and discussion with Craig.

**Comment by cmacknz** [comment]
I spoke with @belimawr today and we came up with the follow proposal to test this:

1. Add a new command line argument for the Beats management package that allows specifying the gRPC server address to connect to directly. This would involve modifying this structure:

https://github.com/elastic/beats/blob/f4374dce89786b1feb7012b1dc984f2435c5a061/x-pack/libbeat/management/config.go#L12-L17

2. When the server address is configured directly, instead of trying to read the server address and mTLS configuration from stdin like it would when running under agent the Beat will create a V2 protocol client to connect directly to that address without TLS. This will involve modifying this block:

https://github.com/elastic/beats/blob/f4374dce89786b1feb7012b1dc984f2435c5a061/x-pack/libbeat/management/managerV2.go#L118-L125

It will look something like the insecure configuration used in the existing unit tests:

https://github.com/elastic/beats/blob/f4374dce89786b1feb7012b1dc984f2435c5a061/x-pack/libbeat/management/managerV2_test.go#L202-L209

3. We will write an integration test that starts a gRPC server with an implementation of the `ElasticAgentClient` service, starts Filebeat as a process, and then sequences the `CheckinExpected` messages in a way that reproduces this problem.

The test will only need to implement the `CheckinV2` RPC, the other RPCs can be stubs. The `Checkin` RPC is deprecated and we don't need `Actions`.

https://github.com/elastic/elastic-agent-client/blob/554dc30ca4b66d9ab41149e6ed099b859c82ad09/pkg/proto/elastic-agent-client_grpc.pb.go#L28-L34

This will give us the foundation to write integration tests that directly control configuration changes sent to Beats without having to rely on editing the agent policy in the required way, and more importantly does not introduce a dependency on the Elastic Agent build system by requiring use of the under development Elastic Agent integration testing framework
