### ISSUE TITLE
[Filebeat][awss3] Input Metrics for S3 should not allow an empty ID

### ISSUE THREAD

**Issue by ebeahan** [elastic/beats#35354]
If the Input Context doesn't exist, the input metrics for S3 should not allow an empty ID:

https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/s3.go#LL80C3-L80C75

Other input metrics always require an ID, and if creating metrics for an empty input ID, it will/should fail.

An example passing the ID as part of `newMetrics` from the TCP input:

https://github.com/elastic/beats/blob/main/filebeat/input/tcp/input.go#L114

Also, how `Run` retrieves input context also from the TCP input, but should be similar on all/most inputs:

https://github.com/elastic/beats/blob/main/filebeat/input/tcp/input.go#L107

**Comment by ebeahan** [comment]
@kgeller would you be willing to take look since you're familiar from your work in https://github.com/elastic/beats/pull/34793?

**Comment by andrewkroh** [comment]
What problem is associated with this? Was it observed that the aws-s3 input was producing an empty `id` on the `/inputs/` HTTP endpoint?

The code mentioned (shown below) is exclusively executed in unit testing to construct non-nil `inputMetrics` object. It does not use the global metric registry (it uses an ephemeral registry created with `monitoring.NewRegistry()`) so there is no chance that metrics created by this code path could ever show up in the `/inputs/` HTTP endpoint.

https://github.com/elastic/beats/blob/29fcd59f9fc3ba1667a17a789d535fa0849561a2/x-pack/filebeat/input/awss3/s3.go#L79-L81

AFAICT all code paths used in the real input have non-nil `inputMetrics` passed in:

1)

https://github.com/elastic/beats/blob/78dc6649400610e9f908af7c90f35819f061e4e0/x-pack/filebeat/input/awss3/input.go#L284-L287

2) 

https://github.com/elastic/beats/blob/78dc6649400610e9f908af7c90f35819f061e4e0/x-pack/filebeat/input/awss3/input.go#L211-L214

-----

So if there is a problem with an empty ID then its probably not an issue exclusive to the aws-s3 input or the code highlight in the issue. I would like to know more about the original issue the led to this so we figure out what problem needs solved.

**Comment by P1llus** [comment]
Initially when I requested that someone could take a look at this, I was still unsure if it was only test related or not, however I still stand by my point, but this is more a personal view rather than anything else, so I do not have anything against leaving it as it is.

My own opinion on this is a bit split:
1. If in a real scenario, the ID should never be allowed to be nil, then why should a unit test be allowed to? Even a hardcoded value would be better, one could even consider that passing a nil value and expecting an error in return would be handy as an extra test.

2. Other tests are not using nil values, so if we want to make them consistent, should we not have it the same for all?
https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/input_benchmark_test.go#L214
https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/metrics_test.go#L24
https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/metrics_test.go#L40
And a few more

3. I would say that, when we create this piece of code, we should not only focus on the current code, but the possibility others might ammend it later, seeing that not having an input ID is for me a failure state, we should take it one step further and ensure its not nil here:
https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/metrics.go#L144

4. I did not mean we needed any drastic changes to the tests, while the above PR takes a bit of a different approach, all I really wanted was to either use a hardcoded ID, or if an input is actually initiated during tests then use the context ID from that, but I believe that's not the case. And after that also ensure newInputMetrics did not allow nil values to begin with, to make it more future proof.


In the end however I might just be overreacting, so I am fine with either outcome.

**Comment by kgeller** [comment]
I don't have a strong opinion either way here, but my thinking was that it didn't feel great to have code specific to tests in 'real-life' code. So I removed it and altered the tests as such. If we do stick with that approach, I'd agree with Marius that it'd be best to add a nil specific test. But I will defer to you both on whichever path we want.

**Comment by ebeahan** [comment]
With the defensive check added and merged in the `inputmon` package in https://github.com/elastic/beats/pull/35453, anything outstanding to discuss or track here? Else I'll close.

**Comment by andrewkroh** [comment]
https://github.com/elastic/beats/pull/35430 is related and pending review.
