### ISSUE TITLE
Structured metricset for Jolokia Module

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3585]
In https://github.com/elastic/beats/pull/3570 a dynamic `jmx` metricset was implemented for Jolokia. There are common values like memory across most jolokia installation. One or several metricsets should be created for the Jolokia module which contain these fields. This allows to simplify the configuration for basic cases and to have shipped dashboards with it as all fields are known in advance.

**Comment by rhuss** [comment]
A good starting point could be https://github.com/rhuss/jmx4perl/tree/master/config which holds the definition for some common Nagios checks. The contain also the MBean and attribute name for some metrics to measure. Especially in `memory.cfg` and `threads.cfg` should be applicable to any JVM.

However, memory is a bit tricky, since e.g. the MBean name for the garbage collector statistics depend on the configured garbage collector and the JVM version used.

**Comment by ruflin** [comment]
Thanks for sharing these configs. For the memory we could make the MBean name configurable and have one as default. Like this it would work for different configs and JVM I hope.

On a different note: I had a look at https://github.com/rhuss/jmx4perl/blob/master/config/jboss.cfg and it seems in there you also define critical and warning. I assume that is when you get a message from the system? In Elastic-Stack terms that is similar to a watcher config?

Did you have a chance to try out the jmx module? Would really like to get some feedback on it :-)
