### ISSUE TITLE
[filebeat][azure-blob-storage] - Fix concurrency issues and flakey tests.

### ISSUE THREAD

**Issue by ShourieG** [elastic/beats#35983]
There are a couple of concurrency issues that exist inside the azure blob storage input, along with some flakey tests. This is issue describes what need fixing.

1) Fix concurrency issues related to dynamic cursor and map iterations.
2) Decouple object timeout from from scheduler timeout.
3) Fix flakey tests.

**Comment by sebastienminne** [comment]
@ShourieG Thanks for the fix, facing the issue currently. 
Any idea when the release will be done ?

**Comment by sebastienminne** [comment]
@ShourieG 

Not sure the fix is effective 

`                                                              goroutine 7801 [select]:                               net/http.(*persistConn).writeLoop(0xc0034638c0)                               	net/http/transport.go:2410 +0xf2                               created by net/http.(*Transport).dialConn                               	net/http/transport.go:1766 +0x173d                                                              goroutine 7465 [select]:                               net/http.(*persistConn).readLoop(0xc001ca59e0)                               	net/http/transport.go:2227 +0xd85                               created by net/http.(*Transport).dialConn                               	net/http/transport.go:1765 +0x16ea                                                              goroutine 7792 [sync.Mutex.Lock]:                               sync.runtime_SemacquireMutex(0xc002a84ed0?, 0x59?, 0x3?)                               	runtime/sema.go:77 +0x26                               sync.(*Mutex).lockSlow(0xc00037c5a0)                               	sync/mutex.go:171 +0x165                               sync.(*Mutex).Lock(...)                               	sync/mutex.go:90                               github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.createUpdateOp(0xc0010fc230, 0xc00037c580, {0x55d7e10eee00?, 0xc001fd42d0})                               	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:91 +0xb1                               github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).Publish(0xc001fd4030, {{0xc13a21886001ff9c, 0x747892354f, 0x55d7e412c260}, 0xc002a84ed0, 0xc002a84d50, {0x0, 0x0}, 0x0}, {0x55d7e10eee00, ...})                               	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:71 +0x86                               github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage.(*job).readJsonAndPublish(0xc00373bce0, {0x55d7e1b86d40, 0xc001cfa140}, {0x55d7e1b35d80?, 0xc0042e2180}, {0xc000083020, 0x54})                               	github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage/job.go:203 +0x374                               github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage.(*job).processAndPublishData(0xc00373bce0, {0x55d7e1b86d40, 0xc001cfa140}, {0xc000083020, 0x54})                               	github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage/job.go:128 +0x397                               github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage.(*job).do(0xc00373bce0, {0x55d7e1b86d40, 0xc001cfa140}, {0xc000083020, 0x54})                               	github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage/job.go:73 +0x12c                               github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage.(*scheduler).scheduleOnce.func1()                               	github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage/scheduler.go:114 +0x70                               created by github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage.(*scheduler).scheduleOnce                               	github.com/elastic/beats/v7/x-pack/filebeat/input/azureblobstorage/scheduler.go:112 +0x2f6                                                              goroutine 7691 [select]:                               net/http.(*persistConn).readLoop(0xc0045f6900)                               	net/http/transport.go:2227 +0xd85                               created by net/http.(*Transport).dialConn                               	net/http/transport.go:1765 +0x16ea`

**Comment by ShourieG** [comment]
@sebastienminne I don't see any specific error or panic in the stack trace though. What exactly seems to be the issue, or am I missing something ?

**Comment by ShourieG** [comment]
@sebastienminne Are you getting this stack trace every time you use a worker count > 1 ? Is filebeat crashing immediately ? Could you share your config ?

**Comment by sebastienminne** [comment]
@ShourieG This happen when worker > 1, sometimes at startup sometime fews minuets after start 
This also happen when having more than one container watched (having one or more worker on containers)

`   filebeat.inputs:
      - type: azure-blob-storage
        id: my-azureblobstorage-id
        enabled: true
        account_name: myAccountStorage
        auth.connection_string.uri: "${STORAGE_ACCOUNT_CONNECTION_STRING}"
        clean_inactive: 1m
        containers:
          - name: container1
            max_workers: 1
            poll: true
            poll_interval: 30s
          - name: container2
            max_workers: 1
            poll: true
            poll_interval: 30s
          - name: container3
            max_workers: 1
            poll: true
            poll_interval: 30s

    output.kafka:
      topic: aTopic
      required_acks: 1
      client_id: filebeat
      version: '1.0.0'
      hosts:
        - ********.servicebus.windows.net:9093
      username: "$ConnectionString"
      password: "${EH_CONNECTION_STRING}"
      ssl.enabled: true
      compression: none
      sasl.mechanism: PLAIN

    output.elasticsearch:
      enabled: false`


What I can observe as well is an incredible amount of 'listBlobs' operation (43 M a day) which cost a lot of money 
It is tunning in kube on a pod having 5 cpu and 10 g of ram

**Comment by sebastienminne** [comment]
Sorry I just noticed the first line of the error wasn't in the stack trace : 

fatal error: concurrent map iteration and map write

**Comment by ShourieG** [comment]
@sebastienminne, extremely weird .. cause with 8.10 we even introduced concurrency tests that work with even 2000 workers after the fix. Could you clear your registry and do a clean stack upgrade and try once more ?

**Comment by sebastienminne** [comment]
@ShourieG test has been made after cleaning the registry 
both many worker on 1 container and 1 worker on multiple container produce the same error

**Comment by ShourieG** [comment]
@sebastienminne I was finally able to reproduce the issue locally, and the problem lies in how partial saves are done atm. Even with mutex locks, some resources are still being accessed concurrently which should not be possible. Either way in 8.11 partial save is being removed in it's current state, which will solve this issue for good.

**Comment by sebastienminne** [comment]
@ShourieG thanks for investigating, I'll give a try to 8.11
