### ISSUE TITLE
Windows packetbeat docs are wrong

### ISSUE THREAD

**Issue by nickdevdfe** [elastic/beats#36552]
I need the install instructions corrected on Packetbeat for Windows Install.

**Comment by nickdevdfe** [comment]
The url is https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-installation-configuration.html

In step 1 (Windows) It states to download a zip file, the file provided is a MSI file, and intended to be installed as a Windows application. It is not intended to be extracted at all. 

And even then, when the files are presented, none of them allow you to follow step 5.

**Comment by jrodewig** [comment]
Thanks, @nickdevdfe. I'll look into this and address it.

**Comment by jrodewig** [comment]
Thanks again for raising this @nickdevdfe. With https://github.com/elastic/beats/pull/36553, I've updated the Windows version of the Packetbeat quick start to link directly to the Windows zip archive (rather than the downloads page that also contains the .msi file). From there, you can follow the rest of the instructions as outlined.

The changes will go live a little later today.
