### ISSUE TITLE
[Filebeat] possible filestream performance regression on Windows

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#36694]
It looks like on Windows the filestream input calls `OpenFile`, `GetFileInformationByHandle`, and `CloseFile` _twice_ for each log line read (six syscalls per line read). It would be good to get a second opinion on this. The code path is through:

https://github.com/elastic/beats/blob/e4d287fbc8bbd3905ea1c110ce17fce88e7a0590/libbeat/reader/readfile/metafields.go#L64

https://github.com/elastic/beats/blob/8ff6894cab0591cc3a898d7abd6a9103e535efdd/libbeat/common/file/file_windows.go#L44-L48

https://pkg.go.dev/os#SameFile

https://cs.opensource.google/go/go/+/master:src/os/types_windows.go;l=243-249?q=loadFileId&ss=go%2Fgo

Relates: #36065

**Comment by rdner** [comment]
@andrewkroh thanks for discovering this, it comes to me as a surprise that `os.SameFile` opens and closes files on Windows, furthermore, it actually acquires a file system lock doing so.

The problem is this `loadFileId` function here:

https://cs.opensource.google/go/go/+/refs/tags/go1.21.4:src/os/types_windows.go;l=165-214

used by `os.SameFile`:

https://cs.opensource.google/go/go/+/refs/tags/go1.21.4:src/os/types_windows.go;l=231-241

As the comment states, this call is required on Windows to fill the IDs in:

```go
fs.vol = i.VolumeSerialNumber
fs.idxhi = i.FileIndexHigh
fs.idxlo = i.FileIndexLow
```

I believe our code populates the IDs elsewhere, so we should be able to get rid of this `os.SameFile` call in `setFileSystemMetadata` by storing the values once they are set for the first time.

I'll have a deeper look as soon as I can.

@pierrehilbert we should prioritise this.

**Comment by pierrehilbert** [comment]
This is currently in our next sprint.
