### ISSUE TITLE
Provide example to update beats template directly for beats -> (non-ES) use case

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#3699]
Currently, we mention in the upgrade guide to update the beats template, but the content is focused on beats -> ES use case.

https://www.elastic.co/guide/en/beats/libbeat/5.2/upgrade-mapping-template.html#upgrade-mapping-template

For users who are not sending directly to ES, eg. beats -> Kafka -> LS -> ES, beats -> LS -> ..., etc.. it will be helpful to provide an example of how they can update the index template against ES directly, eg. (for metricbeat)

```
curl -XPUT -u elastic:changeme "http://localhost:9200/_template/metricbeat" -d @metricbeat.template.json
```

Or maybe we can also consider simply cross linking back to https://www.elastic.co/guide/en/beats/metricbeat/5.2/metricbeat-template.html#load-template-manually.

**Comment by dedemorton** [comment]
This is fixed in the docs for 6.0. Users don't usually have to upgrade the mapping template unless they are upgrading from 5.5 or earlier.  For those users, we've added a section that describes how to load the template manually in 5.6 before upgrading to 6.0: https://www.elastic.co/guide/en/beats/libbeat/6.0/upgrading-5-to-6.html#upgrading-to-5.6 

Please accept my apologies for not resolving this issue sooner.
