### ISSUE TITLE
Generic TCP/UDP protocol

### ISSUE THREAD

**Issue by voelzmo** [elastic/beats#373]
I've seen that packetbeat only supports a few selected protocols and that makes sense if you want to have lots of metadata for the packets sent, e.g. HTTP headers and so on.

However, having a generic solution for tcp/udp protocols would be a nice addition, if I'm just interested in how much traffic is flowing on which port between which processes in my network. I even have processes on my machines which choose a port from the ephemeral port range without me knowing beforehand which one it will be, so I'd like to be able to even specify a range for this generic protocol to watch over.

Is this possible right now and I just cannot find it? If not, can this be implemented with reasonable effort? What would be necessary for that?
What do you think?

**Comment by voelzmo** [comment]
Any opinions on this? 

Am I doing it wrong? Maybe my use-case of getting a full picture of my traffic topology is not the intended use-case for packetbeat? Or there already is a way to achieve this and the requirement for a generic protocol is not even necessary for this?

**Comment by tsg** [comment]
HI @voelzmo, sorry for the late reply. It's not possible right now as until recently we saw Packetbeat focused on the application layer. But now we want to add this, and in our internal planning we target it for early next year. Of course we would also welcome contributions in the area :-).

**Comment by monicasarbu** [comment]
Another client asked for: "Is there a way to record Packetbeat simply with TCP traffic . We used the SMPP protocol and there is no support . It would be enough to have the data with a timestamp in Elastic."

**Comment by knobli** [comment]
+1

**Comment by kripskroll** [comment]
What would be nice is to be able to have a "network" visibility on all flows.
I would like to TAP traffic to a dedicated Packetbeat box in order to look at ALL traffic from L3 to L7.
My goal would be to have L7 performance visibility but also correlate any issue with huge bandwidth usage for example.
And then for this big bandwidth usage, I would like to be able to dig and find that there is a specific port that is using all bandwidth in 4 TCP connections. 
I suppose I need to open a new Issue for an enhancement in order to also create a feature to discover the traffic : I would like to see that all these ports are used in my traffic. I would like the solution to automatically understand that port 8181 is HTTP.

**Comment by discotroy** [comment]
I would very much value the ability to handle generic IP traffic.  Even without auto-magic parsing / sensing of protocols on non-conventional ports, it would be a great help to me.

I look forward to seeing what develops in the new year.

**Comment by andrewkroh** [comment]
I think is now duplicated by #670 which is being released in 5.0.

**Comment by voelzmo** [comment]
@andrewkroh I assume that's 2.0?

**Comment by ruflin** [comment]
@voelzmo Next release will be 5.0 (=2.0): https://www.elastic.co/v5

**Comment by voelzmo** [comment]
Ah, thanks for the link, I missed that. I guess I was additionally confused by all the `1.2.0` and `2.0` labels here in the project :)
