### ISSUE TITLE
Collect windows events remotely through Winlogbeat

### ISSUE THREAD

**Issue by Cryptyk** [elastic/beats#3730]
We have a need to collect windows events remotely as our sys-admins do not want to install beats on each and every windows system. Is there a way you can enhance winlogbeat to pull windows events remotely from a central system.

**Comment by dandrestor** [comment]
We use Windows Event Forwarding to forward logs to a central collector, and pick up the logs via winlogbeat from there.

**Comment by Cryptyk** [comment]
Was this meant for me?


Dennis McMasters | Chief Systems Architecture |+1(415)740-6957
PO Box 12011, Zephyr Cove, NV 89448
email: dennis@cryptyk.com
http://www.cryptyk.com

**Comment by dandrestor** [comment]
Yes, it's an alternative to the enhancement that you're requesting.

**Comment by andrewkroh** [comment]
I agree with @dandrestor, using the built-in features of Windows for centralize the event logs would be best. See https://msdn.microsoft.com/en-us/library/bb427443(v=vs.85).aspx

Please let us know if there is some reason you cannot use the "Windows Event Collector" for this.

**Comment by Cryptyk** [comment]
Thanks a bunch. Sorry i missed the answer.

**Comment by brian-grabau** [comment]
I have issue where remote collection makes sense, I need to work on parsing improvements for and ADFS event but no test ADFS servers, so I need to remote collect so I can see the raw log data. I agree Windows Event Forwarding is the best thing since sliced bread but remote collection would come in handy.  I will do some testing to see if I can get it to work
