### ISSUE TITLE
[Filebeat] Netflow input - add input metrics

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#37762]
**Describe the enhancement:**

Expose metrics from each instance of the netflow input. Users should be able to query the [HTTP endpoint](https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html#_inputs) (e.g. `curl 'http://localhost:5066/inputs/?type=netflow&pretty'`) and get back metrics from each instance of the netflow input.

This input exposes some global metrics now, but these are summed across all instances of the input.

https://github.com/elastic/beats/blob/d4d2ddce3230f21f01a19afdb836626f7b0af4b5/x-pack/filebeat/input/netflow/input.go#L33-L35

In my opinion the same metrics from the [UDP input](https://github.com/elastic/beats/blob/4506e55d50f9ab72164ff55eae7ec0c19a1fd5d5/filebeat/input/udp/input.go#L173-L186) should exist for the Netflow input plus some netflow specific metrics like

- discarded_events_total - The number of events dropped by this input.
- decode_errors_total - The total number of decode errors observed while decoding data in an input.
- open_connections - Active number of netflow sessions (gauge). _UDP doesn't have "connections" but as a metric I feel the meaning could be applied consistently in other inputs._

**Describe a specific use case for the enhancement or feature:**

The feature would be used for monitoring and troubleshooting purposes.

**Comment by pkoutsovasilis** [comment]
Hi @andrewkroh thank you for the initial investigation. From a quick look having metrics per netflow instance makes a lot of sense and I believe it will indeed be extra helpful in monitoring but especially in troubleshooting purposes. 

Now some quick questions:
> In my opinion the same metrics from the [UDP input](https://github.com/elastic/beats/blob/4506e55d50f9ab72164ff55eae7ec0c19a1fd5d5/filebeat/input/udp/input.go#L173-L186) should exist for the Netflow input

@efd6 has already done the heavy-lifting for us in `udp` input (thank you 🙂) but should we just duplicate his code for the `netflow` input or try to make both `udp` and `netflow` use the same code? Although it may sound weird, I lean towards the first option (`duplication`) as these two are different inputs and are susceptible to different metricsets even though currently they significantly overlap

> open_connections - Active number of netflow sessions (gauge). UDP doesn't have "connections" but as a metric I feel the meaning could be applied consistently in other inputs.

Now if I don't miss anything netflow sessions are present in `v9` and `ipfx` which are created by [SessionMap](https://github.com/pkoutsovasilis/beats/blob/ecaf12cd07b5e15f00f7dd9b736946ed364544c1/x-pack/filebeat/input/netflow/decoder/v9/session.go#L140) and they are deemed as expired (inactive?!) by an [interval-based loop](https://github.com/pkoutsovasilis/beats/blob/ecaf12cd07b5e15f00f7dd9b736946ed364544c1/x-pack/filebeat/input/netflow/decoder/v9/session.go#L187). So to capture the _open_connections_ in the context of `netflow` I assume we would want a _gauge_ metric that increases when a session is created and decreased when a session is cleaned from the SessionMap?

**Comment by pkoutsovasilis** [comment]
@andrewkroh @efd6 (since you are the original author of tcp and udp metrics 🙂) I have pushed this commit https://github.com/elastic/beats/pull/38055/commits/fa059a398534e84ec1b70df050766b729e6e8b10 that essentially moves the UDP and the TCP metrics (this last one was necessary to maintain the `procnet` package as `internal`) to the `inputsource` package. Thus each input can instantiate and utilise the same UDP and TCP metrics according to it's need. When you get the chance, have the look and tell me if this seems okay with you two

**Comment by efd6** [comment]
Suggest rather putting them both in internal as either two packages, so that you have e.g. `.../internal/tcpmetrics.New`, or one package that can subsume procnet, e.g. `.../internal/netmetrics.NewTCP`. The only reason procnet exists is to be shared between the two, so if there can be only one, this need goes away and the code locality improves.
