### ISSUE TITLE
7.17 - MacOS Unit tests fail: server_test.go:192

### ISSUE THREAD

**Issue by sharbuz** [elastic/beats#37950]
The issue was found during the pipeline's migration process from Jenkins to Buildkite.
The issue is related to the  `7.17` branch and MacOS Unit-tests

example of the issue: https://buildkite.com/elastic/beats-metricbeat/builds/2364#018d8db5-bb19-457c-a173-d2e0203730fc/567-1004

```
=== Failed
=== FAIL: metricbeat/module/envoyproxy/server TestFetchTimeout (0.05s)
    server_test.go:192:
        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1707479524315693131/elastic/beats-metricbeat/metricbeat/module/envoyproxy/server/server_test.go:192
        	Error:
        	Test:       	TestFetchTimeout
        	Messages:   	expected an error containing '(Client.Timeout exceeded'. Got [error in http fetch: error making http request: Get "http://127.0.0.1:49424/stats": context deadline exceeded]
=== Errors
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:143:1: note: 'IOMasterPort' has been explicitly marked deprecated here
/Users/admin/go/pkg/mod/github.com/shirou/gopsutil@v3.20.12+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
```

**Comment by sharbuz** [comment]
@pazone, please take a look at the issue, could it be related to slow BK Mac agents?

**Comment by oakrizan** [comment]
After all during migration disabled tests were enabled, double checked if the `TestFetchTimeout` still fail. 

**Result:** Test is running successfully and is not disabled.
BK build: https://buildkite.com/elastic/beats-metricbeat/builds/8089#0191080f-b539-4532-a757-00612bed1cd0/1892-1997
```
ok  	github.com/elastic/beats/v7/metricbeat/module/envoyproxy/server	0.413s	coverage: 73.2% of statements
````
[beats-metricbeat_build_8089_mac-metricbeat-macos-x64-64-unit-tests.log](https://github.com/user-attachments/files/16439508/beats-metricbeat_build_8089_mac-metricbeat-macos-x64-64-unit-tests.log)

 `TestFetchTimeout`
https://github.com/elastic/beats/blob/f13893e506d994823b180c458fceb30956c450bd/metricbeat/module/envoyproxy/server/server_test.go#L154-L196

Closing the issue, since is not actual anymore.
