### ISSUE TITLE
Inconsistency of representation diskio from windows and linux

### ISSUE THREAD

**Issue by Elufimov** [elastic/beats#3798]
For confirmed bugs, please report:
- Version: metricbeat 5.2.2
- Operating System: windows server 2012 r2, ubuntu server 16.04

There is inconsistency between diskio Fields from linux and from windows machines. From linux hosts we get cumulative value, however from windows hosts we get "normal" value. It applies to 
```
system.diskio.read.count
system.diskio.write.count
system.diskio.read.bytes
system.diskio.write.bytes
system.diskio.read.time
system.diskio.write.time
system.diskio.io.time
```

**Comment by tsg** [comment]
Pinging @andrewkroh.

**Comment by andrewkroh** [comment]
Yeah, it does look inconsistent.

On Windows the third party lib is using this WMI query to get the data: `SELECT * FROM Win32_PerfFormattedData_PerfDisk_LogicalDisk`

Then is just writes the averaged values into the fields that are supposed to be counters. https://github.com/shirou/gopsutil/blob/v2.0.0/disk/disk_windows.go#L144-L152

From Windows docs:

> Classes derived from Win32_PerfRawData contain raw, or "uncooked" performance data, and are supported by the Performance Counter provider. In contrast, classes derived from Win32_PerfFormattedData contain "cooked", or formatted data...

Maybe we can find a table that has raw values. Anyone want to research this?

**Comment by Elufimov** [comment]
I also think these fields do not work right. I did small experiment, copied files to windows machine and this action was not reflected in elastic index.

**Comment by andrewkroh** [comment]
The averaging from Windows is basically acting as a low-pass filter so those values are not very useful because you won't be able to observe high frequency signals in the data. Getting at the raw data (with relatively high sampling period) would solve this.

**Comment by Elufimov** [comment]
Can I hope to see fix of this? We have mixed infrastructure (linux + windows) and this bug preventing us from bits adoption.

**Comment by maddin2016** [comment]
Hi @andrewkroh. Now our perfmon metricset is merged what do you think of to use this as an internal API to collect these data. The next feature I would add to metricset is to get raw data values.

**Comment by andrewkroh** [comment]
@maddin2016 If it's possible to retrieve the raw values through perfmon then I think that would be a great solution to this issue.

**Comment by maddin2016** [comment]
@andrewkroh, can you please add this to #3828 so we don't miss this?

**Comment by ruflin** [comment]
I would not add it into #3828 as it is not really a cleanup to perfmon metricset but enhancing a feature of an other metricset. I think it is perfectly tracked here as this is the issue that will be closed, in case there will be a PR for it.

**Comment by andrewkroh** [comment]
FYI: Another report for diskio problems on Windows due to the usage of WMI. https://discuss.elastic.co/t/system-diskio-io-time-0-on-windows/85508

**Comment by maddin2016** [comment]
What do you think of adding a helper which collect these counters through the perfmon api? Or is it possible to add a `diskio_windows.go` file?

**Comment by andrewkroh** [comment]
It should be possible to have a separate implementation for windows by using build tags (i.e. `diskio_windows.go`).

**Comment by Elufimov** [comment]
Is this bug was fixed in 6.0?

**Comment by martinscholz83** [comment]
@andrewkroh, i'm currenty implement a solution to retrieve the raw values with perfmon.

**Comment by andrewkroh** [comment]
There is a sample document in the diskio docs: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-diskio.html#_fields_57

I don't have a sample from Windows, but the main difference that the values coming from WMI are averages rather than cumulative. On *nix we get an ever increasing counter (until rollover) that contains the total number for all time. So the differences is basically that on *nix we have counters and on Windows we have gauges ([counter vs gauges](https://prometheus.io/docs/concepts/metric_types/)).

**Comment by martinscholz83** [comment]
@andrewkroh, i have started to implement `diskio_windows` to collect these counters with perfmon. See [here](https://github.com/martinscholz83/beats/blob/feature/windows-diskio-perfmon/metricbeat/module/system/diskio/diskio_windows.go). But I'm afraid that this can not solve the main problem between counters and gauges. With performance counters mostly you only get real time values. There are some counters which stores values since the system is booted but not for logical disk. So if we want cumulative values perfmon is not the right tool. I think we should use the [DeviceIoControl function](https://msdn.microsoft.com/de-de/library/windows/desktop/aa363216%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). Together with [IOCTL_DISK_PERFORMANCE](https://msdn.microsoft.com/de-de/library/windows/desktop/aa365183%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) control code which gives us real counts for a [disk](https://msdn.microsoft.com/de-de/library/windows/desktop/aa363991%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

**Comment by martinscholz83** [comment]
Two questions.

1. Should i keep the new created function `PdhGetRawCounterArray`?

1. `syscall` has the functions `DeviceIoControl` and `CreateFile`. To get the local drive names we need a function like `GetLogicalDriveStrings`. This function is not implemented in `syscall`. So question is to implement all functions we need on our own or to use existing functions from `sycall`?

**Comment by andrewkroh** [comment]
> Should i keep the new created function PdhGetRawCounterArray?

Why would you remove it? Isn't it used by the perfmon metricset?

> So question is to implement all functions we need on our own or to use existing functions from sycall?

Reuse what's already provided if possible. So only add way to use `GetLogicalDriveStrings`.

**Comment by martinscholz83** [comment]
`PdhGetRawCounterArray` and `PdhGetRawCounterValue` are not used by perfmon. We added these functions to offer an API if you want to calculate Raw values. But maybe in the future we can add an option for `perfmon` to use it?!

**Comment by Elufimov** [comment]
Any news on this issue?

**Comment by marekduciuc** [comment]
It would be cool to investigate if other metrics like bellow have equivalent on windows.
system.diskio.iostat.read.request.merges_per_sec
system.diskio.iostat.request.avg_size
