### ISSUE TITLE
Upgrade AWS SDK to support EKS Pod Identity 

### ISSUE THREAD

**Issue by bartoszcisek** [elastic/beats#38174]
### Describe the enhancement

EKS pod identity is an improved way to grant selected access for pods to AWS resources. Support for pod identity starts at [1.47.11 ASW SDK version](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html).  

### Describe a specific use case for the enhancement or feature

Granting elastic agent access to RDS DB for elastic agent AWS integration.  

### What is the definition of done?

Elastic agent uses AWS SDK in version higher that 1.47.11.

**Comment by mholttech** [comment]
I was literally just looking for this. Hope to see the sdk version bumped soon.

**Comment by cucxabong** [comment]
Hi guys,

Do you have any update on this?

**Comment by mholttech** [comment]
Any update on this?

CC: @bvader

**Comment by zmoog** [comment]
Quick update on this issue.

Since we bumped the AWS SDK during standard update cycle, we are testing a recent version of Elastic Agent (8.15.3) to double-check it support EKS Pod Identity.

So far we tested the following inputs.

Logs:
- cloudwatch-logs: OK

Metrics:
- cloudwatch: OK

We still need to fully test the following:

Logs:
- aws-s3 (SQS mode)
- aws-s3 (S3 polling mode)

**Comment by yavor-ivanov-covantis** [comment]
This one seems to be resolved

**Comment by zmoog** [comment]
EKS Pod Identity is available starting at least from 8.15.3. 

I created a public issue https://github.com/elastic/beats/issues/41775 to track the need to update the official docs for Beats and the Elastic Agent integrations.

Feel free to reopen if you run into issues or comment if you have questions.
