### ISSUE TITLE
[Security-Linux Platform Integrations]  Auditbeat missing Session View Process fields 

### ISSUE THREAD

**Issue by Omolola-Akinleye** [elastic/beats#38955]
Audibeat is missing process fields for Session View which is causing empty rows Sessions and Events Table.

I was testing the Session View on FE with auditbeat on my [PR](https://github.com/elastic/kibana/pull/179985). I just noticed some auditbeat events did not have Session View Icon. When I expand the event details,  I saw the process.entry_leader.entity_id  field  was missing.

To test  bug
See [Session View Cloud Credentials](https://p.elstc.co/paste/Ci0L3gSA#ASz3bkZps3AsJQyDlHDagExU2LK0-cLTuqc+aq/sf1E)

Steps to Reproduce
1. Go to Discover
2. Choose audibeat dataview
3. Apply fields not process.entry_leader.entity_id : * and event.action : "executed"
4. Click arrow icon and expand document details
<img width="1543" alt="image" src="https://github.com/elastic/beats/assets/17135495/eb48f294-cd47-4451-8d1a-debc40593c44">

1. Go to Explore > Hosts > Events or  Explore > Hosts > Sessions

Sessions are also Missing
![image](https://github.com/elastic/beats/assets/17135495/9c1716dd-9fd8-4efd-9228-b5da23db9dbf)
Events are also missing
<img width="1242" alt="image" src="https://github.com/elastic/beats/assets/17135495/893d3913-7ac8-4854-8da3-7c747d936264">

DOD
* For Session View events and sessions, process fields should be populated. Audibeat Index to filter documents that don't have `process.entry_leader.entity_id`  or missing Session View process fields.

**Comment by mjwolf** [comment]
This `host.pid_ns_ino` field conflict is coming from cloud-defend, not Beats; I've created an issue in the cloud-defend repo to track that. The other conflicts will be fixed by https://github.com/elastic/beats/pull/38994

**Comment by mjwolf** [comment]
From what I've seen in my testing, the processor will fail to enrich a process when the process is missing from the processdb.

I have [this branch](https://github.com/mjwolf/beats/tree/session-view-missed) with some additional logging on the error when enrichment fails, every time I've seen failure it's because the process is missing from the processdb.  It also attempts to find the process with procfs, if it is missing from the DB. 

There could be two potential problems here:

1. A timing issue when starting the processor. When starting, the processor with scrape procfs to fill in the process DB. There could be a gap between this scraping and when ebpf takes over, and processes will be missed from the DB. Most of the missed happen close to when the processor is started, so I think this is happening.
2. I've seen the enrich event run on processes that are not in the processdb, well after the processor is started. It seems like a timing issue where processes from ebpfevents are inserted into the DB after enrich has already been run on them.

**Comment by mjwolf** [comment]
With https://github.com/elastic/beats/pull/39173, the problem of missing processes in the DB wasn't completely fixed.

I had a theory that the processor was getting the event before the ebpf backend had inserted it into the DB, since auditbeat and ebpf aren't synced. In [this branch](https://github.com/mjwolf/beats/tree/session-view-sync-bpf-events), when processing an event for a process that isn't in the processdb, the processor would wait for the process to be inserted. Even with a delay to wait for the process to be inserted, it never arrived. So the problem isn't a timing issue where the processor is enriching events before ebpf inserts them

One other thing to note about the original query; this includes failed exec calls from auditd (for instance the new executable file isn't found). Since the exec failed, it shouldn't be in the session viewer. This query should find the processes that should be enriched but weren't `not process.entry_leader.entity_id : * and event.action : "executed" and not auditd.result: "fail"`
