### ISSUE TITLE
GCP metricset does not collect Google Cloud Org ID and display name 

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#39203]
It seems the compute metricset [intentionally sets](https://github.com/elastic/beats/blob/bda40535cf0743b97017512e6af6d661eeef956e/x-pack/metricbeat/module/gcp/timeseries_metadata_collector.go#L54-L62) (1) both `cloud.account.name` and `cloud.account.id` (2) with the value of the project_id resource label (3):

![image](https://github.com/elastic/beats/assets/25941/40954a8c-9e74-4c5f-ad14-c48c98d23fea)

Users expectation is to have:

- the project ID in the `cloud.project.id` field (currently missing)
- the Google Cloud ORG ID in the `cloud.account.id` field (currently contains the project ID)
- the Google Cloud ORG display name in the `cloud.account.name` field (currently contains the project ID)

These expectations are in line with the ECS semantics:

- `cloud.project.id`: [schemas/cloud.yml#L133-L151](https://github.com/elastic/ecs/blob/146c96aae530af83b4d3f7283cf2f081fb51f442/schemas/cloud.yml#L133-L151)
- `cloud.account.id` and `cloud.account.name`: [schemas/cloud.yml#L98-L119](https://github.com/elastic/ecs/blob/146c96aae530af83b4d3f7283cf2f081fb51f442/schemas/cloud.yml#L98-L119)

**Comment by lalit-satapathy** [comment]
Assigned @Linu-Elias

**Comment by zmoog** [comment]
Here is the reference to the cloud fields in ECS to double-check that the `cloud.*` field semantics are in line with ECS.

https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html

**Comment by gpop63** [comment]
@zmoog IIRC getting organization info requires an additional API call, right?

**Comment by zmoog** [comment]
> IIRC getting organization info requires an additional API call, right?

Yep! Unfortunately, I didn't keep this info about my research when I created the issue, but I remember the same info.

So I guess we need an additional API call to collect the organization info for each unique project.

**Comment by endorama** [comment]
A couple of notes :)

GCP resources are organized in a hierarchy where at the root there is the organization. `resourcemanager.GetProject` returns a Parent but to reach the root organization you would need to traverse up the tree up to the root node with multiple API calls.
Would be better to use the [getAncestry](https://cloud.google.com/resource-manager/reference/rest/v1/projects/getAncestry) API if possible, [`ProjectService.GetAncestry`](https://pkg.go.dev/google.golang.org/api/cloudresourcemanager/v1#ProjectsService.GetAncestry) in the Golang SDK, which returns a [`GetAncestryResponse`](https://pkg.go.dev/google.golang.org/api/cloudresourcemanager/v1#GetAncestryResponse) that contains a list of parents. The last is the root/org.

Projects may not be part of an organization (as mentioned by ["Create a project"](https://cloud.google.com/resource-manager/docs/creating-managing-projects#creating_a_project) docs, is possible to have the "No organization" value when selecting project location). I'm not sure how this works in detail because there is no clear documentation about it. I've seen it related to managed and non-managed Google accounts, but in general is considered a bad practice because of multiple limitations (especially around IAM management). Still is a possible corner case that must be handled.

**Comment by Linu-Elias** [comment]
Thanks @endorama, we are now using [ProjectsService.GetAncestry](https://pkg.go.dev/google.golang.org/api/cloudresourcemanager/v1#ProjectsService.GetAncestry) in which we get the root/org ID and get the particular organization details (specifically aiming to collect organization name) using- [OrganizationsService.Get](https://pkg.go.dev/google.golang.org/api/cloudresourcemanager/v1#OrganizationsService.Get) 

As we now know that projects may not be part of an organization, and all our projects fall into "no organization" category so [OrganizationsService.Get](https://pkg.go.dev/google.golang.org/api/cloudresourcemanager/v1#OrganizationsService.Get) doesn't really return much. We would need projects which are a part on an actual organization for testing purpose.

**Comment by zmoog** [comment]
@Linu-Elias I have a Google account with [Cloud Identity Free](https://cloud.google.com/identity/docs/editions) which allows me to have an actual Google Cloud organization. We can start by using this for testing.

**Comment by Linu-Elias** [comment]
@zmoog, could you please share the details of the Google account? That would be helpful. If you have an existing project that belongs to an organization, sharing the credentials of a service account with the necessary permissions would also work.

**Comment by zmoog** [comment]
> could you please share the details of the Google account? That would be helpful. If you have an existing project that belongs to an organization, sharing the credentials of a service account with the necessary permissions would also work.

Yep! The quickest option is to share a service account. Let me set up one for you.

**Comment by zmoog** [comment]
Hey @Linu-Elias, I set up the following structure, and there is a service account with access to the "My First Project" project.

![CleanShot 2024-08-05 at 18 19 52@2x](https://github.com/user-attachments/assets/00d38aba-1390-4ef9-9fda-ed4f452eb950)

I shared the service account details using 1Password. See the DM for the link.

In the project, there is a VM running and I can collect `compute` metrics using the following `gcp` module config:

```yaml
- module: gcp
  metricsets:
    - compute
  region: "europe-west12"
  project_id: "<redacted>"
  credentials_json: '<redacted>'
  exclude_labels: false
  period: 1m
```

![CleanShot 2024-08-05 at 18 24 53@2x](https://github.com/user-attachments/assets/571331e1-7010-4a48-ad6a-9142b47a2bf5)
