### ISSUE TITLE
[Agentbeat] incorrect seccomp policy 

### ISSUE THREAD

**Issue by pkoutsovasilis** [elastic/beats#39754]
Now that `AgentBeat` wraps all beats under one single entrypoint, there is the possibility of colliding allowed/disallowed syscalls as different beats extend the same seccomp policy (default). Specifically on `arm64` when running Auditbeat FIM, through `AgentBeat`, with either the `kprobes` or `ebpf` BE, I get a respective permission denied for different invoked syscalls. One particular point that surely causes a collision is the file [here](https://github.com/elastic/beats/blob/main/heartbeat/security/policy_linux_arm64.go#L173) in `Heartbeat` where it overrides completely the default seccomp policy for `arm64` and just applies its own (credits @andrewkroh for bringing this to my attention). 

Info:
- Version: 8.14.0-e2b61b56
- Operating System: Ubuntu 22.04.4 LTS (5.15.0-107-generic)

**Comment by andrewkroh** [comment]
The primary impact here is on arm64 agentbeat. The policy went from a very narrow deny-list (execveat) to an allow-list tailored that is tailored to heartbeat syscall usages. There are likely syscalls used by other Beats that are not allowed by the heartbeat policy for arm64.

**Comment by cmacknz** [comment]
That function call needs to be pulled out of an `init` function if it can.

Doing a search for similar uses there is a template that does the same thing but I haven't tracked down whether or where we build it or not.

https://github.com/elastic/beats/blob/de4958365f45171aedc100c8388138e1246cbd64/libbeat/common/seccomp/policy.go.tpl#L13-L16

**Comment by emilioalvap** [comment]
Indeed, heartbeat requires a locked-down profile due to the nature of browser monitors on all platforms.

@pkoutsovasilis, please let us know if @elastic/obs-ds-hosted-services can be of any help on this issue.

**Comment by andrewkroh** [comment]
Here's a draft PR to change Heartbeat's initialization. https://github.com/elastic/beats/pull/39763

**Comment by pkoutsovasilis** [comment]
> Indeed, heartbeat requires a locked-down profile due to the nature of browser monitors on all platforms.
> 
> @pkoutsovasilis, please let us know if @elastic/obs-ds-hosted-services can be of any help on this issue.

@emilioalvap reviewing the PR of @andrewkroh  to tackle this particular case should be more than enough to help 🙂

**Comment by andrewkroh** [comment]
To prevent Auditbeat's customizations (calls to `seccomp.ModifyDefaultPolicy`) from spilling over into other Beats of Agentbeat (making them more permissive) we should consider moving those calls into the beat `Initialize` call chain (see below) instead of `init()`. This will degrade the code locality because the syscall exceptions won't be next to the code that requires them, but it would help address this.

https://github.com/elastic/beats/blob/930410642ebaf67a18c2a4e77256ac128b45bb21/auditbeat/cmd/root.go#L64

https://github.com/elastic/beats/blob/930410642ebaf67a18c2a4e77256ac128b45bb21/x-pack/auditbeat/cmd/root.go#L69
