### ISSUE TITLE
docs url needs update

### ISSUE THREAD

**Issue by lcgogo** [elastic/beats#40018]
such as

# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/filebeat/main/filebeat-module-nginx.html

the url is 404, think changed to 
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-nginx.html

**Comment by jlind23** [comment]
@kilfoyle any input here?

**Comment by kilfoyle** [comment]
@lcgogo Thanks for reporting this. I believe that at one time `/main/` used to appear in the Elastic docs URLs, but it was deprecated some time ago. This should be true of most or all of the Elastic docs pages.

Taking the Javascript client "Install" page as a random example...

Correct, working link:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/installation.html

Incorrect, non-working link:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/main/installation.html

If you find any non-working links on the docs pages that still use `main` please let me know and I'll try to get them fixed. However, since the changed URL is not specific to this one filebeat page, I will close this issue. Please reopen with details if you think something needs fixing.
