### ISSUE TITLE
[libbeat][fingerprint processor] - Add support for canonical ordering of keys based on config option

### ISSUE THREAD

**Issue by ShourieG** [elastic/beats#40094]
**Describe the enhancement:** Currently the fingerprint processor inside beats does not canonically sort the keys when creating the fingerprint. This can lead to the problem of different fingerprints for the same objects if the canonical order of keys is different. 
The fingerprint processor inside elasticsearch already has [this feature](https://github.com/elastic/elasticsearch/blob/1ec137db8f5b1ef050f9c394411ef686bfbe2570/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/FingerprintProcessor.java#L65) and it should be implemented here also.

**Describe a specific use case for the enhancement or feature:** Reduce duplication issues resulting from unique fingerprint for equivalent objects with different canonical orders.

We need to implement this based on an opt-in approach and should not make it a blanket behaviour as it could cause an initial wave of duplicates wherever fingerprints are used.

**Comment by andrewkroh** [comment]
While this would have been nice to have from the beginning, I don't think the processor needs sorting of the configured keys. This is only needed in what I would consider are edge-cases. They are

- building the configuration of the fingerprint processor dynamically (google workspace did this)
- two or more instances of fingerprint but you didn't order the keys the same (you can fix this by aligning the config)

The feature that is missing IMO is the ability to hash values that are objects or arrays. This is also a feature that elasticsearch ingest node [provides](https://github.com/elastic/elasticsearch/blob/1ec137db8f5b1ef050f9c394411ef686bfbe2570/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/FingerprintProcessor.java#L94-L122). And this feature could have addressed the Google Workspace issue because the fingerprint processor could be configured with name of an array field (e.g. `fields: [json.events]`) and the processor would traverse the elements in a consistent order to produce a hash.

But given that we are focused on building all new modules and integrations using ingest node processing, I wouldn't prioritize that feature either. I'm going to close this because I don't think we should take any action on this.

Relates: https://github.com/elastic/beats/pull/40055/files#r1661656330
