### ISSUE TITLE
Filestream clean_inactive does not work as expected

### ISSUE THREAD

**Issue by ijardillier** [elastic/beats#40178]
Default value for **clean_inactive** should be **0** (disabled) as explained in the filebeat.reference.yml (no default value indicated in the documentation), but **registry entries are removed after 30 min of inactivity**.

Tested with rpm on Redhat 8 and with the official docker image of Filebeat.
Not working as expected on 8.14.2 but was working with the previous versions we used, ie 8.9.1 and 8.11.4.

### How to reproduce

1. Create the following filebeat.yml

```yaml
filebeat.inputs:
  - type: filestream
    id: test-clean-inactive
    enabled: true
    paths:
      - /var/log/test.log

output.elasticsearch:
  enabled: true
  hosts: ["es01:9200"]

setup.ilm.enabled: true
setup.template.enable: true

logging.level: debug
```

1. Start Filebeat

```bash
./filebeat &
```

1. Create the log file

```bash
echo "Test 1">> /var/log/test.log
```

Wait a few seconds, like 10s, for the file to be harvested (you can check the output and/or logs). The "Test 1" event is created.

The registry file contains the following lines:

```json
{"op":"set","id":1}
{"k":"filestream::test-clean-inactive::native::2099010-66309","v":{"ttl":0,"updated":[281470681743360,18446744011573954816],"cursor":null,"meta":{"source":"/var/log/test.log","identifier_name":"native"}}}
{"op":"set","id":2}
{"k":"filestream::test-clean-inactive::native::2099010-66309","v":{"ttl":1800000000000,"updated":[392033801,1720624761],"cursor":null,"meta":{"source":"/var/log/test.log","identifier_name":"native"}}}
{"op":"set","id":3}
{"k":"filestream::test-clean-inactive::native::2099010-66309","v":{"ttl":1800000000000,"updated":[392202394,1720624761],"cursor":{"offset":21},"meta":{"source":"/var/log/test.log","identifier_name":"native"}}}
```

We can see that ttl is defined to 1800000000000 nanoseconds, ie 30min.

2. Wait for the effective inactive delay, ie about 30 min, and the next store cleanup.

3. Look at the logs for the store clean up messages and the registry for the remove operation

You will see that entries were removed, although *clean_inactive* should be disabled.

In filebeat log in debug mode:

```json
{"log.level":"debug","@timestamp":"2024-07-10T15:54:21.392Z","log.logger":"input","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.gcStore","file.name":"input-logfile/clean.go","file.line":85},"message":"1 entries removed","service.name":"filebeat","input_type":"filestream","ecs.version":"1.6.0"}
```

In the registry:

```json
{"op":"remove","id":4}
{"k":"filestream::test-clean-inactive::native::2099010-66309"}
```

4. Add a new line to our test.log

```bash
echo "Test 2">> /var/log/test.log
```

Wait a few seconds, like 10s, for the file to be harvested (you can check the output and/or logs). The "Test 2" event is well created but "Test 1" is now duplicated. Log file has been read from offset 0...

### Possible cause

We did a bit of investigation for the possible cause and we found that the **Create** method in **manager.go** initializes **CleanInactive** with **DefaultCleanTimeout**.

```go
// Create builds a new v2.Input using the provided Configure function.
// The Input will run a go-routine per source that has been configured.
func (cim *InputManager) Create(config *conf.C) (v2.Input, error) {
	if err := cim.init(); err != nil {
		return nil, err
	}

	settings := struct {
		ID             string        `config:"id"`
		CleanInactive  time.Duration `config:"clean_inactive"`
		HarvesterLimit uint64        `config:"harvester_limit"`
	}{CleanInactive: cim.DefaultCleanTimeout}

        // ...
}
```

This DefaultCleanTimeout is initialized to 30 minutes in the **init** method in **manager.go**.

```go
func (cim *InputManager) init() error {
	cim.initOnce.Do(func() {
		if cim.DefaultCleanTimeout <= 0 {
			cim.DefaultCleanTimeout = 30 * time.Minute
		}

		// ...
}
```

### Related PR

This issue may be related to a recent PR:
[#38632](https://github.com/elastic/beats/pull/38632)

**Comment by belimawr** [comment]
@ijardillier Thank you for such a detailed analysis :heart_eyes: 

Indeed the Filestream input is now removing states after 30min of inactivity even when they're not ignored. Which causes the re-ingestion problem you mentioned.

The store clean up has been broken since a long time, it got fixed by https://github.com/elastic/beats/pull/38488, then https://github.com/elastic/beats/pull/38632 fixed the configuration keys, allowing it to be user-configured.

Being able to configure it is great because we can work around this behaviour by just setting `clean_inactive` to a value large enough that the TTL clean up won't affect the file, thus restoring the behaviour prior `v8.14.2`

**Comment by belimawr** [comment]
Elaborating more on the work around I mentioned on https://github.com/elastic/beats/issues/40178#issuecomment-2225918060.

Given that the previous behaviour was to never remove registry entries due to TTL, the way to restore it is to set the TTL to something **really large** like 5 years: `clean_inactive: 43800h0m0s`

**Comment by ijardillier** [comment]
Thanks !

**Comment by ablnk** [comment]
@belimawr @ijardillier I know that `log` input type is deprecated now, so just for awareness - I've encountered a problem of registry entries being removed after 30 min of inactivity with filebeat v8.17.3. Interestingly, the issue is intermittent, it worked fine initially, but after restarting filebeat the other day, hit the issue. I set then `clean_inactive: 0` in the filebeat config, the harvester kept the file active for ~44 minutes, but then `"message":"File is inactive. Closing because close_inactive of 5m0s reached.` appeared again.
