### ISSUE TITLE
x-pack/heartbeat: "build constraints exclude all Go files" for Win tests

### ISSUE THREAD

**Issue by oakrizan** [elastic/beats#40502]
## Problems with tests execution

* **Test Name:** NA
* **Link:** Link to file/line number in github.
* **Branch:** main (related PR: https://github.com/elastic/beats/pull/39690)
* **Artifact Link:** Buildkite build: https://buildkite.com/elastic/beats-xpack-heartbeat/builds/4873#01914ba3-47b1-47c5-b885-dd42a11c2510

* **Notes:** Additional details about the test. e.g. theory as to failure cause
This problem occurred after migration from Jenkins to Buildkite.
Required to be solved, since need to check if https://github.com/elastic/beats/issues/23958 && https://github.com/elastic/beats/issues/23957 are valid for Buildkite.

### Stack Trace

```
>> go test: Unit Testing
exec: gotestsum --no-color -f standard-quiet --junitfile build/TEST-go-unit.xml --jsonfile build/TEST-go-unit.out.json -- -covermode=atomic -coverprofile=build\TEST-go-unit.cov ./...
go: downloading github.com/kortschak/utter v1.5.0
package github.com/elastic/beats/v7/x-pack/heartbeat/include
	imports github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser: build constraints exclude all Go files in C:\buildkite-agent\builds\bk-agent-prod-gcp-1723551214720959957\elastic\beats-xpack-heartbeat\x-pack\heartbeat\monitors\browser
=== Errors
package github.com/elastic/beats/v7/x-pack/heartbeat/include
	imports github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser: build constraints exclude all Go files in C:\buildkite-agent\builds\bk-agent-prod-gcp-1723551214720959957\elastic\beats-xpack-heartbeat\x-pack\heartbeat\monitors\browser
```

**Comment by rowlandgeoff** [comment]
During the migration of beats-ci from Jenkins to Buildkite, a number of tests were failing consistently due to issues unrelated to the migration. Those tests were disabled to stabilize the CI, with the intent to revisit them post-migration. @oakrizan has reviewed them all in her draft PRs linked above in the description, and has opened tickets such as this one to highlight to the product teams the tests that are currently still disabled and could use some attention.
