### ISSUE TITLE
[metricbeat:elasticsearch module] Missing jvm.mem.pools metrics from node.stats

### ISSUE THREAD

**Issue by przemek-grzedzielski** [elastic/beats#40539]
I found that metricbeat v 8.13.4 is not ingesting some of the `elasticsearch.node.stats.jvm.mem.*` metrics, in particular: `elasticsearch.node.stats.jvm.mem.pools.old.max.bytes` and `elasticsearch.node.stats.jvm.mem.pools.old.used.bytes`.

Note that these (and other missing metrics) are listed in the [Metricbeat 8.x documentation](https://www.elastic.co/guide/en/beats/metricbeat/8.13/exported-fields-elasticsearch.html). They're also present in the mappings: 
https://github.com/elastic/beats/blob/46fd21cdb4a32d23813e1401bbd085e760734905/metricbeat/module/elasticsearch/node_stats/_meta/fields.yml#L179

https://github.com/elastic/beats/blob/46fd21cdb4a32d23813e1401bbd085e760734905/metricbeat/module/elasticsearch/node_stats/_meta/fields.yml#L164

They're also exposed via Elasticsearch APIs as per the [node_stats API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html#cluster-nodes-stats-api-response-body) (also tested that this is the case).

@nkvoll traced the changes back to [this commit](https://github.com/elastic/beats/commit/a78436b3b986da8957451ce767721822cf4129c7#diff-91f42a45ae57390892f556f5345a0ea00ea88f7a2fbc42c69c53c0352f8bd173) or [this Pull Request](https://github.com/elastic/beats/pull/24427). 

It seems that these fields have been removed inadvertently and the ask is that they be brought back since a number of services depend on them. 

---
For confirmed bugs, please report:
- Version: 8.13.4
- Operating System: Ubuntu 22.04

**Comment by consulthys** [comment]
@przemek-grzedzielski The actual PR where the `elasticsearch.node.stats.jvm.mem.pools.*` fields were actually removed is https://github.com/elastic/beats/pull/23901 but the PR doesn't contain any reason why. 

My hunch is that those fields have been removed because they were nowhere used in the Stack Monitoring UI, which looking at the SM UI [source code](https://github.com/elastic/kibana/blob/main/x-pack/plugins/monitoring/server/lib/metrics/elasticsearch/metrics.ts) seems to confirm this.

Maybe @pickypg has an idea or some background context since he was involved at that time.
