### ISSUE TITLE
Support GCP region for Vertex AI

### ISSUE THREAD

**Issue by ishleenk17** [elastic/beats#41360]
Add suport of GCP region/zone for the new GCP service of Vertex AI

**Comment by gpop63** [comment]
We could consider exposing the zone/region/location label in the configuration, allowing it to be set from the integration side rather than modifying the beats code for each service. This configuration setting can be hidden from the user to avoid unnecessary complexity.

This approach would ensure that if a new service is added in the future with a different zone/location label, we won’t need to modify the beats code again. The label can be set through the integration configuration instead.

**Comment by ishleenk17** [comment]
> We could consider exposing the zone/region/location label in the configuration, allowing it to be set from the integration side

Thats what I plan to do @gpop63

**Comment by ishleenk17** [comment]
For this specific usecase, I am adding support for vertexai alone to meet the FF of 8.16.1
Created a separate issue to work on generic support for region.zone for all GCP services.
