### ISSUE TITLE
[libbeat][outputs/logstash] - The logstash output waits for acknowledgements forever

### ISSUE THREAD

**Issue by VihasMakwana** [elastic/beats#41534]
Note: This is different from https://github.com/elastic/go-lumber/issues/35, but can cause same effect (queue stalling)

Synchronous data sending to logstash host occurs in following way:

```go
func (c *SyncClient) Send(data []interface{}) (int, error) {
	if err := c.cl.Send(data); err != nil {
		return 0, err
	}

	seq, err := c.cl.AwaitACK(uint32(len(data)))
	return int(seq), err
}
```

- It first sends the data
- Then is waits for ACK, synchronously.

The [`AwaitACK`](https://github.com/elastic/go-lumber/blob/d3a66da160e5b6d9526ebab911e7e13526551e28/client/v2/client.go#L201) is designed as follows:

```go
func (c *Client) AwaitACK(count uint32) (uint32, error) {
	var ackSeq uint32
	var err error

	// read until all ACKs
	for ackSeq < count {
		ackSeq, err = c.ReceiveACK()
		if err != nil {
			return ackSeq, err
		}
	}
	...
	return ackSeq, nil
}
```

For an example, let's say we send 100 events in a request to logstash:
- The client sends 100 events to logstash
- The `AwaitACK` gets called it waits till all the 100 events are acknowledged.
    - Internally, it calls `conn.Read(..)` to read acknowledged events from logstash. You can find the this [here](https://github.com/elastic/go-lumber/blob/d3a66da160e5b6d9526ebab911e7e13526551e28/client/v2/client.go#L175-L198).

There's a problem with this approach. 
This approach works completely fine with a healthy logstash. It would even work well for `slow` logstash (which would return acks at a slower rate)
But, if the internals of the logstash has faced a permanent failure (for eg. one of the pipeline crashed, but the connection is still active), we get stuck in `AwaitAck` loop forever, because logstash will return 0 when we read for events that are acknowledged, indicating no acknowledgement. 

Like this,

```go
func (c *Client) AwaitACK(count uint32) (uint32, error) {
	var ackSeq uint32
	var err error

	// read until all ACKs
	for ackSeq < count {			// ackSeq will always be 0 if logstash is facing some issues,
		ackSeq, err = c.ReceiveACK()	// indicating no acknowledgements.
		if err != nil {
			return ackSeq, err
		}
	}

         ...
	return ackSeq, nil
}
```

I had a brief discussion with @jsvd, and he confirmed that Logstash can return a `0` when reading events that have been acknowledged. 
This means we will be always be stuck in this loop.

**Comment by VihasMakwana** [comment]
I managed to reproduce this locally and I can confirm it always returns `0`, until you fix the logstash issue and restart the failed logstash.

**Comment by cmacknz** [comment]
I think fundamentally we need a timeout for how long we are willing to wait for acknowledgements to come back. It can be quite generous given this is a rare condition that requires Logstash to be alive and responsive to network requests, but otherwise unable to make progress. Something like 5 minutes. It needs to be configurable and there needs to be an obvious error level log message indicating what the problem is when this happens.

If a Logstash instance is stuck in this situation, this approach will keep blocking individual batches on it for the length of the timeout until the problem is solved, but there will be no batches that are never sent.

**Comment by cmacknz** [comment]
There are requests for an unconditional connection TTL, but I don't think this actually helps here. 

- https://github.com/elastic/beats/issues/661

**Comment by jlind23** [comment]
@faec any update on this?

**Comment by faec** [comment]
After discussion with @amitkanfer and @cmacknz and the team, the current plan is a compromise: rather than add a new retry mode to the full pipeline, the Logstash output itself will track when its batches may have stopped making progress and log an error informing the user that the upstream hosts are likely crashed.

Disadvantages:
- This will not actually route around a presumed-deadlocked host, only inform the user of it.

Advantages:
- Effective on all Logstash configurations instead of requiring manual configuration of a new field (the configurable field only worked for users who already knew their Logstash hosts were silently deadlocked. The error logs instead drive users towards the preferred solution, which is to upgrade to a version of Logstash that doesn't leave a deadlocked connection open when a host crashes.)
- Reports errors even if load balancing and/or multiple hosts are not enabled.
- Requires no changes to the pipeline itself (parallel retry required special concurrency cases that were only used by the Logstash output).
