### ISSUE TITLE
Filebeat 8.17.0 docker container not starting

### ISSUE THREAD

**Issue by wargamez** [elastic/beats#42039]
docker run docker.elastic.co/beats/filebeat:8.17.0 
Error: unknown command "container" for "filebeat"
Run 'filebeat --help' for usage.

**Comment by fonfalleh** [comment]
Dockerfile uses `CMD ["-environment" "container"]`, seems to work if overriding using `--environment` instead.
This worked up until 8.16.1 as far as I can tell.

Docs say that `-environment` should have one dash, so that's another place which could use some review as well.
https://www.elastic.co/guide/en/beats/filebeat/8.17/command-line-options.html#global-flags

Saw interesting commit, is this related? https://github.com/elastic/beats/commit/15eae5f17eef6676258d43aa2db0300f3d9cf9c9

**Comment by cmacknz** [comment]
Same as https://github.com/elastic/beats/issues/42038

See https://github.com/elastic/beats/issues/42038#issuecomment-2545786130 for a work around.
