### ISSUE TITLE
filebeat cannot work on the big endian machine

### ISSUE THREAD

**Issue by Baz2013** [elastic/beats#4274]
hello,I find filebeat can not work on the big endian machine , and on the little endian machine it worked well.
anyone could tell me how to deal .
when I execute filebeat,it reports like follow：
-bash: ./filebeat: can not execute binary file

- Version: filebeat-5.3.2-linux-x86_64
- Operating System: Linux app01 3.10.0-229.el7.ppc64 #1 SMP Thu Jan 29 18:40:45 EST 2015 ppc64 ppc64 ppc64 GNU/Linux
- Steps to Reproduce: ./filebeat

**Comment by andrewkroh** [comment]
You are trying to run a binary built for x86_64 on a ppc64 machine, hence the problem. In order to run filebeat on ppc64 you will need to build your own binary. There are not official packages for ppc64. 

If you want to do a quick test you can grab a ppc64 [binary](https://beats-nightlies.s3.amazonaws.com/index.html?prefix=jenkins/filebeat/1385-4adb0eea358841bcab70049588a6727edd2397d3/) built from master off our Jenkins server. You can grab the [snapshot tar](https://beats-nightlies.s3.amazonaws.com/filebeat/filebeat-6.0.0-alpha2-SNAPSHOT-linux-x86_64.tar.gz) package for linux x86_64 to go with it and just replace the binary in the tar with the ppc64 one.

**Comment by adammike** [comment]
Are you still building ppc64 and ppc64le nightlies? Where can I find them?

**Comment by andrewkroh** [comment]
See https://github.com/elastic/beats#snapshots
