### ISSUE TITLE
FileBeat - Output to Kafka

### ISSUE THREAD

**Issue by ragurajendran86** [elastic/beats#4358]
How about enriching filebeat events using kafka in middle layer, instead of using only logstash?

When incoming data rate is too high, it demands the logstash instance to be running all the time. if logstash is down then it will create overhead on the machines where filebeat is running.

Also not flexible to update the logstash config files every time and can't scale the logstash since the filebeat conf has to be updated with all logstash end points.

**Comment by ruflin** [comment]
Can you elaborate on a few points:

* I requires the LS instance to be running all the time: How is that different from Kafka?
* If LS is down
  * Why will it create an overhead on the machine? You mean because of the additional disk space used potentially?
  * The same is the case if Kafka is down?
* How will you send your data from Kafka to ES?

You can scale the LS instance by using one DNS name which points to multiple hosts. @jordansissel  can share more details here.

**Comment by jordansissel** [comment]
> Also not flexible to update the logstash config files every time 

This seems less like a beats problem and more a concern with Logstash?

> since the filebeat conf has to be updated with all logstash end points.

Kafka does nothing to solve this problem, though. Further, what you say is not true. You can add/remove hosts without changing filebeat by using DNS (recommended) or a load balancer (not recommended)

**Comment by ragurajendran86** [comment]
@ruflin, yes if LS is down, the client could machine potentially consume more disk space and it might cause overhead to that machine, where we could run only simple process on the PROD servers for monitoring purpose. If kafka is used, multiple consumers can be process the same data (different tools used to insert data to ES) and we can define more retention on the topic to hold the messages on kafka, this will reduce the overhead on the client machine(until there is no failure on the kafka)

@jordansissel, i will try on the DNS as you have suggested

Also, metricbeat has kafka output, i think the same thing can be used in filebeat also to address the similar issue.

**Comment by ragurajendran86** [comment]
I see 5.4.0 filebeat has kafka endpoint already. I am closing this discussion.
