### ISSUE TITLE
Document npcap requires WinPcap Compatible Mode

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#4364]
Our [docs](https://www.elastic.co/guide/en/beats/packetbeat/current/faq.html#packetbeat-loopback-interface) mention that npcap can be used, but they don't say that you need to choose WinPcap Compatible Mode at install. We should add that. For a silent install the command would be: `npcap-0.86.exe /S /winpcap_mode=yes`.

From the npcap docs:

> WinPcap compatibility: For applications that don't yet make use of Npcap's advanced features, Npcap can be installed in “WinPcap Compatible Mode.” This will replace any existing WinPcap installation. If compatibility mode is not selected, Npcap can coexist alongside WinPcap; applications which only know about WinPcap will continue using that, while other applications can choose to use the newer and faster Npcap driver instead.

Discuss: https://discuss.elastic.co/t/can-packetbeat-be-configured-to-use-npcap-by-default/86166

**Comment by hsluoyz** [comment]
Hi, I'm the author of Npcap. First thanks for using it!

For this issue, another option is to support Npcap native mode.

I found that the current beats doesn't support the Npcap native mode (Npcap DLLs will be installed in ``System32\Npcap`` instead of ``System32``).  The impact is that the user has to install Npcap with ``WinPcap Compatible Mode`` option checked to use (aka ``winpcap_mode=yes``). Otherwise, beats cannot find Npcap DLLs. And enabling this option will install another copy of Npcap driver that is compatible with WinPcap (like installing the DLLs to ``System32``), which may affect the performance. **So Npcap suggests all its downstream software to support Npcap native mode.** Now software like Wireshark, Nmap, GNS3 has already supported Npcap native mode.

Please refer to the docs [here](https://rawgit.com/nmap/npcap/master/docs/npcap-guide-wrapper.html#npcap-feature-native) for details and implementation guidelines.

**Comment by dedemorton** [comment]
This was fixed in #5849 quite awhile ago.
