### ISSUE TITLE
Godep Error when building on Windows (both in the Vagrant box and native)

### ISSUE THREAD

**Issue by Cylindric** [elastic/beats#445]
I'm trying to build the latest version of winlogbeat, so am trying to use the supplied Vagrant box to do so. I have followed these steps:

1. On my host machine:
    1. `cd  `src\github.com\elastic\beats\winlogbeat`
    1. `vagrant up`
1. In the VM:
    1. `mkdir C:\Gopath\src\github.com\elastic`
    1. `mklink /d C:\Gopath\src\github.com\elastic\winlogbeat \\vboxsvr\vagrant`
    1. `go get github.com/tools/godep`

All of that completed successfully, but when I try the next step, `godep go build`, I get an error:

    godep: No Godeps found (or in any parent directory)

I'm not really familiar with Go, so am not sure what information would help to resolve this. The same thing happens if I try to build this on my machine.

**Comment by andrewkroh** [comment]
On Wednesday we switched to using the [GO 1.5 Vendor Experiment](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit?pli=1) instead of godeps and the Vagrantfile and batch files are out of date. A new Vagrantfile has been placed in the root of the project. The new box already has GO15VENDOREXPERIMENT=1 set which causes go to look for a vendor directory to find deps without the use of `godeps`.

We have [nightly builds](https://beats-nightlies.s3.amazonaws.com/index.html?prefix=winlogbeat/) of the packaged Winlogbeat available if you do not want to build it yourself. Also there is only another build that [publishes only the binary](https://beats-nightlies.s3.amazonaws.com/index.html?prefix=jenkins/winlogbeat/) after every change to master (the directory listing format here is {JENKINS JOB NUMBER}-{COMMIT HASH}).

**Comment by Cylindric** [comment]
Ah, that makes sense then, thanks. I'll check out the nightly builds for now :)

**Comment by andrewkroh** [comment]
Thanks for testing. I created a new [Winlogbeat](https://discuss.elastic.co/c/beats/winlogbeat) category on discuss.elastic.co in case there are questions.
