### ISSUE TITLE
Inconsistent CPU Percentage Calculation (Process vs System)

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#4468]
per @andrewkroh 

> The process times are collected using [GetProcessTimes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683223(v=vs.85).aspx). The descriptions of the out params say that the times reported are summed across cores (so you can get greater than 100% usage). The code used by Metricbeat is [here](https://github.com/elastic/gosigar/blob/master/sigar_windows.go#L333-L346).

> The overall system CPU time is collected using [GetSystemTimes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724400(v=vs.85).aspx). The behavior is similar to `GetProcessTimes`. The documentation states, "On a multiprocessor system, the values returned are the sum of the designated times across all processors."

> **[There is] a difference between overall CPU usage and process CPU usage.** In the overall CPU usage [calculation](https://github.com/andrewkroh/beats/blob/241df11fc67d707edce99a02e55d3291680bc595/metricbeat/module/system/cpu/helper.go#L63-L63) the total time value is calculates by summing the parts (i.e. idle + kernel + user). In the process CPU [calculation](https://github.com/andrewkroh/beats/blob/ce0ba232f2ab1b133e7e70cf2287a314ba604055/metricbeat/module/system/process/helper.go#L268-L268) the total time is measured using the difference in wall clock times between samples. Assuming you want 100% to be the max, using wall clock time causes the percentage to be wrong for multi-core systems and inconsistent with the overall CPU percentage value.

> I think we need a change to make percentages be consistent so that they can be compared. We need to decide if we want 100% to be max or if we want 100% * number_of_cores to be the max.

**Comment by tsg** [comment]
Thanks @andrewkroh for the great analysis and find. If we make it 100% * number_of_cores that would be more consistent with what we have on Linux, right? I'd vote for that, in that case, so that people can compare the values across systems.

**Comment by tsg** [comment]
I changed this to bug so we tackle it for 6.0-GA.

**Comment by andrewkroh** [comment]
I'd vote for 100% being the max. I think it would be easier to interpret the data because it doesn't require any knowledge of the number of cores (a value that's not reported AFAIK unless you use correlate it to the `cores` metricset data). Using 100% as max would normalize the data so you can compare values across all systems irregardless of the core count. The downside being that you have lost some sense of the magnitude (2 cores maxed out vs 22 cores maxed out).

Irregardless of the final decision, I think it would be useful to include number of cores as a metric in any CPU related metricsets.

**Comment by tsg** [comment]
After the discussion we had yesterday, my vote would be to support both use cases "natively". Perhaps in the `process` metricset we could have two metrics: 

* `system.process.cpu.total.pct` - this one can go over 100%, like in top
* `system.process.cpu.total.normalized.pct`. Defined as `cpu.total.pct / number_of cores`. It's max 100%.

My understanding is that this would be backwards compatible since in the current version `system.process.cpu.total.pct` can go over 100% on all platforms.

With the above, the `cpu` metricset (system wide) should use the same convetions but there are two issues:

* it would be a BWC change for the `cpu.total.pct` field, at least on Windows (is it on all platforms?)
* There are multiple CPU times in that metricset [data.json](https://github.com/elastic/beats/blob/master/metricbeat/module/system/cpu/_meta/data.json). Adding two values for each would cause a significant increase in disk space.

Perhaps we could add the normalized values behind an option, like we do for `ticks`?

Regardless, I think we should also export `system.cpu.number_of_cores` as a new metric.

**Comment by PhaedrusTheGreek** [comment]
Any chance this can be backported to 5.x ?

**Comment by tsg** [comment]
Hmm, perhaps we can backport the non-BWC bits. Let's first have a concrete PR and we can discuss on it.

**Comment by andrewkroh** [comment]
> it would be a BWC change for the cpu.total.pct field, at least on Windows (is it on all platforms?)

Yeah, this would affect all platforms.

**Comment by andrewkroh** [comment]
I just noticed that we use [`norm`](https://github.com/elastic/beats/blob/v5.4.2/metricbeat/module/system/load/load.go#L62) in the `load` metricset for the normalized load values. It would be inconsistent to use `normalized`. Should we

1. change `load` to use `normalized`,
1. use `norm` in `cpu`, `core`, and `process`,
1. or be inconsistent and not change `load`?

**Comment by andrewkroh** [comment]
> Perhaps we could add the normalized values behind an option, like we do for ticks?

Instead of adding additional `include_normalized` or `normalized.enable` options. I propose we let the user specify a list so that they can pick and choose what to include. And this would deprecate the `cpu_ticks` option.

```
  load.metrics: [averages, normalized_averages]
  cpu.metrics:  [percentages, normalized_percentages, ticks]
  core.metrics: [percentages, normalized_percentages, ticks]
```

**Comment by tsg** [comment]
@ruflin pointed out that `norm` is in the guidelines: https://www.elastic.co/guide/en/beats/libbeat/current/event-conventions.html#abbreviations

Not of a fan of the abbreviation, but I think we should `norm` in this case consistently.

**Comment by tsg** [comment]
I think can be closed.

**Comment by andrewkroh** [comment]
Related PRs:

5.5 - https://github.com/elastic/beats/pull/4544
6.0 (master) - https://github.com/elastic/beats/pull/4550 (backport) https://github.com/elastic/beats/pull/4553 (add normalized values to 6.0)
