### ISSUE TITLE
Fails to open the Filebeat auditd dashboard in Kibana

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4595]
After loading the dashboard for the auditd module in Filebeat, the following error is printed by Kibana:

![screen shot 2017-07-03 at 2 31 02 pm](https://user-images.githubusercontent.com/11757159/27792981-70833fbe-5ffc-11e7-991f-382a18c6f838.png)

**Comment by monicasarbu** [comment]
@andrewkroh can you please have a look? Maybe the error disappears after you have some data.

**Comment by andrewkroh** [comment]
That error makes me think that there is a error parsing the JSON query string. I should be able to run the Filebeat modules test suite to get some data populated in ES and see what happens.

**Comment by andrewkroh** [comment]
I narrow the error down to being caused by the Timelion graph no longer accepting

`.es(q="_exists_:auditd.log NOT auditd.log.res:failure").label("Success") .es(q="auditd.log.res:failed").label("Failure").title("Audit Event Result")`

I pasted the same expression into a 5.2.2 instance I had running and there was no error.

![kibana-timelion-6 0 0-alpha3-auditd-query](https://user-images.githubusercontent.com/4565752/27876784-44cba66e-6186-11e7-9f62-05bbf0d56ca0.png)
![kibana-timelion-5 2 2-auditd-query](https://user-images.githubusercontent.com/4565752/27876786-47c42008-6186-11e7-8c5d-26f4a38b8226.png)

**Comment by andrewkroh** [comment]
Adding a comma between the expressions seems to fix the issue.
