### ISSUE TITLE
Enhancement Request:  Multiple Multiline Statements per file

### ISSUE THREAD

**Issue by StivOstenberg** [elastic/beats#4626]
Our enlightened developers have decided it is really cool to have multiple date-time formats in a single log file,  just to keep things juicy.    Would like to be able to define multiple "multiline" statements for each file to catch this evil behaviour.

**2017-07-06 18:24:58.660** [http-apr-8080-exec-69] [] ........
Jul 06, 2017 6:24:58 PM........
INFO: Undeploying context []
**2017-07-06 18:24:59.103 [**ContainerBackgroundProcessor[StandardEngine[Catalina]]] [] WARN  o.s.b.f.s.DisposableBeanAdapter - Invocation of destroy method failed on bean with name 'ehcache': java.lang.NoClassDefFoundError: net/sf/ehcache/store/chm/SelectableConcurrentHashMap$KeySet
**Jul 06, 2017 6:24:59 PM** org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Statistics Thread] but has failed to stop it. This is very likely to create a memory leak.

Would like something like this:

input_type: log
paths:
/var/log/tomcat7/catalina.out
multiline.pattern: '^[[0-9]{4}-[0-9]{2}-[0-9]{2}' or 'someuglyregexforenglishmonths'
multiline.negate: true
multiline.match: after
exclude_lines: ["INFO: ", "WARN: ", "[] DEBUG"]

**Comment by jstoja** [comment]
Hey guys,

I'm adding a 👍 since I'm facing a more generic issue. That is a consequence of using docker
I'm having some applications logging multiline, some matching text before and some after.
For example Java stacktraces:
```
Exception in thread "main" java.lang.NullPointerException
        at com.example.myproject.Book.getTitle(Book.java:16)
        at com.example.myproject.Author.getBookTitles(Author.java:25)
        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)
```

but also rabbitmq messages:
```
=WARNING REPORT==== 7-Dec-2017::08:51:43 ===
msg_store_persistent: rebuilding indices from scratch
```

In the first example, the multilines are defined by lines starting with space, so they can be appended to the previous ones. In the second example, = will be appended to the next ones.

Now, I could probably set several prospectors with different multiline options, but all the logs are coming from docker and are matched with a wildcard so all containers are collected with filebeat.

I'm also using logstash behind, but the aggregate method is too restrictive and the multiline filter has been removed in favor of a codec that doesn't support multiple beats import...

I'm a bit stuck with no modular solutions and multiple multilines could probably be the solution. What do you think about it?

**Comment by ruflin** [comment]
@jstoja That is an interesting use case. I wonder if autodiscovery could help here: https://github.com/elastic/beats/pull/5245 Like this you could have "container specific" configs. Or do you get both multilines from a single container / single file?

**Comment by jstoja** [comment]
@ruflin That is a feature that could probably solve the issue yes! The fact that it's using the containers metadata to select the config is super interesting.

Right now we avoid having multiple logging formats from a single container. So each container type has it's own (multiline) format.

**Comment by ruflin** [comment]
The autodiscovery will ship in Beta for 6.1. Would be great if you could try this one out.

**Comment by andrewkroh** [comment]
@StivOstenberg Matching two patterns can be accomplished with a composite regular expression that employs an "or".

You can use a non-capturing group `(?:re)` to enclose the "or" `|`. For example `(?:RE_1|RE_2)` where RE_1 and RE_2 are the two patterns that you wish to match.

I put an example [here](https://play.golang.org/p/qyYRtP6PRZj).
