### ISSUE TITLE
Feature - Collect log from O365 via management activity API

### ISSUE THREAD

**Issue by tatdatpham** [elastic/beats#4811]
Do anyone have ideal for collect log O365 via activity API.
Like Splunk have app for collecting log O365. 
Should be we have O365-beat 💃 or any module in any-beat ?
Thanks!

**Comment by hemant-elastic** [comment]
+2 on behalf of two users who had made the same request in last month.

**Comment by SpencerLN** [comment]
We are very interested in this feature as well.

**Comment by Daniel314** [comment]
It is a feature that we are also interested in.  I've been trawling around the web, and there are a couple of sites that have some python code for this now.  One is https://medium.com/@kiamatthews/office-365-management-api-connector-for-elk-b94fe4ed4a53 (which details how to get O365 settings setup).

The other is a collector that has been written for Graylog: https://github.com/ddbnl/office365-audit-log-collector

**Comment by smgduncan** [comment]
+2 for further users who requested this in the last month.

**Comment by andrewkroh** [comment]
Implemented by https://github.com/elastic/beats/pull/16244 for release in 7.7.0.

This will need an update when https://github.com/elastic/beats/pull/14229 finishes to add the ability to store state (like the timestamp of the last read event) so that it can resume without reading events again. But even if you do restart it won't causes duplicates because it sets the `_id` to a value from the event.
