### ISSUE TITLE
Add JSON document structure to beats documentation

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#484]
To build queries for dashboards in kibana or filters in logstash it is good to know the exact document structure that a beat is sending. For topbeat we have documented it in the README.me file here: https://github.com/elastic/beats/tree/master/topbeat

We should add these document structures to all beats as part of the overview: https://github.com/elastic/beats/blob/master/topbeat/docs/overview.asciidoc

**Comment by dedemorton** [comment]
@ruflin Adding this info is a good idea, but it's perhaps too detailed for the overview. It might make more sense to add a new topic before the topic about exported fields. Then the field descriptions have more context. :-) I can add these changes.

**Comment by ruflin** [comment]
@dedemorton :+1:

**Comment by monicasarbu** [comment]
I am not sure if it's a good idea to add this info into the docs, as it changes often and we might probably forget to update. I would suggest to add it to the README file in GitHub, as I did for Topbeat. What do you think?

**Comment by ruflin** [comment]
@monicasarbu I agree it is tricky with the updates all the time so we should find a way to generate it. If it is in the README or in the docs, its the same issue with being outdated. 

The background why I like it because I remember when I started with elasticsearch I was looking quite often at the JSON documents to understand what kind of data is there and which not. For a technical person like me it is much easier to spot a field I'm looking for in JSON document then in a "formatted" text. Perhaps it makes more sense to have it somewhere in a more technical part of the docs?

**Comment by dedemorton** [comment]
@monicasarbu @ruflin I like the idea of including the JSON in the doc because it provides some context for the topic that covers exported fields. Plus the user can immediately see what comes out of the sausage machine.

I'll provide the JSON examples for each type of document, but I won't say, "this is the structure of the doc that you will get." Does that alleviate your concerns that the document might not always be completely accurate?  Let me put together a draft of the Topbeat topic, and you can see what you think.

**Comment by dedemorton** [comment]
Also see the discussion for https://github.com/elastic/beats/pull/492. #492 was not merged because people felt that the examples would get out of date too quickly. Instead, we want to try to automate the creation of the examples. As a first step (instead of adding the examples directly to the doc), @monicasarbu suggests starting small by creating an example file in the GitHub repo and then trying to automate the generation of the file before we try to add the examples to the doc.

@monicasarbu Which label should I use to get this work on the team's to-do list?

**Comment by ruflin** [comment]
This was done and fully automated for metricbeat. This should also be automated for the other beats in the future. Closing this issue as I think so far the experience with the `data.json` is positive.
