### ISSUE TITLE
Heartbeat Kibana saved search has the wrong field  (dashboard does not work with the default configuration)

### ISSUE THREAD

**Issue by pmusa** [elastic/beats#4852]
- Version: 6.0.0-beta1-linux-x86_64
- Operating System: Ubuntu
- Steps to Reproduce: 
Start Heartbeat with the `-setup` flag and then, in Kibana, access the Heartbeat dashboard to see `No results found` message. Digging a bit, I found that every visualization in the auto-loaded dashboard is configured with the Heartbeat "saved search", which is currently using `monitor.name` instead of `monitor.type`.

I am not sure if `monitor.name` was deprecated in favor of `monitor.type` or if there is another problem. Also, in the same "saved search" there is a meta field that also accesses `monitor.name`. Maybe it needs to be changed as well.

**Comment by urso** [comment]
`monitor.name` is freely configurable by users, to potentially differentiate between monitors of same type. If not configured, `monitor.name` defaults to `monitor.type`. The bug is `monitor.name` being empty.

Did you find `monitor.name` being used for filtering (like `monitor.name: http`) or for display only? For filtering we should use `monitor.type` and for display `monitor.name`.
