### ISSUE TITLE
metric names used in metricbeat for vsphere module

### ISSUE THREAD

**Issue by reymondk** [elastic/beats#5181]
This is based on discussion on:
https://discuss.elastic.co/t/collecting-custom-metrics-for-vsphere-module/100278

- Version: Metricbeat 6.0.0-beta2
- Metricbeat Module: vSphere
- Source OS: CentOS 7.3
- Target: vCenter 6.0u3

This is more on the improvement request about metric names that are used in the metricbeat to get the data from vSphere. Although this is not highly important, but the metric names should follow vmware standard. So there will be no confusion for people who already familiar with the VMware world.

These blogs has the list of metrics available for vcenter:
http://www.virten.net/2015/05/vsphere-6-0-performance-counter-description/
http://www.virtuallyghetto.com/2011/08/new-performance-metrics-in-vsphere-5.html

And this is one of the example that we see in the fields.yml file under /etc/metricbeat:
- name: memory.used.host.bytes
   type: long
   description: >
       Used Memory of Host in bytes
   format: bytes

**Comment by andrewkroh** [comment]
So this issue is about the Metricbeat field naming not matching up with the VMware field naming? 

I think I misunderstood your initial description on Discuss. I took it to mean that the Beat was publishing fields that either weren't explicitly defined in fields.yml or were slightly different than what was declared in fields.yml. This would be a bug.

But I think the naming used for the vSphere module fields was chosen to follow the Beat [field naming guidelines](https://www.elastic.co/guide/en/beats/libbeat/current/event-conventions.html) to get consistency with other modules.

**Comment by ruflin** [comment]
Going to close this issue as this issue as I think it was resolved with the above comment.
