### ISSUE TITLE
cluster filebeat

### ISSUE THREAD

**Issue by JasonHuangHuster** [elastic/beats#5212]
why there's no cluster function with filebeat ? commonly , filebeats are installed on many machines and need manged properly . 
what's more , can i custom the output to to storage like HDFS ? right now , there's only logstash and es . and i didn't see tutorials about the cluster and custom output ..

**Comment by andrewkroh** [comment]
We're working on adding a central management feature for managing Beats from a central location. See https://github.com/elastic/beats/issues/7028.

If you wanted to develop a custom output you can do it as a Go plugin which works for Linux. Otherwise you need to compile a custom binary that includes your custom output. This is the interface you need to implement: https://github.com/elastic/beats/blob/master/libbeat/outputs/outputs.go
