### ISSUE TITLE
Harmonize field names between Packetbeat HTTP and Metricbeat Module

### ISSUE THREAD

**Issue by christiangalsterer** [elastic/beats#5354]
Currently the two modules use slightly different names for the same information.
E.g. in Packetbeat HTTP module the field name for the HTTP status code is `code`, where as in Metricbeat Http module it is `statusCode`.

Goal is to harmonise the the field names and potentially also types.
@ruflin: What do you think in general and do you have any preferences which one to follow? Maybe Packetbeat as this is longer available then Metricbeat HTTP module?

I can provide a PR when I get a "go"

**Comment by ruflin** [comment]
I assume you meant in the metricbeat http module it is `status_code`? As the metricbeat module is still beta, it is much easier to change it there to just `code`. I don't think there is a difference between "response code" and "response status code"?

It's an interesting timing you bring this up because we started to discuss internally about standardising naming and is also one of the reasons I opened https://github.com/elastic/beats/pull/5335 so I could start to play around with it. Renaming fields is a bit tricky as it's normally a breaking change.

**Comment by christiangalsterer** [comment]
> I assume you meant in the metricbeat http module it is status_code? 
Yes
> I don't think there is a difference between "response code" and "response status code"?
yes, they are the same.

I will provide a PR for Metricbeat http module soon.

**Comment by christiangalsterer** [comment]
Sorry it took a little bit longer to submit the PR. PR is available at #5469.

**Comment by christiangalsterer** [comment]
Updated/new PR available at #5521

**Comment by ruflin** [comment]
As the PR's got merged, I assume we can close this issue.

@christiangalsterer Please reopen if not the case.
