### ISSUE TITLE
Wrong arguments raise no error

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#537]
By mistake I run Packetbeat with this command line and Packetbeat didn't start and no error was printed:

<pre>
 ~/src/github.com/elastic/beats/packetbeat [master] $ ./packetbeat -c etc/packetbeat.dev.yml -d "publish" -d -I ~/pcaps/palladion.pcap -e
 ~/src/github.com/elastic/beats/packetbeat [master] $
</pre>

**Comment by tsg** [comment]
I guess what happens is that `-I` is taken as a parameter for `-d` and the rest of parameters are getting confused, which probably results in `-e` not being correctly interpreted. If you move the `-e` from the end to before the `-d`, you get an error message.

To be honest, I'm not sure if there's any good way to improve on this, so I'm tempted to close the ticket unless anyone has a good idea of what could be done.

**Comment by urso** [comment]
This is the default flags handling in golang (stumbled upon this a few times). The parser assumes options first and no more options after some addtional arguments (like files). Due to '-d' eating the '-I', the pcap file will be recognized as some non-option argument. Everything following is no option, but an argument -> -e is not recognized as option.

The non-option arguments to packetbeat can be read via flags.Args() . We could check this being empty in packetbeat or libbeat and print error if not. But we might not want to disable args in general, as some other beats might be interested in passing arguments (e.g. additional file names).

There are alternative CLI/flags parsing libraries that might behave differently: https://github.com/avelino/awesome-go#standard-cli

This one remembers me in doing it like in python: https://github.com/codegangsta/cli

**Comment by mrkschan** [comment]
Can we let the beats check if unexpected arguments are passed and prints a warning to stderr?

**Comment by tsg** [comment]
Closing this one, I just didn't see many users stumbling on this problem, so I think it's not worth switching to another library.
