### ISSUE TITLE
How to limit mem use with filebeat6.0

### ISSUE THREAD

**Issue by ZhiqinYang** [elastic/beats#5412]
Excuse me! 
    I wanna to know how to limit the mem usage with filebeat, I run it in docker, and had a test produce 30000 logs per second! I saw the mem used more than 2G+. how can I limit it? I don't want it to use swap.

**Comment by andrewkroh** [comment]
Sorry no one responded to your question. We use the issues feature of Github to track bugs and features. For questions we use https://discuss.elastic.co/c/beats. So if you still have this question please post there.

You might want to try a newer release of Filebeat because there was a memory leak that was fixed.
