### ISSUE TITLE
Kubernetes manifests point to unreleased docker images in master

### ISSUE THREAD

**Issue by exekias** [elastic/beats#5930]
master version of kubernetes manifests point to an unreleased version: https://github.com/elastic/beats/blob/master/deploy/kubernetes/metricbeat-kubernetes.yaml#L96

Users reading docs from master will hit an issue while deploying this, as the image doesn't exist in our docker registry.

We should come up with a solution that sets a safe version in master

Related: https://discuss.elastic.co/t/metricbeat-on-kubernetes/112524/9

**Comment by ruflin** [comment]
@exekias It would be kind of nice if these images would exist but print out lots of warning that this is a pre release.

**Comment by dedemorton** [comment]
@exekias This issue has been open for quite awhile. I'm wondering if there's something we need to do to improve the docs. We already have a note at the top of the page (in master) to indicate that the docker image is not available. Should I add another note later on to indicate that the manifest points to an image that doesn't exist?

If you are keeping this open because you want to provide images eventually, maybe you should remove the docs label?

**Comment by dedemorton** [comment]
Another option is that I could wrap the instructions for getting the manifest in conditional coding so that they don't show up if the release state is unreleased. WDYT?

**Comment by exekias** [comment]
I think the note is working, as we didn't get any new reports from people trying to use these manifests. I think we can close this for now. Once/if we get snapshot builds for docker images I will update the manifests to work with them.
