### ISSUE TITLE
No hosts list or country distribution showing

### ISSUE THREAD

**Issue by dginther** [elastic/beats#60]
used the deploy script with ansible, had to tinker a bit because of my own issues, but I am not getting any results in the traffic distribution or the hosts list. Can you advise why that might be? Thanks!

**Comment by gabrielrcouto** [comment]
Hello,

I'm having a similar problem. All my transactions has the location "0.000000, 0.000000". I installed the GeoIP library and checked Packetbeat running in debug mode, everything appears to be fine. Any tricks?

Thank you very much,
Gabriel

![selecao_016](https://cloud.githubusercontent.com/assets/2197005/7728969/96f47888-fee8-11e4-82d2-05703d3d96f1.png)
![selecao_017](https://cloud.githubusercontent.com/assets/2197005/7728970/96f8b740-fee8-11e4-9899-1abf13b903c7.png)

**Comment by mingfang** [comment]
This is still broken in the latest beta2 for me.
Anyone working on fixing this?

**Comment by tsg** [comment]
@mingfang (or @gabrielrcouto), what OS are you running and what GeoIP package did you installed. From what we know, this is working correctly for most people.

**Comment by mingfang** [comment]
I'm running my agent inside Docker https://github.com/mingfang/docker-packetbeat-agent
My Dockerfile https://github.com/mingfang/docker-packetbeat-agent/blob/master/Dockerfile
is base on ubuntu 14.04 and I'm installing geoip-database.

I'm getting client_ip but no client_location.

**Comment by andrewkroh** [comment]
I looked at @mingfang's docker container. It installs the geoip-database package which contains the GeoLite Country database that will only return country names and not latitude/longitude values. The libbeat [publisher](https://github.com/elastic/libbeat/blob/master/publisher/publish.go#L148) requires that latitude and longitude be non-zero before it will insert the `client_location` field.

If you install the [GeoLite City](https://dev.maxmind.com/geoip/legacy/geolite/) database then you should get latitude and longitude values and therefore have `client_location`.

Try this in your container and you should start getting back locations.

```
curl http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz -o /usr/share/GeoIP/GeoIP.dat.gz
gunzip /usr/share/GeoIP/GeoIP.dat.gz
```

We should update the project documentation to inform users they should use the GeoLite City database. The defaults in [geolite.go](https://github.com/elastic/libbeat/blob/master/common/geolite.go) should also be changed to point to GeoLiteCity.dat rather than GeoIP.data.

**Comment by mingfang** [comment]
Yes, it works!
I wasted an entire day trying to figure this out.
I updated my Dockerfile with this fix.
Thank you very much Andrew.

**Comment by tsg** [comment]
Thanks @andrewkroh and @mingfang! I'll add this to the docs.

**Comment by gabrielrcouto** [comment]
Thank you very much @andrewkroh, I followed your instructions and now the location resolution is working on my Ubuntu Server installation.
