### ISSUE TITLE
Auditbeat docker docs imply use of non-root user

### ISSUE THREAD

**Issue by jamiesmith** [elastic/beats#6003]
https://www.elastic.co/guide/en/beats/auditbeat/6.1/running-on-docker.html#_custom_image_configuration

the docs show using an auditbeat user when building a `FROM auditbeat` docker image, which implies that it should run as a non-root user.  

It should probably be more simple, such as:

```
FROM docker.elastic.co/beats/auditbeat:6.1.1

COPY auditbeat.yml /usr/share/auditbeat/auditbeat.yml

# do other things
```

**Comment by andrewkroh** [comment]
@dede Could you put some kind of conditional around these three lines.

https://github.com/elastic/beats/blob/c42322b2c953ad9e958ed9756b839eb82dfca2e3/libbeat/docs/shared-docker.asciidoc#L58-L60

They should not be displayed for Auditbeat because it runs as root inside of the container.

FYI: The log we use in building the Auditbeat container is here:

https://github.com/elastic/beats-docker/blob/8fdf20fa8d3ea13bc4f5dd521b3cd3dcf32b38e1/templates/Dockerfile.j2#L44-L48

**Comment by andrewkroh** [comment]
Fixed by https://github.com/elastic/beats/pull/6201
