### ISSUE TITLE
Imrove docs about cpu.metrics

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#6020]
A forum user pointed out that the [Metricbeat docs](https://www.elastic.co/guide/en/beats/metricbeat/6.1/metricbeat-metricset-system-cpu.html) that describe the `cpu.metrics` settings for the system module are confusing. There is not sufficient detail about the settings.

See the discussion here: https://discuss.elastic.co/t/metricbeat-odd-cpu-percentage-values/114420

**Comment by Zappelphilipp** [comment]
Its confusing because the default config looks like this:
`- module: system
  metricsets: cpu`
and for me (at least) it wasnt that clear how to expand the config in such a way that it looks like in the docs:

`- module: system
  metricsets: [cpu]
  cpu.metrics: [percentages, normalized_percentages, ticks]`

The answer obviously is, that you have to rewrite the whole block like

`- module: system
  metricsets: cpu
- module: system
  metricsets: [cpu]
  cpu.metrics: [percentages, normalized_percentages, ticks]`
