### ISSUE TITLE
Beats monitoring reports 0 for its own CPU usage

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6063]
Beats monitoring reports 0 for its own CPU usage.

```
  "monitoring": {
    "metrics": {
      "beat": {
        "cpu": {
          "total": {
            "norm": {
              "pct": 0
            },
            "pct": 0,
            "value": 0
          }
        },
        "info": {
          "ephemeral_id": "caf4bf11-75f3-4280-a2c6-035ac6a0f28f",
```

The `last` value is always nil because `ProcsMap` is never updated by `GetOne()`.

https://github.com/elastic/beats/blob/4d0ff2be5199f88173da48afc90adba2387d5433/libbeat/metric/system/process/process.go#L437-L438

Additionally, using a global to store the last collected CPU counters is problematic because the value is shared by all monitoring reporter types (logs and ES). This could cause the differential CPU values to be calculated incorrectly.

https://github.com/elastic/beats/blob/a3970eec1d6d0766fdfa14104f5355b5cefbabb4/libbeat/cmd/instance/metrics.go#L21-L25

**Comment by urso** [comment]
Beats should not report CPU percentage, as this computation is stateful. Having multiple reporters, each potentially running at different intervals, will break the metrics for every reporter. Plus, if one document is missing, the next CPU percentage will be based on the missing documents information and the new state.

Instead consider reporting CPU times. For example `getrusage` can report user and system time of a process. Summing up these gets you the total process its active time.

The active time measures the time an OS thread has been active since start of the process. For one thread `Tactive  <= dT` (dT being the measurement interval). The CPU percentage can be retrieved by computing the time derviative over `Tactive`.

For one process, multiple threads can be active. That is, we actually have `Tactive <= dT * numCPU`. Divide `Tactive` by `numCPU` to get the normalized cpu usage.

By reporting the time used, instead of percentages, reporting can be stateless + missing documents will 'even out' when getting the derivative.

**Comment by kvch** [comment]
During testing I have seen non-zero values, but the reasoning is correct. Thanks for finding it!
