### ISSUE TITLE
Question about max_retries and queue

### ISSUE THREAD

**Issue by cmfatih** [elastic/beats#608]
Hi All,

I have a question about `max_retries` (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_max_retries)

> max_retries
> A value of 0 disables retrying and a value <0 will enable infinite retry until events have been published.

What's the queue size when we set `max_retries: -1`? Does it keep every single event until deliver or crash it self? Also what https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_timeout does when there is a timeout, does it drop events or retry (base on `max_retries`)?

BTW I like Beats, it's great! :+1:

**Comment by urso** [comment]
Hi,

the beats do have different delivery requirements. For example packetbeat has to process a constant stream of network packets, such that we'd prefer to drop events once queues fill up to not jeopardise internal state due to data sinks blocking. Topbeat for example, if blocked long enough will not be able to collect any new stats due to the publishing pipeline blocking, such that events will be finally dropped. You can only choose on which side you want to drop data. Last but not least, Filebeat mandates send-at-least-once semantics, that is we've to retry until we get an ACK.

To make matters more complex, filebeat forwards events in batches (spooler size), but packetbeat/topbeat publish single events which are combined into batches at a later stage (Plus internal go channels are too big it seems). There is currently [this open issue](https://github.com/elastic/beats/issues/516) to improve queue sizing.

Currently the effect of max_retries, when set to -1 is for topbeat and packetbeat to retry sending until ACKed or process crashes. Filebeat ignores max_retries and acts like it's always set to -1, so no lines will be lost. Timeout is handled like any other failure of delivery. On timeout delivery is retried based on `max_retries`.

Queue size (and memory usage) are indirectly configured by bulk_max_size (and spooler size in filebeat). Unfortunately the internal channel sizes are not configurable to date.

**Comment by cmfatih** [comment]
@urso : got it, thanks for your detailed reply.
