### ISSUE TITLE
Improve elasticsearch module documentation for SSL

### ISSUE THREAD

**Issue by untergeek** [elastic/beats#6115]
REF: https://discuss.elastic.co/t/ssl-configured-in-beat-but-es-gives-io-netty-handler-ssl-notsslrecordexception/115421

The elasticsearch module does not support the use of the `protocol` configuration key, but rather should be in the `hosts` array, e.g.:

```
- module: elasticsearch
  metricsets: ["node", "node_stats"]
  period: 10s
  hosts: ["https://hostname.example.com:9200"]
  ...
```

If the example [here](https://www.elastic.co/guide/en/beats/metricbeat/6.1/metricbeat-module-elasticsearch.html) were to show `http` or `https` in the configuration, it would address this, I think.

**Comment by andrewkroh** [comment]
I think the concrete steps we can take to improve this are to 

- replace references to `protocol` in examples with a `host` that contains the appropriate scheme.
  
  ```
  setup.kibana.host: "192.0.2.255:5601"
  setup.kibana.protocol: "https"
  ```
  becomes
  ```
  setup.kibana.host: "https://192.0.2.255:5601"
  ```
- Update examples to have a scheme in the URL. I think that showing `elasticsearch.hosts: ['http://localhost:9200']` rather than `elasticsearch.hosts: ['localhost:9200']` will make it more clear when switching to HTTPS that you need to update the URL.
