### ISSUE TITLE
Topbeat: [proc.cpu.user_p] is 0, also [user] and [system] is high value

### ISSUE THREAD

**Issue by oazabir** [elastic/beats#623]
I see the user_p is 0, although the user and system values are high. 

"proc": {
      "cpu": {
        "user": 5359,
        "user_p": 0,
        "system": 640,
        "total": 5999,
        "start_time": "Jun15"
      },

Logstash 2.1.1. Topbeat 1.0.1.

**Comment by monicasarbu** [comment]
proc.cpu.user_p should have the same value with %CPU from the top command. proc.cpu.user_p shows the CPU time since the last update, expressed as a percentage of total CPU time. It might be that the value is zero if the CPU times for a certain process are not changing between two consecutive updates.

**Comment by monicasarbu** [comment]
We are planning to increase the number of decimals to 4 instead of 2 for the proc.cpu.user_p percentage, so a very small CPU usage to show as a a value grater than zero. https://github.com/elastic/beats/issues/631
