### ISSUE TITLE
provide *beats-metrics via kafka

### ISSUE THREAD

**Issue by das-chick** [elastic/beats#6262]
in our environment we have a kafka cluster in front of our elastic stack. so it would be great if there would be a possibility to ship beat metrics via kafka. i had a look into the code right now, but i only saw the elasticsearch target. 
i talked to monica today in munich and she said, it would be possible to ship those metrics via kafka, w/o creating indices and dashboards.
regards
tobi

**Comment by ruflin** [comment]
@das-chick If you are thinking of the metrics collected by metricbeat from other services, you can use the kafka output. If you are referring the beats internal metrics, AFAIK there is currently no option to send these to Kafka as we will only ship Elasticseach support with the upcoming 6.2. But we are discussing since some time on how we could add other outputs.

@monicasarbu Perhaps you can comment as you have more background here?

**Comment by praseodym** [comment]
I'd very much like to see an option to send metrics in-band, so to ship them to Logstash or Kafka along with other events that Beats collects.
