### ISSUE TITLE
Keystore: Store PEM information directly in the keystore

### ISSUE THREAD

**Issue by ph** [elastic/beats#6377]
Currently, it is possible to store PEM information in the Keystore, but the problem with that is we don't have the possibility to retrieve it.

You can use the following command to add the data from stdin:

```
cat mypem | filebeat keystore add --stdin mypem
```

In our configuration definition we assume that the certificate or the CAs are string or slice of strings, we will need to use a custom type here that can accept both a file or the raw content of the certificate when we do the unpack.

```golang
type TLSConfig struct {
	Enabled          *bool                         `config:"enabled"`
	VerificationMode transport.TLSVerificationMode `config:"verification_mode"` // one of 'none', 'full'
	Versions         []transport.TLSVersion        `config:"supported_protocols"`
	CipherSuites     []tlsCipherSuite              `config:"cipher_suites"`
	CAs              []string                      `config:"certificate_authorities"`
	Certificate      CertificateConfig             `config:",inline"`
	CurveTypes       []tlsCurveType                `config:"curve_types"`
	Renegotiation    tlsRenegotiationSupport       `config:"renegotiation"`
}

type CertificateConfig struct {
	Certificate string `config:"certificate"`
	Key         string `config:"key"`
	Passphrase  string `config:"key_passphrase"`
}
```

**Comment by kaem2111** [comment]
+1 especially when introducing  beat Central Management and the ability to distribute keystore value this could enable us to setup node specific certificates automatically. I have implemented something similiar today but I would be glad to be able to switch to the ootb solution again.

**Comment by ph** [comment]
@kaem2111 Can you give some details about your solution maybe we can learn from it before developping it.

**Comment by kaem2111** [comment]
@ph I have written a python skript, which calls a webservice every 10 minutes to get new configuration since the last call. 
```
        request = urllib2.Request("http://%s/config/beat?lastrun=%d" % (conf["host"], conf["lastrun"]))
        result = urllib2.urlopen(request)                  # server provides config for my ip-address only
        answer = json.load(result)                         # get updated config since lastrun
```
If any result, it is written to metricbeat.yml or filebeat.yml and agents are restarted if appropiate. The webservice determines the partner IP address to send the correct node specific configuration back.
You use a management.accesstoken, which is even better. 

If no certs are present, it calls a service to retrieve generated pem certs and some passwords. The certs are saved in files and the passwords stored in keystore using 
```
            open("%s/.x" % dir0, "w").close()              # dummy .yml config
            prc = subprocess.Popen(["%s/bin/%s" % (dir0, item), "-c", "%s/.x" % dir0, "--path.home", dir0, "keystore","add",pwd.split("=",1)[0],"--stdin", "--force"], stdin=subprocess.PIPE, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
            print prc.communicate("%s\n" % pwd.split("=",1)[1]) # send psw to program
```
 I think you as a developer have a more elegant way to accomplished this.

Finally agents are checked and restarted, if required.

If I could plan an optimal solution, I would:

1. enable beats agent to read certs from keystore, as suggested here in this request
1. establish a way to download certs and others values from a new .managament-beat type: keystore
1. provide an 'other config' section in the type:output 'Edit configuration block'  of CM, so that cert-locations can be specified.
1. provide a new type:include_tag to include the configuration of another tag. Then you can assign a  cascaded definitions of configurations to a node with only one master tag. I have a tag: linuxbeats, which assigns a bunch of configurations to a new linux server comming up.  
1. provide the update service from a cascaded logstash enroll plugin instead of Kibana as mentioned  in #9916.

 The last topics is the most challenging, it implies that logstash provides something like a synchronous mode instead of todays mostly fire and forget, but on a segmented network you love to have only one (beats) port to be firewall enabled. 

Together with the anounced CM API, customers will have a flexible way to customize nodes according to their needs.

Thanks therefore in advance!

**Comment by ph** [comment]
Thanks @kaem2111 for the write up, its always useful to me to understand how people are moving pass theses issues so we can improve our software.

**Comment by jlind23** [comment]
Backlog grooming: Stalled issue, closing for now. Feel free to reopen it if needed
