### ISSUE TITLE
Add metric about that aggregates all diskio per host

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#6378]
Currently, Metricbeat ships the diskio for the host per disk. The one issue with this is that there will be double counting because Metricbeat ships /dev/hda , /dev/hda1, /dev/hda1 (/dev/hda is both /dev/hda1 and /dev/hda2 combined) but there's not an easy way to say "What's the diskio across all disks for this host?" without getting double counting. 

One option would be to use a panel filter for system.diskio.name:/dev/hda but the issue there is that each disk name is determined by the host/os and it's not consistent across every install.

I think the best solution for this would be to have something like `system.diskio.all.read.bytes` which would be an aggregate of all the (top level) disk controllers.

**Comment by ruflin** [comment]
In general if we have a summary it would have to go into a separate metricset like we do with `process_summary`. An alternative is to filter out the metrics for `hda` if there is `hda1`, `hda2`. Is there some advantage of having `hda` if there is also `hda1` and `hda2`?

**Comment by j-haj** [comment]
I have been giving this some thought and have a few comments:

* It does not seem there is a way to get top level disk usage for any system without making assumptions about the device naming conventions. It seems particularly challenging with Windows, although I am not a Windows user so I may be missing something here.
* If we filter out metrics based on prefixes, then calling the read all bytes function could silently fail (i.e., double count) when called on a system with a weird naming convention for its disks. Maybe this is OK, but we should document the assumptions being made.

Otherwise, I think we can pretty easily remove the prefixes from `m.includeDevices`. Maybe that is a good first step.

**Comment by onequid** [comment]
I'd love to give a try to implement it for Linux, may I?
We would:
1. pick out the top level disk controllers if there exists a sub level one (say `hda` if there is `hda1`) in module `diskio`;
2. add an additional `diskio_summary` module.

Am I missing anything?

**Comment by onequid** [comment]
A PR is created. The `diskio_summary` module is not added yet, and some furthur discussion about this would be lovely.
Instead the `diskio` metricset have records with `system.diskio.name : summary`.
And stats of top level controllers would be remove if at lease one sub level controller exists (`sda` is gone if `sda1` exists)

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
