### ISSUE TITLE
sample LS config for beats->kafka->ls->es

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#7071]
A single spot for information on setting up this pipeline would be great, especially for the logstash config.  A link from the kafka output docs (eg https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html) would be lovely too.

**Comment by dedemorton** [comment]
I agree. I'm not sure where this content would live in the current doc structure (probably within the Logstash Reference with pointers back and forth to the Beats Reference). Although I see the value of having it all in one place, I worry about documenting LS config in the Beats docs (or vice versa) because the information gets stale over time. Automated testing might help, but we don't have that right now. 

@karenzone WDYT about the location of these docs?

**Comment by karenzone** [comment]
WRT "probably within the Logstash Reference with pointers back and forth to the Beats Reference"
That makes the most sense to me.

**Comment by dedemorton** [comment]
Closing this issue since we decided it should be documented in the LS reference. See the issue I created in the Logstash repo here: https://github.com/elastic/logstash/issues/9833
