### ISSUE TITLE
unsure how to contribute a new beat

### ISSUE THREAD

**Issue by cleesmith** [elastic/beats#711]
I have created a new beat called Unifiedbeat (for lack of a better name) at:
https://github.com/cleesmith/unifiedbeat
This beat is useful for anyone wishing to index alert, event, and packet data from Snort/Suricata unified2 binary files ... it's really filebeat altered to handle the data in unified2 files.

I tried performing a "pull request" as stated in the developers guide, but unsure about the exact steps involved.
Any help is appreciated.
Thanks,
Chris

**Comment by urso** [comment]
Hi,

Unifiedbeat looks awesome!!! Great job on filebeat diagram!

You can find the community beats document at:
https://github.com/elastic/libbeat/blob/master/docs/communitybeats.asciidoc

You can create a PR on master (github.com/elastic/beats repository) with your new beat + you have to sign the [CLA](https://www.elastic.co/contributor-agreement/) for us being able to merge your PR. If you are still unsure, we can add your beat to the list.

I see unifiedbeat being based on a quite old filebeat implementation. The code-base has come quite along since. Check out https://github.com/elastic/beats/tree/master/filebeat. We started introducing different prospector-types, as different file types might have different requirements on when to be picked up or not, if they can be tailed easiliy or not (key word in-place circular log files). We hope the prospectors to become more pluggable and provide some common functionality regarding harvesters + prospector functionality for reuse.

**Comment by cleesmith** [comment]
I did notice the changes to filebeat, but I started unifiedbeat back in November 2015 and it's hard to hit a moving target sometimes. I will review filebeat and update if needed. It just seemed to me that filebeat was more like "syslogbeat", i.e. about text files. Where unified2 files are binary, so I just ignored the text code in filebeat. It would be ideal if filebeat was more general and pluggable ... good to see it's headed in that direction.

I did sign the CLA, but I still can't figure out the PR process. As I just get a grayed out "Create pull request" button. Sorry, but I mostly work on private github repo's and not open source code ... for my day job. So if someone can, and think it's a good idea, please add unifiedbeat to the list of available contributed beats. That list seems to be growing.
Thanks again.
Thanks.

**Comment by ruflin** [comment]
To open the PR you must do the following step:
* Fork the beats repository
* Make the change in your fork
* As soon as you made the change in your fork, it normally asks to create a PR. If not, go the the PR page and click Pull Request. There you can select your fork.

Also happy to do it for you in case this is too much of a hassle. 

I just had a quick look at code of unifiedbeat. It seems like you were able to reuse quite some parts of filebeat. Perhaps it could make sense to actually import some of the packages directly from our filebeat repo instead of having a local copy. The advantage is that every time you update the dependency you get also the newest "features" and your beat gets more lightweight by making it obvious what the differences are. The disadvantage is that some of our changes could of course break your beat.

**Comment by cleesmith** [comment]
There is a lot in common with filebeat, except for needing to read/decode binary data instead of lines of text. Also, it's unlikely that anyone would ever prospect/harvest more than one unified2 file at a time, so they are different that way too. 

Sounds like if I want to contrib unifiedbeat I will have to backtrack and figure out how to **override** ```input/file.go``` and ```harvester/log.go``` .. any suggestions of how to do that are welcomed. 
I don't consider myself a Go expert. However, I think unifiedbeat is much better than my previous attempt using Python--see: https://github.com/cleesmith/uni2espy which works fine but isn't as complete or fast.

Unifiedbeat is just a weekend project for me, so it might take me a while to change it. 
I just wanted to give back a little as I use ElasticSearch for lots of other projects.
Thanks.

**Comment by ruflin** [comment]
What you probably need for your case is also a new prospector. Best is having a look at the stdin prospector with the stdin harvester https://github.com/elastic/beats/blob/master/filebeat/crawler/prospector_stdin.go as this is also a prospector with only 1 file. There is still work to be done to fully abstract it on the harvester level but if you have your separate prospector, you can fully decide which harvester to call (and could even remove the other harvesters). 

We should definitively update change the developer guid to point to the right repo (cc @dedemorton) Thanks for spotting that.

**Comment by cleesmith** [comment]
Thanks, that sounds like a good approach.  

But I completely forgot that Snort/Suricata do **rotate** unified2 files--usually around a fixed size of 128MB. However, only the **latest** file is ever written into, which is why I was focused on just the one. So it's very possible, at least initially or after some server down time, that unifiedbeat would have to **prospect and harvest** several unified2 files. It's never easy.

It seems this __spooling pattern__ of watching paths, tailing files, and processing the data read is very old and common. Even the ancient C program [Barnyard2](https://github.com/firnsy/barnyard2), circa mid-2000's or earlier, spools/tails unified2 files into MySQL ... it's still in use.

Is handling file types other than log files, not just line-delimited text, a part of the roadmap for Filebeat ?
That would make sense given the name **File**beat, but I realize filebeat is a replacement for an older Logstash shipper. Just curious...

Is there any additional documentation (I know, silly question) for Filebeat other than the source code ?
Thanks.

**Comment by cleesmith** [comment]
@ruflin 
Unfortunately, and not meant as a criticism, the struct **FileEvent** snakes it way throughout filebeat — often revealing itself as _*input.FileEvent_ in reference to a slice or a channel or both:
* beat/spooler.go
* beat/unifiedbeat.go
* crawler/crawler.go
* crawler/prospector.go
* crawler/registrar.go
* harvester/harvester.go
* harvester/log.go
* input/file.go
Not to mention that the unifiedbeat specific code is replacing files in the beat, crawler, harvester, and input packages. Also, config/config.go must change to handle the new config settings for rules.gen_msg_map_path and rules.paths in the etc/unifiedbeat.yml file. 
**That accounts for every package comprising filebeat.**
With the exception of input/file.go, which is  the largest amount of new code , most of the changes are very minor, yet the whole package is being changed. 

Coding can be a tough nut sometimes, and not everything can be a duck.
So after much review the facts are: _filebeat is for syslogs_ and _unifiedbeat is for unified2 files_.
I don’t see simpler way forward, well, dropping the project is an option I suppose — but it seems a perfect use case for ElasticSearch.

Also, I **do not want to offend** by reusing a huge chunk of code from the older filebeat ... it's more of a compliment really that filebeat's code is so adaptable.
Please let me know if I should fork the beats repo and then do a PR --or-- drop the idea of offering unifiedbeat as a community contributed beat.
Just to be clear, either way is fine, really, no biggie.
Thanks.

**Comment by monicasarbu** [comment]
@cleesmith Thank you for the great work! 

@dedemorton Could you please add more details under the section "https://www.elastic.co/guide/en/beats/libbeat/current/new-beat.html#_sharing_your_beat_with_the_community"? Currently, it's just one line :) 
Also, I would use as a link to `communitybeats.asciidoc` the one from GitHub instead of website. Thanks!

**Comment by urso** [comment]
Hi,

the filebeat codebase was originally derived from logstash-forwarder, which main purpose was to forward line based log-files. That's why you will find input.FileEvent all over the place. We're still in the process of cleaning things up.

It's really cool having some other beat being based on filebeat. And it's a great learning experience for us someone pointing out difficulties (minor or not) encountered in doing so. This gives us some ideas what can be improved to support you and others in implementing custom beats based on filebeat.

Would be nice if you have had to implement the file decoding part only and finally instantiate your beat like this:

    import (
      filebeat "github.com/elastic/beats/filebeat/beat"
      "github.com/elastic/beats/libbeat/beat"
    
      // register unified2 prospector type
      _ import "github.com/cleesmith/unifiedbeat/unified2"
    )
    
    func main() {
       beat.Run("Unifiedbeat", Version, filebeat.New())
    }

If possible, this would reduce code-maintenance for you, as you only have to implement the Propsector/Harvester parsing unified2 files. Plus, you would be able to combine multiple decoders into one beat. Unfortunately we're not there yet, but any input (ideas, comments in upcoming PRs, pull requests) is welcome.

Maybe it is a good idea to hold out for required changes to filebeat before switching unifiedbeat to be based on new filebeat code-base.

We are very happy to see unifiedbeat as community contribution. Plus it's a very cool use-case complementing the other beats. You already have some kibana dashboards in mind?

The way we currently handle community beats as community contributions is by listing them. But the beat itself will live in your own repository, as it is your project.

We will add unifiedbeat to the list for you. You ok with the description:
> Reads records from Unified2 binary files generated by
network intrusion detection software and indexes the records in Elasticsearch.

**Comment by cleesmith** [comment]
@monicasarbu  thanks, and thanks for packetbeat

@urso 
It would be ideal to just write the decoding stuff, however it also requires a different reader for the binary file as well as assigning the json fields (plus geolocating the IP's) for indexing into ElasticSearch.  

Initially, I thought changing **Text *string** in **FileEvent** to something like **IndexableStuff interface{}** would be more flexible, and then switch on it's type via _switch f.IndexableStuff.(type) { case string: . . ._. 
I did this in unifiedbeat because this is what the decoder returns after reading a record ... but in general it's maybe a bad idea (not sure, but interface{} is over used).

Thanks you for adding unifiedbeat to the list and the description is good.

When I see it on the list, I will let friends know about it and see how things go from there.
Securing servers is _kind of a dark corner_ in software development so I don't expect this to be all that exciting or popular. Plus there are lots of existing software with long and trusted histories, while ElasticSearch would be consider a new kid on the block. But we have used it to great success.

Again, thanks to all, and especially those who wrote filebeat and the whole beats idea.

**Comment by ruflin** [comment]
@cleesmith Thanks again for the beat and sharing your insights on potential improvements / problems on filebeat. Feel free to reach out to us if we can support you in any way with the beat.

**Comment by cleesmith** [comment]
Filebeat is great, we use it for syslogs more than Logstash (which is also great).
Everyone has been fantastic ... no wonder Elastic is prospering.
Thanks.

**Comment by urso** [comment]
Community beats list will be updated with upcoming 1.1 release. [Here you go](https://www.elastic.co/guide/en/beats/libbeat/1.1/community-beats.html).
