### ISSUE TITLE
Fields docker.network.out.bytes and docker.network.in.bytes doesn't report what they say

### ISSUE THREAD

**Issue by beiske** [elastic/beats#7240]
The fields `docker.network.out.bytes` and `docker.network.in.bytes` are actually reporting the average number of bytes per seconds for the duration, but the docs state that they're totals. Some kind of total is what I intuitively would expect from the field names, but docs doesn't say if the totals are supposed to be totals since container or metricbeat started or if theyre the total amount since the previous value was reported.

For monitoring in Elastic Cloud we need the total amount transferred and estimating that based on average speed is cumbersome and error prone. Ideally we want the amount since the previous value.

**Comment by nyetwurk** [comment]
This is particularly annoying since all other objects than end in .bytes are long

**Comment by jsoriano** [comment]
Hey @nyetwurk, what do you mean? These docker network metrics are also stored as long.

**Comment by nyetwurk** [comment]
Logstash is spewing errors .. it seems to be getting floats from metricbeat
```Apr 21 00:01:00 ip-10-0-0-83 logstash[18749]: [2020-04-21T00:01:00,240][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"xxx", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x5e515005>], :response=>{"index"=>{"_index"=>"xxx", "_type"=>"_doc", "_id"=>"6rUJmnEBMeiAMkJGtU-z", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"mapper [docker.network.out.bytes] cannot be changed from type [float] to [long]"}}}}```

**Comment by jsoriano** [comment]
I have been trying and even if the mapping is not as correct as it should, it works for me, both with and without Logstash. Only problem I see is that these bytes metrics are indexed with the decimal part truncated, what I don't see so important as we are talking about bytes. Also these fields are deprecated since 6.4, they will be removed at some point and same information could be obtained with the derivative of `docker.network.outbound.bytes`.

To solve your problem I think that you should investigate if you are using the mapping provided by [metricbeat setup](https://www.elastic.co/guide/en/beats/metricbeat/7.6/metricbeat-template.html). It is very recommended to use this mapping to avoid this kind of problems.
In any case I think this would be a complete different issue. Could you please open a topic in discuss to continue investigating it? https://discuss.elastic.co/

**Comment by nyetwurk** [comment]
The root cause is indeed that we have not loaded the metricbeat setup; just trying to keep things simple, but logstash + lucene making crazy assumptions (such as truncating 0.0 to 0 so that floats are interpreted as ints if the first record for that object in an index is 0.0) is making things much more complicated than it needs to be, especially since we aren't even using those fields for anything. IMO the interaction between logstash and lucene really makes for counterintutive results, with or without the inclusion of the entire metricbeat template.

Just posting here because those objects are most certainly not being sent as integers by metricbeat (contrary to the comments in this bug and the documentation).
