### ISSUE TITLE
Filebeat logs have missing severity (or log_level etc.) field

### ISSUE THREAD

**Issue by Teressss** [elastic/beats#7292]
I have running workflow rsyslog -> logstash > ELK. I wanted to get rid of rsyslog and ship logs only with Filebeat. It works, but I am missing the most important part - in logs there is NO SEVERITY or log_level (or how you want to nema it) field. I searched forums for last week and didn't found a way, how to add this field to my logs.

Source logs are /var/log/syslog and /var/log/kern.log and when shipping via rsyslog I have the severity field present on my ELK. When I try to ship the same logs via Filebeat, this field is missing.

Can please somebody point me right direction. Thansk a lot.

**Comment by ph** [comment]
This question looks more appropriate to our [discuss](https://discuss.elastic.co/) but lets me add a few things here.

The severity or log level is calculated with bitwise operation on the priority of the original message.

In the next Filebeat version 6.3.0 (out soon),  we are releasing a Syslog input which currently supports receiving events from TCP or UDP and will correctly parse Syslog (BSD style or rfc3164).

We will probably make it work with File on disk really soon since the parser is easily reusable.
