### ISSUE TITLE
Find way to link to docs from config files

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7376]
Currently there is one global link to elastic.co docs page on top of our docs. There is no way at the moment to have links to specific sections of the docs. For examples instead of having many processor examples there should be one and a link to the docs.

Important when creating links we should make sure they link the correct version and that we have a method to verify that the links keep working.

**Comment by dedemorton** [comment]
This issue is quite old, so I'm closing it. If we still want to add support for testing doc links in config files, please open an issue in https://github.com/elastic/elastic-docs. If this is a common requirement, we should have a company-wide solution that everyone follows. With the introduction of agent and agent policies, I'm not sure we need the doc links in the config files.
