### ISSUE TITLE
TCP input slows down on adding connections

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#7502]
Found on `master` branch

We have noticed that adding connections is slowing down the TCP input drastically.

1 connection gives a throughput of 100k events/sec 
2 connections gives only 20k events/sec

**Comment by ph** [comment]
I will need to do a bit of testing on my side for this, since the TCP input doesn't have a lot of logic in it, I would like to have a bit more details on the downstream configuration.

@vjsamuel Can you give us a bit more details, are you using the memory queue or the persistent queues? Also, can you share the settings that you are using for the configured queue?

**Comment by ph** [comment]
after discussing with @vjsamuel we can close this, there was no performance issue with the input itself.
