### ISSUE TITLE
Keepalive and Timeout Configurations for logstash.output

### ISSUE THREAD

**Issue by robgil** [elastic/beats#7590]
Ref: https://github.com/elastic/beats/issues/7575

Request to add full TCP configurations for `logstash.output`
- [ ] Keepalive
  - [ ]  tcp_keepalive_probes
  - [ ] tcp_keepalive_time
  - [ ] tcp_keepalive_intvl
- [ ] Connect Timeout
  - This being the time beats should wait for a connect out to logstash before retrying
- [ ] Retry Interval
  - How frequently to retry the connection. This should preferably be some kind of multiplier
- [ ] TTL Revamp
  - This feature triggers a hard reconnect at the specified interval.
- [ ] Add an idle timeout
  - This timeout would close unused connections to logstash. If new items were ready to be shipped, a connection would be re-established. This reduces resource load on the ingestion infrastructure and load balancers in large environments.

### TTL Explained
The `ttl` option appears to be a hard reconnect after the interval defined. This is undesirable as it creates unnecessary reconnects. 
```
ERROR logstash/sync.go:96 error closing connection to logstash host ***:5044: write tcp ***:41516->***:5044: i/o timeout, reconnecting...
```
This could be improved by replacing it with an idle timeout. For example, setting a 60s idle timeout would close the connection if there was nothing that needed to be sent to the output. When new data is ready to be shipped, a connection would be re-established. We have many log sources and even auditbeat that may go 5 minutes+ without sending any data. 

### Considerations for Load Balancers / Proxies
Load balancers have their own timeouts. As a result, Keepalive will help keep connections open without being closed or falling back to the existing `ttl` functionality. If the ELB timeout is reached, or the logstash timeout is hit, we get those EOF errors because logstash or the ELB has already closed the connection. 

Sample EOF Errors
```
2018-07-12T03:36:55.933Z	ERROR	logstash/async.go:235	Failed to publish events caused by: unexpected EOF
2018-07-12T03:36:55.934Z	ERROR	logstash/async.go:235	Failed to publish events caused by: client is not connected
```

These are due to the load balancer closing the connection or logstash closing the connection. Both have idle timeouts and without keepalive will kill the connection on the server side. 

We'll need a separate issue for keepalive and various timeouts for the `logstash-input-beats` plugin so we have a full story and avoid disconnects and resets.

**Comment by webmat** [comment]
For having managed a pretty big fleet of servers all connecting over the Lumberjack protocol, I have to say forcing a hard reconnect with the TTL every once in a while is still useful. Otherwise when you scale up, new resources take a really long time to join the fray and take up some of the load. But totally 👍 on adding an idle timeout and documenting how to use all of these adjacent settings together.

**Comment by skmizuho** [comment]
Seconding this...

**Comment by richard-mauri** [comment]
+1 - this should not be closed because of idle activity

In our case the output.logstash is a load balancer in front of a fleet of container based logstash instances.
I have pipelining:0 with ttl: 120s so as to "work around" issue where the persistent connection to LS goes "silent" because the LS instance is gone or broken. We've had production escalations where the beat would not deliver any events and Elastic recommended using the ttl to periodically force a reconnection. This is crude and in practice what I see is the beat log shows errors closing the connection like:

ERROR logstash/sync.go:96 error closing connection to logstash host ***:5044: write tcp ***:41516->***:5044: i/o timeout, reconnecting...

Somaybe this is actually doing its job and confirms the connection is somehow broken, but there is no clear log message, that I see, from the beat that the reconnect was successful.

It would be better that insead of this crude work around of breaking thetcp to LS connection via ttl that the connection be reestablished if the beat detected errors or idle activity.

The Elastic team continually verbally or via email recommends, but does not clearly document, to not use a load balancer in front of a fleet of containers under an autoscaling group, but to instead have beat perform the load balancing and have the logstash hosts be a list of large more stale LS instances.

**Comment by sagarkal** [comment]
Hi,

From what I understand, if no TTL is specified, does the connection from a beat (say Filebeat) to Logstash remain open indefinitely?
