### ISSUE TITLE
Support OpenStack in add_cloud_metadata Processor

### ISSUE THREAD

**Issue by herver** [elastic/beats#7649]
Filebeat version: 6.3.1
Environment: OpenStack Queens

We run filebeat in our Openstack infrastructure and it'd be nice to add support for Openstack in the `cloud_metadata` processor.

I thought it would work out of the box with the EC2 provider because Openstack provides an AWS-compatible metadata service (https://docs.openstack.org/nova/latest/user/metadata-service.html) but it appears that the EC2 processor uses a different endpoint to get the data (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html)

I can contribute the provider for OpenStack, but would it make more sense to "fix" the EC2 provider ?

**Comment by ruflin** [comment]
I would suggest to add an openstack provider that probably reuses 99% of the code from the AWS provider. Otherwise I worry users that don't know the two are almost identical they get confused that AWS is loaded but they use open stack.

Would be great if you contribute it.

If we build a separate provider, does AWS still need some fixing?
