### ISSUE TITLE
[Thrift-rpc] Add support to provide file globs to specify thrift files in packetbeats.yml.

### ISSUE THREAD

**Issue by npallavi1988** [elastic/beats#7654]
Hi

We are trying to use Packetbeat to monitor our TCP thrift service layer.
 
Can you provide support to give file globs which contains all my thrift files instead of providing individual file names in packetbeat.yml? We have around 100 thrift files. Our thrift file repo follows a directory structure for different types.

yml config can be a combination of thrift file names, directory name or a regex or glob:
idl_files: [ 'my_dir1/*.thrift', 'my_dir2', 'my_dir3/my_dir4' ]

Discuss post for reference:
https://discuss.elastic.co/t/monitor-thrift-transport-using-packetbeat/140844

-
Thanks,
Pallavi

**Comment by npallavi1988** [comment]
Hi @adriansr ,

I have added this feature which supports globs like: 
my_dir/*.thrift
my_dir1/my_dir2/*.thrift

Please review: 
https://github.com/npallavi1988/beats/blob/thrift_file_glob/packetbeat/protos/thrift/thrift_idl.go

Tried writing code in go lang.
-
Thanks,
Pallavi

**Comment by adriansr** [comment]
Hi @npallavi1988 

Thanks for working on this!

Can you make a pull request to the beats repo? This way it's easier to see exactly what you changed.

A few comments:
- I would prefer the glob to be done in the `readConfig` method at `thrift.go`, so `newThriftIdl` is already called with the expanded list of files. Otherwise, the feature is hidden inside the thriftIdl side.
- Can you add an entry to the CHANGELOG.asciidoc

If you need help I can walk you through the steps of creating a pull-request or do it for you.
