### ISSUE TITLE
Change fields in template to be case insensitive

### ISSUE THREAD

**Issue by vbohata** [elastic/beats#7814]
For a lot of fields (host name, beat name, beat timezone, error type, ...) it make sense to be case insensitive. Currently I had to override template settings for these fields to make them case insensitive using the lowercase normalizer:

          "custom_normalizer_lowercase": {
            "type": "custom",
            "filter": ["lowercase", "asciifolding"]
          }

I would be great to have these fields case insensitive by default.

**Comment by ruflin** [comment]
We had some discussions on this here: https://github.com/elastic/ecs/issues/56 I definitively see also benefits to have these fields "standardised" for correlation. Should we continue the discussion on https://github.com/elastic/ecs/issues/56 ?

**Comment by vbohata** [comment]
Sure.

**Comment by roncohen** [comment]
Hi @vbohata. Changing the fields to be case insensitive will not work for everyone, so I don't think that's a solution at the moment. If this problem is still relevant to you, do you mind elaborating on concrete situations where you run into this problem? For example, which software are you using to ingest the data?

Since this is a rather old issue, I'm going to close the issue for the time being.  Please feel free to reopen if you're still having issues with this.
