### ISSUE TITLE
add_kubernetes_metadata does not work correctly inside POD

### ISSUE THREAD

**Issue by benkeil** [elastic/beats#8018]
For confirmed bugs, please report:
- Version: 6.3.2
- Operating System: Docker/Kubernetes

I can't use the kubernetes plugin if I run filebeat in a POD. The plugin needs a docker container id to run properly, but that makes no sense. In the log you see:

`2018-08-18T00:34:00.306+0200	INFO	kubernetes/util.go:69	kubernetes: Using pod name mls-8dc4c8d-mxnlv and namespace mls to discover kubernetes node`

That is all you need to gather data from the kubernetes API..

**Comment by ruflin** [comment]
Hi @benkeil Not sure I fully understand your issue is and what part doesn't work. Could you open a topic in discuss (https://discuss.elastic.co/c/beats) with the Beat you use and share a bit more details on what you are trying to do and doesn't work? Please also post your config there.

We are trying to keep Github for confirmed bugs.
