### ISSUE TITLE
collect log slow with winlogbeat on windows server 2008

### ISSUE THREAD

**Issue by tatdatpham** [elastic/beats#815]
Hi, i'm using winlogbeat nighly build 1.2.0 (18/01/2016).
I installed winlogbeat on mail server. I have 120GG log/events per day.
I check and see winlogbeat can''t shipper all log created to LS forwarder. (shipped 70% compare with time). it mean if server have 100M event. after 10min, winlogbeat ship to LS-Forwarder ~ 60M event.
By time, i alway missing log.
I set 6 worker / host LS-Forwarder. (i have 2 LS-forwarder).
Can;t you help me fix this. Thanks

**Comment by andrewkroh** [comment]
Thanks for testing Winlogbeat.

Can you please post your configuration file and the output of running `Get-EventLog *` in PowerShell?
I am assuming by LS-Forwarder you actually mean Logstash. Correct if I am wrong.

**Comment by tatdatpham** [comment]
Sorry because i reply too late,
Here is my config file
[Config file](http://pastebin.com/6nCC8k9f)

And here is output when run " Get-EventLog * "
[Output](http://pastebin.com/b4hp7C0q)


> I am assuming by LS-Forwarder you actually mean Logstash. Correct if I am wrong.
Yes. I'm using Logstash (Ls-Forwarder -> RabbitMQ -> LS-Indexer)

**Comment by andrewkroh** [comment]
First we need to identify where the bottleneck is then we can work on optimizing.

Have you done any tests with Winlogbeat using just the file output instead of the logstash output to test if it can keep up with the event rate? I would try this first.

If you uncomment the `metrics` section of the config file it will expose some counters at `http://localhost:8123/debug/vars` that can be used to more accurately measure the event rate. Take a look at this [post](https://discuss.elastic.co/t/insufficient-throughput-from-filebeat/39564/5), it has a python script that can measure the event per second rates using the data from those counters.

Next I would do the same measurement using the Logstash output and see what kind of rate you get.

Can you also report your Logstash version and  logstash-input-beats version.

```
./bin/logstash --version
./bin/plugin list --verbose logstash-input-beats
```

**Comment by tsg** [comment]
Closing due to lack of feedback, @tatdatpham please reopen if you can provide extra information.
