### ISSUE TITLE
To include all available Mbeans under jmx mappings

### ISSUE THREAD

**Issue by kathirj88** [elastic/beats#8168]
Would be good to have something like jmx.mappings: * to include all Mbeans without mentioning each and every Mbean which leads lot of manual work.

(And I don't see any dashboard for JMX mappings in Kibana. Would be great to have basic dashboard.)

**Comment by piellick** [comment]
Nice request !

**Comment by exekias** [comment]
cc @jsoriano you have been thinking about something similar maybe?

**Comment by jsoriano** [comment]
We can probably do it, the trickiest thing would be to keep the mapping, we have to think more about this.
An option could be to use dynamic mapping and keep all the metrics under `jmx.metrics.type.path` and dedot the path. A level for the types may be needed because values returned by jmx can be of any kind.
I will start a proposal for this soon.

**Comment by ssc327** [comment]
Has this been prioritized?

**Comment by jsoriano** [comment]
I created an issue to keep track of discussions about the dynamic mapping here https://github.com/elastic/beats/issues/13316, but there are no specific plans yet.
