### ISSUE TITLE
Kafka output config should remove "worker"

### ISSUE THREAD

**Issue by weichuliu** [elastic/beats#8563]
For confirmed bugs, please report:
- Version: 6.4

In https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html there's `worker` config for Kafka

But actually it's removed in commit `eefdbd6f0a4ad64bf3208f7dc27a9805136c4bf3` (just did a rough search)

The `worker` in Kafka conf should be removed from the doc

**Comment by weichuliu** [comment]
Of course, the flag should also be removed from all configuration examples, if exists.

**Comment by jsoriano** [comment]
Hi @weichuliu, thanks for your report.

In principle `worker` should still work, in code you can see it removed from kafka because this functionality was moved to a common place so it can be used with any output.
Did you have any issue with this setting?
I am going to close this by now, if it is causing any problem to you we can reopen, if you need help with configuration, please consider using https://discuss.elastic.co
