### ISSUE TITLE
Can someone share customized Beats for windows

### ISSUE THREAD

**Issue by 1sunil1** [elastic/beats#8598]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: 
- Operating System: OS
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by faulander** [comment]
What are you expecting from a request like this?
What do you want to achieve?

**Comment by 1sunil1** [comment]
i wanted to run the beats from community beats in windows...

**Comment by ph** [comment]
@1sunil1 I don't think we can help in that case, We generate windows binaries for all the official beats. We provide the framework that dev can use to creates binaries. If you want a windows binary from a specific community beat you will have to ask the author.

I will close this issue, because it's not something we can help further.
