### ISSUE TITLE
Run Filebeat once for predefined files

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#880]
Similar with what we have for Packetbeat, I suggest to add an option to filebeat to pass a file with logs or a `gz` archive with logs.

For example in Packetbeat we have the `-I` option where you can pass a `pcap` file and Packetbeat is replying the traffic from that particular pcap. For Filebeat, instead of passing the `pcap` file, we can pass a `gz` archive, for example. It's up to us if we decide to copy the archive in a directory from where Filebeat is fetching the logs or we can just read that file and skip the file discovery part.

I think this would be really useful for purposes like: testing, development and even trainings.

**Comment by marnikvde** [comment]
+1
I could use this as well

**Comment by ruflin** [comment]
I think this is indirectly already possible through the stdin. The problem is that after processing Filebeat does not stop afterwards. To make it more obvious, I will change the title of the issue.

For the gz part this is related to https://github.com/elastic/beats/issues/637

**Comment by strootman** [comment]
I could use this as well. 
I cannot rely on our network, so I need to re-ship files after nightly log rotation to ensure that the daily index is complete.

**Comment by ruflin** [comment]
@strootman Filebeat is able to track file rotation and with LS you can process the log line with a timestamp inside (hopefully) which then can send the log lines to the correct index.

**Comment by strootman** [comment]
@ruflin Thank you. Under normal circumstances, there is nothing wrong with what you describe. 

However, when just getting started and going through the process of creating, modifying, and refining the index mappings for my logs, I have got myself into a situation where it is just easier to blow away all my indices, and re-ship all of my previous data.

There is no problem with the normal setup of filebeat shipping my logs, but I have to go through a few manual steps to perform a one-shot task of re-shipping *ALL* of my previous logs to correct an invalid mapping. 

We use ansible to automate many of our infrastructure tasks, and having the ability to detect when filebeat is done shipping a set of files (and producing a return code of `0` or `1`) makes automating the task of `reship all these logs, because I am just starting, and didn't realize how quickly I could bring my cluster to its knees because I introduced an invalid mapping(s)` a lot easier.

Without this feature, I have to baby-sit these tasks, using a combination of `marvel`, index stats, visualvm monitoring of logstash, and inspection of the filebeat registry file to _ensure_ that everything has been re-shipped.

Not impossible, just highly inconvenient. _Especially_ since I have to do this for;
* each of our dev environments, 
* each of our QA environments, 
* and (eventually) production.

Do you know how long it takes to re-ship a months worth of logs from all these hosts?! 

I wish I could have the following conversation; 
**Me:** "Hey, I've got this one-time thing I need done, but I have a ton of other stuff to get to. Here are the requirements. Can I rely on you?"
**Filebeat:** "Yeah man! This is no problem. This is a lot of work, no guarantees on how fast, but I'll let you know the _second_ I'm done"
**Me:** "Filebeat, you're pretty cool! Talk to you later."

Then, some time later.
**Filebeat:** "Yo, I did that thing you asked." 
**Me:** "Sweet! Thank you so much filebeat, but I've got requirements for 50+ more jobs. Can I count on you?"
**Filebeat:** "Come on man! You know me! I've got this!!"

You see? If filebeat were that cool, I could manage my time more effectively, hopefully getting to more fun stuff with Elasticsearch rather than re-thinking every mistake which put me in this current predicament.......

Now, to be defensive of my actions. 

Yes, I know I should have done a better job at controlling the mappings of my logs, but you make it *SO EASY* to get started and just start indexing stuff!!! So I did!! I just started shipping stuff! I took an _"agile"_ approach to refining my logstash configs and index templates to make sure that my mappings would be okay. I used sample sub-sets of files with my ES stack set up on my machine. 

THE POWER!!! Everything was golden!

But .... I'll save you the finite details, stuff happens. And now I am re-building everything (in addition to the daily re-shipping task I described _*very briefly*_ above).

I am 100% certain that I am not the only one who has been in this situation. 

I hope this illustrates the _need_ for this feature.

**Comment by ruflin** [comment]
@strootman Thanks a lot for going into this much details and explaining your use case. I have one more use case from our side which is testing filebeat. We currently do some magic by tracking log lines which can lead to errors.

One elasticsearch feature that could potentially help with your use case above is the new Reindex API. So instead of having to ship all logs again and put load on your network, you just use the Reindex API to reindex your data with a new mapping? https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

**Comment by strootman** [comment]
@ruflin BTW, I've been using the re-index API, and it has helped. Thanks for the suggestion. 

I even made an Ansible Role, [CyVerse-Ansible.es_api_reindex](https://galaxy.ansible.com/CyVerse-Ansible/es_api_reindex/).

**Comment by ruflin** [comment]
@strootman Good to hear it worked. Would be nice to get your feedback on the new `-once` option to see if this also works as expected: https://github.com/elastic/beats/issues/2456

**Comment by mhyousefi** [comment]
Has there been progress in this regard? 

I'd really like to have the ability to finish the Filebeat process and stop its container once Filebeat has sent everything. In my case, I am starting a Filebeat container as per request to send different log files. Now the number of these requests could be high enough to concern me with my server's resource restrictions, not to mention that there is no need for the container to be up once it is done serving its purpose.
