### ISSUE TITLE
Java Agent

### ISSUE THREAD

**Issue by jamroks** [elastic/beats#91]
Hi,  as a feature request i think, and evolution of packetbeat could be to offer monitoring on application with the help of agent deploy to the target host and included in the startup script of the application. this feature will be greatly appreciate from the community and the community could be contributing by implementing different type of "plugin agent" for multiple target application stack like :  
- Java
- Ruby 
- Python
- Php
  etc ...whatever stack ..

Would be glade to contribut to such effort. 
I'm guessing this something the core commiter of the project already have in mind for the futur of packetbeat.

**Comment by tsg** [comment]
Hi, that's right, this is the direction we want to go in. We're currently working on a common format for the transaction data, so all the sources are normalised to a somehow standard format. See here: https://github.com/packetbeat/packetbeat/blob/master/etc/fields.yml

After that we'll do a sample middleware agent. We'll start with an agent either for a python or for a golang framework, because these we know best. We'll be more than happy to work with you to get a Java agent as well.

**Comment by jamroks** [comment]
Super Great !!  i'll take a look a the format in the link you provided and can't wait to see the implementation so that i can contribute on the java part 

Cheers

**Comment by monicasarbu** [comment]
Closing this issue as Java is something that the Elastic APM will add soon.
