### ISSUE TITLE
[CM] Unable to connect to TLS'd cluster for enrollment

### ISSUE THREAD

**Issue by toddferg** [elastic/beats#9129]
**Describe the enhancement:**
When using an internal CA, or when you might have a hostname mismatch (for example: nat'd address) when enrolling in beat central management, there isn't a command line flag that gives the opportunity to specify ssl_verification: none, or specify a custom CA. 

**Describe a specific use case for the enhancement or feature:**
In my deployments I sign from an internal CA, and need to specify the ssl settings in the configuration.

**Comment by gjelenc** [comment]
+1

**Comment by ph** [comment]
I think we should do the following, it appears that we already support having `management.kibana.tls.*` The problem is this option is not used by the enroll command but they are used when we start kibana.

**Comment by ph** [comment]
After talking with @mattapperson, since we are planning to move the enroll token to a web token we could add the CA as data in the web token and use that information when enrolling the beats.

We would still need to allow the enroll subcommand to read the configuration from the yml when using the api with the username / password.
