### ISSUE TITLE
Port over modules collection script to golang

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#9130]
We are trying to [move away](https://github.com/elastic/beats/pull/9118#discussion_r234195444) from Python scripts called from Makefiles to golang scripts called from magefiles. Currently the [modules collection script in Metricbeat](https://github.com/elastic/beats/blob/master/metricbeat/scripts/modules_collector.py) is written in Python. It should be ported over to a golang script.

**Comment by andrewkroh** [comment]
I did some of this for x-pack/filebeat to prove that it works, but none of it has been applied to other Beats. For example this creates the module.d directory

https://github.com/elastic/beats/blob/122fb9364c9fc9d1d6508a864e132396180f9c38/x-pack/filebeat/magefile.go#L213

If this is something that you can reuse then generalize it and move it into `dev-tools/mage/`.

So some things have been ported over, but the old python/make version hasn't yet been replaced.

**Comment by ycombinator** [comment]
Cool, thanks for the pointer @andrewkroh. I'll definitely look into it and try to generalize it. For a bit more context, this issue spun out of this conversation: https://github.com/elastic/beats/pull/9118#discussion_r234195444

**Comment by jsoriano** [comment]
I think @sayden was also migrating some things to Go.

**Comment by sayden** [comment]
Thanks for the heads up @jsoriano 

Yeah, I started a backwards compatible PR that covers quite a lot of things by modifying "as little as possible" to make the build system work in x-pack metricbeat but I haven't tried to write anything from scratch, I've just modified what we have now to have something working ASAP.

I did [this](https://github.com/elastic/beats/pull/8829/files#diff-76b4bf8135404f03917a93974117ad72) changes to the modules collector script but feel free to change whatever you need with magefiles, I'll update my branch later, all in all I know that part of my work is going to be just useful for a short period of time because @andrewkroh is doing a huge work to port everything to Go already.
