### ISSUE TITLE
Elasticsearch client capabilities

### ISSUE THREAD

**Issue by urso** [elastic/beats#9219]
Different versions of elasticsearch have different capabilities. Right now we acquire the version and check in a few places in the code if this particular version has the required capabilities, by knowing the version number only. A few checks are duplicate code. Each place in code needs to know about the exact version and whenever some capability is added removed, all places must be found and updated accordingly. This is some error prone and painful task.

Alternatively the Elasticsearch/Kibana clients in Beats could provide some capability checks, that are aware of versions. This way we move version checks into one place, but have the code checking for a capabilities decoupled from actual version checks. By introducing enums (do not use strings ;) ) the compiler (or simple grep) can find locations that need to be updated when capabilities are added or removed.

Some of this functionality seems to overlap with the license manager.

**Comment by ph** [comment]
The current license manager is Elastic Licensed, but we could maybe work around that.

Currently, any part of the code that want to be license aware can just implement the Watcher interface and register itself to the manager, periodically it will receive updates. We could extend that to also receive the version, but we would need something to support kibana.

Because of this, I think option 2 is what makes more sense for us because its simplier to unify on this strategy for remote system. I suspect Metricbeat has similar issues.

I think it would make sense to have the following flow, use a factory that will do a version check at the beginning and will take care of instantiating the right type depending on the version. We just provide a common interface on top of it to hide any difference.

Looking at our current code base, I think we have added features to our client organically, we have most of the building block.

The list bellow contains functions that I think are mostly stable and should not change between version.

- A transport HTTP client (we already have that)
- A low level ES clients, maybe just generalize error handling.  We can decorate the handling with different type depending on the version.
- A Client Pool.

More likely to change.
- A Sniffing to update the pool. (might be less stable)
- Actual Batcher can change (_doc vs doc)


So I propose we split some of the code in the output/elasticsearch and create an elasticsearch module that will encapsulate version and specific types to make the actual calls and the current elasticsearch module will just glue the pipeline to the new module.


pseudo code would be something like this (not actual golang):
```golang
client, err := elasticsearch.NewClient()..
batcher, err := elasticsearch.NewBatcher(client)
results, err := batcher.Send(mybatch) // inspect resuls to know if we need to retry.
results, err := elasticsearch.BatchRetryer(batcher, retrypolicies).Send(mybatch)
```

That would do a bit more composition and would make unit testing easier, that will probably simplify some of our kibana code?

**Comment by ph** [comment]
This enforce us to add types inside a specific package, meaning that the elasticsearch package is now responsable of handling concrete calls, versioning and to adapt the data it receives if a specific version of ES cannot handle it.

**Comment by urso** [comment]
> So I propose we split some of the code in the output/elasticsearch and create an elasticsearch module that will encapsulate version and specific types to make the actual calls and the current elasticsearch module will just glue the pipeline to the new module.

+1 on support packages for ES, Kibana, LS
