### ISSUE TITLE
[Processors] Mutate processor to apply basic transformations to fields

### ISSUE THREAD

**Issue by frittentheke** [elastic/beats#9227]
**Describe the enhancement:**
I quite like the powerful and efficient dissect filter and respect the decision to not have Grok filtering in Filebeat.  Additionally the various conditions, including even regex, allow for branching the parsing / processing pipeline within Filebeat. 

But even if one can dissect all fields, there are lots of very sluggishly formatted log formats, which require some cleanup, mostly in the form string mutations, like removing whitespaces or normalizing multiple variants of a value (i.e. by doing "tolower").

Logstash has the mutate plugin (https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-proc_order) which is very powerful in this regard.
It also does casting / typing, as is suggested in https://github.com/elastic/beats/issues/8124

**Describe a specific use case for the enhancement or feature:**
Cleanup of inconsistent formatting of the same type of data in logs. 
Also basic removal of sensitive data could be a use case: Removal of last two octets of IPv4 addresses, partial removal of logged usernames or customer ids, ...

**Comment by ph** [comment]
@frittentheke  Thanks for the comment for dissect, we plan to improve his power in future version. I always point people to the [specifications](https://github.com/elastic/dissect-specification/) to see if we can improve the experience or syntax.

+1 of having mutate-like feature in libbeat, but I think its worth to either create a custom processor for each operation and maybe a better  way to express the manipulation of string, IE: some kind of scripting language support.

**Comment by frittentheke** [comment]
I dont think this is stale.

**Comment by jsoriano** [comment]
Since 7.2, beats include a [`script` processor](https://www.elastic.co/guide/en/beats/filebeat/7.12/processor-script.html), that can be used to do any modification of fields in events using javascript. I think this could cover this use case.

For the specific use case of casting/typing, the `dissect` processor supports the conversion to specific data types since recent versions (7.10 I think). There is also a [`convert` processor](https://www.elastic.co/guide/en/beats/filebeat/7.12/convert.html) that can be used for this purpose.

I am going to close this issue, please reopen if there is some processing use case that wouldn't be covered by these features.

**Comment by adrian-skybaker** [comment]
It's unfortunate that functionbeat doesn't support the script processor.
