### ISSUE TITLE
Elasticsearch _xpack endpoint is getting deprecated

### ISSUE THREAD

**Issue by ph** [elastic/beats#9424]
We have a few things inside beats that depends on some _xpack's endpoint and that endpoint is [deprecated](https://github.com/elastic/elasticsearch/issues/35958)

- monitoring
- functionbeat's license checker 

cc @urso @ruflin

**Comment by ph** [comment]
@ruflin Yes we need to do that and what about the x-pack directory in our repo?

**Comment by ruflin** [comment]
I would treat the x-pack directory differently in the dev repo as we need a way to separate the files and that is only for engineers and not user facing.

**Comment by ycombinator** [comment]
@ph @urso My reading of this issue is that it's not specific to the `GET _xpack` endpoint, but the general class comprising various `_xpack/*` ES endpoints, right?

Assuming that's the case, I recently did an audit of the entire Beats codebase for use of `_xpack/*` ES endpoints, as part of resolving #17880. I found that there are three types of uses of `_xpack/*` ES endpoints:
1. Calls to the specific `GET _xpack` ES API endpoint. AFAIK this endpoint is not going away, not even in `8.0.0` / `master` ([doc](https://www.elastic.co/guide/en/elasticsearch/reference/master/info-api.html) | [source](https://github.com/elastic/elasticsearch/blob/216f11f674a7215a7145ee9bf4a550120ec6383a/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/rest/action/RestXPackInfoAction.java#L24-L29)).
2. Calls to the specific `GET _xpack/usage` ES API endpoint. AFAIK this endpoint is not going away, not even in `8.0.0` / `master` ([doc](https://www.elastic.co/guide/en/elasticsearch/reference/master/usage-api.html) | [source](https://github.com/elastic/elasticsearch/blob/216f11f674a7215a7145ee9bf4a550120ec6383a/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/rest/action/RestXPackUsageAction.java#L30-L32))
3. Calls to all other `_xpack/*` endpoints. All of these are guarded by version checks so they will only be called if the Beat is talking to an ES < 7.0.0. Some examples:
   - https://github.com/elastic/beats/blob/a141e88dcad125f0c4eaa02f2da0bc14e73b2b21/libbeat/esleg/eslegclient/bulkapi.go#L152-L154
   - https://github.com/elastic/beats/blob/a141e88dcad125f0c4eaa02f2da0bc14e73b2b21/metricbeat/module/elasticsearch/elasticsearch.go#L269-L271
   - https://github.com/elastic/beats/blob/a141e88dcad125f0c4eaa02f2da0bc14e73b2b21/metricbeat/module/elasticsearch/ml_job/ml_job.go#L74-L76

So for (1) and (2), we need to keep those uses as-is. For (3), I think we can get rid of the guarded clauses for < 7.0.0 **only in** `master` / `8.0.0` now? In other words, an 8.0.0+ Beat talking to an 6.x Elasticsearch cluster may not be a supported use case?

---

As for `xpack.*` configuration settings, I found these:
- `xpack.enabled` in the `elasticsearch`, `kibana`, `logstash`, and `beat` Metricbeat modules. This setting toggles whether the data collected by these modules is sent to "regular" `metricbeat-*` indices vs. stack monitoring `.monitoring-*` indices. I think we could introduce a different setting for this toggling in, say, `7.9` and deprecate the `xpack.enabled` setting. Then in `8.0.0` / `master` we could remove the `xpack.enabled` setting altogether. WDYT?
- `xpack.monitoring.*` settings in Beat configuration. These settings indicate that the Beat's own monitoring data must be sent to the _production_ Elasticsearch cluster (instead of directly to the _monitoring_ Elasticsearch cluster). These settings have been deprecated since 7.2.0 and replaced by `monitoring.*` settings. I think we can remove the `xpack.monitoring.*` settings in `8.0.0` / `master`. WDYT?

**Comment by urso** [comment]
Sounds like a plan :)

Will xpack monitoring functionality be gone in ES/Kibana with 8.0 as well?

**Comment by ycombinator** [comment]
> Will xpack monitoring functionality [routing monitoring data via the production cluster] be gone in ES/Kibana with 8.0 as well?

I believe this is the plan. @chrisronline @jakelandis can confirm.

**Comment by jakelandis** [comment]
It is planned for the `/_xpack/monitoring/_bulk` (currently removed from master) as well as `/_monitoring/bulk` will be going in away in 8.0 in favor of the clients writing directly to the `_bulk` end point with the correctly formatted monitoring documents.

**Comment by chrisronline** [comment]
Yes, legacy collection will be removed in 8.0

**Comment by ycombinator** [comment]
Thanks @jakelandis and @chrisronline for confirming that the legacy collection path is going away from Elasticsearch in 8.0.0.

**Comment by ycombinator** [comment]
> As for `xpack.*` configuration settings, I found these:
> - `xpack.enabled` in the `elasticsearch`, `kibana`, `logstash`, and `beat` Metricbeat modules. This setting toggles whether the data collected by these modules is sent to "regular" `metricbeat-*` indices vs. stack monitoring `.monitoring-*` indices. I think we could introduce a different setting for this toggling in, say, `7.9` and deprecate the `xpack.enabled` setting. Then in `8.0.0` / `master` we could remove the `xpack.enabled` setting altogether. WDYT?

Regarding deprecating and renaming the `xpack.enabled` setting currently being used by Metricbeat stack modules to toggle collection and indexing for Stack Monitoring, I had an off-issue chat with @igoristic and @chrisronline about a new name. We all like `mode`. Here's how that would relate to the current `xpack.enabled` setting:

| | Collect and index like normal Metricbeat modules (default) | Collect and index for Stack Monitoring purposes |
| --- | --- | --- |
| `xpack.enabled` (current name; to be deprecated) | `false` | `true` |
| `mode` (proposed new name) | `normal` | `stack_monitoring` |

One advantage of using `mode` is that it allows for additional values, if needed, in the future. IOW, it's more extensible than a boolean setting.

@urso @exekias At this point I'd like to check with you if there is any precedent in other Metricbeat modules for such a concept — where the module's metricsets behave differently depending on a configuration setting. If so, it might be good to try and be consistent with our naming here.

**Comment by urso** [comment]
> One advantage of using mode is that it allows for additional values, if needed, in the future. IOW, it's more extensible than a boolean setting.

+1. I like using an enum with descriptive names over a boolean :)

What does 'normal' exactly mean? Can we come up with a more descriptive name (e.g. legacy)? Do we even need a `mode` after 8.0? 

> At this point I'd like to check with you if there is any precedent in other Metricbeat modules for such a "mode" concept — where the module's metricsets behave fundamentally differently (not just changing things like the period or hosts) depending on a configuration setting. If so, it might be good to try and be consistent with our naming here.

I'm not really aware of any.

**Comment by ycombinator** [comment]
> What does 'normal' exactly mean? Can we come up with a more descriptive name (e.g. legacy)? Do we even need a mode after 8.0?

Yeah, "normal" is not a very descriptive name, so happy to replace this with something more descriptive. What this mode will do is:
- collect only some basic metrics about stack products, not the very rich set of metrics that are needed by the Stack Monitoring UI and Telemetry, and
- index data into `metricbeat-*` indices (or whatever the default/user configuration dictates).

So maybe `default` is a better name?

Shaunak

**Comment by ycombinator** [comment]
> Do we even need a mode after 8.0?

Yes, I think we will. There is some future in which the Stack Monitoring UI may be driven by data in `metricbeat-*` indices OR this UI is merged into the Metrics UI (which is already driven by `metricbeat-*` indices). In that case we would want to use the `normal` (or `default` or whatever better name we come up with) mode and deprecate the `stack_monitoring` mode).

**Comment by ycombinator** [comment]
BTW, one related change to changing the name of the `xpack.enabled` setting. For ease of use we provide users the ability to do `./metricbeat modules enable $STACK_PRODUCT` or `./metricbeat modules enable $STACK_PRODUCT-xpack` today. The latter corresponds to configuring the `$STACK_PRODUCT` module with `xpack.enabled: true`. 

Since we're changing the name of the setting from `xpack.enabled` to `mode`, we should probably change the the suffix from `-xpack` to `-stack` or `-stack-mon` or `-stack-monitoring` (too long?) something like that?

**Comment by urso** [comment]
`default` or `minimal` work for me. We can also introduce 'aliases' in the future if we want to. e.g. `stack-monitoring` could be replaced with `rich`? Naming is hard :)

> Since we're changing the name of the setting from xpack.enabled to mode, we should probably change the the suffix from -xpack to -stack or -stack-mon or -stack-monitoring (too long?) something like that?

:(
Now I'm wondering if we want to change the setting at all in 7.x. Renaming the module from `-xpack` to something different is a breaking change. E.g. this can mess with automation done via Ansible.
Given that these settings are normally hidden behind the modules + users are encouraged to use `metricbeat modules enable ...` I'm inclined not to change anything on the configuration side.

Any plans on moving stack monitoring to use fleet integrations instead (yet another index again :) )?

**Comment by ycombinator** [comment]
> Now I'm wondering if we want to change the setting at all in 7.x. 

Well, it wouldn't be done as a breaking change in 7.x. We'd introduce the new setting names in 7.x and deprecate the old ones. In 8.0, we'd remove the old ones.

> Any plans on moving stack monitoring to use fleet integrations instead (yet another index again :) )?

Pinging @elastic/stack-monitoring-ui for any thoughts/news on this.

**Comment by urso** [comment]
> Well, it wouldn't be done as a breaking change in 7.x. We'd introduce the new names in 7.x and deprecate the old ones. In 8.0, we'd remove the old ones.

👍

**Comment by ycombinator** [comment]
> - `xpack.monitoring.*` settings in Beat configuration. These settings indicate that the Beat's own monitoring data must be sent to the _production_ Elasticsearch cluster (instead of directly to the _monitoring_ Elasticsearch cluster). These settings have been deprecated since `7.2.0` and replaced by `monitoring.*` settings. I think we can remove the `xpack.monitoring.*` settings **only in**  `8.0.0` / `master`.

PR for this change is up: https://github.com/elastic/beats/pull/18608.

**Comment by ycombinator** [comment]
> Calls to all other `_xpack/*` endpoints. All of these are guarded by version checks so they will only be called if the Beat is talking to an ES < 7.0.0... I think we can get rid of the guarded clauses for < 7.0.0 **only in** `master` / `8.0.0` now? In other words, an 8.0.0+ Beat talking to an 6.x Elasticsearch cluster may not be a supported use case?

PR for this change is up: #18609.

**Comment by ycombinator** [comment]
> `xpack.enabled` in the `elasticsearch`, `kibana`, `logstash`, and `beat` Metricbeat modules. This setting toggles whether the data collected by these modules is sent to "regular" `metricbeat-*` indices vs. stack monitoring `.monitoring-*` indices. I think we could introduce a different setting for this toggling in, say, `7.9` and deprecate the `xpack.enabled` setting.

PR for this change is up: https://github.com/elastic/beats/pull/18610

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity.
