### ISSUE TITLE
Provide an indication that a line is a multiline.

### ISSUE THREAD

**Issue by incogniro** [elastic/beats#957]
When a multiline is processed and shipped by Filebeat, add to 'tags' an indicator. This is to mimic the behaviour the logstash multiline filter performs by adding 'multiline' to tags.
Originally [reported](https://discuss.elastic.co/t/add-multiline-to-tags-field/41285) on the discuss forum.

**Comment by ruflin** [comment]
I was having a quick look on this on how we could implement it. It is a little bit more complicated as I thought as the reader is completely decoupled from the event creation. One solution could be to add a Info() method to the LineProcessor interface. This would then return the type of the last line read. 

Instead of using a tag I would suggest to add a multiline field which as content has the number of lines which were combined. Like this we directly how some additional met information.

**Comment by alpha-centauri** [comment]
+1 for the idea of adding a multiline field with the number of lines
