### ISSUE TITLE
[Metricbeat] Windows perfmon wildcard queries doesn't show correct instance name

### ISSUE THREAD

**Issue by martinscholz83** [elastic/beats#9835]
In windows/perfmon when you you do a wildcard query like `'\Process(*)\% Processor Time'` you don't get the correct instance name for processes which have multiple instances. For example if you are running VSCode.
It has multiple instances like `Code, Code#1, Code#2,...`

With perfmon you get this: `Code, Code, Code,...`
This seems to be a bug in PDH.

Workaround is to instead of running the wildcard query with `_PdhGetFormattedCounterArray` we should first expand the wildcard query with [PdhExpandWildCardPathW](https://docs.microsoft.com/en-us/windows/desktop/api/pdh/nf-pdh-pdhexpandwildcardpathw) which returns the paths for every counter in the wildcard query with the correct name  `'\Process(Code)\% Processor Time', '\Process(Code#1)\% Processor Time', '\Process(Code#2)\% Processor Time',...` and then make a call for every of these counters.

**Comment by narph** [comment]
hi @martinscholz83 , 
Indeed, for a certain process, the instance will match the process name. For the following ones the instance name is modified by appending `#1`, `#2`.
This is something we do not retrieve at the moment and just stick with the initial name.
The downside of adding the instance number is that it is possible for the instance name associated with the process to change. This could happen when an earlier process in the numeric sequence ends. There is a race-condition between determining the instance name and acquiring the relevant counters.

For example if `Hyper.exe#2` exits, `Hyper.exe#3` will become `Hyper.exe#2` and so on. 
This means, if we were returning metric values per instance, the new metric values do not belong to the old  Hyper.exe#2 instance, also makes the entire process of monitoring these instances very confusing.

Not sure if this will help with the issue or complicate things further but you can opt for the PID instead of the number which should be unique, https://support.microsoft.com/de-de/help/281884/the-process-object-in-performance-monitor-can-display-process-ids-pids

Let us know if you think this issue should still be considered further.

**Comment by narph** [comment]
will close issue since there has been no reply, feel free to reopen if necessary

**Comment by JameySteinmann** [comment]
The same issue and others are present when looking at different counters such as the Per Process Per Network Interface Card Activity object and the DPCs Queued per second counter. This one uses the nic device name which has two issues.

1. For nics like Intel that put "(Intel)" as part of the name it truncates the string right before the ')' character. This happens with any instances that have a close parenthesis.

2. For this same counter there is a #207 or number at the end to identify the adapter. This would inherit the same problem as described in the issue.

If we could reconsider resolving these problems it would make these metrics more useful on windows systems
