### ISSUE TITLE
Dedot Kubernetes labels and annotations

### ISSUE THREAD

**Issue by exekias** [elastic/beats#9860]
Dots in Kubernetes labels/annotations can lead to mapping issues (see #8773).

We want to transition to automatically "dedotting" both labels & annotations by introducing the `labels.dedot` setting in 6.x and enable it by default in 7.0. Similar to https://github.com/elastic/beats/pull/9505

Kubernetes labels & annotations can be found in:

- [ ] Metricbeat Kubernetes module
- [ ] Libbeat autodiscover provider
- [ ] Libbeat add_kubernetes_metadata processor

closes elastic/beats#8773

**Comment by kaiyan-sheng** [comment]
Should this be a subtask in https://github.com/elastic/beats/issues/9501 ?

**Comment by exekias** [comment]
yes! I have added it to the list, thank you!

**Comment by morganchristiansson** [comment]
It seems like the PR that closed this issue was for add_kubernetes_metadata however metricbeat kubernetes module still doesn't support dedotting?

It's [enabled by default in the stable helm chart](https://github.com/helm/charts/blob/master/stable/metricbeat/values.yaml#L59) and is breaking if there are labels with dots.
