### ISSUE TITLE
CPU Load chart in Monitoring dashboard is emptied for beats running on Windows 

### ISSUE THREAD

**Issue by hoigau** [elastic/beats#9944]
For confirmed bugs, please report:
- Version: 6.2.2
- Operating System: Windows
- Discuss Forum URL:
- Steps to Reproduce: 

Enable monitoring at the beats running on windows, observe in the Beats Monitoring dashboard the system load chart has nothing.

<img width="1281" alt="screen shot 2019-01-07 at 1 45 07 pm" src="https://user-images.githubusercontent.com/23717402/50823787-bcb84000-136f-11e9-8790-6bad40973988.png">

**Comment by ruflin** [comment]
@ycombinator Could you have a look at this? We currently don't support Windows for the system load also in Metricbeat.

**Comment by cachedout** [comment]
@ruflin Is the idea here that we'd try figure out how to add system load metrics from Windows on the beats side or is this a bug in that the graph is present when we know it will never be populated from beats on Windows?

**Comment by ruflin** [comment]
I would think we should add support for it on the Beats side.

**Comment by ycombinator** [comment]
Just doing some research around this issue and wanted to post a couple early notes:

1. The reason system load for Beats is empty on Windows is because Beats use the https://github.com/elastic/gosigar library to fetch system metrics. This library is a fork of https://github.com/cloudfoundry/gosigar, which is a golang implementation of https://github.com/hyperic/sigar.

   Unfortunately, sigar does not know how to collect load averages for windows: https://github.com/hyperic/sigar/blob/ad47dc3b494e9293d1f087aebb099bdba832de5e/src/os/win32/win32_sigar.c#L1140-L1149. This is then reflected in cloudfoundry/gosigar: https://github.com/cloudfoundry/gosigar/blob/50ddd08d81d770b1e0ce2c969a46e46c73580e2a/sigar_windows.go#L30-L32. And its reflected in elastic/gosigar as well: https://github.com/elastic/gosigar/blob/7bed2391b1d10309feac210aee9df44e8db2d060/sigar_windows.go#L57-L59

2. FWIW, elasticsearch also does not report system load when run on Windows. Here's the output of `http://localhost:9200/_nodes/_local/stats?filter_path=nodes.*.os.cpu` on a MacOS machine:

   ```json
   {
     "nodes": {
       "f10coZjnTEOLC_nvTc80RQ": {
         "os": {
           "cpu": {
             "percent": 15,
             "load_average": {
               "1m": 1.34033203125
             }
           }
         }
       }
     }
   }
   ```

   And here is the output of the same API call on a Windows 10 Pro machine:

   ```json
   {
     "nodes": {
       "0JHZ22HxRFq3xHOxOxPqUw": {
         "os": {
           "cpu": {
             "percent": 19
           }
         }
       }
   ```

**Comment by ycombinator** [comment]
https://github.com/boundary/sigar, which is a fork of https://github.com/hyperic/sigar, seems to implement the `sigar_loadavg_get` function for Windows: https://github.com/boundary/sigar/blob/a6c61edf8c64e013411e8c9d753165cd03102c6e/src/os/win32/win32_sigar.c#L1084-L1125

**Comment by ycombinator** [comment]
Created https://github.com/elastic/gosigar/issues/114 per previous comment.

**Comment by ruflin** [comment]
@andrewkroh @narph might also be able to share some input here. There is also https://github.com/elastic/go-windows/ and https://github.com/elastic/go-sysinfo/ which might be useful.

**Comment by cachedout** [comment]
Here is a link to what I think are probably the minimum version requirements for this approach working:

https://docs.microsoft.com/en-us/previous-versions/aa394272(v%3dvs.85)#requirements

Perhaps we could include that information in the release notes?

**Comment by ycombinator** [comment]
I did some research on this and chatted with @andrewkroh and @narph about this. Here's a PR I started to try and calculate load averages on Windows: https://github.com/elastic/gosigar/pull/115. It has 

Long story short, the effort to figure out how to calculate load averages on Windows **in a way that is semantically equivalent to load averages on *nix systems** seems non-trivial. Side note: there is also a difference in how Linux calculates load averages compared to other *nix systems: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html (see the "Linux Uninterruptible Tasks" section).

Chatting with @cachedout, given the level of effort required here and given that there are other system-level metrics available in the Beats Monitoring UI, we're not going to be taking on this bugfix, certainly not any time soon.
